### ISSUE TITLE
shared calendar can not be hidden

### ISSUE THREAD

**Issue by Nemofly** [owncloud/calendar#1001]
### Steps to reproduce
1. Share Calendar to test account
2. login in test account
3. try to hide the shared calendar

### Expected behaviour
if you have a lot of calendars, you want to hide some of them. My own calendar i can hide but all other which are shared with me i can not hide.

### Actual behaviour
hide a shared calendar did not work

### Server configuration
**Operating system**:
Ubuntu 15.10
**Web server:**
Apache 2.4
**Database:**
MySql 5.6.27
**PHP version:**
5.6.11-1ubuntu3.1
**ownCloud version:** (see ownCloud admin page)
8.2.1.4
**Updated from an older ownCloud or fresh install:**
updated version and tested on a fresh install
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - announcementcenter: 1.0.0
  - audios: 1.2.5
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - news: 6.1.1
  - notes: 1.1.0
  - notifications: 0.1.0
  - ownbackup: 0.3.7
  - passwordpolicy: 2.0.0
  - passwords: 16.2
  - provisioning_api: 0.3.0
  - qownnotesapi: 0.4.1
  - rainloop: 4.9
  - sketch: 0.1.1
  - tasks: 0.8.1
  - theme_switcher: 1.0
Disabled:
  - external
  - files_epubviewer
  - files_external
  - files_videojs-sublime
  - gallery
  - logreader
  - ocdownloader
  - templateeditor
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocf19d41c871",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.de",
            "213.136.92.209"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "test",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 1,
        "theme": "vsl",
        "maintenance": false,
        "default_language": "de",
        "mail_smtpmode": "smtp",
        "mail_from_address": "service",
        "mail_domain": "test.de",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "mail.test.de",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 42.0
**Operating system:**
Windows 7 / Windows 10

Thank You!

**Comment by georgehrke** [comment]
#21
