### ISSUE TITLE
calendar of a deleted user still visible

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/calendar#1003]
I am using ownCloud 8.2.0 and have my users stored in OpenLDAP. Now I deleted an LDAP user a few days ago and it is gone from the Users section in the admin web interface but I can still see the calendar of this user.

How do I get rid of the calendar of that already deleted user?

**Comment by georgehrke** [comment]
> How do I get rid of the calendar of that already deleted user?

you have to delete it from the database.

> Now I deleted an LDAP

@blizzz This means there is no delete hook triggered, right?

**Comment by hostingnuggets** [comment]
yikes, that's ugly... can you at least give me the correct SQL DELETE command that you think would be appropriate so that I do not mess up anything by directly touching the OC database?

**Comment by blizzz** [comment]
See manual for LDAP User Cleanup.
