### ISSUE TITLE
Missing cancel button

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/calendar#1007]
### Steps to reproduce
1. Edit an calendar
2. 
3.

### Expected behaviour
Tell us what should happen
A clearly visible Cancel key with an "X", so that it is clear that it is a Cancel key.

### Actual behaviour
Tell us what happens instead
The Cancel button is very hard to see.
![Missing Button](https://user-images.githubusercontent.com/29964525/56812062-79a8ac80-683a-11e9-9254-deadba7f9891.JPG)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see your admin page)
10.1.1
**Calendar version:** (see the apps page)
1.6.2
**Updated from an older installed version or fresh install:**
updated from older with tarball
**Signing status (ownCloud 9.0 and above):**

**Comment by DeepDiver1975** [comment]
fixed with this one - https://github.com/owncloud/calendar/pull/996

It has not yet been released ... will happen soon
