### ISSUE TITLE
implement a search function

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#101]

**Comment by aspdye** [comment]
Does that mean that the Search Function, removed with ownCloud 8.1 - not brought back with 8.2 - will still not be integrated with the new ownCloud 9 :Confused: :sob: :sob:

**Comment by phsc** [comment]
I'd also vote to have a search function with OwnCloud 9.0.

But nevertheless, I really appreciate your effort @georgehrke and @raghunayyar! It's great to see so much progress on the new calendar app.

**Comment by raghunayyar** [comment]
@georgehrke what exactly you want to search within the calendar? Is it a filter like, finding events in an area / searching events? Or searching calendars in the app-navigation? The later one is fairly simple.

**Comment by aspdye** [comment]
I think it should be the same as that what many of us miss since version 8.1. Not more and not less. Later is still time for improvements :see_no_evil:

**Comment by raghunayyar** [comment]
^ Can you please tell me what it was, I didn't work on search in 8.1 (calendar app)

**Comment by phsc** [comment]
In my opinion, the calendar search should search for events.

**Comment by raghunayyar** [comment]
Awesome, and yes, it surely should. :P

**Comment by georgehrke** [comment]
The biggest priority is currently getting the calendar rework ready for ownCloud 9. Some features like creating and editing events are not fully reimplemented yet and that's definitely more important than searching events ;).

If we come up with more and more features and always postpone the initial release, we'll never release this. We have to set milestones and assign priorities to be able to release something anytime soon. Anyhow this is not set in stone. If there is plenty of time left between us finishing the rework (this doesn't only include coding but also lots of heavy testing, which is really important here) and ownCloud 9 being released, we might implement this for ownCloud 9. The same goes if someone sends a really good pull request.

**Comment by DeepDiver1975** [comment]
Absolutely the right decision by @georgehrke to set this for 9.1 - basic functionality is prio for 9.0

And as usual - this is open source - contribute! THX a lot!

**Comment by aspdye** [comment]
I don't know anybody who could fix this directly, but for me "event search" is one of the most important features. Is there any way to post a bounty on this bug? I am currently using ownCloud 8.0 because it is the last version with the search for calendar and contacts.

**Comment by jeffrobo** [comment]
I know you guys are busy, but I've been pushed quite hard by one of my clients to get a good search function working. They're running 8.2 and they have to have a search. They have customers who call and don't know when their appointment is. My client needs to search the calendar to find the customer's appointment time.

I re-enabled the standard search by inserting...
`<div id="searchresults" class="hidden"></div>`
...after line 3 of templates/calendar.php. I apologize in advance to the Lucene guys, but it's incredibly slow (45-60 seconds) and the results are nearly useless. I deleted the line to turn it back off.

So I'm attacking this from two fronts: first, I created a stand-alone search utility that gets my client up and running again; and second, I am trying to integrate a new search function into the calendar. Once I get it running, I am happy to offer it up if there's someone who wants to add it to the code base. I didn't know 9.0 was coming out, so I'll update it with those changes once it does.

On this posting, I'd like to offer the stand-alone utility. On the next posting, I'm looking for some help. I'm stuck on what should be a simple ajax call and I can't figure out what I'm doing wrong.

Here's the stand-alone search utility. I have it in a file called cal-search.html and I dropped it in the owncloud folder. If you want to do something different, read the notes below. Also, I'm not a software engineer. This is not the prettiest code you're going to see, but it gets the job done. It's in use now and my client loves it.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Calendar Search</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="../favicon.ico" />
    </head>
    <body>
        <div style="font-size:12px;font-family:Verdana;">
            <div style="width:300px;height:75px;padding:30px;background-color:#bbb;">
                <form name="form" action="cal-search.html" method="post">
                    <input type="hidden" name="process" value="true" />
                    <label style="font-weight:bold;">Search</label>
                    <input type="search" name="query"
                           value="<?php if(isset($_POST['query'])) {echo ($_POST['query']);} ?>"
                           autocomplete="off" tabindex="0" style="width:90%">
                </form>
                <script type="text/javascript">
                    document.form.query.focus();
                </script>
            </div>
<?php
            $months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
            $categories = array(
                "3" => "Calendar Name Alpha",
                "4" => "Calendar Name Bravo",
                "6" => "Calendar Name Charlie",
                "7" => "Calendar Name Delta",
                "10" => "Calendar Name Echo",
                "18" => "Calendar Name Foxtrot",
                "22" => "Calendar Name Golf",
                "25" => "Calendar Name Hotel",
                "28" => "Calendar Name India",
                "30" => "Calendar Name Juliet"
            );
            include ("config/config.php");
            $con = mysql_connect($CONFIG[dbhost], $CONFIG[dbuser], $CONFIG[dbpassword]) OR DIE("Unable to connect to database! Please try again later.");
            mysql_select_db($CONFIG[dbname], $con);
            $search_words = "/" . $_POST['query'] . "/i";

            if ($_POST['process'] == 'true' && $search_words !== '') { // If set to True, the submit button has been clicked to begin a search.
                $column_calid = "calendarid";
                $column_calname = "calendardata";
                $tbl_name = "oc_clndr_objects";
                $sql_query = "SELECT $column_calid, $column_calname FROM $tbl_name";
                $sql_results = mysql_query($sql_query, $con);
                while ($row = mysql_fetch_array($sql_results, MYSQL_NUM)) {
                    $final_results[] = $row;
                }
                mysql_close($con);
                $cnt = count($final_results);

                if ($cnt != '0') {
                    for ($i = 0; $i < $cnt; $i++) {
                        $matches = preg_grep($search_words, $final_results[$i]);
                        if ($matches != null) {
                            $just_matches[] = $final_results[$i];
                        }
                    }

                    $match_count = count($just_matches);
                    if ($match_count != '0') {
                        for ($i = 0; $i < $match_count; $i++) {
                            if ($categories[$just_matches[$i][0]] != '') {
                                $cat_cal = $categories[$just_matches[$i][0]];
                                $col_data = $just_matches[$i][1];
                                $dt_string = "DTSTART";
                                $title_string = "SUMMARY:";
                                $desc_string = "DESCRIPTION:";

                                $start_dt = substr($col_data, stripos($col_data, ":", stripos($col_data, $dt_string)) + 1, 15);
                                $start_date = substr($start_dt, 0, 8);
                                if (substr($start_dt, 8, 1) == 'T') {
                                    $start_time = substr($start_dt, 9, 6);
                                } else {
                                    $start_time = "allDay";
                                }

                                if ($start_time == 'allDay') {
                                    $show_time = "All Day Event";
                                } else {
                                    if (substr($start_time, 0, 2) < '13') {
                                        $dt_hour = substr($start_time, 0, 2);
                                        $am_pm = "AM";
                                    } else {
                                        $dt_hour = substr($start_time, 0, 2) - 12;
                                        $am_pm = "PM";
                                    }
                                    if (substr($start_time, 0, 2) == '12') {
                                        $am_pm = "PM";
                                    }
                                    $show_time = $dt_hour . ":" . substr($start_time, 2, 2) . " " . $am_pm;
                                }

                                $date_mdy = $months[substr($start_date, 4, 2) - 1] . " " . substr($start_date, 6, 2) . ", " . substr($start_date, 0, 4);
                                $event_title = substr($col_data, stripos($col_data, $title_string) + 8, stripos($col_data, chr(0x0D), stripos($col_data, $title_string)) - stripos($col_data, $title_string) - 8);
                                if(stripos($col_data, $desc_string) !== false){
                                    $event_desc = str_replace("\\n", "<BR>", substr($col_data, stripos($col_data, $desc_string) + 12, stripos($col_data, chr(0x0A), stripos($col_data, $desc_string)) - stripos($col_data, $desc_string) - 12));
                                }else{$event_desc = '';}

                                // $tbs_fields is To Be Sorted. The array will be [0]=>Numerical Date, [1]=>Category, [2]=>Date, [3]=>Start Time, [4]=>Title, [5]=>Description. We will sort by Numerical Date.
                                $tbs_fields[] = array($start_date, $cat_cal, $date_mdy, $show_time, $event_title, $event_desc);
                            }
                        }
                        usort($tbs_fields, function($a, $b) {
                            return $b[0] - $a[0];
                        });
                        $sorted_count = count($tbs_fields);
                        for ($i = 0; $i < $sorted_count; $i++) {
                            if ($i % 2 == '0') {
                                $bk_color = "#fff";
                            } else {
                                $bk_color = "#eee";
                            }
                            echo "<div style=\"width:360px;background-color:" . $bk_color . ";\">";
                            echo "<span style=\"font-weight:bold;\">Category: </span>" . $tbs_fields[$i][1] . "<br>";
                            echo "<span style=\"font-weight:bold;\">Date: </span>" . $tbs_fields[$i][2] . "<br>";
                            echo "<span style=\"font-weight:bold;\">Start Time: </span>" . $tbs_fields[$i][3] . "<br><br>";
                            echo "<span style=\"font-weight:bold;\">Title: </span>" . $tbs_fields[$i][4] . "<br><br>";
                            echo "<span style=\"font-weight:bold;\">Description: </span>" . $tbs_fields[$i][5] . "<br><br>";
                            echo "</div>";
                        }
                    } else {
                        echo "<div>There were no matches for " . $_POST['query'] . "</div>"; // This means that there no matches for the searched words.
                    }
                } else {
                    echo "<div>Database Failure(?) No records were found.</div>"; // This really means that there were no records in the database at all.
                }
            } // First time through. Show blank form.
            ?>

        </div>
    </body>
</html>

```
Notes:
1. If you name it something other than cal-search.html, be sure to change the name in `action=" "` in the `<form>`.
2. I created the static list of calendars to limit which ones can be searched. There are about a dozen users, so there are about a dozen Personal Calendars which should not be searched. Be sure to edit the $categories array with your own calendar names. You'll need to look in the database table oc_clndr_calendars to match the id with the displayname.
3. If you place it somewhere other than in the owncloud folder, be sure to change the path to the config.php file.
4. It works like Find in Word or Excel. It will match exactly what you type in.
5. It is case-insensitive.
6. It searches all of the fields of a calendar event. You can search for words in the Title (summary), Description, or dates. For dates, you have to use the format YYYYMMDD.
7. Results are listed by most recent day, but not necessarily by hour.
8. Most of the Description fields are incomplete.

I couldn't figure out a good way to extract the Description data from the calendardata cell in the database. The software above takes everything from DESCRIPTION: to the next line feed. But there are multiple line feeds in the description, so it extracts only part of the data. The guys who wrote the Calendar software are obviously smarter than me because they do it every time you open a calendar event.

**Comment by jeffrobo** [comment]
I have a different idea of how the search should work in the Calendar. People I am working with need to be able to click on more than one search result to find what they're looking for. Having the search results disappear once they've clicked on their first choice is not helpful at all.

So I stole some room at the bottom-left where the Settings tab is. It now looks like this:

![Search tab minimized](http://apparient.com/hosting/dc/1.png)

When it opens, it stays open even when you click on other parts of the calendar.

![Search tab maximized](http://apparient.com/hosting/dc/2.png)

I have everything in place, but when I make an ajax call to the server to do the search and fetch the results, nothing happens (except the loading icon spinning around). I initially tried to write this keeping it separate from the Calendar files, but it got too convoluted. I know I shouldn't be editing the Calendar files, but the first step is to get it to work. So here's what I've done:

In __templates/calendar.php__ I added this include to bring in the code to create the Search tab. It immediately follows the code that creates the Settings tab.

`<?php include("apps/calendar/3rdparty/search/search.php") ?>
`

The Search tab code in __search.php__ looks like this. The first part creates the tab and the second part creates the search box.

```
<div id="searchresults" class="hidden"></div>
<div id="app-search">
    <div id="app-search-header">
        <button class="search-button generalsettings" tabindex="0"></button>
    </div>
    <div id="app-search-content">
                <form class="" id="calsearch" name="calsearch" action="#" method="post" role="search">
                    <label class="bold"><?php p($l->t('Search'));?></label>
                    <input id="search-words" type="search" name="query"
                           value="<?php /*if(isset($_POST['query'])) {p($_POST['query']);};*/?>"
                           autocomplete="off" tabindex="0" style="margin-left:16px;width:80%">
                </form>
    </div>
</div>
```

In __js/calendar.js__ I added the following lines to the Util: section.
```
		calendarSearch: function(searchwords){
			Calendar.UI.loading(true);
			$.post(
			OC.filePath('calendar','3rdparty/search','data.php'),
			{
				searchwords:searchwords
			},
			function(result){
				if(result.status !== 'success'){
					OC.dialogs.alert(result.data.message, t('calendar', 'Error retrieving search results'));
				}
                                Calendar.UI.loading(false);
				alert("Possible " + result);
			}
                        );
		},
```

In the bottom of __/js/calendar.js__ I added this code to the `$(document).ready(function(){` section:

```
        $('#app-search-header').on('click keydown',function(event) {
		if(wrongKey(event)) {
			return;
		}
		var bodyListener = function(e) { // Remove the comment slashes in this section if you want to close the search tab whenever you click elsewhere on the page.
//			if($('#app-search').find($(e.target)).length === 0) {
//				$('#app-search').switchClass('open', '');
//				$('#app-search-header').switchClass('open', '')
//			}
		};
		if($('#app-search').hasClass('open')) { // Close the search tab window
			$('#app-search').switchClass('open', '');
			$('#app-search-header').switchClass('open', '');
			$('body').unbind('click', bodyListener);
		} else { // Open the search tab window
			$('#app-search').switchClass('', 'open');
			$('#app-search-header').switchClass('', 'open');
			$('body').bind('click', bodyListener);
                        $('#search-words').focus();
		}
	});
        $('#search-words').keypress(function (e) {
            var searchwords = $('#search-words').val();
            // Wait for the enter key to be pressed.
            if (e.which === 13) {
                $('#calsearch').submit(function () {
                    return false;
                });
            Calendar.Util.calendarSearch(searchwords);
            }
        });
});
```

In the Util: part of __js/calendar.js__ you can see that I'm using `$.post` for the ajax call to a file called __data.php__. The contents of __data.php__ are:

```
<?php
// Check if we are a user
OCP\JSON::checkLoggedIn();
OCP\JSON::checkAppEnabled('calendar');
OCP\JSON::callCheck();

$searchwords = $_POST['searchwords'];
return $searchwords;
?>
```
And I should mention that there is a css file that makes everything look nice.

So it looks pretty simple. If you type in a word in the search box, it should appear below it. Instead, it gets to `Calendar.UI.loading(true);` and the loading icon is displayed, but next is the `$.post` function and nothing happens past that.

I've been staring at this for 2 days now and all I can figure is that there something special about Owncloud or Calendar that I'm not aware of so I'm not calling something that I should. I've looked through some of the Calendar training manuals, but it's too generic to help me out. Does anyone have any ideas?

Thank you for looking.

**Comment by jeffrobo** [comment]
If it helps, here is the css file. I added this line to __index.php__ so it gets called:

`OCP\Util::addStyle('calendar','../3rdparty/search/style');
`

This is style.css
```
/* APP-SETTINGS ---------------------------------------------------------------*/

/* settings area */
#app-settings {
	width: 123px;
}
#app-settings-content {
	width: 230px;
}

/* search area */
#app-search {
	position: fixed;
	bottom: 0;
	z-index: 130;
}
#app-search.open {
        z-index:150;
}
#app-search-header {
	background-color: #eee;
	width: 123px;
        margin-left:127px;
}
#app-search-header.open {
	background-color: #ddd;
}
#app-search-content {
	display: none;
	padding: 10px;
	background-color: #eee;
	width: 230px;
}
#app-search.open #app-search-content {
	display: block;
	/* restrict height of settings and make scrollable */
	max-height: 300px;
	min-height: 300px;
	overflow-y: auto;
}
#app-search input, #app-search select {
	margin-left: 0;
	margin-right: 0;
}
/* display input fields at full width */
#app-search-content input[type='text'] {
	width: 93%;
}

.search-button {
	display: block;
	height: 44px;
	width: 100%;
	padding: 0;
	margin: 0;
	background-color: transparent;
	background-image: url('../../../../core/img/actions/search.svg');
	background-position: 14px center;
	background-repeat: no-repeat;
	box-shadow: none;
	border: 0;
	border-radius: 0;
	text-align: left;
	padding-left: 42px;
	font-weight: normal;
}
.search-button:hover,
.search-button:focus {
	background-color: #ddd;
}

```

**Comment by DeepDiver1975** [comment]
@jeffrobo all your code changes seem to be targeting the old calendar app which is discontinued.

With 9.0 we will deliver a different approach where caldav and carddav live in core and the apps (calendar and contacts) are pure javascript clients.

Search will be implemented using CalDAV search functionalities as specified by the rfc.

I hope this helps. Cheers

**Comment by georgehrke** [comment]
@jeffrobo Please refrain from posting hundreds of lines of code in issues. Please outsource them to [gists](https://gist.github.com) in the future.
Thx! :)

**Comment by aspdye** [comment]
Could help: owncloud/contacts#164

**Comment by georgehrke** [comment]
Nope, it doesn't ;)

**Comment by aspdye** [comment]
:cry:

**Comment by georgehrke** [comment]
The pr you referred to just searches in all the contacts it already loaded and doesn't integrate with the ownCloud search in the top right corner.
Loading all events isn't an option for us, we need to send "search requests" to the caldav server, that's a bit more complex.

**Comment by aspdye** [comment]
How have we done this in ownCloud 8? With 8.1 this function was lost :unamused: ...but why is it so hard to bring it back :question:

**Comment by georgehrke** [comment]
> How have we done this in ownCloud 8?

Prior to ownCloud 8.1 we had this implemented in PHP. 
AFAIK we need to implement it with JavaScript in ownCloud 8.1 and later.

Also the PHP code from ownCloud 8.0 won't work anymore, because we rewrote the entire app.

But there is a milestone assigned to it, so you can expect it in May. :)

**Comment by MetallianFR68** [comment]
+1 for the search functionality which is a must-have

**Comment by aspdye** [comment]
Please dont post +1 or something. There is a milestone assigned - so it WILL come :wink: 
The Priority of this was already discussed above.

**Comment by georgehrke** [comment]
Please suggest properties that should be searchable:
- [ ] title
- [ ] description
- [ ] location
- [ ] Attendee name
- [ ] attendee email

anything else?

**Comment by georgehrke** [comment]
- [ ] Categories / tags once we integrate with ownCloud's tagging mechanism

**Comment by phsc84** [comment]
Sounds sufficient to me. 👍

**Comment by aspdye** [comment]
- [ ] Maybe also the date of an event 😕 (I don't know whether this is needed, because you can already go to an date by clicking around in the calendar - but maybe typing "31/12/2016" into the search-field would be nice. What do you think?)

**Comment by georgehrke** [comment]
Searching thru the date of an event seems weird to me, you can just go there. but maybe we can show an `Go to 31/12/2016` search result, to jump to this date.

@jancborchardt What do you think? ^

**Comment by georgehrke** [comment]
This would come also very handy when you want to browse to a distant date. If you want to go to 2013, you'd have to click at least 24 times the prev button in the month view right now.

**Comment by wiswedel** [comment]
I suggest to discuss the "jump to date" feature under a separate issue since it doesn't really fit the "search" topic.

**Comment by georgehrke** [comment]
ref https://github.com/owncloud/calendar/issues/372

**Comment by jancborchardt** [comment]
Yeah, the search parameters mentioned above seem sufficient. The extra date stuff is a whole different beast.

**Comment by kreil** [comment]
Searching for events in a certain date range would certainly be most useful. Like
   "board meeting" before:2016-04-01
or similar.

**Comment by ulph0** [comment]
hi, i would appreciate if a search would work in nextcloud. since the calendar is my memory and since sometimes i and maybe soe others want to know "hmm when did i met carmen 5 years before?" that really was an important feature in google calendar, which of course i don't use anymore. it would be great to be able to search in there over dav AND the webUI.

**Comment by DeepDiver1975** [comment]
I'm closing this - nobody is working activly on this app.
