### ISSUE TITLE
In calendar app the time (AM/PM) is cut off

### ISSUE THREAD

**Issue by bnvk** [owncloud/calendar#1014]
### Steps to reproduce

In the "create new calendar event" modal which pops up, the time field only lists hours + minutes, while the AM / PM part is hidden (due to input field being too small). The only way to discover if an event is AM or PM is to put cursor into field and go to the far right

### Expected behaviour

It should be clear which half of the day an event a user is creating falls into "AM vs. PM"

### Actual behaviour

The AM / PM part is hidden by too narrow of a field

![owncloud-am-pm](https://cloud.githubusercontent.com/assets/48677/12247005/289d6460-b8b2-11e5-9640-ada3f631ce06.png)

### Client configuration

47.0.2526.80 Built on 8.2 Chromium 

**Operating system:**

Debian 8.2 (64-bit)

**Comment by georgehrke** [comment]
will be fixed with owncloud 9
