### ISSUE TITLE
Soft delete

### ISSUE THREAD

**Issue by intrixius** [owncloud/calendar#1015]
Is there a feature to soft delete events, so they are not really removed from the database but just hidden in the calendar when the user "deletes" it?

**Comment by georgehrke** [comment]
No, why would one want this?

Please excuse my brevity and typos. 
Sent from my mobile



Please excuse my brevity and typos.

**Comment by intrixius** [comment]
We are using the calendar module to track special events in a clinical
trial, so we don't want to lose trace of events that are deleted (on
purpose or by accident) by end users
Op 16-jan.-2016 00:48 schreef "Georg Ehrke" <notifications@github.com>:

**Comment by intrixius** [comment]
I am thinking of putting a view in front of the database table, add a
"deleted_at" column in the base table and create a trigger that will just
update the "deleted_at" field in the base table...
Would that break anything in the module?
Op 16-jan.-2016 07:37 schreef "Koen Janssens" <janssens.k@gmail.com>:

**Comment by georgehrke** [comment]
This is a very very rare use case. Can't you just extract the information from database backups?

**Comment by intrixius** [comment]
Using DB backups would be very cumbersome to combine all the backups, not?
What do you think about my solution that would only involve database
changes?
Op 16-jan.-2016 12:37 schreef "Georg Ehrke" <notifications@github.com>:

**Comment by georgehrke** [comment]
You can setup a cron job or some database triggers,
If I delete an event, I expect it to be deleted and not restorable for admins.
