### ISSUE TITLE
Import - Missing button labels

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/calendar#1016]
### Steps to reproduce
1. Import an .ics file
2. Now we don't see a label.
![Missing label - calendar import](https://user-images.githubusercontent.com/29964525/60756156-695f3b80-9ffa-11e9-8486-5b75638feb1b.png)

### Expected behaviour
Tell us what should happen
See Icon (Check and Cancel) or labels on the buttons.

### Actual behaviour
Tell us what happens instead
See screenshot

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see your admin page)
10.1.1
**Calendar version:** (see the apps page)
1.6.2
**Updated from an older installed version or fresh install:**

**Signing status (ownCloud 9.0 and above):**

**Comment by Julian1998** [comment]
This bug is probably already fixed on master. Could you test it.

**Comment by prsnbrg** [comment]
@Julian1998 The master branch looks like version 1.6.2, which I'm already using.

**Comment by Julian1998** [comment]
@prsnbrg No it's not. Have a look at the release list - the latest release has been on the 24th February. (https://github.com/owncloud/calendar/releases)

The PR which I asked you to test (https://github.com/owncloud/calendar/pull/996) has been merged into master on the 28th of March

**Comment by prsnbrg** [comment]
Oh, okay, thanks.

However, the page for the calendar does not build up properly but all individual elements are displayed. Even the ones that are normally hidden behind drop down menus and buttons.

Is it possible it has to do with a cache of oC?

**Comment by Julian1998** [comment]
No problem at all
You have to run `make` once :)

**Comment by Julian1998** [comment]
@prsnbrg Did you get it to work? Otherwise I will test it :)

**Comment by prsnbrg** [comment]
Hey @Julian1998,
I'm having some problems with the Make command right now, I'll take a closer look at them over the next week or weeks.

Would be great if you could do the testing.

**Comment by Julian1998** [comment]
I will do it :)
It's probably your npm version. Had the same problem some weeks ago

**Comment by prsnbrg** [comment]
@Julian1998 some new information to this bug? It’s fixed on master?

**Comment by Julian1998** [comment]
@prsnbrg Didn't test it yet, sorry! But yeah master should be fixed as I fixed a "missing cancel icon button" issue some weeks ago ;)

**Comment by prsnbrg** [comment]
@Julian1998 @DeepDiver1975 can you make a final release for 1.6.3?

**Comment by prsnbrg** [comment]
Fixed in 1.6.3
