### ISSUE TITLE
deselect shared calender not only own calender

### ISSUE THREAD

**Issue by kmelchinger** [owncloud/calendar#1017]
Congratulation:  calendar is an awesome tool for colaboration!
There is only one issue causing problems: there is no chance to deselect shared calendars, You HAVE to see them all in the owncloud-web, no chance to deselect. You are able to deselect your OWN calendars, Is there any chance to get this feature quite soon ?

**Comment by RealRancor** [comment]
@kmelchinger Please search existing issues first before opening a new issue. You can also find a FAQ here: https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#faq where you can find a link to an existing feature request for this.

The contributing file is also linked in the yellow box shown when creating a new issue. That link should be followed and read before creating a new issue.

**Comment by buskjan** [comment]
@RealRancor Do you hava an id for the existing issue? All i can find is from 2013 and marked as solved. I have the same issue.

**Comment by RealRancor** [comment]
https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#faq -> https://github.com/owncloud/calendar/issues/21

as advised above.

**Comment by buskjan** [comment]
Well, it seems that I'm not at my best to day. I didn't see that it was an open issue. Just that it was opened in 2013. Sorry!
