### ISSUE TITLE
Birthday at 31-12-YYYY listed as birthday in YYYY+1

### ISSUE THREAD

**Issue by radoeka** [owncloud/calendar#1021]
In the web calendar birthdays are listed.  
For a person that has a birthday at 31-12-YYYY, the year is shown is YYYY+1

### Steps to reproduce
1. Add contact person with a birthday at 31-12-2000
   Year can be any year
2. Go to the calendar https://<server>/owncloud/index.php/apps/calendar/
3. Select January
4. Look at 31-12

### Expected behaviour
The year should show 2000

### Actual behaviour
The year shown is 2001

If the birthday of the above user is set to one day before ( 30-12-yyyy), the year shown is correct.

### Server configuration
**Operating system**:  linux

**Web server**: apache

**Database**: sqlite3

**PHP version**: 5.4.20

**ownCloud version:** 8.2.2

**Comment by gvde** [comment]
Duplicate of owncloud/contacts#1110
Pull request available at owncloud/contacts#1111

**Comment by radoeka** [comment]
Problem solved with change reference by @gvde
