### ISSUE TITLE
Failure to synchronize with Thunderbird - corrupt entries exported during sync

### ISSUE THREAD

**Issue by tlhackque** [owncloud/calendar#1023]
New install of `ownCloud 8.1.1.7` on a Synology NAS.  `Thunderbird 39.5.1 / Lightening 4.0.5.2` with `SOGo Connector 31.0.2`. (Package source: synocommunity.com)

I exported a large calendar to an `.ics` file from Thunderbird (a local calendar), which I want to make accessible from multiple PCs.  FWIW, the `.ics` file is 8871 lines long.

I imported it successfully to `ownCloud` by uploading in the files app & clicking on it in the `ownCloud` web interface.  All events seem to be present in the web view of the calendar.  

I created a new network calendar on my PC using the 'New Calendar' wizard.  The calendar appears and many entries populate.

However, many entries are missing.

If I open the Thunderbird error console, there are entries in the log indicating format errors in received calendar items; it appears that the start and end times are corrupt.  For example, in the following note that `DTEND` has an extra `;VALUE=` (or perhaps a missing `DATE` after the `=`)...

This is the error console message:
```
Timestamp: 29-Jan-16 05:52:57
Warning: Failed to parse item: BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.7.3
BEGIN:VEVENT
CREATED:20160129T021224Z
LAST-MODIFIED:20120921T141040Z
DTSTAMP:20120921T141040Z
UID:a36ba90e-38af-4adc-a2e6-77fc342e5902
SUMMARY:Easter
CATEGORIES:Holiday
DTSTART:19990404T010000
DTEND;VALUE=:19990405T010000Z
LOCATION:United States
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR


Exception:[Exception... "Component returned failure code: 0x8000ffff
(NS_ERROR_UNEXPECTED) [calIIcalComponent.endTime]"  nsresult:
"0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame ::
resource://calendar/modules/calUtils.jsm ->
file:///C:/Users/timothe/AppData/Roaming/Thunderbird/Profiles/bkq1fxqu.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calItemBase.js
:: cIB_mapPropsFromICS :: line 788"  data: no]
Source File:
file:///C:/Users/timothe/AppData/Roaming/Thunderbird/Profiles/bkq1fxqu.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/components/calDavCalendar.js
Line: 1041
```
Looking in the input `.ics` file, we have a sensible `DTEND` for this UID:

```
BEGIN:VEVENT
CREATED:20160129T021224Z
LAST-MODIFIED:20120921T141040Z
DTSTAMP:20120921T141040Z
UID:a36ba90e-38af-4adc-a2e6-77fc342e5902
SUMMARY:Easter
CATEGORIES:Holiday
DTSTART:19990404T010000
DTEND:19990405T010000
LOCATION:United States
TRANSP:TRANSPARENT
END:VEVENT
```
(This event comes from `http://www.mozilla.org/projects/calendar/caldata/USHolidays.ics`, which is one of the contributors to the calendar that I exported.)

I wonder if this is a Y2K issue, as the date is in 1999... BTW, the date picker on the web needs a way to jump to a desired year - clicking left-arrow 200ish times to get back to 1999 is a lot of work!

In any case, either ownCloud is sending corrupt entries, or SOGo Connector is corrupting them...

Obviously, I can't switch to the cloud calendar until I can sync reliably...

Thanks for any help...

**Comment by gvde** [comment]
This is a duplicate. Pull request is available.

**Comment by tlhackque** [comment]
Thanks for the quick reply.  I assume you mean your pull request 1004, which makes
` $object->DTEND['VALUE'] = $object->DTSTART['VALUE'];` conditional on `if ( !empty($object->DTSTART['VALUE']) ) ` 

I applied this patch to `apps/calendar/lib/import.php`, and restarted the webserver.

The symptom didn't go away until I re-imported the ICS file. Apparently although the web view of the calendar had all the events, the entries were corrupt there.

I'll open a new issue on the date picker so it doesn't get lost.

I won't close this issue as the pull request is pending.

Thanks again!

**Comment by gvde** [comment]
I meant #994, #1004, #1022 depending on the version you have. They are all the same anyway.

The patch fixes the import, thus, you have to remove the broken contacts from owncloud and re-import to get it fixed. Otherwise you could also remove the broken VALUE= from the database directly.

You can close this issue and comment on the pull requests that it solves your problem. That may help to expedite the pull requests getting merged as currently there is no maintainer for this app...

**Comment by tlhackque** [comment]
Right, I figured that out (initially thought it was the export via sync), but thought I should document for the next person.

I'll close and comment on #1004 as you suggest.

Thanks again.
