### ISSUE TITLE
404 not found (Cannot use 'Float' as class name as it is reserved)

### ISSUE THREAD

**Issue by produnis** [owncloud/calendar#1027]
Hi there,
I have several calenders which all work fine, but one.
If I try to download this calender with URL `https://myserver.org/owncloud/index.php/apps/calendar/export.php?calid=6`
I get a 404 file not found
All other calenders (calid=1,2,3,4,5,,7,8,9) do work just fine,
and calender 6 is available at the webside, being able to add/edit/remove events.

Apache error log says:

> [Sun Jan 31 15:25:01.770286 2016] [:error] [pid 5533] [client 178.203.204.144:59292] PHP Fatal error:  Cannot use 'Float' as class name as it is reserved in /srv/http/www/owncloud/3rdparty/sabre/vobject/lib/Property/Float.php on line 18

Any help welcome

I am on Archlinux with php7 and ownCloud 8.2.2

**Comment by RealRancor** [comment]
@produnis oC and especially calendar and contacts apps are currently not compatible with PHP7. You need to wait until oC 8.2.3 is released shipping a PHP7 compatible version of sabredav and vobject.

For now you can test https://github.com/owncloud/3rdparty/pull/246#issuecomment-175460328 which should fix this issue.
