### ISSUE TITLE
retrieve Error parsing carddata

### ISSUE THREAD

**Issue by tflidd** [owncloud/calendar#1031]
When I open the calendar via web interface, I get this error:
````
{"reqId":"IGbnaJHQWSYT9QgwsH0W","remoteAddr":"2001:","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 265 This parser only supports VCARD and VCALENDAR files","level":3,"time":"February 09, 2016 22:21:29"}
{"reqId":"IGbnaJHQWSYT9QgwsH0W","remoteAddr":"2001:","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 265 This parser only supports VCARD and VCALENDAR files","level":3,"time":"February 09, 2016 22:21:29"}
{"reqId":"IGbnaJHQWSYT9QgwsH0W","remoteAddr":"2001:","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 265 This parser only supports VCARD and VCALENDAR files","level":3,"time":"February 09, 2016 22:21:29"}
````
a bit similar like this issue https://github.com/owncloud/calendar/issues/903 but I do access via the webinterface and not via client. Though, I do also use external clients which might have created an entry that's causing this issue. A new user, or a different user that hasn't been connected to external clients, does not show this error.

OC 8.1.5
Calendar: 0.7.3

Is there a way to find out which entry causes this issue? Then we can try to trace back which program creates this problem.

**Comment by georgehrke** [comment]
Your log says contacts and not calendar ;)

**Comment by tflidd** [comment]
Sorry, but the error appears when I'm opening the calendar app!!!

**Comment by georgehrke** [comment]
You seem to have a corrupt contact, reach out to the contacts folks to find out which one it is
