### ISSUE TITLE
Share task list

### ISSUE THREAD

**Issue by alve89** [owncloud/calendar#1032]
Since every calendar creates a task list (and so a shared calendar creates a shared task list), I'm asking if theres an option (in future releases) to create another task list within a calendar (and perhaps with the possibility to share this list)?
Of course this is not (only) a problem of oC but also of DAV - but I don't know if SabreDAV supports this by default?

**Comment by georgehrke** [comment]
tasks are not part of the calendar app. please reach out to the tasks app folks.
Beginning with ownCloud 9 CalDAV won't be a part of the calendar anymore, but will rather reside in ownCloud's core.
