### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by pille** [owncloud/calendar#1033]

**Comment by georgehrke** [comment]
THIS IS A PUBLIC BUGTRACKER! FOR CRYING OUT LOUD. READ https://owncloud.org/security/ FIRST

**Comment by pille** [comment]
you're welcome.
so is this in ```/dev/null``` now or are you dealing with it somewhere else?

**Comment by georgehrke** [comment]
We are dealing with it somewhere else. Somewhere where we also take care of other issues that reach us via the described way in https://owncloud.org/security/

**Comment by pille** [comment]
glad to see your CAPS key isn't really broken.
it would be nice to receive feedback on the issue, so please add me to whatever@somewhere.
thanks for your support.
