### ISSUE TITLE
Calendar not interpreting line break on addresses entered by iOS

### ISSUE THREAD

**Issue by sndrsk** [owncloud/calendar#1035]
When I am adding an event to my calendar via iOS, and entering an address suggested by iOS, it enters the address as the following:

123 Main St
Anytown, US 12345

with the line break in between the street name and city/state. Then oC Calendar interprets this on a single line as "123 Main StAnytown, US 12345". If you follow the link to Mapquest Open, it can't interpret that address due to no space or a comma between the street and city.

It seems we can add a comma between the street and city ("123 Main St, Anytown, US 12345") and Mapquest will interpret it correctly.

Is it possible for oC Calendar to see the line break from the iOS address and just enter a comma and space there?

**Comment by georgehrke** [comment]
fixed in rework, will come with ownCloud 9
