### ISSUE TITLE
Function - Import new calendar

### ISSUE THREAD

**Issue by 247-z** [owncloud/calendar#1035]
Can You create new functions "_Import new calendar_"?

I do update old version of ownCloud, but ownCloud have error with the code integrity check. Because i would by like create new clean installation and them import older only data. Files - no problem, but data from calendar can i export, but I don't can import in clean new installation.

**Comment by Julian1998** [comment]
There is an "import new calendar" feature in the bottom left.

![Bildschirmfoto vom 2019-09-17 09-29-35](https://user-images.githubusercontent.com/2546997/65020551-afefe100-d92d-11e9-8a66-baf21a6b929c.png)

**Comment by 247-z** [comment]
Aha. I must first click in left bottom on "_Setting and Import_".
