### ISSUE TITLE
Feature Request: id code for calendar names

### ISSUE THREAD

**Issue by alve89** [owncloud/calendar#1036]
Hello all!

I have an idea because I am a little annoyed of the following issue:
Because I love ownCloud I use this in multiple areas / organizations. This brings the problem that new users get new calendars - every calendar has the same name ("Persönlich" / "Personal"[?]). So I have four "Persönlich" calendars now and - on iOS - the host / the oC name is not displayed.
What do you think of an id code the admin can set up in config file that is added at the beginning of every calendars name (example: id = "oC xyz", every new (!) calendars name (not the already created ones of course) becomes "oC xyz: Persönlich").

Of course I could just change every calendar. But this wouldn't change the names of my users calendars. So what do you think? 

If not: Could some one tell me where in the code the new calendars are created?

Regards

**Comment by georgehrke** [comment]
definitely nothing we will implement.

To find out how to implement this on your own (although applying your own patches is not recommended) please join owncloud-dev on free node and ask DeepDiver

**Comment by alve89** [comment]
Not sure if this is readable when I comment this: I'm not sure why this could not be implemented (especially because it's a job of two minutes)?!
I think this could be very interesting for people who use more than one oC. I patched this on my own (just a config.php value and a small if-clause in calendar.php.
If someones interested or this could become interesting to implement, just ask. :-)
