### ISSUE TITLE
Api access

### ISSUE THREAD

**Issue by akademy** [owncloud/calendar#1038]
I can't find any API access to the calendar. If there isn't one is there any other way to access the data stored?

(Some background: I'm trying to create a widget in another OwnCloud App called Dashboard, it will display future appointments from the Calendar. ).

Cheers.

**Comment by georgehrke** [comment]
Starting with ownCloud 9, this app won't be maintained anymore.
It will be replaced by the calendar rework and the dav app.
The dav app implements the CalDAV server and the calendar rework is just a caldav web client accessing it.

To cut a long story short, just access the calendar data via CalDAV, there is no PHP API
