### ISSUE TITLE
Documentation should tell how to install the Owncloud Calendar app

### ISSUE THREAD

**Issue by insanity54** [owncloud/calendar#1039]
I'm a new user and I don't know how to install the Calendar app into Owncloud.

* The [README.md](https://github.com/owncloud/calendar/blob/5cbd4607d584bbd05f9f8905163592c9dab284bf/README.md) does not tell how to install the Owncloud calendar app.
* The [Calendar app marketplace page](https://marketplace.owncloud.com/apps/calendar) does not tell how to install the calendar app.
* The Owncloud GUI `/settings/admin?sectionid=apps` page does not tell how to install the calendar app
* The [Calendar app Documentation page](https://doc.owncloud.org/server/10.0/user_manual/pim/calendar.html) does not tell how to install the calendar app. 
* The [project FAQ page](https://github.com/owncloud/calendar/wiki/FAQs) does not tell how to install the calendar app.

### Expected behaviour
There should be instructions on how to install the calendar app to OwnCloud on one or more of the aforementioned locations. Especially the [Calendar app marketplace page](https://marketplace.owncloud.com/apps/calendar).

**Comment by wom-bat** [comment]
>>>>> "Chris" == Chris Grimmett <notifications@github.com> writes:

Chris> I'm a new user and I
Chris> don't know how to install the Calendar app into Owncloud.

Doesn't visiting your Owncloud page as an administrator, finding the
Market, finding the calendar app in the market, and clicking the
'Install' button do it?

Peter C

**Comment by insanity54** [comment]
That's the undocumented process that I would have loved to see in one in the aforementioned places.

It is not what I intuitively tried. I first tried the settings page,`/settings/admin?sectionid=apps`. I saw the installed apps so naturally it looked like I was in the right place for adding more. However, the screen lacks any method of installing new plugins.

I was further confused by the marketplace giving me a .tar.gz file. The UI doesn't have any place to upload .tar.gz files.

**Comment by ho4ho** [comment]
Web-GUI -> Hamburger menu top left -> Market -> Search calendar -> install

Manual install by https://doc.owncloud.org/server/10.3/admin_manual/installation/apps_management_installation.html, better create new issue by https://github.com/owncloud/docs/issues to extend above in it?

**Comment by ho4ho** [comment]
Ask for above by https://github.com/owncloud/docs/issues/2128

**Comment by settermjd** [comment]
@insanity54, thanks for taking the time to report the problem and sorry for the frustration that a lack of instructions has caused. Using the Market app is the official way to install the app. I'll update the Calendar app to with the relevant instructions so that it's explicitly clear.

**Comment by settermjd** [comment]
@insanity54 @ho4ho @wom-bat does #1046 rectify the problem?
