### ISSUE TITLE
Update timezone database

### ISSUE THREAD

**Issue by enbrnz** [owncloud/calendar#1045]
https://github.com/owncloud/calendar/blob/master/js/timezones/zones.json#L2

This database is out of date, as for example Brazil has ended daylight savings time this year, this creates wrong time data in the calendar.

I found the following issue & pull-request in nextcloud, perhaps somebody can see whether we can include this here as well.
https://github.com/nextcloud/calendar/issues/1473
https://github.com/nextcloud/calendar/pull/1635

**Comment by DeepDiver1975** [comment]
@Julian1998 please have a look - afaik running the python script in this folder should be enough .... let me know if you need more input. THX
