### ISSUE TITLE
Sync History

### ISSUE THREAD

**Issue by kallegit1950** [owncloud/calendar#1048]
My next cloud calendar shows all old entries way back in the past. When I use caldav for synchronization then it seems that only the last 4 months are being synced. I sync my next cloud calendar with Kontact (Linux KDE) and with Android devices using DAVx5. If only one remote calendear would show the issue I would blame the remote software, but it is on both ends so I rather would search on next clouds end. I was not able to find a setting how far in history items are being synced. Is that a known issue?

Thanks, K.

**Comment by Julian1998** [comment]
Why aren't you asking in the nextcloud calendar repo? This is ownCloud. This is different software. So helping isn't possible. Sorry
