### ISSUE TITLE
Please hide birthdays for Deceased contacts

### ISSUE THREAD

**Issue by JeremyStent** [owncloud/calendar#1058]
### Steps to reproduce
1.  Add a contact
2.  Add a "Birthday" and a "Date of Death" date field to the contact
3.  This person shows up with a birthday on the Calendar even after the Date of Death

### Expected behaviour
The contacts birthdate should not show on the calendar after the Date of Death

### Actual behaviour
The contacts birthdate shows on the calendar even for years after the date of death

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see your admin page)
10.3.2.2

**Calendar version:** (see the apps page)
1.6.3

**Updated from an older installed version or fresh install:**
Updated from an older vrsion

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by j-ed** [comment]
As always this is a question of everyone's personal preference. I personally prefer to get a birthday reminder although for dead persons. If you don't want to get a birthday reminder, remove the birthday entry from the persons record or copy the date to the notes field to get rid of the reminder. Due to the fact that most people have less records of death persons in their database than of persons still alive, this would be the simplest way to go.
