### ISSUE TITLE
Randomly failing JS test

### ISSUE THREAD

**Issue by phil-davis** [owncloud/calendar#1086]
This tests fails "randomly". It used to fail in the same way "randomly" on Travis, and we have the same behaviour on drone. So at least it is "consistent".

Work out why it sometimes fails and fix it.

https://drone.owncloud.com/owncloud/calendar/38/4/4
```
Firefox 73.0.0 (Ubuntu 0.0.0) ColorUtility <9.1 should provide a list of default colors for <9.1 FAILED
	Expected $.length = 9 to equal 8.
	Expected $[0] = '#000000' to equal '#31CC7C'.
	Expected $[1] = '#000000' to equal '#317CCC'.
	Expected $[2] = '#000000' to equal '#FF7A66'.
	Expected $[3] = '#000000' to equal '#F1DB50'.
	Expected $[4] = '#000000' to equal '#7C31CC'.
	Expected $[5] = '#000000' to equal '#CC317C'.
	Expected $[6] = '#000000' to equal '#3A3B3D'.
	Expected $[7] = '#000000' to equal '#CACBCD'.
	Unexpected $[8] = '#000000' in array.
	<Jasmine>
	@tests/js/unit/utility/colorUtilitySpec.js:131:31
	<Jasmine>
```

**Comment by DeepDiver1975** [comment]
This is the Case für years 🤷

Never unterstood why.

**Comment by Julian1998** [comment]
We always thought this is just a weird timeout. So we just restarted

**Comment by phil-davis** [comment]
> We always thought this is just a weird timeout. So we just restarted

Yes, I suspect that is the case. I also "just restart" - standard call-centre advice ;)

It would be nice to find out what the cause is and fix it some day - but it might be difficult and is not really high priority.

**Comment by Julian1998** [comment]
I am not even sure if this test is really important. Maybe we can just skip it

**Comment by phil-davis** [comment]
Happened again last night:
https://drone.owncloud.com/owncloud/calendar/61/4/4

I vote for skipping it!
