### ISSUE TITLE
How to delete old calendarobjects

### ISSUE THREAD

**Issue by ethpi** [owncloud/calendar#1090]
### Expected behaviour
Searching for MySQL command for deleting old calendarobjects

### Server configuration

**Operating system**: raspbian jessie

**Web server:** apache2 2.4.10-10

**Database:** mysql 5.5.62-0

**PHP version:** 5.6.40

**ownCloud version:** 10.0.3.

**Calendar version:** 1.6.3

**Updated from an older installed version or fresh install:** fresh

**Signing status (ownCloud 9.0 and above):** don't know, 

Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.`

**List of activated apps:**

```
Enabled:
  - bookmarks: 0.10.5
  - brute_force_protection: 1.0.1
  - calendar: 1.6.3
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.5
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.10.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - audioplayer
  - encryption
  - external
  - files_antivirus
  - richdocuments
  - theme-example
  - user_external

```

**ownCloud configuration:**

```
{
    "system": {
        "instanceid": "ocwzfuzjjiff",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "192.168.1.15"
        ],
        "datadirectory": "\/var\/oc_data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "oc",
        "dbhost": "localhost:3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "default_language": "de",
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "debug": true,
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 8",
        "mail_smtpsecure": "ssl",
        "theme": ""
    }
}


```
**Are you using external storage, if yes which one:** local

**Are you using encryption:** no (I use a luksencrypted harddrive)

**Are you using an external user-backend, if yes which one:** korganizer, davdroid

Hi,

I'm searching for a possibility to delete old calendar objects. I didn't find a way to to do this with the webgui or with a korganizer or davdroid. So I tried to do this directly on the database. 

I think the calendar objects are stored in the table "oc_calendarobjects". If I like to delete all calendarobjects older than one and a have year I think I have to use this mysql command (db-name is "oc", tableprefix is "oc_"):

```
DELETE
FROM oc.oc_calendarobjects
WHERE lastoccurence < UNIX_TIMESTAMP(NOW()) 
     AND (UNIX_TIMESTAMP(NOW())-lastoccurence) > 1.5*365*24*3600
```

Is this correct?

Many thanks for answers.

**Comment by DeepDiver1975** [comment]
There is no built-in feature to do something like this.

I suggest to not manipulate the data in the db directly. Calendar object changes are stored in a second table and you will loose consistency.

A more sane option could be to travel back in time with the calendar app and delete calendar objects.

I'm closing this now - not an issue at the end.
