### ISSUE TITLE
Calendar CI fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/calendar#1127]
https://drone.owncloud.com/owncloud/calendar/245/4/4
```
error An unexpected error occurred: "https://codeload.github.com/georgehrke/jstimezonedetect/tar.gz/d90d861a98a30a802cb1f4c7864854fe3a583134: Request failed \"404 Not Found\"".
```

It seems that the repo http://github.com/georgehrke/jstimezonedetect has been deleted.

**Comment by phil-davis** [comment]
@georgehrke did you intend to delete this repo?

can it be recovered?  or should we go searching for a fork that still exists somewhere?

**Comment by georgehrke** [comment]
I'm sorry, I didn't think anyone would still be using it. It was just a clone i made of `jstz`, before it was available on npm.

You can simply replace it with https://www.npmjs.com/package/jstz. The APIs are the same.

**Comment by phil-davis** [comment]
I guess it got left like that in the owncloud calendar app because nobody ever reviewed it and changed to a "proper" package.
Now is the time to change :)

I found that https://github.com/pellepim/jstimezonedetect is on GitHub since 2019, so it is easy to switch to there. PR #1128
