### ISSUE TITLE
Release Calendar 1.6.5

### ISSUE THREAD

**Issue by phil-davis** [owncloud/calendar#1129]
Issue #1127 PR #1128 fixed up a dependency that went away.

It might be good to make a release containing that change?

**Comment by phil-davis** [comment]
Also dependabot #1140 "[Security] Bump http-proxy from 1.18.0 to 1.18.1"

Is that relevant to this repo?

**Comment by jnweiger** [comment]
Release is blocked by https://github.com/owncloud/calendar/issues/1165

**Comment by jnweiger** [comment]
@phil-davis is this obsoleted by #1259 ?

**Comment by phil-davis** [comment]
> @phil-davis is this obsoleted by #1259 ?

yes - 2.0.0 has been released now, with all the code that is in master, including core min-version 10.11.

That means that people will need to wait for core 10.11.0 to be released, and then they will be able to update to the latest Calendar 2.0.0 which will have "all the fixes".
