### ISSUE TITLE
Sync with Thunderbird lightning fails

### ISSUE THREAD

**Issue by taich001** [owncloud/calendar#1146]
### Actual behaviour
After adding the calDAV link in thunderbird calender acount exists but can not be activated.

**ownCloud version:** (see your admin page)
10.5.0.10

**Calendar version:** (see the apps page)
1.6.4

**Comment by linkp** [comment]
It would be helpful if you fill out the complete template, as your description lacks many relevant details. I have encountered symptoms similar to what you describe, that appear to have a relation to the ownCloud OAuth app. Even if you don't have that app installed, it may still be worth your time to review [this thread](https://central.owncloud.org/t/calender-connection-with-thunderbird-fails-401-unauthorized/17519/5) on the ownCloud forums.

**Comment by taich001** [comment]
I have OAuth installed but dont use it with thunderbird. There is an thunderbird addon called Tbsync. I can enter my credentials and it connects to owncloud showing me the available calendars. But when I try to sync nothing happens. Is there a way to watch a log?

**Comment by taich001** [comment]
You can find more details here
https://github.com/jobisoft/TbSync/issues/405

**Comment by linkp** [comment]
I, too, have TbSync installed. I have resigned to accept that it does not work with ownCloud calendars, or at least mine, and I instead use the native Thunderbird Lightning CalDav to sync my ownCloud calendars using the path change specified in the linked ownCloud Central post in my previous comment.

**Comment by taich001** [comment]
I just tested it. Changing dav to caldav as you suggested does not change anything. I have been asked for password, that was ok, but then calendar is not synced. If I acivate sync again it will be disabled after a second.

I also installed nextcloud and there calendar get synced. One can enter data in thunderbird or in calendar app and it gets synced.

So I assume there is a bug in in owncloud calendar app. Is there somewhere a point in calendar app code where I can hook in and investigate.

**Comment by linkp** [comment]
Did you change caldav to dav in TbSync or did you use the Thunderbird Lightning native CalDAV option? The former does not work, whereas the latter does for me.

As for the underlying cause of the undesirable behavior, I don't know what you mean by "hook in and investigate", but there are web server logs and ownCloud logs, not to mention, based on your report that Nextcloud calendar behaves as expected, perusing the source code of both calendar apps might turn up something.

**Comment by taich001** [comment]
I got it working with TbSync.

calendar app gives me this primary calDAV address.
`https://servernm/remote.php/dav/`

But this address is wrong instead it should be this one:
`https://servername/remote.php/caldav/`

This bug should be fixed.
