### ISSUE TITLE
Shared Calendar: include "Private" appointments

### ISSUE THREAD

**Issue by peossource** [owncloud/calendar#116]
Hi,

I'm not sure if it's allowed to post feature requests?
Now I'm on ownCloud 8.2 and just recognized that you'll bring this rework with OC 9.

How about an additional calendar internal sharing option like "Including Private"?
When checked the other user (B) can see all the filtered private stuff of user A too.
This option must respect the settings of the other sharing options. So if none of the other options is selected the other user (B) can only view but the private stuff is included. If for example "create", "change", "delete" and "Including Private" is checked then the behavior for the other user (B) is effectively the same as it's it's own calendar.

This enables ownCloud to have a "family calendar" and every user (A and B) has it's own account.
When both users have access via their own CalDAV link then this will work with private stuff to.
A third user (C) can be allowed without "Include Private" if wanted.

Another advantage is when you sync via user A's CalDAV link to Outlook (company MS Exchange account), then all private appointments of user A and B (family) will be private within the company.

I've no clue how complicated this feature will be to implement but it seems that there is only a "private filter" to leave disabled...?

Best regards and thanks,
Christian

**Comment by georgehrke** [comment]
You can have different calendars. For example a "personal" calendar for your private stuff you share with your spouse and a work calendar you share with your colleagues.
Your suggestion is a complete overkill.
