### ISSUE TITLE
Security and other BUMPS

### ISSUE THREAD

**Issue by mmattel** [owncloud/calendar#1165]
There are atm 13 open bumps open including an important security one. Some of them are green, at some of them CI did not start. PR #1129 (Release Calendar 1.6.5) should in case of a new build contain the merges if done.

@phil-davis @micbar

**Comment by micbar** [comment]
@DeepDiver1975

**Comment by jnweiger** [comment]
I'd like to push forward the 1.6.5 release. Not sure how many of these version bumps should be included. I'd vote for all, unless they break our CI in a way we cannot easily fix.

**Comment by phil-davis** [comment]
@jnweiger I agree. The calendar app needs to be manually tested anyway. There are unit tests for PHP and JS, but no end-to-end automated UI tests. We may as well apply any dependabot PRs that pass the CI  that we have. Then manual testing will confirm that the app UI really works.

Who is going to press the review and merge buttons on the PRs? (I can do it when someone agrees)

**Comment by micbar** [comment]
@jnweiger @phil-davis The DEV and release cycles are managed by @DeepDiver1975 only in this app.

We need to wait until he is back in two weeks.

**Comment by jnweiger** [comment]
Ping @DeepDiver1975

**Comment by jnweiger** [comment]
@DeepDiver1975 @JanAckermann  are we ready for release here?

**Comment by DeepDiver1975** [comment]
In case the sec bumps are 'only' for build time tools there is no need for a release ...

**Comment by jnweiger** [comment]
@DeepDiver1975 Is it the case? I am happy to close the release ticket then... :-)

**Comment by jnweiger** [comment]
Probably obsoleted by #1259 ?

**Comment by jnweiger** [comment]
all pending updates were released with 2.0.0 already.
