### ISSUE TITLE
Possibility to set default alarm on new events

### ISSUE THREAD

**Issue by pulcov** [owncloud/calendar#119]
Hi,

When create a new event in calendar, there are no reminders define by default.

Would it be possible to implement a such feature, with possibility to set default reminders parameters for each calendar.

Thank you.

**Comment by georgehrke** [comment]
CalDAV allows this on a per-calendar basis

**Comment by georgehrke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Yeah, of course this would be good and we need this for feature parity eventually. However this is not a major priority given we still need to get down the basics.

(Btw @georgehrke let’s please not use the same crazy enhancement-subtags like in core. One simple »enhancement« tag is enough, no micromanagement needed.)

**Comment by georgehrke** [comment]
> Btw @georgehrke let’s please not use the same crazy enhancement-subtags like in core. One simple »enhancement« tag is enough, no micromanagement needed.

I agree that core has too many labels, but I think these two sub tags are very useful. People who are interested in contributing code by implementing new features can easily see which enhancements got approved, so they don't waste their time on thing which we eventually don't want to merge.
