### ISSUE TITLE
Release 2.0.0 for Guzzle7

### ISSUE THREAD

**Issue by phil-davis** [owncloud/calendar#1259]
for guzzle7 core issue https://github.com/owncloud/core/issues/39387

to release with oC core 10.11

**Comment by jnweiger** [comment]
## Issues seen while building
* [ ] calendar/Makefile uses rsync, this is not included in the releasesigning docker image
* [x] https://github.com/owncloud/calendar/issues/1260

**Comment by phil-davis** [comment]
Note: this needs PR #1258 "Bump owncloud min-version to 10.11 for Guzzle7" merged. That missed getting into https://github.com/owncloud/calendar/releases/tag/v2.0.0-rc.1
