### ISSUE TITLE
Check that calendar is working OK after Guzzle7 core update for core 10.11

### ISSUE THREAD

**Issue by phil-davis** [owncloud/calendar#1263]
Check the calendar app with current core master (to be 10.11 release), and raise issues for any new problems.

Related to issue https://github.com/owncloud/core/issues/39387

**Comment by kiranadh1452** [comment]
Calendar download: :heavy_check_mark:
Calendar import: :heavy_check_mark:  
Calendar Share using link: :heavy_check_mark: 

## Locally Shared calendar tests
Edit permission: :heavy_check_mark: 
Creating new event: :heavy_check_mark: 

Subscription of calendar through link (two different servers): 
  - 'Repeating' is shared.
  - 'Reminders' is not shared.
  - 'When shared show only busy' : :heavy_check_mark: 
  - 'When shared hide this event' : :heavy_check_mark: 


## Some failing cases were found inside Issues so did not mention them here.

**Comment by ho4ho** [comment]
Not clear by me if calendar app compatible by ownCloud 10.11. Any hint?

**Comment by phil-davis** [comment]
@kiranadh1452 please clarify - from your results above, I think that there are no new regressions, only whatever issues were already open about calendar?

**Comment by ho4ho** [comment]
Also have seeing by https://marketplace.owncloud.com/apps/calendar:

> [#39387](owncloud/core#39387) - Update guzzle major version to 7
>    This version requires ownCloud 10.11.0 or above

and by owncloud/core#39387:

> Calendar (owncloud/calendar#1212) - release issue owncloud/calendar#1259

so hoping calendar 2.0 + ownCloud 10.11.0 fine.

**Comment by kiranadh1452** [comment]
No new regressions were detected as of 11th July.

**Comment by kiranadh1452** [comment]
> @kiranadh1452 please clarify - from your results above, I think that there are no new regressions, only whatever issues were already open about calendar?

No new regressions were detected as of 11th July.

**Comment by ho4ho** [comment]
Thanking for clarify, issues could closed?
