### ISSUE TITLE
Enhance new event dialog design

### ISSUE THREAD

**Issue by tomneedham** [owncloud/calendar#128]
Before:
<img width="1185" alt="screen shot 2016-02-05 at 00 01 28" src="https://cloud.githubusercontent.com/assets/660805/12833929/bb665364-cb9b-11e5-84eb-926e8c6cfa1b.png">

After:
<img width="1187" alt="screen shot 2016-02-05 at 00 00 48" src="https://cloud.githubusercontent.com/assets/660805/12833930/bdebf562-cb9b-11e5-8d14-b42354a074be.png">

Tried to follow existing trends in owncloud already, and give some more focus to the dialog as it was pretty lost before. @jancborchardt 

Done in chrome inspector for now but not too hard to go through and implement.

**Comment by tomneedham** [comment]
Things missing which I couldn't get to work in 5 mins:
 - [ ] Close icon
 - [ ] 3px Rounded corners

Copying the styles mostly from the editor popover that we switched to, and using the tabs layout/design from Files.

**Comment by tomneedham** [comment]
- [ ] Inactive tabs should have a lighter font like files tabs

**Comment by raimund-schluessler** [comment]
Looks much better than before. :satisfied:

However, I miss the option to change the calendar. Will this be implemented too?

And you may consider using https://github.com/angular-ui/ui-select in the Multiselect version for the categories support, similar to how it is handled by the Tasks app.

**Comment by georgehrke** [comment]
We already have a new event dialog concept:
discussed here: https://github.com/owncloud/calendar-rework/issues/74
and being implemented here: https://github.com/owncloud/calendar-rework/pull/117 ;)

**Comment by jancborchardt** [comment]
Nice, this rocks!

@tomneedham @georgehrke please work together to get this or a new layout implemented and in the Calendar. The only piece of feedback I have for now is that the tab header should not be a header – the first thing in the dialog should be the event title. Attendees and alarms can be lower down, like in the mockups at #74

**Comment by georgehrke** [comment]
As said, #74 is already implemented in #117. Only a few minor css hickups need to be fixed.
Let's please focus on that pr. We need a working solution very soon, let's not start all over again ;)

**Comment by tomneedham** [comment]
Yes sorry @jancborchardt, I hadn't realised there was already a WIP. Will close this for now.

**Comment by jancborchardt** [comment]
@tomneedham that said, looking from the screenshots your modifications look awesome! Just apply them to push #117 forward. :)

**Comment by georgehrke** [comment]
#117 has a completely different editor. There is a simple popover with the basic input and a sidebar with the advanced input. 
No more jQuery UI :)
