### ISSUE TITLE
finish implementation for importing multiple ics files

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#13]

**Comment by wtayyeb** [comment]
Hi
I just want to tell who cares that I have write a simple python code to do an import from ics to caldav including owncloud. absolutely it is not merge-able with your php codes but it may help someone need it.

https://github.com/wtayyeb/ics2caldav

**Comment by georgehrke** [comment]
removed milestone, we first need a milestone for #46. This will be taken care of in a later sprint.
