### ISSUE TITLE
Sharing todos

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/calendar#130]
IMO, todo:
- [x] Fix jerk action when searching for typeahead (style the loading element)
- [ ] Close the sharee editor when click away
- [ ] Move cursor to input on share icon click for usabilitiy
- [ ] BUG: Sharee sees themself in list of sharees. Do we disable sharing for calendar recipients?

**Comment by georgehrke** [comment]
@raghunayyar

**Comment by georgehrke** [comment]
ping @raghunayyar
