### ISSUE TITLE
show/hide sidebar functionlaity

### ISSUE THREAD

**Issue by martingabelmann** [owncloud/calendar#134]
Have a button to show/hide the left sidebar (like the calendarplus).
Very useful for laptops/small screens.

Thanks for the nice work done so far!

greetings
Martin

**Comment by georgehrke** [comment]
that's already done by snap.js
On small screens, the left sidebar will automatically hide with an button showing up enabling you to show it.

**Comment by martingabelmann** [comment]
yeah but that is not really satisfying, see also this [issue](https://github.com/owncloud/calendar-rework/issues/134#). Thats why the calendarplus had its own implementation of this. Especially on my 15" laptop the sidebar can be annoying but is not hidden per default...

i tried to change some of the vars in snap.js to have smaller threshold value for this behaviour but without success.  is there a way of doing this?

**Comment by georgehrke** [comment]
you are linking to this very same issue

**Comment by martingabelmann** [comment]
sorry :) i`ve edited it

**Comment by georgehrke** [comment]
In @jancborchardt 's proposal in https://github.com/owncloud/calendar/issues/596#issuecomment-60216427 it sounds like it should be implemented in core

**Comment by martingabelmann** [comment]
hmm okay... the workaround to change the mobile.css seems to be good enough for me. Thought that there maybe is a way to do a similar thing in the calendar css/js code so that its not a global setting.

**Comment by jancborchardt** [comment]
Yeah. We’re experimenting with this in the Maps app, and can also experiment with it in Calendar in the future. But first we need to get the app running again. :)
