### ISSUE TITLE
Mac OS X Calendar app and iOS app cannot delete calendars

### ISSUE THREAD

**Issue by cabal95** [owncloud/calendar#136]
For whatever reason, on Mac OS X Calendar app (tested on 10.8), you cannot delete calendars from an owncloud CalDAV server.  Or, more specifically, what happens is a new "unnamed" calendar is created and then the original is deleted.  From what I can tell by looking at packet traces the following takes place when you attempt to delete a calendar:

> REPORT /remote.php/caldav/calendars/daniel/3C1B43E3-A39D-4DEF-89A9-4CE6AB177CC2/
> MKCALENDAR /remote.php/caldav/calendars/daniel/7EE1096D-C477-452E-8691-102657780A86/
> DELETE /remote.php/caldav/calendars/daniel/3C1B43E3-A39D-4DEF-89A9-4CE6AB177CC2/
> PROPFIND /
> PROPFIND /remote.php/webdav/
> PROPFIND /remote.php/caldav/calendars/daniel/
> PROPPATCH /remote.php/caldav/calendars/daniel/7EE1096D-C477-452E-8691-102657780A86/
> etc.

3C1B43E3-A39D-4DEF-89A9-4CE6AB177CC2 is the calendar to be deleted and 7EE1096D-C477-452E-8691-102657780A86 is the new calendar with the name "unnamed".

Doing a trace against Apple's Calendar Server for the same operation the only operation that is sent is the DELETE command, none of the others are sent to the server.

Trying to delete from iOS seems to do nothing.  It is removed (temporarily) from the iOS UI, but no commands are sent to the server.

Because the initial REPORT command is never executed against Apple's server, my only guess is that the results of a previous command (maybe an earlier PROPFIND) are indicating something about the server not being able to delete calendars, which Apple Calendar app deals with by creating a new empty calendar and then deleting the old one.

I don't know if this is a known issue or possibly a known shortcoming.  Maybe iCal/Calendar is doing something non-standard which is causing the problem.  So far this is the only thing I have found that keeps me from switching calendars to ownCloud, everything else seems to work. But this is unfortunately a big deal for our users with how we plan to use calendars, which requires a decent amount of deletion of calendars.  Trying to explain to them why they have to go to a website to delete a calendar "when the delete button is right there" is a difficult task.

**Comment by blizzz** [comment]
Fixed with newer SabreDAV versions.
