### ISSUE TITLE
Change event fails with iCal on MacOS X 10.7 and 10.8

### ISSUE THREAD

**Issue by jfqd** [owncloud/calendar#158]
If I create an event in iCal it is directly synced to the owncloud CalDAV-Server. After the first sync all other changes are rejected by the owncloud CalDAV-Server with a 412 Precondition failed. On the next day I can change the event one time, after that any changes are rejected again.

This behavior started with MacOS X 10.7 and is still valid with 10.8.5. It concerns owncloud 3.x up to the latest 5.0.11.

Copy from the apache log:

"PUT /apps/calendar/caldav.php/calendars/test/test/7495666C-92C4-4EF6-A720-21DF11C34F47.ics HTTP/1.1" 201 20 "-" "Mac OS X/10.8.5 (12F37) CalendarAgent/57"
"GET /apps/calendar/caldav.php/calendars/test/test/7495666C-92C4-4EF6-A720-21DF11C34F47.ics HTTP/1.1" 200 902 "-" "Mac OS X/10.8.5 (12F37) CalendarAgent/57"
"PUT /apps/calendar/caldav.php/calendars/test/test/7495666C-92C4-4EF6-A720-21DF11C34F47.ics HTTP/1.1" 412 369 "-" "Mac OS X/10.8.5 (12F37) CalendarAgent/57"
"GET /apps/calendar/caldav.php/calendars/test/test/7495666C-92C4-4EF6-A720-21DF11C34F47.ics HTTP/1.1" 200 902 "-" "Mac OS X/10.8.5 (12F37) CalendarAgent/57"

This bug is really annoying, we lost a lot of event changes through it.

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
