### ISSUE TITLE
show previous and next month in date picker

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#163]

**Comment by raghunayyar** [comment]
I am not really sure about how this affects things. cc @jancborchardt

**Comment by georgehrke** [comment]
I don't mean the entire previous and next month, but only the days in the first and last week

**Comment by georgehrke** [comment]
<img width="273" alt="calendar - owncloud chromium today at 6 47 55 pm" src="https://cloud.githubusercontent.com/assets/1250540/12984842/fddebc96-d0ef-11e5-8c68-7237413e8982.png">
In this example, we would also display January 31st and March 1st thru 5th

**Comment by jancborchardt** [comment]
Yeah, if there’s any days to fill up the line, we should show them. At 50% opacity though to signify it’s a different month. We should do the same in the datepicker on the top left, where we currently show a lot more weeks.
