### ISSUE TITLE
New user has no default calendar but can create event

### ISSUE THREAD

**Issue by tflidd** [owncloud/calendar#176]
### Steps to reproduce
1. Create new user
2. Login, go to calendar (don't create a new calendar, there is none by default)
3. Create a new event
### Expected behavior

A warning that a calendar needs to be created before a new event can be created. Or creation of a new calendar per default.
### Actual behavior

You create a new entry, click on "create", nothing happens
### Server configuration

**Operating system**: Debian 8

**Web server:** Apache

**Database:** Mysql

**PHP version:** mod_php

**ownCloud version:** 9.0 beta 1

**Calendar version:** Version 1.0 alpha 1

**Updated from an older ownCloud or fresh install:** updated

nothing in the logs (browser/server/wherever), no encryption, no other apps, no external storage.

**Comment by georgehrke** [comment]
> You create a new entry, click on "create", nothing happens

This part of the issue is related to:
https://github.com/owncloud/calendar-rework/issues/141

We should definitely add default calendars

@DeepDiver1975 Do you consider this a task of the server or the client?
@jancborchardt What default calendar(s) should be created?
One called "Personal" and another one called "Work"?

**Comment by georgehrke** [comment]
@jancborchardt And what if a user already has a writable calendar shared with them? Create the default calendar(s) anyway?

**Comment by jancborchardt** [comment]
There should always be a default calendar called »Personal«, yeah. No second default calendar needed. Just exactly as we did it with the old app as well.

**Comment by georgehrke** [comment]
Creating the default calendar is a core issue: https://github.com/owncloud/core/issues/22360
