### ISSUE TITLE
Show subscriptions by clicking on the box

### ISSUE THREAD

**Issue by tflidd** [owncloud/calendar#178]
### Steps to reproduce
1. Get a calendar shared with somebody
2. Select or unselect this calendar by clicking on the box

![unbenannt](https://cloud.githubusercontent.com/assets/8111200/12991514/d589e9d0-d10f-11e5-91f1-6a4605fd4698.PNG)
### Expected behavior

Enables or disables the view of this specific calendar. It works when I click on the text.
### Actual behavior

Nothing happens

ownCloud version: 9.0 beta 1

Calendar version: Version 1.0 alpha 1

**Comment by georgehrke** [comment]
It's the same behavior as the calendar list. Either we change both or none.

please comment @jancborchardt

**Comment by jancborchardt** [comment]
We don’t have any other action for the box, right? Calendar color editing is done via the edit menu. So clicking on the text as well as on the box should toggle the calendar visibility. :)

**Comment by georgehrke** [comment]
ok, will change the behavior :)
