### ISSUE TITLE
Hide event in shared calendar is not working

### ISSUE THREAD

**Issue by tflidd** [owncloud/calendar#179]
### Steps to reproduce
1. Share a calendar to some other user (read only)
2. Create a new event
3. Go on more...
4. Select "when shared show only busy" or "when shared hide this event"
5. Save event.
6. Re-open and edit details
### Expected behavior

Setting should be the same as they have been set. Hidden or "only busy" entries should not be visible to any other user.
### Actual behavior

Switch went back to the default "when shared show full event". The event is at full display for the other user you shared the calendar with.

ownCloud version: 9.0 beta 1

Calendar version: Version 1.0 alpha 1

**Comment by georgehrke** [comment]
@tflidd Thanks for testing and the detailed bug reports! I appreciate it :)
