### ISSUE TITLE
Send out invites 

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#195]

**Comment by georgehrke** [comment]
this is a server-side feature and should actually already happen. We just need to validate this.

**Comment by DeepDiver1975** [comment]
This is done withhttps://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/schedule/imipplugin.php

**Comment by DeepDiver1975** [comment]
There is something missing - even if an attendee is added there is no invite sent out ....

**Comment by DeepDiver1975** [comment]
I'll debug this on the server side ...

**Comment by DeepDiver1975** [comment]
the ORGANIZER is missing in the VEVENT

see https://github.com/fruux/sabre-vobject/blob/master/lib/ITip/Broker.php#L207

**Comment by DeepDiver1975** [comment]
@georgehrke where are the properties of a new event initialized?

**Comment by georgehrke** [comment]
> @georgehrke where are the properties of a new event initialized?

Right here: https://github.com/owncloud/calendar-rework/blob/master/js/app/models/veventmodel.js#L364

Do you want to add an ORGANIZER to all events, even though they don't contain any attendees? I'm really not sure about this. I would rather add the organizer on demand.

Another issue is that a user may have an e-mail address, but that's only optional. What's about users that don't have an e-mail address stored?

**Comment by DeepDiver1975** [comment]
> Another issue is that a user may have an e-mail address, but that's only optional. What's about users that don't have an e-mail address stored?

don't allow to add attendees and have a notification?

**Comment by georgehrke** [comment]
Probably the best solution for now.

Wasn't it planned to alter the user table, have a numeric user id and store the email alongside the user?
Is it planned to make an email address mandatory?

**Comment by DeepDiver1975** [comment]
> Is it planned to make an email address mandatory?

not really - at least nothing I'm aware of

**Comment by georgehrke** [comment]
okay, thx
