### ISSUE TITLE
add input for recurrence rule

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#2]

**Comment by georgehrke** [comment]
we will add rrule and exdate support in the editor for now, we might add rdate later on

**Comment by georgehrke** [comment]
we might move this one to beta1

**Comment by georgehrke** [comment]
moving to beta1

**Comment by georgehrke** [comment]
This sentence from the iCalendar standard doesn't make any sense to me:

> The numeric value in a BYDAY rule part with the FREQ rule part set to YEARLY corresponds to an offset within the month when the BYMONTH rule part is present, and corresponds to an offset within the year when the BYWEEKNO or BYMONTH rule parts are present.

https://tools.ietf.org/html/rfc5545#section-3.3.10
Page 42, first paragraph, second sentence

What is confusing me:
When BYMONTH rule is present, the offset is within the month
When MYWEEKNO __OR__ BYMONTH is present, the offset is within the year

There are two rules, that apply if BYMONTH is present. Does the RFC want me to guess in this case? I don't think so.

Maybe @evert is able to explain this. :)

**Comment by evert** [comment]
Looks like an error. See:

https://www.rfc-editor.org/errata_search.php?rfc=5545

Search for  Errata ID: 3779

**Comment by georgehrke** [comment]
Thx :)
I didn't know that page
