### ISSUE TITLE
Throw exception when adding objects containing emojis to database backend

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#20]
emojis and other 4 byte unicode characters

**Comment by georgehrke** [comment]
@codeling Would you be interested in implementing this? :-)

**Comment by codeling** [comment]
@georgehrke Yes, I'm on it!

**Comment by georgehrke** [comment]
obsolete here, still very relevant in https://github.com/owncloud/core/issues/20047

**Comment by codeling** [comment]
is there a different solution to this?

**Comment by georgehrke** [comment]
The calendar won't take care of storing the calendar objects anymore. The dav app will take care of this.
A solution has yet to be discussed.

**Comment by codeling** [comment]
Ah so the calendar rework will already work with the dav app?
Sorry about my lack of engagement those last few weeks, I've been extremely busy at work and privately, I hope to have more time at the latest second half of December!
