### ISSUE TITLE
Remove unnecessary scrollbar

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/calendar#202]
The scroll bar should only be there when it is needed?

![bildschirmfoto vom 2016-02-15 15 16 09](https://cloud.githubusercontent.com/assets/213943/13051000/2d545008-d3f7-11e5-8049-e1ea48485226.png)

@georgehrke

**Comment by georgehrke** [comment]
@raghunayyar Please take a look

**Comment by raghunayyar** [comment]
I can also reproduce this. Will make a PR asap.

**Comment by vanMacG** [comment]
Also when editing the calendar there are scrollbars, see screenshots in #250

**Comment by jancborchardt** [comment]
Fixed via my pull request https://github.com/owncloud/calendar/pull/296 – please review.
