### ISSUE TITLE
Can not enable calendars by clicking on the "checkbox"

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/calendar#203]
I observed this by myself and my wife, we both tried to enable/disable a calendar by clicking on the icon.
![bildschirmfoto vom 2016-02-16 10 06 01](https://cloud.githubusercontent.com/assets/213943/13071660/381452a6-d495-11e5-8ee0-c34775f7a08d.png)

This worked on the old calendar, but in the rework you currently have to click on the name.

Would be nice if this could be fixed.

@raghunayyar

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar-rework/issues/178

**Comment by nickvergessen** [comment]
Right, sorry
