### ISSUE TITLE
calendar downloads

### ISSUE THREAD

**Issue by simonruber** [owncloud/calendar#205]
The download icons on the right (in this example the second icon) doesn't give me a download link, it just leads me to a blank page.

The "share" icon overlaps with the "shared" icon 
![bildschirmfoto 2013-11-13 um 16 27 20](https://f.cloud.github.com/assets/5917496/1532468/25f35ccc-4c78-11e3-8130-0b5ab358906a.png)

aren't the "read only iCalender Links" at the end of the dialog just links to the downloadfiles, are they? So that this "links" and the download icons are more or less the same?
@jancborchardt 
@sabrina12

**Comment by jancborchardt** [comment]
This has been fixed some time ago. Any further issues can be reported in the Calendar repository: https://github.com/owncloud/calendar/issues
