### ISSUE TITLE
Test the new Calendar app and contribute!

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#215]
We are working on the Calendar rework for 9.0: https://github.com/owncloud/calendar-rework
The CalDAV syncing was moved into core, and this is the repo for the new Calendar app frontend.

I’m using this issue to cc everyone who worked on Calendar in the past:
@rysiekpl, @libasys, @vgezer, @ben-denham, @wtayyeb, @citronalco, @mopagemo, @nickvergessen, @ganomi, @suraia, @enoch85, @jbtbnl
You can easily help in several ways:
- test everything and open issues!
- have a look at issues and contribute (or ask developer friends to help): https://github.com/owncloud/calendar-rework/issues
- review pull requests https://github.com/owncloud/calendar-rework/pulls
- join the #owncloud-calendar IRC channel

Thanks a lot! :)

**Comment by enoch85** [comment]
`git clone`, right?

**Comment by georgehrke** [comment]
> `git clone`, right?

Either that or simply grab the latest release
https://github.com/owncloud/calendar-rework/releases

**Comment by enoch85** [comment]
Noticed that you needed ownCloud 9... JFTR; download this VM for easy deployment of 9.0-beta1: https://github.com/enoch85/ownCloud-VM/releases

**Comment by enoch85** [comment]
@georgehrke Will this be the default calendar for ownCloud 9, or do all users have to de-install the old one and re-install the new one?

Btw, REALLY great work. This looks awesome!! :beers:

**Comment by georgehrke** [comment]
It's planned that you just go to the app-management page and enable the calendar. It should automatically detect, that the old version is incompatible with ownCloud 9 and grab the new one from the App Store, but we should definitely test this prior to the release :)

**Comment by jancborchardt** [comment]
Same for the Contacts app btw – help testing! :) https://github.com/owncloud/contactsrework/issues/34

**Comment by ronnicek** [comment]
Hi,

I was checking new contact & calendar apps from @enoch85 site (https://owncloudphp7.techandme.se) and it would be great if calendar share feature can look into contact app for contacts and also if you can share it directly when you are creating event :)

**Comment by enoch85** [comment]
@ronnicek FYI, that's the old calendar and contacts app. If you want to try the new one, download the beta VM: https://www.techandme.se/pre-configured-owncloud-installaton/

**Comment by enoch85** [comment]
@ronnicek Ok, so I updated the live demo so that it now contains the latest apps (calendar alpha2) and OC 9. Feel free to test! :) https://owncloudphp7.techandme.se 
USER: testuser
PASS: testingphp7
