### ISSUE TITLE
Time is displayed wrong

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#217]
As I live in Sweden, we use military time. And it seems like no matter what changes I do to the time it stays AM/PM in the overview. But, if I click on the event, the time shows correctly.

Here are an example:
http://i.imgur.com/n2ao6qT.png

**Comment by georgehrke** [comment]
So you expect it to be 24h, but it's displayed wrong in the actual calendar-view?

**Comment by enoch85** [comment]
Yes.

**Comment by enoch85** [comment]
A did a `git clone` and edited the code directly, set correct permissions and tested.

Now I can't add specific time, and when I tested to add events on two different days and then pressed cancel - both events disappeared. Maybe I'm doing it wrong?
