### ISSUE TITLE
calendar migration skips ldap users

### ISSUE THREAD

**Issue by p5n** [owncloud/calendar#221]
### Steps to reproduce

Upgrade from 8.2.2 -> 9.0beta1 with ldap backend enabled
1. sudo -u http ./occ upgrade
2. LDAP user's calendars are missing however users from oc_users table are ok
### Expected behaviour

All calendars migrated
### Actual behaviour

Only local DB user's calendars migrated from calendar to calendar-rework
### Server configuration

**Operating system**: Arch Linux

**Web server:** apache-2.4.18

**Database:** mariadb-10.1.11

**PHP version:** 7.0.3

**ownCloud version:** (see ownCloud admin page) 9.0beta1

**Calendar version:** (see ownCloud apps page) -0.8.2 -> -rework-1.0alpha2

**Updated from an older ownCloud or fresh install:** from 8.2.2
#### Workaround
1. Revert db
2. Copy all ldap users to oc_users
3. Do upgrade again
4. delete ldap users back from oc_users table

**Comment by georgehrke** [comment]
please report this in https://github.com/owncloud/core

**Comment by georgehrke** [comment]
@DeepDiver1975 fyi

**Comment by georgehrke** [comment]
Ah, they already reported it in core, so never mind

**Comment by georgehrke** [comment]
Core issue: https://github.com/owncloud/core/issues/22508
