### ISSUE TITLE
Moving entries via drag'n'drop doesn't get reflected in opened sidebar

### ISSUE THREAD

**Issue by DemoFreak** [owncloud/calendar#225]
### Steps to reproduce
1. Create event
2. Click on it, choose "More..."
3. After sidebar opened, move or change the event via drag'n'drop
### Expected behaviour

The event starting/ending dates changes respective to the moved event.
### Actual behaviour

The dates stays unchanged, and if one click to "Accept", the changed event gets resetted.
### Server configuration

Preconfigur4ed VM 9.0.0 beta2 from https://en0ch.se/index.php/s/zfVYCMabgWdw90k
### Client configuration

**Browser:** Firefox 44.0 @ OpenSUSE Tumbleweed

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar-rework/issues/196
