### ISSUE TITLE
Translation error (German)

### ISSUE THREAD

**Issue by DemoFreak** [owncloud/calendar#226]
VM 9.0.0 beta2

The button for creation of new events reads "Neuer Ordner" ("Create folder" in english) instead of "Neues Ereignis" or "Veranstaltung erstellen".

**Comment by georgehrke** [comment]
I think there is a dedicated tracker for translation issues at transifex.

@DeepDiver1975 Can probably explain this.

This is definitely the wrong place ;)

**Comment by DemoFreak** [comment]
As I didn't know if this is a simple translation error or if the button itself is labelled wrong, and as I got a "Access denied" at transifex as I tried to contribute as requested, I thought here is a better place than "nowhere".
But YMMV. ;-)

**Comment by georgehrke** [comment]
well, it says 'create' in the original version. You can just change your language to english to check ;)
Anyway, I fixed it on transifex. It's now 'Erstellen'. :)
