### ISSUE TITLE
What does 'floating' mean in the timezone drop down?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/calendar#232]
From transifex https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/calendar-rework/75081301?reviewed=no:

But what does floating mean? As in no timezone... or 'unspecified' or something... so always in the current time of the user?

**Comment by DeepDiver1975** [comment]
@georgehrke

**Comment by georgehrke** [comment]
> always in the current time of the user

:white_check_mark: 

We should probably rename it in the source code to something more self-explanatory.
Can you think of any short phrase describing it?

**Comment by georgehrke** [comment]
@jancborchardt Do you know a good term?

**Comment by georgehrke** [comment]
maybe just `None`?

**Comment by georgehrke** [comment]
Created a pr for renaming it to `None`: #243

**Comment by jancborchardt** [comment]
Sounds good, yeah.

**Comment by jancborchardt** [comment]
Did you check how Google Calendar or iCloud do it?
