### ISSUE TITLE
Firefox style bugs

### ISSUE THREAD

**Issue by vanMacG** [owncloud/calendar#250]
I found two style bugs in Firefox. I used the current version 44.0.2.
For reference "as it should be" I included images from Chrome (Opera is also ok).
Calendar is release: Version 1.0 alpha 2
ownCloud: 9.0.0 beta 2 (testing)

First there are scrolling-buttins right to the calender name:
FF: ![cal1](https://cloud.githubusercontent.com/assets/8269814/13404413/c8828dc4-df19-11e5-9533-0996bb30e5cc.PNG) Chrome: ![cal2](https://cloud.githubusercontent.com/assets/8269814/13404420/cd91ef26-df19-11e5-88e0-13bc2ae83256.PNG)

Second, when editing the calender to choose color and change name, ok and cancle buttons are underneath:
FF: ![cal3](https://cloud.githubusercontent.com/assets/8269814/13404491/1605e50a-df1a-11e5-9eb7-0ad9c253117c.PNG) Chrome: ![cal4](https://cloud.githubusercontent.com/assets/8269814/13404497/1d58a018-df1a-11e5-8186-6529810f199c.PNG)

**Comment by georgehrke** [comment]
please use the issue template, it's already prefilled ...

Especially the used OS is interesting here

**Comment by georgehrke** [comment]
it works just fine in Firefox on OS X

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar-rework/issues/202

**Comment by vanMacG** [comment]
I run Windows 7 SP1
