### ISSUE TITLE
sharing calendars publicly via link

### ISSUE THREAD

**Issue by timorei** [owncloud/calendar#254]
It's more of a feature request, that was once available (was it 4.something) but got lost when the sharing was refactored. 

A feature very usefull for i.e. local soccer groups, firedepartments, communities, school-events,...

Ideal would be a way to generate multiple links for sharing per calendar - diversifying on permissions:

| Calendar | Public Reading | Public Editing | _ |
| --- | --- | --- | --- |
| Private | https://oc.../userY3FGD543.ics [x] | [generate] |  |
|  | https://oc.../userASDF2136.ics [x] | [generate] | [Add row] |
| Soccer Team | [generate] | [generate] | [Add row] |
| Local Firefighters | [generate] | [generate] | [Add row] |

Maybe even another mode "Public Free/Busy" could be interesting for some 'get an appointment, just call us' applications and could be implemented using mostly the same functions.

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/core/issues/22735
