### ISSUE TITLE
Feature request : improve visbility of events in day view and week view

### ISSUE THREAD

**Issue by nmset** [owncloud/calendar#256]
If succeeding events occur for example every 15 mins, they cannot be identified at a glance in day view or week view. In month view, the cell height can grow.

A similar behaviour in the two other views would enhance global usability of the calendar.

Thanks for considering.

**Comment by aproposnix** [comment]
I've created a call log calendar (synced with Android) where I have many events which are less than 15 minutes. All I see  are thin lines 
![selection_006](https://cloud.githubusercontent.com/assets/6204273/5987421/026f1e12-a929-11e4-8001-b88335746169.png)

**Comment by jancborchardt** [comment]
So we should force the minimum height of an event to text size.

**Comment by aproposnix** [comment]
@jancborchardt it would be great if this solution could also be combined with issue #693 

Here's an example from Google Calendar (note the overlap). It would be awesome if you guys could implement something like this: 


![selection_011](https://cloud.githubusercontent.com/assets/6204273/6076787/365d6c60-ade8-11e4-96df-b15ffa6d49ad.png)

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/calendar/pull/729, please test.
