### ISSUE TITLE
Consider signing the application

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/calendar#261]
You might want to consider signing the application when uploading to the appstore. Uploaded release balls on GitHub can everybody modify :see_no_evil: :speak_no_evil: :hear_no_evil: 

It would be an additional step before TAR'ing, see https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html#how-to-get-your-app-signed on how to request a certificate.

**Comment by georgehrke** [comment]
`openssl req -nodes -newkey rsa:2048 -keyout contacts.key -out contacts.csr -subj "/CN=contacts"`

@LukasReschke Can I also use 4096 or is there any limitation in core why I shouldn't do this?

**Comment by LukasReschke** [comment]
> @LukasReschke Can I also use 4096 or is there any limitation in core why I shouldn't do this?

Should also work :)

**Comment by georgehrke** [comment]
https://github.com/owncloud/appstore-issues/issues/48
