### ISSUE TITLE
When upgrading from older versions to the built in stuff in 9.0, all previous calendars are lost

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/calendar#264]
Either refuse the upgrade if older installs are present or migrate the old calendars using appinfo/updrade.php

**Comment by georgehrke** [comment]
Everything migration is now done in core.

**Comment by BernhardPosselt** [comment]
Core does not migrate previous calendars however

**Comment by georgehrke** [comment]
if that's the case, please create a bug report in core ;)
thx

**Comment by BernhardPosselt** [comment]
https://github.com/owncloud/core/issues/22883
