### ISSUE TITLE
Cancelling an event will remove previous events from current session.

### ISSUE THREAD

**Issue by stp-ip** [owncloud/calendar#282]
### Steps to reproduce
1. Create an event and save
2. Create an event, but cancel
3. See both events being gone
### Expected behaviour

The first event should still be available.
### Actual behaviour

Both events get killed.
### Server configuration

**Operating system**: Ubuntu 14.04.04 LTS

**Web server:** Apache 2.4.10

**Database:** MySQL

**PHP version:** 5.4

**ownCloud version:** 9.0.0-RC3

**Calendar version:** v1.0.0-ALPHA2

**Updated from an older ownCloud or fresh install:** fresh

**Are you using encryption:** no
### Client configuration

**Browser:** FF 44.0.2

**Operating system:** Archlinux

**CalDAV-clients:** -

**Comment by georgehrke** [comment]
not reproducible on latest master, most likely fixed.
Please speak up if it's not fixed in the stable version which will be released later today
