### ISSUE TITLE
Calendar name »contact_birthdays«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#289]
Should be called »Contact birthdays«, without technical underscore and properly capitalized.

**Comment by georgehrke** [comment]
I think this should be fixed in core, as it's the place where this calendar is generated.

@DeepDiver1975 Do you agree?

**Comment by georgehrke** [comment]
We would just have to add `'displayname' => $this->l10n->t('Contact Birthdays')` to the array in https://github.com/owncloud/core/blob/ffc29503939ae34338108a50aaaba20e1ec1ad75/apps/dav/lib/caldav/birthdayservice.php#L54

Maybe add http://graphemica.com/🎂 in front of it

**Comment by jancborchardt** [comment]
Don’t worry about an icon. But the capitalization should be correct – only capitalize the first word: »Contact birthdays«.

**Comment by jancborchardt** [comment]
For 9.0 we can’t fix it in core anymore. A way to overwrite it from the Calendar app?

**Comment by georgehrke** [comment]
Well, I would consider it a bugfix, so it should go into 9.0.1.

There are ways to overwrite it from the calendar app, but in contrast to the server, we don't know if it's a calendar created by a user who called it contact_birthdays or if it's the actual birthday calendar generated by the server. Guessing around when modifying user-data is never good.

Also the next update (1.1) is planned for early April. A fix in the calendar app wouldn't reach users much earlier than 9.0.1

**Comment by georgehrke** [comment]
potential fix is in https://github.com/owncloud/core/pull/23082

**Comment by DeepDiver1975** [comment]
> I think this should be fixed in core, as it's the place where this calendar is generated.

what could be done in the calendar app as general approach for calendars without displayname:
- capitalize the first word and replace all - and _ with a space

**Comment by georgehrke** [comment]
fix is in https://github.com/owncloud/core/pull/23128

**Comment by binarykitchen** [comment]
probably off topic, but i d like to be able to delete it

at the moment, when i click on the trash can next to it, it disappears fine but on page reload, it comes back.

**Comment by binarykitchen** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
Actually being able to delete it (also for other caldav clients) would be an issue for core. cc @DeepDiver1975 

Why is hiding it not enough?

**Comment by binarykitchen** [comment]
@georgehrke why hide when i do not need it at all? also think of performance ...

**Comment by georgehrke** [comment]
One additional entry in the XML the server sends in it's response is really not a big performance issue.

**Comment by binarykitchen** [comment]
@georgehrke i just tend to slack down things, less is better. and what if you have really lots, lots of contacts?

**Comment by georgehrke** [comment]
> and what if you have really lots, lots of contacts?

That doesn't matter. The birthday calendar is generated with a cron or when you create/edit a contact.
If a calendar is hidden your browser won't load its events from the server. The very same applies to the birthday calendar.
Concerning the initial CalDAV requests: It's just an additional row being read from the database. That's it.

**Comment by binarykitchen** [comment]
understand, thanks for explaining @georgehrke 

but the thought that the cron is computing the birthday calendar every 15 mins on my server unnecessaryily scares me. because it is already slow and increases server load.

**Comment by georgehrke** [comment]
If this really concerns you file a bug report in https://github.com/owncloud/core/issues please.
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser. If you dislike the birthday calendar being created automatically core is the place to go :)

**Comment by binarykitchen** [comment]
done, thanks for the suggestion @georgehrke
