### ISSUE TITLE
Pre-enable default calendar 

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#291]
[It was a bit confusing](https://github.com/owncloud/calendar/issues/287) before I realized that I had to choose the default calendar to show all the events.

It would be better it it was selected per default.

**Comment by georgehrke** [comment]
Definitely!

**Comment by jancborchardt** [comment]
Very important! Setting to priority.

**Comment by georgehrke** [comment]
I will check if it's easier to fix in the server, we should also set a default color

**Comment by georgehrke** [comment]
When loading the calendar for the first time the property that describes the visibility for the default calendar is neither true nor false but null.

Currently null is also interpreted as false.

@jancborchardt What do you think about the following?
If the calendar is owned by the user null should be interpreted as true.
If the calendar is shared from another user null should be interpreted as false.

**Comment by georgehrke** [comment]
still reproducible

**Comment by jancborchardt** [comment]
@georgehrke can you fix this, do you need help? We should fix it rather quickly and make sure it's updated for all installations as this is quite a dealbreaker.

**Comment by georgehrke** [comment]
It's assigned to 1.3, which is planned for next Tuesday. Will look into this in the next days :)

**Comment by jancborchardt** [comment]
Ok, please do say if you need help as we should really fix it for that next release. ;)
