### ISSUE TITLE
use email address from user object

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#292]
In the `div ui-calendar="uiConfig.calendar" id="fullcalendar"` there is an attribute: `data-emailaddress="jan@example.com"`

If anything, the correct email address should be taken from settings. :)

**Comment by georgehrke** [comment]
The email address comes straight from the personal settings:
https://github.com/owncloud/calendar/blob/master/controller/viewcontroller.php#L77

**Comment by georgehrke** [comment]
We should definitely use the proper user method in the future, but it's accessing the very same property already.

https://github.com/owncloud/core/blob/master/lib/private/user/user.php#L333

**Comment by georgehrke** [comment]
- [ ] use `$user->getEMailAddress();` instead of accessing the settings property
