### ISSUE TITLE
can't sync calendar with special char in calendar name

### ISSUE THREAD

**Issue by SunboX** [owncloud/calendar#292]
I'm using OC 6.0a on Apache 2

I created a new calendar named "André" and tried to sync it with my BlackBerry Z10 running on BlackBerry OS 10.2.1. This didn't work. Than I tried to rename the calendar to "Andre", didn't work either. After deleting the calendar and creating a new one named "Andre" it syncs fine. So I think there is a issue with special chars in calendar names.

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
