### ISSUE TITLE
Contact birthday calendar pushes itself as primary calendar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#295]
The contact birthday calendar seems to take precedence over the default »Personal« calendar. This should never happen. In the list as well as in the new event select dropdown, it should always be the last one.

**Comment by georgehrke** [comment]
Should the birthday calendar be writable at all?

**Comment by jancborchardt** [comment]
Probably not, right.

**Comment by georgehrke** [comment]
@DeepDiver1975 Is it (easily) possible make the birthday calendar read-only?
Do you want me to create an issue?

**Comment by ghost** [comment]
There was a feature request and a pull request to support reminders at the birthday calendar for the old calendar app. (can't find them currently). This would need a write able birthday calendar to delay and dismiss a reminder of a birthday.

**Comment by georgehrke** [comment]
ok, if we don't make it read-only, we can set the order to 1000 or so

**Comment by georgehrke** [comment]
The problem is that upon editing a contact the birthday event will be regenerated and any previously added alarm would be lost.

@DeepDiver1975 Is this correct?

**Comment by ghost** [comment]
Ok, found the PR: https://github.com/owncloudarchive/contacts/pull/440

Just to consider if the birthday calendar should be made read-only. The feature itself is out of scope of this discussion.

**Comment by DeepDiver1975** [comment]
> Is it (easily) possible make the birthday calendar read-only?

it should already be readonly - if not please open a bug in core - THX

**Comment by georgehrke** [comment]
will test again to make sure and report a bug if necessary

**Comment by georgehrke** [comment]
Follow up Issue in core: https://github.com/owncloud/core/issues/23046

**Comment by enoch85** [comment]
Maybe this is related to the failing DAVDroid sync? What do you think @jancborchardt @georgehrke? It tries to sync birthdays - but this happens:

```
<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:sabredav-version>3.0.7</s:sabredav-version>[LF]
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>[LF]
  <s:message>Node with name 'contact_birthdays' could not be found</s:message>[LF]
</d:error>[LF]
```
