### ISSUE TITLE
Cannot scroll subscriptions in sidebar

### ISSUE THREAD

**Issue by blizzz** [owncloud/calendar#299]
### Steps to reproduce
1. Have OC 9, migration successful, and calendars shared to you
2. Go to Calendars
3. Scroll down subscriptions in the left sidebar in order to enable them
### Expected behaviour

All calendars shared to me do appear
### Actual behaviour

At least one is not visible. 
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):** Awesome

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 42

**Operating system:** Antergos

**Comment by georgehrke** [comment]
@blizzz Can you check if this is fixed in https://github.com/owncloud/calendar/pull/296 please :)

**Comment by blizzz** [comment]
@georgehrke yes, looks like it fixes it! :)

**Comment by georgehrke** [comment]
#296 was merged
