### ISSUE TITLE
No zero after colon at full hour

### ISSUE THREAD

**Issue by scheisserchen65** [owncloud/calendar#301]
### Steps to reproduce
1. Have OC 9
2. goto calendars
3. make a new entry with a time at full hour
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache2 

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:** updated

**Signing status (ownCloud 9.0 and above):** awesome

**List of activated apps:** Calendar, Contacts

**Browser:** Firefox 42

**Operating system:** Windows 7

Hier the example for an entry at 13:00
![2016-03-09 11_35_44-kalender](https://cloud.githubusercontent.com/assets/17741575/13632686/3714e12e-e5eb-11e5-8122-498dfb820043.png)

**Comment by georgehrke** [comment]
please use the issue template, there is more than one place, where we display the time ;)

**Comment by georgehrke** [comment]
Considering https://github.com/owncloud/calendar/issues/302, the used local seems to be german

**Comment by enoch85** [comment]
I would prefer 13:00 instead of just 13 IMHO

**Comment by georgehrke** [comment]
We use fullcalendar's local. http://fullcalendar.io/docs/text/timeFormat/
So we have to options here:
1. report an upstream bug for certain languages like german or swedish 
2. kind of craft our own time string, but it's hard for us to validate that this will work for all locales.

cc @jancborchardt What do you think about it displaying just 13 instead of 13:00?

**Comment by enoch85** [comment]
Done --^

**Comment by georgehrke** [comment]
okay, makes the decision easier ^^

**Comment by enoch85** [comment]
@georgehrke Update: https://github.com/fullcalendar/fullcalendar/issues/3093#issuecomment-196921975

**Comment by enoch85** [comment]
@georgehrke another update. --^ Can this be closed?

**Comment by georgehrke** [comment]
No, we still need to add the local fixes :)

**Comment by jancborchardt** [comment]
I was also confused by this and would strongly prefer 17:00 over 17

**Comment by jancborchardt** [comment]
(Sure we don’t have much space there, but well … the time shouldn’t be bold, because it’s less important than the event text itself. Rather, the time should be at a smaller font size.)

**Comment by georgehrke** [comment]
@jancborchardt Can you take care of the CSS magic? I will make sure we never drop ':00'

**Comment by jancborchardt** [comment]
Check https://github.com/owncloud/calendar/pull/403
