### ISSUE TITLE
Wrong position for button 'new calendar' 

### ISSUE THREAD

**Issue by scheisserchen65** [owncloud/calendar#302]
### Steps to reproduce
1. Have OC 9
2. goto calendars
3. look at the left side
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache2 

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:** updated

**Signing status (ownCloud 9.0 and above):** awesome

**List of activated apps:** Calendar, Contacts

**Browser:** Firefox 42

**Operating system:** Windows 7

The button for 'new calendar' and the '+' sign are at an very ugly position  #:)
The entry new calendar is in the field of monday and the '+'-sign ist behind the 'day'-button.
![2016-03-09 11_26_57-kalender](https://cloud.githubusercontent.com/assets/17741575/13632582/a7ea7e1e-e5ea-11e5-8332-6109b12fdcf4.png)

**Comment by georgehrke** [comment]
seriously, please use the issue template ...

**Comment by georgehrke** [comment]
Bitte verwende das gesamte (!) issue template.
Mit den beiden Bugreports in ihrer aktuellen Art kann man absolut nichts anfangen und es gibt einen Grund, warum das issue template von vornherein in dem Feld ist ;)

**Comment by lukas-buergi** [comment]
That problem still exists. It seems the original poster added some of the infos the issue template asks for. Is that enough or should I submit more information?

Also I can't click on that button, it's not just in the wrong position: when clicking on it the dialog for creating a new event appears instead (which is the right behaviour for a click in that location).

Edit: Oh, right, when I click at the semi-visible plus on the very left, then I can add calendars. Just not by clicking on the text which says so.

Edit 2: And some other buttons locations are also wrong. Probably I should really file a detailed report.

**Comment by georgehrke** [comment]
> Is that enough

Yes, it's enough. But it's only reproducible with Firefox on Windows. Firefox on Linux and OS X works just fine and no one of the developers uses Windows as their main operating system, that's why it's not happened to be fixed yet. Pull requests welcome :wink:

>  And some other buttons locations are also wrong. Probably I should really file a detailed report.

yes, please :)

**Comment by bohni** [comment]
I use FF 45.0.1 on Windows 7 and Windows 10 and the Button is shown ok.
![calendar-button](https://cloud.githubusercontent.com/assets/1252254/14132961/5d9797fe-f64b-11e5-92b0-115680c65112.png)

**Comment by georgehrke** [comment]
@TT44bb What Firefox version do you use? 
Maybe this is an issue with Firefox 42 that was fixed with Firefox 45.

**Comment by lukas-buergi** [comment]
I was probably using Iceweasel (Firefox) 38.7.1 when reporting it (i.e. whatever gets installed by default on a Debian stable system), and that's the one I'm also using now, and getting lots of problems with.
I checked on Firefox 45 on Windows 10 and there is no problem there.
Don't know why I didn't note earlier that the issue depends on which browser I use. Chromium/Debian works fine too.

So... probably a browser issue and can be closed? Or do older versions of browsers still get support?

**Comment by georgehrke** [comment]
> Or do older versions of browsers still get support?

We only support the very latest version of Firefox, Safari and Chrome/Chromium

**Comment by georgehrke** [comment]
Yep, I just booted my gaming machine, updated Firefox and now I can't reproduce it anymore.

@scheisserchen65 Please update your Firefox, especially on Windows there is no reason to use an outdated firefox.

**Comment by georgehrke** [comment]
@TT44bb I'm not sure if we want to support Iceweasel. The one in Jessie is quite outdated and there is no ice weasel in jessie back ports (yet) :confused:

**Comment by lukas-buergi** [comment]
_Everything_ in Jessie is quite outdated, that's the main point of the Debian interpretation of "stable". :-D

I can understand that you might not want to support it. It kind of reduces the Debian stable vision to absurdity, though, that developers do this (understandable thing).

**Comment by bohni** [comment]
@georgehrke 

> We only support the very latest version of Firefox, Safari and Chrome/Chromium

As a developer I understand the pain of supporting multiple versions of browsers.

But you should at least also support the LTS versions, because business users often use these LTS version to minimize the necessary updates of their client machines.

**Comment by georgehrke** [comment]
> because business users often use these LTS version to minimize the necessary updates of their client machines.

Business users also have money to pay someone to add support for the LTS versions :wink:

**Comment by bohni** [comment]
@georgehrke you're right :wink:
