### ISSUE TITLE
Fallback to UTC and show error when defaulttimezone not found

### ISSUE THREAD

**Issue by onny** [owncloud/calendar#303]
### Steps to reproduce
1. Upgraded owncloud
2. Enable calendar app
3. Go to the calendar app and try to activate calendar
### Expected behaviour

Events should be displayed of the enabled calendar
### Actual behaviour

Spinning wheel keeps spinning but no events are displayed. Its possible to create and delte new calendars but they are also unresponsive and unusable. Further its not possible to create events.
I checked the mysql database and it looks like (according to the count) that all events have been merged into the new calendar table.

![screenshot from 2016-03-09 13-09-39](https://cloud.githubusercontent.com/assets/757752/13636449/e4c8a022-e5f9-11e5-9491-2453788f055b.png)
### Server configuration

**Operating system**: ArcHlinux

**Web server:** nginx 1.8.1 & php-fpm 7.0.4

**Database:** mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.2

**PHP version:** 7.0.4

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Calendar version:** (see ownCloud apps page) 1.0

**Updated from an older ownCloud or fresh install:** owncloud 8.2.2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- gallery: 14.5.0
- mail: 0.4.0
- news: 7.1.2
- provisioning_api: 0.4.1
- systemtags: 0.2
- tasks: 0.8.1
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "527b7f969713e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/share\/webapps\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "mysql.**",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "maxZipInputSize": 5145728000,
        "allowZipDownload": true,
        "trusted_domains": [
            "owncloud.***.org",
            "http.**",
            "**.**",
            "**"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***.org",
        "mail_smtpmode": "php",
        "mail_from_address": "owncloud",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** firefox 45

**Operating system:** ArchLinux

**CalDAV-clients:** none
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

Loglevel set to 0 but nothing calendar or caldav related in there.

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://owncloud.***.org 'unsafe-eval'"). calendar:1:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://owncloud.***.org 'unsafe-eval'"). calendar
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117
uncaught exception: [object Object]

b) The network log 
There was one 404 in the list for:
https://owncloud.***.org/index.php/apps/calendar/v1/timezones/ETC/UTC.ics

c) ...
```

**Comment by georgehrke** [comment]
Can you please execute the following in the javascript console and tell us the result?

```
jstz.determine().name()
```

**Comment by onny** [comment]
```
"Etc/UTC"
```

**Comment by georgehrke** [comment]
Okay, that's strange. (Nevertheless the calendar should catch this error and not silently fail)

What's your system's timezone?

**Comment by onny** [comment]
date +%Z local:

```
UTC
```

and on the server

```
CET
```

**Comment by georgehrke** [comment]
Ok, will look into it, should be fixed with version 1.1.

You can mitigate this in the meantime by setting your local timezone to a proper Olson timezone like `Europe/Berlin`

**Comment by georgehrke** [comment]
- [ ] Fallback to UTC and show error when defaulttimezone not found
- [ ] add alias from `Etc/UTC` to `UTC`

**Comment by lwinch2006** [comment]
Is it something we can do (without changing timezone) on OC9 systems with Calendar 1.0 or we need just to wait until 1.1 version released?

**Comment by georgehrke** [comment]
> OC9 systems

This isn't triggered by the server's timezone but by the user's timezone.
If you don't won't to change the user's timezone you'll have to wait for 1.1 (scheduled for April 12th)

**Comment by lwinch2006** [comment]
Yepp. I just thought that it is possible somehow to "add alias from Etc/UTC to UTC" in Linux distribs so that Calendar 1.0 would not be confused by different names but after googling understood that it is not possible. So will wait until next release. Thx for information about the problem.

**Comment by georgehrke** [comment]
> "add alias from Etc/UTC to UTC"

Nothing you can do in your distro but rather something we need to fix in the calendar code
