### ISSUE TITLE
Raise version in appstore to 1.0

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#308]
Hi,

currently https://apps.owncloud.com/content/show.php/Calendar?content=168707 has the version `0.6.7` set however the download for oC 9.0 contains version `1.0`.

Because of that the calendar will shop up with the version 0.6.7 within the oC internal appstore even if 1.0 is installed.

**Comment by georgehrke** [comment]
That's an issue in the App Store. The lowest available version (for 8.0) is 0.6.7

**Comment by georgehrke** [comment]
Not sure what do you about this :/

**Comment by georgehrke** [comment]
<img width="693" alt="edit _app_apps_owncloud_com_safari__today_at_1_43_59_pm" src="https://cloud.githubusercontent.com/assets/1250540/13669822/546b7d1a-e6c6-11e5-947b-b1251c585863.png">

The issue is related to this field. I could simply swap Content file 1 and Content file 4, but then ownCloud 8 would show 1.0 even though it's just 0.6.7.

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by ghost** [comment]
Ah, i see the issue there. Wasn't are how this is configured within the appstore.

Contacts for example is using the highest version 1.0.0.0 at https://apps.owncloud.com/content/show.php/Contacts?content=168708

**Comment by georgehrke** [comment]
Yes, this is how it looks for the contacts app:
<img width="690" alt="contacts" src="https://cloud.githubusercontent.com/assets/1250540/13669913/ed9fc5ea-e6c6-11e5-9073-15dce550cf7c.png">

**Comment by georgehrke** [comment]
Swapping it would probably be the easiest, although I think this should be properly fixed in core

**Comment by ghost** [comment]
Yes, i agree that this is rather something which should be fixed in core.

**Comment by georgehrke** [comment]
@RealRancor Could you open an issue there please? :)

**Comment by aspdye** [comment]
What have the contacts guys made different - they are also providing multiple versions for 8.0, 8.1, 8.2 and 9.0 and App Store is showing up 1.0.0.0 :confused: 

@Henni @jancborchardt @georgehrke

**Comment by georgehrke** [comment]
@aspdye Compare the screenshots ;)

**Comment by aspdye** [comment]
Have missed the second screenshot :sweat_smile:

**Comment by ghost** [comment]
Ref: https://github.com/owncloud/core/issues/23089

**Comment by georgehrke** [comment]
swapped the versions

**Comment by aspdye** [comment]
Why 1.0 instead of 1.0.0.0 like contacts does?

**Comment by ghost** [comment]
Works, https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=922&approved=all is now showing 1.0

**Comment by georgehrke** [comment]
because calendar and contacts use different versioning schemes. 
Ours is described [in the wiki](https://github.com/owncloud/calendar/wiki/Maintenance-and-Release-Schedule#versioning-scheme)

**Comment by jancborchardt** [comment]
Could we all maybe just use semver.org? cc @Deepdiver1975 @Henni

**Comment by georgehrke** [comment]
not quite sure how to distinguish between minor and patch releases for the calendar. It's planned that all releases also contain new features.

**Comment by Henni** [comment]
@jancborchardt I also discussed this with @irgendwie.
I'm wondering why owncloud needs four digits?

@georgehrke don't release patch releases. Just increase the patch number during development (for example if you need it to update the database or to mark significant changes during development).
But sometimes it might make sense to create patch releases. For example if you find a bug immediately after a major release.

**Comment by georgehrke** [comment]
> I'm wondering why owncloud needs four digits?

`major.minor.patch` and the fourth digit is used to count alphas, betas and RCs.

>  if you need it to update the database

We don't use the database anymore ^^

> For example if you find a bug immediately after a major release.

In this case I would simply release temporarily switch two mayor.minor.patch and release 1.0.1 (as an example), but I see reason to always keep the `.0` in the releases.
