### ISSUE TITLE
New calendar event not working on chrome v32

### ISSUE THREAD

**Issue by theunisdk** [owncloud/calendar#310]
### Expected behaviour
On creating an event, the modal should close and the event gets created.

### Actual behaviour
After clicking create a second modal appears behind the current one and no event is created. If you click on the modal that appears second, an error appears saying "Missing or invalid fields : Title".

It works correctly on Firefox.

### Steps to reproduce
1. Click Calender from the main nav on the left.
2. Double click on a day
3. Fill in a title in the "Title of event" field.
4. Click create event.
5.  Notice the second modal behind the one u click on.
6. Click on the modal block behind the top one to see the error.

### Server configuration
Operating system: Ubuntu 13.10
Web server: Apache
Database:mysql
PHP version: 5.5.3
ownCloud version: 6.0.0a
Updated from an older ownCloud or fresh install: Fresh install
List of activated app: Default ones plus ldap
Are you using external storage, if yes which one: No

### Client configuration
Browser: Chrome 32.0.1700.76
Operating system: Win7 64bit

### Logs
Nothing relevant in the logs. 

![owncloud_2](https://f.cloud.github.com/assets/3517286/1922637/5790f204-7e09-11e3-8c64-07276d8d466b.jpg)
![owncloud_1](https://f.cloud.github.com/assets/3517286/1922638/579701c6-7e09-11e3-906c-1a0ec808f06b.jpg)

**Comment by blizzz** [comment]
This is fixed, latest in OC 8.1, but i think already earlier. Tried with current Chromium. Please reopen if this indeed should still exist.
