### ISSUE TITLE
Add possibility to subscribe to external ics-calendar.

### ISSUE THREAD

**Issue by mdosch** [owncloud/calendar#310]
Please add support for subscribing to external ics-calendars. 
It should also be possible to subscribe to external calendars with username and password authentification.
Update interval should be configurable.

This is actually an old feature request: https://github.com/owncloudarchive/calendar/issues/344

**Comment by georgehrke** [comment]
please search for existing issue before creating new ones

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/132

**Comment by toefel1** [comment]
I can understand mdosch very good - this is one absolutely feature necessary to make the ownCloudCal a No.1 choice Calendar...

**Comment by DeepDiver1975** [comment]
> I can understand mdosch very good - this is one absolutely feature necessary to make the ownCloudCal a No.1 choice Calendar...

this is implemented for a long time.
