### ISSUE TITLE
Calendar external and internal naming

### ISSUE THREAD

**Issue by mmattel** [owncloud/calendar#311]
### Steps to reproduce
1. Create a oC calendar eg "Test" and a second calendar "BBB"
2. Sync with Outlook the via Caldav Synchronizer, the calendar name is selectable, chose "Test"
3. Delete after syncing the oC calendar "Test" and create a new one in oC with the same name
### Expected behaviour

The caldav url used (/remote.php/dav/calendars/xxxx/Test) should stay the same and syncing should be possible.
### Actual behaviour

The caldav url used has changed to "/remote.php/dav/calendars/xxxx/Test-2" and must be fresh assigned to be syncable
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) ownCloud 9.1.0 pre alpha (git)

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** via ocdev

**Calendar version:** (see ownCloud apps page) 0.82

**Signing status (ownCloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**The content of config/config.php:**

```
    "system": {
        "instanceid": "ocnyg5ougn5r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/xxxx\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.1.0.0",
        "dbname": "oclg",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/xxxx",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 1,
        "maintenance": false,
        "theme": ""
    }
}
```

**List of activated apps:**

```
  - activity: 2.3.0
  - comments: 0.3.0
  - dav: 0.2.1
  - federatedfilesharing: 0.2.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - gallery: 15.0.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.0
```
### Client configuration

**Browser:** Opera, IE11, Chrome

**Operating system:** W7x64
#### Web server error log

```
no corresponding log entry
```
#### ownCloud log (data/owncloud.log)

```
no corresponding log entry
```

**Comment by georgehrke** [comment]
I don't consider this a bug, but rather a feature request.
Why do you want this?

What is the use case?

**Comment by georgehrke** [comment]
You create a new calendar, so (imho) it's completely legitimate, that it might have a new URL.

**Comment by mmattel** [comment]
- The primary oC caldav address from settings is always the same, so it is from this point of view not visible that there was a change.
- During the first negotiation between the client and oC, the final url used is defind and selectable.
- When you now delete the calendar and create a new one with the same name or I just tried: rename it and rename it back, the internal address is now different and the sync profile broken.

From oC´s screen view and from the sync clients view, nothing has changed, but syncing is now broken and you do not see the cause for. So it is very easy to break a sync setup and have no clue why it does not work anymore.

When you delete a calendar, I expect that all data around this calendar is deleted, also from the database. When you now create a new calendar having the same name, there are no leftovers and the internal name should be the same again

And I also do not understand when you just rename a calendar it breaks syncing.

In the last case (where I checked the logs in more detail), I have seen that a fatal error is raised when trying to sync a renamed/back-renamed calendar:

```
FATAL: Exception: {"Message":"Every instance of the event must have the same organizer.","Exception":"Sabre\\VObject\\ITip\\SameOrganizerForAllComponentsException","Code":0,"Trace":"#0 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/vobject\/lib\/ITip\/Broker.php(198): Sabre\\VObject\\ITip\\Broker->parseEventInfo(Object(Sabre\\VObject\\Component\\VCalendar))\n#1 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(518): Sabre\\VObject\\ITip\\Broker->parseEvent(Object(Sabre\\VObject\\Component\\VCalendar), Array, NULL)\n#2 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(294): Sabre\\CalDAV\\Schedule\\Plugin->processICalendarChange(NULL, Object(Sabre\\VObject\\Component\\VCalendar), Array, Array, false)\n#3 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->calendarObjectChange(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), Object(Sabre\\VObject\\Component\\VCalendar), 'calendars\/xxxx...', false, true)\n#4 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(887): Sabre\\Event\\EventEmitter->emit('calendarObjectC...', Array)\n#6 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(768): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/xxxx...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), true)\n#7 [internal function]: Sabre\\CalDAV\\Plugin->beforeCreateFile('calendars\/xxxx...', 'BEGIN:VCALENDAR...', Object(OCA\\DAV\\CalDAV\\Calendar), false)\n#8 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#10 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(525): Sabre\\DAV\\Server->createFile('calendars\/xxxx...', Resource id #28, NULL)\n#11 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#12 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#13 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#14 \/xxxx\/www\/xxxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \/xxxx\/www\/xxxx\/apps\/dav\/lib\/server.php(137): Sabre\\DAV\\Server->exec()\n#16 \/xxxx\/www\/xxxx\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#17 \/xxxx\/www\/xxxx\/remote.php(138): require_once('\/xxxx\/w...')\n#18 {main}","File":"\/xxxx\/www\/xxxx\/3rdparty\/sabre\/vobject\/lib\/ITip\/Broker.php","Line":856,"User":"xxxx-xxxx"}
```

**Comment by georgehrke** [comment]
What's the use case for deleting a calendar and immediately creating one with the very same name? Why do you do that?

**Comment by georgehrke** [comment]
(to see the entire caldav url, you can hover over the calendar name and wait for the tooltip to appear)

**Comment by mmattel** [comment]
Because you pressed the wrong button too quickly...
Users are sometimes strange folks

Hoover: hmmmm, tested with Chrome: and I just see xxxx/index.php/apps/calendar/#/

Additional note: it seems that back renaming just renames the user side but not the internal once, so the calendar must be deleted and resetup...

**Comment by georgehrke** [comment]
> Because you pressed the wrong button too quickly...

That's what this issue is for: https://github.com/owncloud/calendar/issues/252

**Comment by mmattel** [comment]
And renaming?

**Comment by mmattel** [comment]
And we should cover the FATAL and make an INFO/WARNIG message instead pointing to the problem...

**Comment by georgehrke** [comment]
> And renaming?

The url is then same after renaming. The same goes for renaming twice and using the old name again. I can't reproduce what you describe.

> And we should cover the FATAL and make an INFO/WARNIG message instead pointing to the problem...

That's most likely a bug in your desktop client, that's sending an invalid calendar entry to the server. Seems related to recurring events with attendees

**Comment by mmattel** [comment]
> recurring events with attendees

This is possible, but the Fatal should be covered.

**Comment by georgehrke** [comment]
> but the Fatal should be covered.

please report this in https://github.com/owncloud/core/issues
The CalDAV server isn't part of the calendar app no more.

**Comment by mmattel** [comment]
ok
