### ISSUE TITLE
Birthdays calendar not auto-populating

### ISSUE THREAD

**Issue by bunnyfu** [owncloud/calendar#321]
After upgrading to owncloud 9.0 birthday calendar doesn't populate from contacts birthday entries. This was working fine in 8.2.2.

**Operating system**: Debian 8
**Web server:** Nginx
**Database:** Mysql
**PHP version:** 7.0.4
**ownCloud version:** 9.0
**Contacts version:** 1.0
**Updated from an older ownCloud or fresh install:** 8.2.2

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**

```
    "system": {
        "instanceid": "oc22b9a3txz2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "\/var\/owncloud\/",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logfile": "\/var\/log\/nginx\/owncloud.log",
        "appstore.experimental.enabled": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "info",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav
### Client configuration

**Browser:** Safari

**Operating system:** Mac OS X 10.11

**CardDAV-clients:** OS X Contacts, CardDav sync for Android

**Comment by ghost** [comment]
Probably a duplicate of one of those: https://github.com/owncloud/core/issues/23051, https://github.com/owncloud/core/issues/22971, https://github.com/owncloud/calendar/issues/298
