### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [owncloud/calendar#322]
Hello!
It would be cool if there would be a possibility, to add an online-caldav-abo to the app, so that it can sync with another caldav server.

**Comment by georgehrke** [comment]
You can write a dedicated app that fulfills this task, but I see absolutely no need to implement something like this in this app.

**Comment by Happyfeet01** [comment]
i would be nice if you can make this possible. Like for an EM Calendar from here: https://calendar.google.com/calendar/ical/6eg1noirmh70doip6aa3gsmnis%40group.calendar.google.com/public/basic.ics
