### ISSUE TITLE
Make 24h events shown as all day events automatically

### ISSUE THREAD

**Issue by martingabelmann** [owncloud/calendar#324]
### Steps to reproduce
1. import a calendar with this entry:

```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20160111
DTEND;VALUE=DATE:20160111T235959
DTSTAMP:20090211T175526Z
UID:201611722801
CLASS:PUBLIC
CREATED:20130101T060000Z
DESCRIPTION:  
LAST-MODIFIED:20130101T060000Z
LOCATION:example
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:exampleentry
TRANSP:OPAQUE
END:VEVENT
```
### Expected behaviour

In the week view, the event should be shown in the upper cell as all day event.
### Actual behaviour

The event is shown the whole day/spamming the week view (imagine if you have many from them).
### Server configuration

**PHP version:** 7

**ownCloud version:** 9.0.0

**Calendar version:** checkout c09293c6752deccd2f7070f3

**Updated from an older ownCloud or fresh install:** fresh

**Signing status (ownCloud 9.0 and above):** all checks passed

**List of activated apps:** standard + Calendar + Tasks

Note: The Calendar+ app already had this feature or at least something similar: 
The decribed behaviour only happens on events that i had imported from another calendar into my Calendar+ (where they were showed in the upper cell) and now from the Calendar+ to the rework (where the are showed the whole day column). Events that were created in the Calendar+ and marked as all day there are working perfectly in the rework...

**Comment by georgehrke** [comment]
> DTEND;VALUE=DATE:20160111T235959

This doesn't follow the ICAL standard. What program did create this?

**Comment by georgehrke** [comment]
Actually both DTSTART and DTEND are of type DATE, so it should already be allday, might be an upstream issue, need to investigate

**Comment by martingabelmann** [comment]
Im not sure what kind of program did that. It's from a web application of a [district office](http://www.awb-landkreis-rastatt.de/,Lde/startseite/Aktuell/Abfallkalender.html). So, I guess it's just some kind of selfmade script... 

If I understand you right, a workaround could be to `sed -i  's/DTSTART:20060910T220000Z/DTSTART:20060910T220000Z/ calendar.ical` (similar for DTEND) ?

edit:
sorry i mean 
`sed -i  's/DTEND;VALUE=DATE:20160111T235959/DTEND=20160111T235959/ calendar.ics`

**Comment by gvde** [comment]
Well, if it is VALUE=DATE then it must be a DATE according to RFC 5545. It can't be a DATE-TIME value with a VALUE=DATE. Thus technically, the VEVENT is broken and the importer must make a choice about how to interpret the DTEND value: it is meant to be

```
DTEND;VALUE=DATE-TIME:20160111T235959
```

(which is still broken in this VEVENT because the VALUE type of DTEND doesn't match that of DTSTART) or

```
DTEND;VALUE=DATE:20160112
```

(corrected after georgehrke  comment...)

Only the latter is RFC conform and only the latter makes it a whole day event.

Results of importing broken objects may always be unpredictable. I would suggest you fix the VEVENT object and tell the source how a correct VEVENT would look like...

**Comment by georgehrke** [comment]
The DTEND is actually supposed to be `DTEND;VALUE=DATE:20160112`

>  and tell the source how a correct VEVENT would look like...

LOL, asking a public office in germany to fix their IT. ^^
I admire your optimism 

Asking them to replace the DTEND with a DURATION of 1D might be easier for them than fixing the DTEND.

**Comment by georgehrke** [comment]
taking care of broken icals is not a high priority at the moment.

**Comment by georgehrke** [comment]
Documented the broken ICAL in our wiki, I think we will see more in the future:
https://github.com/owncloud/calendar/wiki/Broken-ICALs

**Comment by martingabelmann** [comment]
Actually the initial posted VEVENT does not cause the described error :
I imported the events from my Calendar+ and thought that they are exported the same way as they are imported, but what Calendar+ does is

```
DTSTART;VALUE=DATE:2016037
DTEND:2016037T235959
```

I imported a new Calendar from the website above with the syntax from the initial report. It worked very well, all events ar all day... 

From my point of view there is no further investigatement needed, because this bug is triggered by the deprecated Calendar+...

EDIT: i edited the broken icals in the wiki

**Comment by georgehrke** [comment]
okay :)

**Comment by gvde** [comment]
@georgehrke I think the import function should check for RFC compliance and if something is broken tell the user about that because the result is unpredictable and may not be as expected. That way confusion like this could be avoided to some extent...
