### ISSUE TITLE
ICS subscriptions

### ISSUE THREAD

**Issue by buzz** [owncloud/calendar#327]
Hey,

I think it would be nice if one could create subscriptions directly in the calendar app.

Like a list of subscriptions where each subscription consists of:
- Import URL
- Target calendar
- update interval (?)

The OC cronjob (I guess) would then take care of mirroring the events from the subscribed ICS file into the calendar. The calendar should probably be read-only in the calendar app front-end.

In order to be a free alternative to products like Google Calendar we would definitely need this I think. 

I created a rather hack-ish solution based on CalDAV here:
https://github.com/buzz/ics2owncloud.py
(But would be nicer to have this functionality built-in though.)

As CalDAV moved to core I'm not sure if this was the right place for creating the issue.

Thanks for feedback on this.

**Comment by georgehrke** [comment]
please search for existing issues before creating new ones ...

**Comment by georgehrke** [comment]
just search for webcal

**Comment by buzz** [comment]
I did and used many different combinations of search terms in this issue tracker and in core.
Sorry.

**Comment by buzz** [comment]
#132
