### ISSUE TITLE
Creating calendars with comps VEvent and VTodo by default

### ISSUE THREAD

**Issue by guidtz** [owncloud/calendar#329]
Hello,

   I discuss with @raimund-schluessler about update task list when calendar is created in owncloud 9 with task branch DAVClient. Could you see this : 
[(https://github.com/owncloud/tasks/issues/298)] 

> If you want calendars created in the Calendar app to appear in the Tasks app, you will have to ask the Calendar developers to change https://github.com/owncloud/calendar/blob/master/js/app/service/calendarservice.js#L166 to also specify VTodo.

Thanks for your help

**Comment by georgehrke** [comment]
What's the use case?

Task list and Calendars are, although they share the same standard, fundamentally different things.
I would definitely not like see all my calendars as a task list in my task app and I don't like to see the my `Groceries list` task list in my calendar.

cc @jancborchardt

**Comment by guidtz** [comment]
Hello, in owncloud 8 when we create a calendar, task list is auto updated with this new calendar.
So this will be optionnal, if we could choose if a task list is linked to calendar this will be sufficient.
