### ISSUE TITLE
Make sure we only ship the really needed dependencies

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#33]
Do we really need ... at all?
- [x] angular-route
- [x] fontawesome
- [x] jquery-fileupload
- [x] appframeworkjs

Do we need ... in production?
- [x] angular-mocks

**Comment by raghunayyar** [comment]
We can get definitely get rid of fontawesome if get some awesome icons from @jancborchardt. I can supply the list of icons needed, they can be a part of core.

I dont think we need mocks in production, we need it in development. jquery-timepicker is used in the events editor when the all day mode is turned off. We can think of getting rid of that as use the angular date-picker itself.

**Comment by jancborchardt** [comment]
List the icons you use from fontawesome and where/why you need them.

(Great initiative to question the dependencies!)

**Comment by georgehrke** [comment]
> List the icons you use from fontawesome and where/why you need them.

ping @raghunayyar

**Comment by raghunayyar** [comment]
I think we should use font-awesome till the time we have the editor our way, I will remove it when we start pushing it to a popover.

**Comment by jancborchardt** [comment]
I’d say drop fontawesome as soon as possible.

**Comment by georgehrke** [comment]
I'd really go with @jancborchardt here. We use at most 5 font-awesome icons in the in the events editor, probably less. font awesome is huge, shipping it is a real overkill for us

**Comment by raghunayyar** [comment]
file upload will also go once the import PR is in. \o/

**Comment by georgehrke** [comment]
angular-mocks is only a development dependency by now,
ng ui calendar requires ng-route -> can't drop

**Comment by georgehrke** [comment]
jQuery file upload will go with https://github.com/owncloud/calendar-rework/pull/58
