### ISSUE TITLE
calendars not loading

### ISSUE THREAD

**Issue by vxq9e7bx** [owncloud/calendar#330]
Unfortunately I dont know how to reproduce, but it already happened twice. Deleted the calendar/user and recreated from scratch
### Steps to reproduce (guessed)
1. create new calendar
2. sync to iOS / OSX device
3. create recurring events on these devices
### Expected behaviour

when accessing calendar app in browser, calendars should snap-load and all calendar events be displayed in their color
### Actual behaviour

blank calendar is displayed, spinner symbol instead of calendar color symbol is shown on the left.
when 'spinning' calendar is disabled, the other calendar events are loaded and displayed
### Server configuration

**Operating system**:
Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
"Debian Jessie"

**Web server:**
nginx version: nginx/1.6.2

**Database:**
mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)

**ownCloud version:** 
ownCloud 9.0.0 (stable)

**Calendar version:** 
Calendar  1.0

**Updated from an older ownCloud or fresh install:**
fresh install

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- rainloop: 4.12
- rehashpass: 0.0.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "www.weller.pm",
            "weller.pm"
        ],
        "datadirectory": "\/var\/oc_data",
        "overwrite.cli.url": "https:\/\/www.domain.tld",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "maildomain.tld",
        "mail_from_address": "cloud",
        "memcache.local": "\OC\Memcache\APCu",
        "default_language": "en",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": true,
        "enable_avatars": true,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "skeletondirectory": "\/var\/www\/owncloud\/core\/skeleton",
        "appcodechecker": false,
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "check_for_working_wellknown_setup": true,
        "config_is_read_only": false,
        "log_type": "owncloud",
        "logfile": "\/var\/oc_data\/owncloud.log",
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "debug": false,
        "cron_log": true,
        "mail_smtpauth": 1,
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "enabledPreviewProviders": [
            "OC\Preview\PNG",
            "OC\Preview\JPEG",
            "OC\Preview\GIF",
            "OC\Preview\BMP",
            "OC\Preview\XBitmap",
            "OC\Preview\MP3",
            "OC\Preview\TXT",
            "OC\Preview\MarkDown"
        ],
        "blacklisted_files": [
            ".htaccess"
        ],
        "cipher": "AES-256-CFB",
        "filesystem_check_changes": 0,
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Chrome, Safari

**Operating system:**
Windows7, OS X 

**CalDAV-clients:**
#### Web server error log

<IP> - - [16/Mar/2016:10:28:06 +0100] "POST / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:06 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 33007 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:06 +0100] "GET /index.php/core/js/oc.js?v=e022706f208c7df01c7fee5f57e76d14 HTTP/1.1" 200 2601 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 6538 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 201 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?subfiles=true&path=%2F&format=json HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /index.php/core/preview.png?file=%2FGrusiMontag.pptx&c=08237662ca2d2ad1756580e487a99ebd&x=32&y=32&forceIcon=0 HTTP/1.1" 404 6814 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /index.php/core/preview.png?file=%2FownCloud_User_Manual.pdf&c=a2d7b3d70dfb88de6557fdc3e883a8c3&x=32&y=32&forceIcon=0 HTTP/1.1" 404 6814 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:07 +0100] "GET /index.php/core/preview.png?file=%2FGutschein.pdf&c=9be1f275d5345dfaa1277d025081f9bc&x=32&y=32&forceIcon=0 HTTP/1.1" 404 6814 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:11 +0100] "GET /index.php/apps/calendar/ HTTP/1.1" 200 48941 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:11 +0100] "GET /index.php/core/js/oc.js?v=e022706f208c7df01c7fee5f57e76d14 HTTP/1.1" 200 2601 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "PROPFIND /remote.php/dav HTTP/1.1" 207 563 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "GET /index.php/apps/calendar/v1/timezones/EUROPE/BERLIN.ics HTTP/1.1" 200 356 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "POST /index.php/apps/calendar/v1/view HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "PROPFIND /remote.php/dav/principals/users/username/ HTTP/1.1" 207 574 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "PROPFIND /remote.php/dav/calendars/username/ HTTP/1.1" 207 16248 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "REPORT /remote.php/dav/calendars/username/username-calendar-name1/ HTTP/1.1" 207 12374 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:12 +0100] "REPORT /remote.php/dav/calendars/username/CALENDAR/ HTTP/1.1" 207 4787 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:13 +0100] "REPORT /remote.php/dav/calendars/username/contact_birthdays/ HTTP/1.1" 207 6840 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:17 +0100] "PROPPATCH /remote.php/dav/calendars/username/CALENDAR/ HTTP/1.1" 207 491 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
<IP> - - [16/Mar/2016:10:28:22 +0100] "PROPPATCH /remote.php/dav/calendars/username/CALENDAR/ HTTP/1.1" 207 491 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
#### ownCloud log (data/owncloud.log)

{"reqId":"xek3qF8hEllVCIZ8ii9Z","remoteAddr":"IP","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/fpm\/php.ini on line 1952 at Unknown#0","level":3,"time":"March 16, 2016 09:26:45"}
{"reqId":"zabdV3dtE7VEhuzeRlku","remoteAddr":"IP","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"March 16, 2016 09:26:51"}
#### Browser log

...

**Comment by georgehrke** [comment]
Do you remember what exact recurrence rule you used?

This looks like an infinite loop.

That the other events don't appear will be addressed in https://github.com/owncloud/calendar/issues/162

**Comment by vxq9e7bx** [comment]
@georgehrke repeat weekly until date

**Comment by utack** [comment]
Same problem, only my logfile does not complain about anything at all.

**Comment by georgehrke** [comment]
@wetsixteen And it only happens with certain until dates?

Could you send me an example if possible please :)

**Comment by jufey** [comment]
@wetsixteen
Are you using an Ipv6 adress?
I have the Same Problem if i use
Https//[Ipv6 adress]/owncloud

**Comment by utack** [comment]
excellent observation @jufey , IPv4 works for me too

**Comment by georgehrke** [comment]
What? :confused: 

There is nothing v4 specific in the code, are you sure this is not a server config issue?

**Comment by TecJon** [comment]
See maybe #334

**Comment by vxq9e7bx** [comment]
@SamEliotFisher yes, #334 could be exactly the same problem.
@jufey: in the nginx logs were IPv4, so that's not it... 
@georgehrke when the problem comes again, I will send the ics-file. for now I already had removed the calendar and recreated it... creating the exact same in OSX calendar app seems not to break it

edit: duplicate of #334, and there are more details. it is not the repeat until, but the location tag given by iOS calendar...

**Comment by georgehrke** [comment]
closing in favor of #334, as it's more detailed
