### ISSUE TITLE
Let user decide which day starts the week

### ISSUE THREAD

**Issue by TecJon** [owncloud/calendar#336]
Currently the language of the user specifies if Sunday or Monday is starts the week.

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by georgehrke** [comment]
@SamEliotFisher What's bad about the current approach to use the language? Why should it be changed?

**Comment by TecJon** [comment]
My user interface is English but I would like the calendar week to start on Monday not on Sunday.

**Comment by georgehrke** [comment]
You can use British english 

Please excuse my brevity and typos. 
Sent from my mobile

Please excuse my brevity and typos.

**Comment by TecJon** [comment]
@georgehrke interesting workaround. The issue would be solved for me then.

**Comment by areteichi** [comment]
@georgehrke 
I use my ownCloud in German but I want the week to begin with Sunday...

**Comment by jancborchardt** [comment]
Please see this core issue: https://github.com/owncloud/core/issues/376 (global region format) – any contribution is welcome! :)

**Comment by ghost** [comment]
No British English option in my Personal > Language settings, only English so can't change start day of week or date format from m/d to d/m.

**Comment by MRZA-MRZA** [comment]
I can't select British English. I want to use English and Monday as first day of a week.

**Comment by jadesoturi** [comment]
The British English selection is further down in the list, between Eesti and Español(Mexico). Solved the problem for me at least..

**Comment by sgofferj** [comment]
I find it almost absurd to have to change language settings to British English just to have the calendar in the "right" format. EVERY calendar app I know allows setting of preferred first day of week, date format and time format. For good reason! There's people living in foreign countries which use their native or an agreed-on common language but still use the date and time formats of the country. Or also agreed-on date an time formats.
I, for example, am German, live in Finland, use American English as working and everyday language and usually ISO8601 date/time format and 24 hour format for time only. Removing this settings made the Owncloud calender app pretty much unusable for me.

**Comment by llalueza** [comment]
If you are still interested on this feature, you can easily hack it with almost no effort.

ownCloud's calendar is using `moment` as a time library, so you can easily configure it by [following `moment` API](http://momentjs.com/docs/#/i18n/changing-locale/). Assuming this we only have to include to `<owncloud_dir>/apps/calendar/js/public/app[.min].js`:

```js
moment.locale('en', { week: { dow: 1 }});
```

Note that the important part is the `dow: 1` which indicates the starting day of the week will be Monday.

Hope this helps!
