### ISSUE TITLE
Add ability to share a calendar without details

### ISSUE THREAD

**Issue by TecJon** [owncloud/calendar#337]
A way of sharing a calendar without its details meaning without the title, location, description etc. of the events. Effectively only idle/free times are shared.

**Comment by georgehrke** [comment]
https://github.com/owncloud/core/issues/22914

**Comment by TecJon** [comment]
Thanks for pointing this out.
Is also a feature planned to find a common time slot with another user for an event?
Meaning similar to "Find a time" of Google calendar. [https://support.google.com/calendar/answer/37161](url)

**Comment by georgehrke** [comment]
Not at the moment. Due to some limitations in the ownCloud CalDAV server I doubt that this is possible right now. Maybe after ownCloud 9.1 or 9.2
