### ISSUE TITLE
Calendar loading in loop for a specific day

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/calendar#338]
### Steps to reproduce

After upgraded from 8.2 to 9.0 and enabling calendar .. (previously I used calendar plus on the 8.2)
### Expected behaviour

See 20 march event as usual..
### Actual behaviour

When I show event by week or month, the calendar are loading in loop. If I use "day" view I have see the behavior for 20 march only. So I think an event at his date is corrupt/broken.
### Server configuration

Ubuntu 14.04

**Web server:**
apache2

**Database:**
mariadb
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0
**Calendar version:** (see ownCloud apps page)
1.0
**Updated from an older ownCloud or fresh install:**
update from 8.2 to 9.0
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

Enabled:
- activity: 2.2.1
- announcementcenter: 1.1.1
- calendar: true
- comments: 0.2
- contacts: true
- dav: 0.1.5
- documents: true
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- news: true
- notes: 2.0.0
- notifications: 0.2.3
- ownbackup: 0.3.8
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- files_external
- files_sharing
- files_texteditor
- user_external
- user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

m{
    "system": {
        "instanceid": "ocd190207304",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "192.168.1.3",
            "nxworld.club",
            "www.nxworld.club"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "force ssl": "true",
        "appcodechecker": false,
        "memcache.local": "\OC\Memcache\APCu",
        "theme": "",
        "default_language": "fr",
        "enable_previews": "true",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "mail_smtpdebug": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtptimeout": 10,
        "mail_from_address": "pgagne",
        "mail_domain": "gmail.com",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "loglevel": 2,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
see zip file
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

[owncloud.zip](https://github.com/owncloud/calendar/files/178934/owncloud.zip)

**Comment by enoch85** [comment]
Please change milestone @georgehrke if it's wrong.

**Comment by georgehrke** [comment]
Anything in the browser log?

**Comment by georgehrke** [comment]
This is most certainly related to a repeating event. Please connect with a caldav client (which will most likely be able to show all events) and check if there is any repeating event on March 20th.
If yes it would be great if you could post it :)

**Comment by thenamelessthing** [comment]
I have only one event at this date., it's not a repeating event. I can see the event on my Android phone but not on the OC webpage.

How can I post it's content?

**Comment by georgehrke** [comment]
You can probably export it on android. Send it to yourself via mail and copy the content with a text editing software.

You might want to look thru the data and replace personal data with some dummy values.

**Comment by thenamelessthing** [comment]
I found how, here is the event zipped.
[Match série 1954782429.zip](https://github.com/owncloud/calendar/files/180167/Match.serie.1954782429.zip)

**Comment by thenamelessthing** [comment]
One thing I have try with success, I have deleted the problematic event (from my android phone) and importing the broken event I join in this issue and the problem was fixed! So it's strange because it look the event was repaired when exporting it or the problem was in the db itself and not in the event...? So we can close
