### ISSUE TITLE
Need to be able to import ICS files

### ISSUE THREAD

**Issue by syntax922** [owncloud/calendar#339]
### Steps to reproduce
1. Double click ICS file that has been uploaded to OwnCloud
   2.
   3.
### Expected behaviour

Options are displayed for which calendar to import to
### Actual behaviour

Text file is displayed with information
### Server configuration

**Operating system**: Ubuntu 14.04 (trusty)

**Web server:** Apache2

**Database:** my sql

**PHP version:**

**ownCloud version:** 9.0.0 Stable

**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2

**Signing status (ownCloud 9.0 and above):**

no issues

**List of activated apps:**
Calendar
Contacts

```
```

**Comment by syntax922** [comment]
#StupidEndUser

**Comment by czettnersandor** [comment]
What was the solution here?

**Comment by syntax922** [comment]
It's in the lower left when you're in the calendar view.
