### ISSUE TITLE
Calendar settings gone

### ISSUE THREAD

**Issue by robertwenner** [owncloud/calendar#340]
### Steps to reproduce
1. Upgrade Owncloud from latest 8.x to 9.0.0
2. Enable calendar app
3. Go to calendar app
4. Click the settings gear symbol on the bottom left
### Expected behaviour

I'd expect to see settings for time zone and date / time format, as described in the manual at https://doc.owncloud.org/server/9.0/user_manual/pim/calendar.html#managing-calendar-settings
### Actual behaviour

I only see the caldav URLs, but no settings. See attached screenshot.
### Server configuration

Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic i686)

**Web server:**
Apache2

**Database:**
mysql  Ver 14.14 Distrib 5.5.37, for debian-linux-gnu (i686) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4 (cli) (built: Apr  9 2014 17:08:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Calendar version:** (see ownCloud apps page)
1.0

**Updated from an older ownCloud or fresh install:**
Updated over various 7 and 8 releases.

**Signing status (ownCloud 9.0 and above):**

```
Not Found

The requested URL /index.php/settings/integrity/failed was not found on this server.
Apache/2.4.7 (Ubuntu) Server at media.olalmaro Port 80
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - bookmarks
  - encryption
  - external
  - files_external
  - search_lucene
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc62a90a0174",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "media",
            "media.local",
            "media.olalmaro"
        ],
        "datadirectory": "\/home\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "forceSSLforSubdomains": true,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
none
### Client configuration

**Browser:**
Firefox or Midori on Ubuntu 14.04.4 LTS

**Operating system:**
Ubuntu Linux

**CalDAV-clients:**
none
#### Web server error log

```
[Sun Mar 13 06:25:03.142103 2016] [ssl:warn] [pid 27306] AH01909: RSA certificate configured for media:443 does NOT include an ID which matches the server name
[Sun Mar 13 06:25:03.142397 2016] [mpm_prefork:notice] [pid 27306] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Mar 13 06:25:03.142416 2016] [core:notice] [pid 27306] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 18 20:11:52.274408 2016] [:error] [pid 29185] [client 192.168.11.122:58481] script '/var/www/html/index.php' not found or unable to stat
```
#### ownCloud log (data/owncloud.log)

```
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20100525+lfs\/wikidiff2.so' - \/usr\/lib\/php5\/20100525+lfs\/wikidiff2.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2014-06-30T03:20:17+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20100525+lfs\/wikidiff2.so' - \/usr\/lib\/php5\/20100525+lfs\/wikidiff2.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2014-06-30T03:20:47+00:00"}
```
#### Browser log

```
Firebug console:

4
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://media.olalmaro 'unsafe-eval'").


onsubmit attribute on DIV element

5
TypeError: events is undefined


for (var i = 0; i < events.length; i++) {


app.js?...207ce8b (line 2139, col 24)
```

**Comment by robertwenner** [comment]
![calendar-no-settings](https://cloud.githubusercontent.com/assets/7452108/13896030/5459f5fe-ed4c-11e5-9b1d-95d264e0ed67.png)

**Comment by georgehrke** [comment]
I'm afraid the manual is outdated,
it's intended that these settings are gone.

**Comment by raghunayyar** [comment]
Can we please update the manual?

**Comment by georgehrke** [comment]
sure, go ahead ^^

**Comment by georgehrke** [comment]
https://github.com/owncloud/documentation/blob/master/user_manual/pim/calendar.rst

**Comment by robertwenner** [comment]
Why are these settings gone? How do I adjust these now? If these are gone, does that mean I am stuck with am/pm instead of 24 hours, for example?

**Comment by georgehrke** [comment]
These options are automatically determined by the language used.
If you use german, the week will start on Mondays and it's 24 hours.
The same goes for british english.

**Comment by robertwenner** [comment]
Oh, I see. I guess that makes it much easier for most people. However, it leaves everybody else stuck with settings they don't want. For example, people who chose to run their systems in English so they don't have to wait for various translations, or expats.

Can I file a change / feature request for this?

**Comment by raoel** [comment]
Yeah, please, I like my OS and everything set to English but I always configure 24h timezones in every app. An application that does not support this would be a first time for me.

**Comment by gvde** [comment]
> Yeah, please, I like my OS and everything set to English but I always configure 24h timezones in every app. An application that does not support this would be a first time for me.

The language and the 12h clock settings of a OS are two very separate things in all OS I know. Thus, set your OS to 24h clock and all times in all your applications should be 24h clock.

Setting your OS to 12h clock and then hoping that all your applications allow you to override the OS setting to 24h is... optimistic at least. I don't see the point of that.

**Comment by robertwenner** [comment]
> Setting your OS to 12h clock and then hoping that all your applications allow you to 
> override the OS setting to 24h is... optimistic at least. I don't see the point of that.

Isn't this a per-user setting anyway?
Or should it be?
Shouldn't I be able  set my time format to 24h, and allow other users to use am/pm if they prefer?

**Comment by georgehrke** [comment]
There is a discussion about adding a dedicated region format in core.
We won't re-add time format and first day of week in the calendar though!

https://github.com/owncloud/core/issues/376

**Comment by raoel** [comment]
@gvde My OS is set to "English US" and then I changed the date-format to 24h.
Owncloud calendar sticks to am/pm though. 

I looked through my Chromium-settings and only thing I can change is the language-settings, nothing on dates. I think Chromium is telling Owncloud I have set EN-US and therefore the default setting is am/pm.

**Comment by gvde** [comment]
> Shouldn't I be able set my time format to 24h, and allow other users to use am/pm if they prefer?

Yes. Your OS allows multiple users and each user can set it's own language, region, locale settings. Your browser usually uses these settings which the user has defined in the OS.

**Comment by georgehrke** [comment]
> I think Chromium is telling Owncloud I have set EN-US and therefore the default setting is am/pm.

:+1:

**Comment by robertwenner** [comment]
> Yes. Your OS allows multiple users and each user can set it's own language, region, locale 
> settings. Your browser usually uses these settings which the user has defined in the OS.

I thought this was an owncloud **server** setting, not a browser or client OS setting.

Could you point me to the correct settings?
I have my client set to 24 hour format (clock in XFCE, date shell command, LC_DATE), and still owncloud uses am/pm.
In Firefox, when I go to Preferences > Content > Languages and make German / Germany the top item and reload the owncloud calendar page, I still get am/pm. When I restart Firefox, I get a German text "Angemeldet bleiben" on the login page, but still dates show up in am/pm.
I don't see any other locale settings in Firefox.

**Comment by robertwenner** [comment]
> There is a discussion about adding a dedicated region format in core.
> We won't re-add time format and first day of week in the calendar though!

Well, I am not familiar with the technical details, and if there is an owncloud-wide setting for time format and start of the week which the calendar honors, that certainly works for me.

**Comment by gvde** [comment]
> I thought this was an owncloud server setting, not a browser or client OS setting.

No, generally, language and formatting is an issue of the frontend, thus it's related to the locale settings on the computer. That defines how a date/time is converted into a string.

Of course, things get more complicated once you start using browser or other settings to modify that. The browser language settings determine which language(s) are requested from the server when the server has multiple languages to offer. This affects language of text in the html document. It does not affect the JavaScript a web server delivers to your browser and which runs on your computer: if the JavaScript uses standard locale it will show you date/time strings in your computer locale, even though maybe buttons, labels, etc. on the web page are in a completely different language. But it depends on the JavaScript rendering the application in the browser...

The owncloud server has it's own language setting which unfortunately is used to override everything else by the server. So they don't seem to rely on the frontend locale and use scripts in the browser to do the formatting but instead have a language settings which combines locale, texts, buttons, everything. 

Thus if you set the language to "English" it's U.S. English and they format everything in the way they think an U.S. American expects it. If you use British English, you get British texts and formatting including 24h clock.

So it seems at this time you are stuck with what they offer which is far inferior to what most operating systems now offer.  I hope at some point they will switch that to the frontend so that the user can define what he wants on his computer and it's formatted that way...

> I don't see any other locale settings in Firefox.

It's a setting of the operating system. Your Windows, OS X, Linux, or whatever you use. But it seems owncloud doesn't make use of that but instead does everything on it's own, again...

**Comment by robertwenner** [comment]
I've been thinking about this a bit now.

First, I think using the user's settings to pick defaults is a good idea. You probably get it right in most cases. However, I'd still like to configure this and override the defaults, and here is why.

There are enough reasons the locale does not necessarily reflect the preferred time format; see for example https://www.w3.org/International/questions/qa-accept-lang-locales But most importantly, changing my browser's accept-language like suggested in this thread seems out of proportion. Just because I want ONE page (the owncloud calendar) to display 24 hour format, I'd have to change my global browser settings that effect ALL pages I visit --- with possibly unknown consequences on other pages. IMHO it would be better to have one setting for one thing, i.e., owncloud (calendar) time format for owncloud calendar times (or even owncloud times), but not have my owncloud settings possibly interfere with some other random page that also happens to use accept-language.

What do you think?

**Comment by georgehrke** [comment]
> But most importantly, changing my browser's accept-language like suggested in this thread seems out of proportion

That's not necessary. There is a language option in ownCloud's personal settings. If you configure a language in your personal ownCloud settings, ownCloud will ignore your browser's accept-language.

**Comment by robertwenner** [comment]
Awesome! That was not clear to me. I can live with this solution.

Just one thing: please make sure that goes in the manual or even better in the settings page. I'd never have guessed that setting the language to German would get me 24h time format.

**Comment by josh4trunks** [comment]
I'm trying to change my language to German in my Personal Settings but it's not saving. Other changes save just fine but every time I reload the personal Settings page the language is reset to English.

I prefer to use 24h format, and start my week on Mondays. @georgehrke Any ideas why it's being reset and do you have any suggestions? Thanks

**Comment by georgehrke** [comment]
> I'm trying to change my language to German in my Personal Settings but it's not saving.

That's obviously not a bug in the calendar. please report in https://github.com/owncloud/core/issues

**Comment by josh4trunks** [comment]
makes sense.

assuming I don't change my language is the calendar app reading LC_TIME for my operating system? I'm wondering if that's the best solution in my case.

**Comment by georgehrke** [comment]
If you don't select a language in your personal settings,  ownCloud will fallback to  your browser's language.

**Comment by josh4trunks** [comment]
OK, so owncloud language is the prefered way to set this. thanks

**Comment by gvde** [comment]
> If you don't select a language in your personal settings, ownCloud will fallback to your browser's language.

If that's the case then there seems to be no way in the settings to unset the selection, i.e. fall back to the browser's preferred language...

**Comment by georgehrke** [comment]
@gvde again, calendar is not the right place :wink: 
Please report a bug in core :)

**Comment by ChargingBulle** [comment]
see [core#376](https://github.com/owncloud/core/issues/376).
