### ISSUE TITLE
Revise color selection for calendars

### ISSUE THREAD

**Issue by TecJon** [owncloud/calendar#344]
### Some (design) suggestions for the calendar colors
- Provide more colorful and high-contrast default colors (currently eight).
  - I'd suggest red, orange, yellow, green, blue, purple, pink, brown (similar to OSX)
- Provide a 'other' or 'more' option to choose a custom color: #135 
  - The 'other' or 'more' could be realized by a plus symbol occupying and replacing the last rectangle to choose a color.
- Prevent a messy line break when editing a calendar:
  - I'd suggest a single line for colors and a single line for both buttons.

![calendarcolor](https://cloud.githubusercontent.com/assets/11375752/13897987/73174438-edc4-11e5-81da-ea03c97cdca0.png)
- Also remove both scroll bars, as the horizontal bar wasn't mentioned in #335 yet.

Here a quick suggestion how it could look like
![calendarsuggestion](https://cloud.githubusercontent.com/assets/11375752/13898129/5ff80fbe-edc8-11e5-8fa3-be5758b5e4e7.png)
Note, of course the text input, the colors and the buttons should be aligned on the right.

**Comment by georgehrke** [comment]
generally speaking create one ticket per actual issue please.

I'm very happy with the current colors and I think the ones you are suggesting are bad for readability.
As you already said there is a ticket for the second issue.

Can we agree to make this ticket about the third issue?

**Comment by georgehrke** [comment]
cc @raghunayyar

**Comment by TecJon** [comment]
I wanted this thread to collect ideas. Once agreed, each issue can be opened in a single ticket.

I guess the colors truly are a matter of taste. However, I think current colors 1, 2, and 4 are too similar and including 3 a little too dull. The ones I suggested in the image were quickly chosen, a designer should advise on actual good choices for readability (the red and orange are quite similar, too). Nonetheless, I would vote for more colorful default colors. :-)

**Comment by georgehrke** [comment]
I would agree that 1,2 and 4 are too similar.
"Dull" colors are not necessarily a bad thing. These colors don't need to be bright and shiny. What's important is that you can read the text very easily. A bright and shiny background is often bad in this regard.

**Comment by TecJon** [comment]
I agree, readability should be the primary concern here. 

But I believe readability and a little colorfulness are not mutually exclusive. For example the labels on here on github are quite colorful yet easy to read.
OSX solved the issue by using a lighter version of the color as the background color of the event.

![Image of OSX calendar 1](http://cdn.cultofmac.com/wp-content/uploads/2015/03/Week-View.jpg)

One could think about matching the owncloud contacts app colors.

**Comment by georgehrke** [comment]
Well, that ain't OS X Calendar but Fantastical, but I like that as well. :wink:

**Comment by TecJon** [comment]
Oh haha! Well that's a little unfortunate. :smiley: 

For the sake of completeness 
![Really OS X calendar](http://images.apple.com/v/mac/shared/osx/g/images/builtinapps/calendar_screen_large.jpg)

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by j-ed** [comment]
I like the idea of having more colorful and high-contrast default colors too. I cannot understand why a user should be limited to low-contrast default colors only. Many people cannot differenciate colors correctly or need to wear glasses so that it is essential for them to select colors based on their requirements. Unfortunately this is ignored by many developers because they didn't know or due to design descisions. The original color-picker mockup of @SamEliotFisher therefore seems to be the right way to go.

**Comment by eesko** [comment]
Custom color selection would be useful. I have a number of calendars that are color coded across all different programs/devices that I use. The limited color choices in the ownCloud calendar app make it impossible to use the colors I use across all other programs/devices. Also if I happen to have more than eight calendars I must currently assign same color for more than one calendar.

I also think that the dark colors are too close to each other. Some of the other default color choices seem odd to me as well. There is a gradient from yellow to orange to red but only one shade of blue and no green at all.

**Comment by koenlek** [comment]
I agree with @eesko, a custom color picker would be great, 8 colors is not enough for me...

**Comment by raghunayyar** [comment]
@koenlek @eesko Contributions are welcome. :)

**Comment by georgehrke** [comment]
As mentioned in this issues description: There is an issue for a rich color picker: https://github.com/owncloud/calendar/issues/135

**Comment by jancborchardt** [comment]
@eesko @koenlek can you elaborate on why this is not enough? How many Calendars do you have?

cc @skjnldsv by the way – it would be good to generate the calendar colors with the core script. Currently they are hard coded.

**Comment by skjnldsv** [comment]
It's possible! Do you want me to open a pr? :)

**Comment by jancborchardt** [comment]
@skjnldsv that would be pretty damn cool! :) Cause the calendar colors are something I overlooked on the list of where we want to stay consistent on colors.

**Comment by skjnldsv** [comment]
@jancborchardt damn I almost forgot about this issue! :)
Should we use the same colors from owncloud/mail#1434 ?

Or should we add a color wheel?
And the ability to choose a random color from the generator?

**Comment by jancborchardt** [comment]
Use the same colors as in Mail I'd say. Not a wheel or generator, just the grid of 8 colors as we do now. Since there's 9 in mail, just cut the turqoise right next to green – not that easy to distinguish anyway.

**Comment by skjnldsv** [comment]
That's a shame I can't choose my own color though! :/

**Comment by jancborchardt** [comment]
Well, first comes the proper color adjustment. Custom colors is a separate thing and has way lower priority. ;)

**Comment by jancborchardt** [comment]
(Way lower priority than some other Calendar issues, that is. :)

**Comment by skjnldsv** [comment]
:p

**Comment by skjnldsv** [comment]
@jancborchardt Hum, I've been thinking, and I don't think we can use the core generator. The calendar app is using a defined color code, and it's not using a string or a hash to generate a color. Aside from using the idea of associating a hash to a calendar and use it for the color generator, I can't use the color function to generate a set of valid color for the user to choose. 

I don't see if i'm understandable or not, but this should be an issue.
I really think we should associate a calendar id and let the user change it to generate a new colour for his calendar.

**Comment by skjnldsv** [comment]
@jancborchardt bump

**Comment by jancborchardt** [comment]
@skjnldsv right – what we can do easiest at the moment is to simply get 8 colors out of the algorithm across the color spectrum and replace the hardcoded list in calendar with those. That way calendar will use the same color spectrum as the rest. Ok?

**Comment by skjnldsv** [comment]
Ok, will work on it this week! :)
