### ISSUE TITLE
ICs file can't import

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#348]
Hi, I am pretty much upset about the continuous changes to the worst and not to the better!
I wanted to import a .ICs file in an existing calender, but it does not work at all, the way it used to be in the past. I am getting sick and tired of OwnCloud and the way it handles common tasks!

regards, hitam4450

### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
By clicking on ICs file, it should import into existing folder!
### Actual behaviour

Tell us what happens instead
It does not import, only shows content
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0
**Calendar version:** (see ownCloud apps page)

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
the import moved to the app. Click the gear in the lower left corner

**Comment by georgehrke** [comment]
> upset about the continuous changes to the worst

This is free software. Contribute!

**Comment by hitam4450** [comment]
I contribute since a long time ago, already!
![calendar](https://cloud.githubusercontent.com/assets/9738727/13904883/acb8484a-eeaf-11e5-920e-34b9595cb110.png)

Hiding a **menu (Action- Kalender importieren ) Item** under **Option (Einstellungen)** menu is not really intuitive, not understandable and not traceable!

In the option menu is for selecting options and not for tasking actions!
That is at least my understanding!
In this case Kalender importieren ist located at the wrong place, because of the logic of the menu **option**

regards, hitam4450!
