### ISSUE TITLE
OC9 - unable to select and contantly activate subscribed calendars

### ISSUE THREAD

**Issue by j-ed** [owncloud/calendar#351]
## Expected behavior

It should be possible to select and activate all subscribed calendars under the
subscription section and keep them activated until a different descision is felt.
## Current behavior

Only some of the subribed calendars under the subsription section are displayed,
but all of them are inactive. It is not possible to scroll down to show all available
calendars, except you reduce the browser zoom level, because no scrollbar is
displayed for these calendars.

Additionally it is possible to constantly activate these calendar because they are
automatically disabled again once the calendar app is closed.
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.0.0 (20160320)
Updated from OC8.2.2
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by georgehrke** [comment]
> Only some of the subribed calendars under the subsription section are displayed,
> but all of them are inactive. It is not possible to scroll down to show all available
> calendars, except you reduce the browser zoom level, because no scrollbar is
> displayed for these calendars.

dup of https://github.com/owncloud/calendar/issues/299

> Additionally it is possible to constantly activate these calendar because they are
> automatically disabled again once the calendar app is closed.

That's a server related issue that will be fixed with ownCloud 9.1.
Not related to the calendar app.
