### ISSUE TITLE
OC9 - calendar authentication credentials need to be re-entered because the calendar naming has changed

### ISSUE THREAD

**Issue by j-ed** [owncloud/calendar#352]
## Expected behavior

After upgrading from OC8.2.2 to OC9.0 it should be possible to access and use all
CalDAV calendars without re-entering the authentication credentials.
## Current behavior

The authentication credentials for all subscribed calendars need to be re-entered
in e.g. Thunderbird/Lightning because the calendar naming has slightly been changed.

Example:
OC 8.x: https://your-server-url (**ownCloud** (Name of calendar))
OC 9.x: https://your-server-url (**sabre/dav** (Name of calendar)) 
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.0.0 (20160320)
Updated from OC8.2.2
#### Client Configuration

Browser: Thunderbird 38.7.0/Lightning 4.0.7
Operating system: Windows 7

**Comment by georgehrke** [comment]
caldav issue -> please report in https://github.com/owncloud/core/issues
