### ISSUE TITLE
OC9 Unable to change the color of a calendar

### ISSUE THREAD

**Issue by Noo75** [owncloud/calendar#353]
WIth Owncloud, it was easy to change the color of a calendar: https://doc.owncloud.org/server/8.0/user_manual/pim/calendar.html

Now with the new Calendar app, the "settings wheel" doesn't show up. 

![oc_calendar_9](https://cloud.githubusercontent.com/assets/17979180/13914554/564e297a-ef4f-11e5-9585-e61d85205f25.png)

Is it still possible to change the color of the calendar?

**Comment by raimund-schluessler** [comment]
That's a bug, see https://github.com/owncloud/calendar/issues/347#issuecomment-198939569. It will be fixed with version 1.1.
