### ISSUE TITLE
CLASS-Settings (rfc5545, section 3.8.1.3) are not editable via owncloud-GUI nor will be respected on sharing

### ISSUE THREAD

**Issue by mape2k** [owncloud/calendar#354]
In 2012/2013 i added support for CLASS-Settings to owncloud calender which are editable on Web-GUI and respected on sharing calendar with others (e.g. did not show or just show busy).

After upgrade to 9.0 (also latest daily!) this feature is gone and all events (also private!) are exported on sharing. The entries will also be fully exported if you're using a DAV-Client like Thunderbird. 

**This is a big privacy issue!**

This issue could also be related to https://github.com/owncloud/core/issues/23317.
### Steps to reproduce
1. Install/Migrate to owncloud 9 (or latest daily).
2. Create user with calender.
3. Add a entry with class PRIVATE or CONFIDENTIAL (others than PUBLIC) using a DAV-Clients which supports CLASS-Feature (e.g. Thunderbird/Lightning).
4. Create another user and share your calender to this user.
5. Login as second user and see your PRIVATE entries :(
### Expected behaviour

PRIVATE entries should not be exported on Sharing
CONFIDENTIAL entries should be exported with a few fields and Summary "Busy"
(see implementation in 2012 via https://github.com/owncloud/apps/pull/309)
### Actual behaviour

All 
### Server configuration

**Operating system**:
Gentoo
**Web server:**
Apache 2.4
**Database:**
MySQL 5.5
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0
**Calendar version:** (see ownCloud apps page)
1.0
**Updated from an older ownCloud or fresh install:**
update from 8.2.3

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** FF45

**Operating system:** Gentoo

**CalDAV-clients:** Thunderbird/Lightning

**Comment by georgehrke** [comment]
Well, it's already in the code, but I had to comment it out in the GUI, because the new CalDAV server doesn't support it anymore.
https://github.com/owncloud/core/issues/22914

**Comment by mape2k** [comment]
There's no warning on update or in calender, so you just want to ignore this major privacy issue in also Changelog?
