### ISSUE TITLE
CalDAV Link for each Calendar missing

### ISSUE THREAD

**Issue by brrrrrrrt** [owncloud/calendar#356]
just another regression:

E.g. with Thunderbird SoGo Connector **we need the full CalDAV URL for each calendar**. The "primary CalDAV URL" is not usable with it.

Users must enter the full URL to get a working calendar with the sogo connector, which is a real PITA: You must read it from the calendar's tooltip, when hovering over the calendar name in the web app and then type it in by hand in the sogo connector configuration.

**Comment by georgehrke** [comment]
you can find the entire caldav link when hovering over the calendar name

**Comment by georgehrke** [comment]
we are thinking about bringing back the caldav link input field, that's why I will keep this issue open for now

**Comment by brrrrrrrt** [comment]
thanks for looking into the issue! 
would be really great to have that feature back, as it is not very easy to copy a url from a tooltip.

**Comment by timreeves** [comment]
I agree with @brrrrrrrt , it would be helpful for TB users to have this back.

**Comment by georgehrke** [comment]
It would be even more helpful if TB would finally implement an automatic discovery of calendars :wink:

**Comment by gjedeer** [comment]
I just came here to open the same bug: not only with ownCloud 9 the calendar URLs have changed, it's now very hard to find the correct calendar link when setting up Thunderbird.

If possible, either bring it back or make the old links work again.

**Comment by godfuture** [comment]
Typing from tooltip...Really? You do surprise me. Why u forgot about us TB users? :(

**Comment by brrrrrrrt** [comment]
i also think that a calendar discovery from the primary URL in TB would be a much better solution:  https://bugzilla.mozilla.org/show_bug.cgi?id=1259300

but until this happens we still need to use the full URL.

**Comment by georgehrke** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=306495

Please excuse my brevity and typos.

**Comment by brrrrrrrt** [comment]
@georgehrke oh i see, that bug exists since 2005, with 8 duplicate bugs :(

quite unlikely that there will be progress soon.

**Comment by minneyar** [comment]
While it would be great if TB could auto-discover calendars, there's no indication that it will ever be implemented.

In the meantime, having the URL in a tooltip is completely useless if I can't copy/paste from it.

**Comment by georgehrke** [comment]
blocked by https://github.com/owncloud/calendar/pull/400
