### ISSUE TITLE
Cut off alpha value from #RRGGBBAA

### ISSUE THREAD

**Issue by cthil** [owncloud/calendar#358]
I have set custom colors for different calendars using iCal. While they were shown with the old calendar (so they are saved in the database), the new Web UI displays all 'custom' colors as blue and also does not show the color indicator in the list view on the left (the square is always white, independent of the calendar visibility state).

Stock colors:
![stock colors](https://cloud.githubusercontent.com/assets/8024840/13934573/38b39e5e-efb3-11e5-97be-4d60d410aca4.png)

Custom colors:
![custom colors](https://cloud.githubusercontent.com/assets/8024840/13934574/38b7ecc0-efb3-11e5-999a-a727a7df10fa.png)

**Comment by georgehrke** [comment]
Could you please check the `oc_calendars` table and tell me what the `calendarcolor` field for the corresponding rows looks like?

**Comment by cthil** [comment]
Ah! It seems that iCal uses RGBA colors. At least all custom colors have an additional FF at the end, like #44A703FF.

**Comment by georgehrke** [comment]
Wow ... and Safari doesn't like this format. It's unable to parse `44A703FF`. :see_no_evil: 

<img width="323" alt="custom calendar colors break colors-indicators on web ui issue 358 owncloud-calendar safari today at 10 38 54 pm" src="https://cloud.githubusercontent.com/assets/1250540/13935077/c08d3b3a-efb5-11e5-9534-d08534163c4b.png">

Well done Apple!

Anyway, we are able to check the colors length and if necessary cut off the last two characters.
Assigning to Version 1.1

**Comment by cthil** [comment]
Actually I discovered the bug with Chromium at work, so probably you should strip the alpha in general before writing the color to the DB.
Thanks for fixing this!
