### ISSUE TITLE
Exported calendar filename has no file extension

### ISSUE THREAD

**Issue by stonie08** [owncloud/calendar#359]
When exporting an owncloud calendar the filename is always "calendarname" (without file extension) while the import dialogue automatically filters for files with "*.ics". Therefore the exported filename should end with a .ics file extenson.
### Steps to reproduce
1. Create calendar
2. export created calendar
### Expected behaviour

Calendars should be exported with a name that is expected when importing the calendar, therefore ending on .ics.
### Actual behaviour

Calendars are only exported with the calendarname itself and without file extionsion
### Client configuration

**Browser:**
Mozilla Firefox 45.0.1

**Operating system:**
Windows 7

**CalDAV-clients:**
Browser

**Comment by georgehrke** [comment]
server issue -> please report in http://github.com/owncloud/core/issues
