### ISSUE TITLE
Clarify repeating settings

### ISSUE THREAD

**Issue by Bullnados** [owncloud/calendar#361]
Dialog "Every day" to "Every n day"
after selecting
Repeat every .. n -->days,weeks etc<--
Ending after... x times. Would be also nice if u can set a end date

**Comment by MTRichards** [comment]
Thinking about it, probably should be "Every n days"

**Comment by georgehrke** [comment]
@Bullnados Can you please elaborate a bit more?

I'm not sure I can follow your few notes.

**Comment by Bullnados** [comment]
Normaly u can choose none, every day, every week etc. 
In this first step it isnt clear, that u can choose personal reapting times.
Solution: Change to Every n day(s) or Every x week(s)
After selecting f.e. Every day u can choose how often u want repeat the meeting
For claryfication i wouldn't wrote 
Repeat every... 3
but
Repeat every 3 days, weeks etc.

End repeat(I would also take capital letter for End) or "Repeat ends" with the selection of none, times or date
Would be nice if u can also choose an end date btw :)

**Comment by georgehrke** [comment]
Ah ok :)

We are already working on a more advanced repeating events editor in https://github.com/owncloud/calendar/pull/197

You will have the simple options you already have (every day, week, ...), but without the additional input.
Additionally there will be 'Custom' option, where you have various input fields.

**Comment by georgehrke** [comment]
I will close this issue in favor of https://github.com/owncloud/calendar/pull/197
