### ISSUE TITLE
[CalDAV] Calendar returns non-existing calendar-homeset for group principals

### ISSUE THREAD

**Issue by rfc2822** [owncloud/calendar#363]
### Steps to reproduce
1. Query an admin user principal (e.g. /principals/users/test/) for `group-membership`. It returns `/principals/groups/admin/` as a group membership (as expected).
2. Query this admin principal for calendar-home-sets. It returns `/dav/calendars/admin/`.
3. Query the returned homeset. → It does not exist.
### Expected behaviour

The home set should only be returned if there's actually a home set owned by the admin group (and not a specific user).
### Actual behaviour

The admin group principal contains an invalid calendar-home-set.

**Comment by georgehrke** [comment]
caldav issue -> please report in http://github.com/owncloud/core/issues
