### ISSUE TITLE
Do not try and create events in birthday calendar

### ISSUE THREAD

**Issue by PVince81** [owncloud/calendar#365]
### Steps
1. Setup OC core master (ea07a428f463a866b2c5e44e243a33d8980c8850)
2. Install calendar app master (c08e01dfc18aa2ea19bd5d01af71eb59b489ea2c)
3. Install contacts app master (3da8d4b3a480b7be699cd830864947d81e80f847)
4. Open the calendar app's web UI
5. Directly create an event and do not touch the calendar selection dropdown in the dialog
### Expected

Should not be able to create an event.
### Actual

The birthday calendar is selected by default in the event dialog (but has empty string), and the code tries to create an event into the birthday calendar, receives a 404:
http://localhost/owncloud/remote.php/dav/calendars/admin/contact_birthdays/ownCloud-04pxvrwgdfueg66rolt7n0w4wz3hm2t9.ics
### Versions

See above.

@georgehrke

**Comment by georgehrke** [comment]
I think this is a server issue:

PROPFIND http://owncloud.dev/remote.php/dav/calendars/admin/

``` xml
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/contact_birthdays/</d:href>
  <d:propstat>
   <d:prop>
    <d:displayname>Contact birthdays</d:displayname>
    <cal:calendar-description/>
    <cal:calendar-timezone/>
    <x1:calendar-order xmlns:x1="http://apple.com/ns/ical/">0</x1:calendar-order>
    <x1:calendar-color xmlns:x1="http://apple.com/ns/ical/">#FFFFCA</x1:calendar-color>
    <cal:supported-calendar-component-set>
     <cal:comp name="VEVENT"/>
     <cal:comp name="VTODO"/>
    </cal:supported-calendar-component-set>
    <d:acl>
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/admin/</d:href>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:read/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/admin/</d:href>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:write/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
    </d:acl>
    <d:owner>
     <d:href>/remote.php/dav/principals/users/admin/</d:href>
    </d:owner>
    <oc:invite/>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
```

It contains a write permission, although it's not supposed to

**Comment by georgehrke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> I think this is a server issue:

yes 

@PVince81 is the birthday calendar displayed in the calendar app as regular calendar or as subscription? Mind pasting a screenshot? THX

**Comment by PVince81** [comment]
![calendar-bday](https://cloud.githubusercontent.com/assets/277525/14018435/12f8eee0-f1ce-11e5-9fdf-2aad9f1d90a7.png)

The dropdown is empty and if I click "Create" it fires the invalid request as above.

**Comment by DeepDiver1975** [comment]
@georgehrke the birthday calendar is readonly - basically the issue is that there is no calendar at all where the event can be written to

**Comment by PVince81** [comment]
Weird thing. I refreshed master and the submodule (did I really miss that one twice in a row ?!) and now after resetting ownCloud several times it looks fine:
![calendar-bday2](https://cloud.githubusercontent.com/assets/277525/14018804/db94aa78-f1cf-11e5-8011-e878ac31c8ba.png)

Or could there be a race condition between activating calendar/contact apps ?

**Comment by PVince81** [comment]
Can't seem to reproduce it now, even when omitting the submodule when switching from stable9 to master... Weird stuff

**Comment by DeepDiver1975** [comment]
I suspect this is causing the different behavior: https://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/calendar.php#L34-L36

**Comment by DeepDiver1975** [comment]
This is the changing commit: https://github.com/owncloud/core/commit/85521879cd573e66139eb3256c37cf13a4a80599

**Comment by georgehrke** [comment]
Will close in favor of: https://github.com/owncloud/calendar/issues/376

With that one and the fix in core this issue should be resolved.
