### ISSUE TITLE
[Thunderbird] Mail for calendar is not the one choosen when i create / accept an event

### ISSUE THREAD

**Issue by crazy-max** [owncloud/calendar#369]
Hi!
### Steps to reproduce
1. Create a new calendar on Owncloud 9
2. Copy the caldav link on Thunderbird 38.7.0 (latest) to create a new calendar
3. Click on properties for the calendar created on Thunderbird and link an email address
4. Create an event
### Expected behaviour

The mail choosen on Thunderbird calendar when i create or accept an event for this calendar must be the one selected in Thunderbird like it does on Owncloud 8.2.
### Actual behaviour

When an event is created or accepted on Thunderbird, the mail address is not the one choosen on Thunderbird but the one on Owncloud :(
### Server configuration

**Operating system**:
Debian GNU/Linux 8 (jessie) 64bits

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.1.12

**PHP version:**
PHP 5.6.17

**ownCloud version:** (see ownCloud admin page)
9.0.0.19

**Calendar version:** (see ownCloud apps page)
1.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "octsmzfmuh8e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.1"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Paris",
        "log_authfailip": true,
        "cron_log": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": false,
        "trashbin_retention_obligation": "7,15"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

NO

**Are you using encryption:** yes/no

NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

NO
### Client configuration

**Browser:**
Firefox 45.0.1

**Operating system:**
Debian Jessie

**CalDAV-clients:**
Thunderbird 38.7.0
DavDroid 0.9.1.3 (downloaded via Fdroid)

**Comment by georgehrke** [comment]
> Create an event

inside thunderbird?

**Comment by crazy-max** [comment]
Yes inside thunderbird!

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by crazy-max** [comment]
Ok thanks
