### ISSUE TITLE
Sidebar as default view for events that are already existing

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#370]

**Comment by georgehrke** [comment]
why?

**Comment by georgehrke** [comment]
(we will have the sidebar as default on smaller screens, but I don't see a need to get rid of the popover at all)

**Comment by georgehrke** [comment]
ping @aspdye 

Please explain why :)

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, this should not be the case. Especially not on mobile actually. The default should always be the popup with only the essential info (title, time and calendar).

**Comment by georgehrke** [comment]
@jancborchardt so no https://github.com/owncloud/calendar/issues/193?

The popover is really not useful in mobile right now. You can't reach all buttons.

**Comment by jancborchardt** [comment]
Well, we simply need to make the popover work on mobile. The sidebar has too much info for quick mobile input, no?

**Comment by georgehrke** [comment]
> Well, we simply need to make the popover work on mobile. The sidebar has too much info for quick mobile input, no?

To me the popover looks just strange on a mobile device.
Also as both take up almost the entire screen it's hard for the user to distinguish if they are in the popover or the sidebar. Having two different dialogs that look very similar but have a different set of inputs is bad in my opinion.

**Comment by jancborchardt** [comment]
@georgehrke hmm, ok. Makes sense since the footer with the buttons is sticky.

But then the »Cancel« and »Save« button in the sidebar have to be next to each other to avoid misclicks. Also, the extra text field in the small popover should then go away and we should make it more compact to have it really be a very quick means of input.
