### ISSUE TITLE
can't make new calendar

### ISSUE THREAD

**Issue by copos77** [owncloud/calendar#371]
### Steps to reproduce
1. Install OC 9.0.0
2. activate Calendar
3. click on the +New Calendar tab
4. Fiel the Name on the field
5. click on the tab make it
### Expected behavior

I can't create new calendar, only in the mysql database, the calendar opened in the database works fine.
### Server configuration

**Operating system**:

**Web server:**
Cyon.ch
**Database:**
mysql
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Calendar version:** (see ownCloud apps page)
1.0
**Updated from an older ownCloud or fresh install:**
fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Safari
**Operating system:**
OS X El Capitan
**CalDAV-clients:**
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

Error   no app in context   Exception: {"Exception":"DomainException","Message":"Calendar tables are missing. Nothing to do.","Code":0,"Trace":"#0 \/home\/nbautech\/public_html\/oc_9.0.0_test\/apps\/dav\/lib\/migration\/migratecalendars.php(84): OCA\Dav\Migration\CalendarAdapter->setup()\n#1 \/home\/nbautech\/public_html\/oc_9.0.0_test\/apps\/dav\/appinfo\/application.php(202): OCA\Dav\Migration\MigrateCalendars->setup()\n#2 \/home\/nbautech\/public_html\/oc_9.0.0_test\/apps\/dav\/appinfo\/install.php(27): OCA\Dav\AppInfo\Application->migrateCalendars()\n#3 \/home\/nbautech\/public_html\/oc_9.0.0_test\/lib\/private\/installer.php(621): include('\/home\/nbautech\/...')\n#4 \/home\/nbautech\/public_html\/oc_9.0.0_test\/lib\/private\/installer.php(572): OC_Installer::includeAppScript('\/home\/nbautech\/...')\n#5 \/home\/nbautech\/public_html\/oc_9.0.0_test\/lib\/private\/installer.php(546): OC_Installer::installShippedApp('dav')\n#6 \/home\/nbautech\/public_html\/oc_9.0.0_test\/lib\/private\/setup.php(370): OC_Installer::installShippedApps()\n#7 \/home\/nbautech\/public_html\/oc_9.0.0_test\/core\/controller\/setupcontroller.php(64): OC\Setup->install(Array)\n#8 \/home\/nbautech\/public_html\/oc_9.0.0_test\/lib\/base.php(823): OC\Core\Controller\SetupController->run(Array)\n#9 \/home\/nbautech\/public_html\/oc_9.0.0_test\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/home\/nbautech\/public_html\/oc_9.0.0_test\/apps\/dav\/lib\/migration\/calendaradapter.php","Line":68}
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Is there some reverse proxy or load balancer in place?

Do you see MKCALENDAR requests in your access log? If you can't access it, please contact Cyon.ch's support and ask them if MKCALENDAR requests are allowed.

**Comment by copos77** [comment]
in the OC Version 8.2.3 this function was enabled and i make new calendars

Liebe Grüsse

Christian Marty
christian@s-martys.ch

Am 26.03.2016 um 18:22 schrieb Georg Ehrke notifications@github.com:

Is there some reverse proxy or load balancer in place?

Do you see MKCALENDAR requests in your access log? If you can't access it, please contact Cyon.ch's support and ask them if MKCALENDAR requests are allowed.

**Comment by georgehrke** [comment]
That might be the case, but we rewrote the entire calendar app.

**Comment by georgehrke** [comment]
We switched from MKCALENDAR to MKCOL
