### ISSUE TITLE
Repeat section for new calendar entries not displayed in language selected by user

### ISSUE THREAD

**Issue by thorsten19** [owncloud/calendar#374]
### Steps to reproduce
1. Set OC9 language for a user to a language different than English (e.g. German or Dutch)
2. Login with the user account and select the Calendar app.
3. Create a new calendar entry and select the More... button to access the Repeating settings.
### Expected behaviour

Repeating section should be displayed in the language selected for the user (in OC9)
### Actual behaviour

Complete Repeating section with all subsettings is displayed in English
### Server configuration

Operating system: Raspbian GNU/Linux 8 (jessie)
Web server: Apache
Database: MySql
PHP version: 5.5.44
ownCloud version: (see ownCloud admin page) 9.0.0
Calendar 1.0
**Updated from an older ownCloud or fresh install:**Fresh install

![calendar-repeating](https://cloud.githubusercontent.com/assets/18091239/14062682/8acf162a-f3a8-11e5-829e-d23f08acedfc.PNG)
### Client configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by georgehrke** [comment]
already translatable, see https://github.com/owncloud/calendar/blob/master/js/app/controllers/recurrencecontroller.js#L29

**Comment by georgehrke** [comment]
Please check ownCloud at transifex if these elements are translated and contribute if not.
New translations will be added with the next release.

**Comment by thorsten19** [comment]
Thank you @georgehrke 
Thought it was a bug as the other settings are in local languages displayed. Great to see it is no bug.
Checked transifex and found the elements for "repeating" to be translated in German and Dutch. Requested to be added to help in future translations.
