### ISSUE TITLE
No calendar could not be activated/enabled when using in Firefox browser on Linux system.

### ISSUE THREAD

**Issue by lwinch2006** [owncloud/calendar#378]
### Steps to reproduce
1. Enable "Calendar" in Apps section of Owncloud.
2. Go to "Calendar" app
3. Try to enable (show events) on default or contact_birthdays calendars. 
### Expected behaviour

The square near to the name of the calendar (on the left panel) should be filled with color and all events from this calendar should be shown on the right panel. 
### Actual behaviour

The actual behaviour is that there is a rotating circle (waiting cursor) shown constantly instead of filled with color square and no events being shown on the right panel. There is neighter possible to add events, no popup window (Add event) comes up when clicking on a particular date.

For your information!!! In Firefox 45 (stable) browser in Windows 7 all working OK.
### Server configuration

**Operating system**: 
Debian 8 (Jessie)

**Web server:** 
Apache/2.4.10 (Debian)

**Database:** 
MySQL Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** 
PHP 5.6.17-0+deb8u1 (cli)

**ownCloud version:** (see ownCloud admin page) 
owncloud 9.0.0

**Calendar version:** (see ownCloud apps page) 
1.0

**Updated from an older ownCloud or fresh install:** 
fresh install

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- bookmarks: 0.7
- calendar: 1.0
- comments: 0.2
- contacts: 1.1.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notes: 2.0.1
- notifications: 0.2.3
- ownnote: 1.07
- provisioning_api: 0.4.1
- systemtags: 0.2
- tasks: 0.9.0
- templateeditor: 0.1
- updatenotification: 0.1.0

Disabled:
- encryption
- external
- files_external
- galleryplus
- user_external
- user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

would rather prefer to not show config.php file.

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

There are no commands defined in the "ldap" namespace.
### Client configuration

**Browser:**
Firefox Developer Edition 47 (Archlinux)
Firefox Stable 45 (Archlinux)
Iceweasel 38.5 (Debian 8 (Jessie))

**Operating system:**
Archlinux or Debian 8 (Jessie)

**CalDAV-clients:**
no clients, issue with web interface of Calendar app.
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

a) Javascript log.
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] /
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://..ip-address here.... 'unsafe-eval'"). calendar:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://..ip-address here.... 'unsafe-eval'"). calendar
GET 
XHR 
https://..ip-address here../owncloud/index.php/apps/calendar/v1/timezones/ETC/UTC.ics [HTTP/1.1 404 Not Found 100ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117
uncaught exception: [object Object] (unknown)

![owncloud_firefox_linux_calendar_issue](https://cloud.githubusercontent.com/assets/6912915/14068462/b9bf4f4c-f473-11e5-9512-e04343330297.png)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/303
