### ISSUE TITLE
Enabled all Calendars allways wenn Login

### ISSUE THREAD

**Issue by copos77** [owncloud/calendar#380]
How to enabled the Calendars and shared Caledars by default?

I want see all the events by starting the Calendar.

It is possibel?

Thanks for help

**ownCloud version:** 9.0.0

**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:**
fresh

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/291 and https://github.com/owncloud/calendar/issues/366

**Comment by georgehrke** [comment]
and please use the entire issue template next time
