### ISSUE TITLE
Sharing options overlap

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/calendar#381]
### Steps to reproduce
1. Create a calendar
2. Type in a search string into the share field
### Expected behaviour

Beautiful list :heart_eyes: 
### Actual behaviour

![bildschirmfoto vom 2016-03-30 09 36 16](https://cloud.githubusercontent.com/assets/213943/14135027/2846aa4e-f65b-11e5-87ec-9ac533a1c72e.png)
### Server configuration

**Operating system**: Linux Mint 17.3

**Web server:** Apache2

**ownCloud version:** master 

**Calendar version:** master

**Updated from an older ownCloud or fresh install:** install

**List of activated apps:**

```
Enabled:
  - activity: 2.3.0
  - calendar: 1.0
  - comments: 0.3.0
  - dav: 0.2.2
  - federatedfilesharing: 0.2.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.0
```
### Client configuration

**Browser:** Firefox 45.0, Chromium 49.0

**Operating system:** Linux Mint 17.3

**Comment by georgehrke** [comment]
@raghunayyar

**Comment by nickvergessen** [comment]
works, thanks :+1:
