### ISSUE TITLE
Pressing enter in new calendar input doesn’t create calendar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#382]
You need to manually click the button, which is quite annoying. Pressing enter after having put in a calendar name should also work.

(Observed when I watched @nickvergessen use the the Calendar app ;)

**Comment by georgehrke** [comment]
@jancborchardt Should the dialog disappear after hitting enter? (or generally after creating a calendar)

**Comment by georgehrke** [comment]
I doesn't hide neither at the moment

**Comment by nickvergessen** [comment]
PS: enter works, dont know what you looked at

**Comment by jancborchardt** [comment]
Yes, it should. :)

**Comment by georgehrke** [comment]
pr: https://github.com/owncloud/calendar/pull/384
