### ISSUE TITLE
Link with anchor to event or day

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#383]
e.g. needed for https://github.com/owncloud/contacts/issues/316 :wink: 

cc @DeepDiver1975 @skjnldsv

**Comment by DeepDiver1975** [comment]
and maybe back as well - as in open the contacts app from the birthday event in the calendar

**Comment by skjnldsv** [comment]
Agreed! :+1:

**Comment by aspdye** [comment]
:point_up_2: There you go :wink: (https://github.com/owncloud/contacts/issues/318)
