### ISSUE TITLE
Special characters in german language (umlauts) are ignored in calendar names

### ISSUE THREAD

**Issue by godfuture** [owncloud/calendar#385]
### Steps to reproduce
1. Create new calendar
2. Name it with german umlauts
3. Move mouse cursor over calendar and check Dav Link for missing umlaut in name
### Expected behaviour

The umlaut is visible in dav link or at least gets escaped
### Actual behaviour

Umlauts are ignored and therefore simply missing
### Server configuration

**Operating system:** Ubuntu Server 15.10 x64
**Web server:** Apache2
**Database:** MySQL 5.6
**PHP version:** 5.6.13
**ownCloud version:** 9.0
**Calendar version:** 1.0

**Updated from an older ownCloud or fresh install:** fresh
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 44

**Operating system:** Windows 7

**CalDAV-clients:** Thunderbird
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
That's the intended behaviors, because most clients have issues with umlauts and other special characters.

**Comment by godfuture** [comment]
Escaping?

**Comment by georgehrke** [comment]
makes the url really ugly and as far as I recall there has been issues with escaping the names as well.
