### ISSUE TITLE
Calendar import doesn’t show calendar directly

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#389]
Importing a calendar from an ICS file, I get the calendar title and the spinner in place of the color. That’s fine.

But then nothing really happens.

Out of curiosity I tried clicking on the calendar name, then clicked it again and the spinner was gone then and the events appeared. Really strange that it doesn’t do that automatically.

**Comment by georgehrke** [comment]
1.0 or master?

**Comment by jancborchardt** [comment]
master

**Comment by georgehrke** [comment]
can't always reproduce, needs some more investigation, moving to 1.2

**Comment by areteichi** [comment]
As I wrote in the other thread, this happens to me on ownCloud 9.0.1 and Calender 1.1 as well.

> I think I'm having the same issue.
> 
> I recently fresh installed ownCloud 9.0.1 and imported my calender data from ownCloud 8.2.3 (by exporting/importing them as ICS file). I've discovered that I can see all the events March 2016 onwards, but all the events prior to February 2016 seem not to be accessible.
> 
> The color icon on the left panel just keeps on spinning and the calender does not load when I go back, say, to February 2016.
