### ISSUE TITLE
Imported calendars have same color

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#390]
I just imported two calendars from .ics files and both have the same dark blue color.

For any new calendar or imported calendar, the color should automatically be set to the first unused color.
Also, we should not have this dark blue, still dark blue and the dark grey … they are much too dark and not distinguishable either. For example, we don’t have any green color at all.

**Comment by georgehrke** [comment]
@jancborchardt What if all colors are used?

Do you know a JS lib to generate new colors based on an existing set of colors? The new one should be 'as different' as possible.

**Comment by jancborchardt** [comment]
I think that’s what the core color placeholder.js library might be good for. It’s being improved by @skjnldsv, please take a look at https://github.com/owncloud/core/pull/23638

**Comment by skjnldsv** [comment]
This is exactly why I wrote this code, there is infinite possibilities (as far as web colors go).
We could get some very subtle tone variations, but overall we should get a good colors randomisation.

**Comment by jancborchardt** [comment]
Yeah, if there’s 30+ calendars of course then it’s subtle. :) But if the spread for the first 7 or so is reasonably nice, it’s great!

Awesome to have you @skjnldsv! :) It’s these details which make ownCloud great, and we need to always make sure our stuff is standardized among apps.

**Comment by skjnldsv** [comment]
Glad to hear that! :)
Actually you will need more than 30 items to have very subtle tones. ;)
But this is some statistics after all, you could end up with two exact colors, what are the odds!

**Comment by georgehrke** [comment]
we have to revert https://github.com/owncloud/calendar/pull/526 and fix this later
