### ISSUE TITLE
scrolling in sidebar broken

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#395]
not possible to see everything

**Comment by georgehrke** [comment]
@raghunayyar Do you have time to look into this? :)
If the window's height is not big enough the buttons overlay the content which is not scrollable

**Comment by georgehrke** [comment]
@raghunayyar Mind taking a look?

**Comment by onny** [comment]
There seems to be some styling issues in the sidebar ...
![2016-05-21-125934_swaygrab](https://cloud.githubusercontent.com/assets/757752/15448167/7022fb6a-1f5a-11e6-9dcc-c5532be608d4.png)

**Comment by georgehrke** [comment]
@onny That's the app-navigation. With sidebar I'm referring to the advanced events editor on the right. 
Please report a dedicated bug about the app-navigation issue :)

**Comment by onny** [comment]
So you mean this styling issue, right?
![right_menue](https://cloud.githubusercontent.com/assets/757752/17189039/0a4eab20-5440-11e6-9928-0410a5f54d48.png)

**Comment by georgehrke** [comment]
exactly

**Comment by MariusBluem** [comment]
Thats what we've spoken about @jospoortvliet @jancborchardt :wink:

**Comment by oparoz** [comment]
It makes it impossible to change the reminders

**Comment by georgehrke** [comment]
@raghunayyar I'd appreciate if you could take a look at this very soon

**Comment by raghunayyar** [comment]
Yes, on it.

**Comment by raghunayyar** [comment]
Fixed, please check guys. :)

**Comment by steckerhalter** [comment]
@raghunayyar Seems like the overflow is hidden and there is no scrollbar in Calendar v1.3.3:

![](https://cloud.githubusercontent.com/assets/3024024/18578494/8d43d136-7bf0-11e6-9d09-415774ea493f.png)

So calendars below are not visible at all.

**Comment by georgehrke** [comment]
The sidebar is referring to the advanced events editor.
Please report a dedicated issue
