### ISSUE TITLE
Empty first dropdown value on ics import

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#397]
@georgehrke check this out:
![capture du 2016-03-30 18-03-38](https://cloud.githubusercontent.com/assets/925062/14148867/c5a8ff6c-f6a1-11e5-99d8-928a09a6a2d9.png)

**Comment by georgehrke** [comment]
There probably was a contacts_birthday at that time already, right?

**Comment by jancborchardt** [comment]
Yeah

**Comment by jancborchardt** [comment]
But that shouldn’t be shown in the event import dropdown :)

**Comment by georgehrke** [comment]
> But that shouldn’t be shown in the event import dropdown :)

obviously, but I think it's related to a read-only calendar existing. :)

**Comment by jancborchardt** [comment]
Kk
