### ISSUE TITLE
use MKCOL instead of MKCALENDAR

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#398]
JS issue:

```
MKCALENDAR http://cloud.jancborchardt.net/remote.php/dav/calendars/jan/events/
405 (Request not allowed)
in client.js line 183 
```

@georgehrke any idea?

**Comment by georgehrke** [comment]
Server config issue

**Comment by georgehrke** [comment]
MKCALENDAR is a standardized method

**Comment by jancborchardt** [comment]
Really? I didn’t have this issue before at all

**Comment by georgehrke** [comment]
yes :) 

http://icalendar.org/CalDAV-Access-RFC-4791/5-3-1-mkcalendar-method.html

But we should switch to MKCOL, because it basically does the same and it seems to be better supported ...
