### ISSUE TITLE
Calendar cannot be shared to a group 

### ISSUE THREAD

**Issue by dirkpape** [owncloud/calendar#404]
### Steps to reproduce
1. login as user1 and share a calendar to a group of users containing user2, but not to the user2 himself
2. subscribe to the caldav service as the user2
3. see what calendars you can use
### Expected behaviour

calendar should be visible for user2
### Actual behaviour

calendar is not visible for user2.
But it is visible if shared directly (not via group) with user2.
### Server configuration

**Operating system**:
Ubuntu 14.4 LTE

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23

**Database:**
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.0.1RC

**Calendar version:** (see ownCloud apps page)
1.0

**Updated from an older ownCloud or fresh install:**
updated from 8.2.3

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.1.0.0
- dav: 0.1.6
- direct_menu: true
- documents: true
- encryption: 1.2.0
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_mv: true
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- galleryplus: true
- logreader: true
- news: 8.0.0
- notifications: 0.2.3
- ownnote: true
- polls: 0.7.0
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

Disabled:
- gallery
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "518cbe88de454",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "datadirectory": "xxxxx",
        "dbtype": "mysql",
        "version": "9.0.1.1",
        "dbname": "xxxxxxx",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "default_language": "de_DE",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "trusted_domains": [
            "xxx"
        ],
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "noreply",
        "mail_domain": "xxxxx",
        "mail_smtphost": "localhost",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src _; img-src *; font-src 'self' data:; media-src *",
        "maintenance": false,
        "enable_avatars": true,
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\OC\Memcache\Redis",
        "memcache.local": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "trashbin_retention_obligation": "auto",
        "updater.secret": "_**REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no
### Client configuration

**Browser:**
Safari or Firefox

**Operating system:**
Macos X 10.11.4

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues
