### ISSUE TITLE
ownCloud Calendar Sharing not working - group users not able to create/edit events in shared calendar

### ISSUE THREAD

**Issue by law** [owncloud/calendar#407]
### Steps to reproduce
1. Create group
2. Create user other than yourself, add to group
3. Create calendar, share calendar to group, check "<group> can edit"
4. Create events (as initial user) in shared calendar
5. Log in as newly-created user, go to Calendars, try and either edit the pre-existing event or add a new event to the shared calendar
### Expected behaviour

The other users in the group (to whom the calendar appears as a 'subscription') should be able to edit events or add events to the shared calendar
### Actual behaviour

The other users are unable to edit events or add shared events to the calendar - the 'create' dialog does not show the shared calendar as an option, etc.  
### Server configuration

**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache 2.4.7-1ubuntu4.9 

**Database:** 5.5.47-0ubuntu0.14.04.1

**PHP version:** 5.5.9-1ubuntu4.14 

**ownCloud version:** (see ownCloud admin page): 9.0.0 (stable)

**Calendar version:** (see ownCloud apps page): 1.0

**Updated from an older ownCloud or fresh install:** 8.2

**Signing status (ownCloud 9.0 and above):** unknown

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed: 
paste the results here.
```

"No errors have been found."

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:** 45.0.1

**Operating system:** OS X El Capitan

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ghost** [comment]
@law Probably a duplicate of https://github.com/owncloud/core/issues/23699. There have been some fixes for group sharing in https://github.com/owncloud/core/pull/23342 / https://github.com/owncloud/core/pull/23552 which gets shipped with oC 9.0.1.

For further issues please note that CalDAV and CardDAV issues now belongs to core like stated in the issue  template:

> Migration and CalDAV issues belong in the core repo!
> https://github.com/owncloud/core/issues

See also https://github.com/owncloud/calendar/issues/404#issuecomment-203891885

**Comment by law** [comment]
These look shockingly similar, thank you for clarifying that for me.  When is 9.0.1 expected to ship, and/or is there a way I can pull down an RC with the patches before then?  I've got quite a few people relying on this shared calendar functionality, I'm bordering on desperate to get this sorted for them.

**Comment by law** [comment]
re: "When is 9.0.1 expected to ship", it's amazing what I can find when I Google instead of just asking dumb questions :-) 

https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by ghost** [comment]
Have a look at https://owncloud.org/install/#instructions-server -> "Find development packages for testing here." where you find testing packages (9.0.1 RC currently). But i think those fixes are not included in this RC yet.

The release schedule is available here: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
