### ISSUE TITLE
Creating Subscriptions is giving a 500 error

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/calendar#41]
My owncloud.log shout this : 
`{"reqId":"dZP1W6v+esvo29jB75B2","remoteAddr":"::1","app":"PHP","message":"Cannot use OCP\\AppFramework\\Db\\Entity as Entity because the name is already in use at \/Applications\/MAMP\/htdocs\/ownCloud\/core\/apps\/calendar\/db\/timezonemapper.php#26","level":3,"time":"2015-10-24T17:58:54+00:00"}
{"reqId":"2WkNu0MHv23KOUmkgjjK","remoteAddr":"::1","app":"PHP","message":"Cannot use OCP\\AppFramework\\Db\\Entity as Entity because the name is already in use at \/Applications\/MAMP\/htdocs\/ownCloud\/core\/apps\/calendar\/db\/timezonemapper.php#26","level":3,"time":"2015-10-24T18:02:17+00:00"}
{"reqId":"01KSlfoSOJLqtjyJMUIX","remoteAddr":"::1","app":"PHP","message":"Cannot use OCP\\AppFramework\\Db\\Entity as Entity because the name is already in use at \/Applications\/MAMP\/htdocs\/ownCloud\/core\/apps\/calendar\/db\/timezonemapper.php#26","level":3,"time":"2015-10-24T18:05:03+00:00"}`

**Comment by georgehrke** [comment]
what does the call to the http subscription api return?

**Comment by raghunayyar** [comment]
<img width="684" alt="screen shot 2015-10-24 at 11 41 04 pm" src="https://cloud.githubusercontent.com/assets/992488/10711944/c4e90f60-7aa8-11e5-9fb5-1900214cd1bd.png">

**Comment by georgehrke** [comment]
and the response message?

**Comment by georgehrke** [comment]
never mind, it says content-length is zero, is there anything in the server error log?

**Comment by raghunayyar** [comment]
MAMP, php log : 
`24-Oct-2015 18:02:17 UTC] PHP Fatal error:  Cannot use OCP\AppFramework\Db\Entity as Entity because the name is already in use in /Applications/MAMP/htdocs/ownCloud/core/apps/calendar/db/timezonemapper.php on line 26
[24-Oct-2015 18:05:03 UTC] PHP Fatal error:  Cannot use OCP\AppFramework\Db\Entity as Entity because the name is already in use in /Applications/MAMP/htdocs/ownCloud/core/apps/calendar/db/timezonemapper.php on line 26
`

**Comment by georgehrke** [comment]
not relevant, when moving to dav app
=> won't fix
