### ISSUE TITLE
Show Full Name instead of username for shared calendars 

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#416]

**Comment by georgehrke** [comment]
- [x] check if there is a way to get the display name for any user in JS
  - [ ] if not ask core to add display name to dav responses

**Comment by wiswedel** [comment]
Not really a bug, more a CR, isn't it?

**Comment by georgehrke** [comment]
@wiswedel: Well, the LDAP backend has random strings as user Ids, that's why we should use the display name instead :wink:

**Comment by wiswedel** [comment]
Ah ok, in that case I understand.

**Comment by georgehrke** [comment]
https://github.com/owncloud/core/issues/23877#issuecomment-207833512

**Comment by georgehrke** [comment]
duplicate of https://github.com/owncloud/calendar/issues/379

**Comment by ksteinb** [comment]
Hi Georg,

where do I find the patch for this problem, I have  the version  1.2.2 installed and I have the problem. Also I do not find the patch anywhere on github?

**Comment by georgehrke** [comment]
This is a duplicate of #379 which is still open. It wasn't fixed yet.
Contributions welcome :wink:

**Comment by ksteinb** [comment]
Hi Georg,

> This is a duplicate of #379
> https://github.com/owncloud/calendar/issues/379 which is still open.
> It wasn't fixed yet.

I did try to output shareWithDisplayName instead of shareWith in the
app.js file but to no help, its probably set to owncloud_name.

It looks like there are more changes needed, the apps probably needs to
use OCP\IUsermanager

Sincerly,
Klaus
