### ISSUE TITLE
Updated calendar-shares loosing edit-rights

### ISSUE THREAD

**Issue by ionum** [owncloud/calendar#418]
### Steps to reproduce
1. Update existing db with calendar-shares (with edit-right) from owncloud 8.2.x
### Expected behaviour

former-edit-rights-shares should be edit-rights-shares
### Actual behaviour

former-edit-rights-shares loosing edit-right
### Server configuration

mysql 5.5
owncloud 9.0.0
calendar 1.0

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by ionum** [comment]
Done.

https://github.com/owncloud/core/issues/23796
