### ISSUE TITLE
Implement editing vcal-status described in rfc 2445 and display options for different status

### ISSUE THREAD

**Issue by ionum** [owncloud/calendar#419]

**Comment by georgehrke** [comment]
please add an bit more elaborated description

**Comment by ionum** [comment]
VCAL has an option STATUS for indicating if the event is confirmed, tentative or canceled like this:
BEGIN:VCALENDAR
VERSION:1.0
BEGIN:VEVENT
STATUS:TENTATIVE
DTSTART:19960401T033000Z
DTEND:19960401T043000Z
SUMMARY:Your Proposal Review
END:VEVENT
END:VCALENDAR

This should be editable (simple dropdown) as well as displayed differently in the calendar

**Comment by MathieuSchopfer** [comment]
Select the event status using a scroll-down select providing three values:
![scoll_down](https://cloud.githubusercontent.com/assets/17726101/16238201/e546be70-37df-11e6-973f-20be00f79369.png)

**Comment by MathieuSchopfer** [comment]
Render the event using different styles, depending on its status:
![events_rendering](https://cloud.githubusercontent.com/assets/17726101/16238202/e54e32cc-37df-11e6-9e52-2596f129c70e.png)

I am not sure about the styling though ... Any suggestion ?

**Comment by georgehrke** [comment]
@MathieuSchopfer Looks really good! :)
I'm not so sure about the question mark in front of tentative event though. cc @jancborchardt

**Comment by ionum** [comment]
@MathieuSchopfer Tres bien Mathieu!

Maybe less opacity and omit the question mark? outlook and thunderbird have an vertical bar on the left side for status... but this may be more difficult to implement....

**Comment by jancborchardt** [comment]
Nice, the styles look good! Great work @MathieuSchopfer!

I would just remove the `(?)` from the tentative event because the opacity works to communicate that already. No further info is needed.

**Comment by MathieuSchopfer** [comment]
I am not convinced by the question mark either, let's get rid of it.

@ionum An icon, if really necessary, could be implemented in conjunction with #137.

**Comment by georgehrke** [comment]
implemented by @MathieuSchopfer 

will be released with 1.3
