### ISSUE TITLE
Create event in shared calendar created by other user doesn't send emails to attendees

### ISSUE THREAD

**Issue by javesin** [owncloud/calendar#422]
### Steps to reproduce
1. Log into ownCloud as user1 using LDAP account
2. create new calendar, setup share for other user2 with edit permition
3. create new event, add user1 (me) and user2 as attendees
4. mail invitation to user2 is sent
5. logout
6. login as user2 using LDAP
7. in shared calendar create new event, add user1 and user2 as attendees
8. no mail sent
### Expected behaviour

Even I create event in calendar created by other user (in case I have edit permitions) mail notification (invination, changes, reminder etc.) should be sent.
### Actual behaviour

No mail sent in that case.
### Server configuration

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
### Client configuration

firefox: latest stable (45.0)
xubuntu/ubuntu:  latest stable (LTS 14.04)

**Comment by georgehrke** [comment]
This is an issue in the CalDAV server, closing in favor of https://github.com/owncloud/core/issues/23946
