### ISSUE TITLE
Creating new event in more detail forgets selected calendar

### ISSUE THREAD

**Issue by javesin** [owncloud/calendar#424]
### Steps to reproduce
1. Log into ownCloud
2. create more than one calendar ie named "cal1" and "cal2" so cal1 is listed on the first place, cal2 on second position
3. create new event by clicking into calendar 
4. New event form is opened
5. cal1 is pre-set calendar in this form (because it is first in the list)
6. select cal2 in the listbox
7. click "More..." button in this form before Create action
8. more detailed form is opened but cal1 is set again (other attributes are copied - title, date/time, location)
### Expected behaviour

After switching into detail mode selected calendar should stay
### Actual behaviour

Always is pre-set first calendar in the listbox
### Server configuration

ownCloud version: (see ownCloud admin page)
ownCloud 9.0.0 (stable)
### Client configuration

firefox: latest stable (45.0)
xubuntu/ubuntu: latest stable (LTS 14.04)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/343
