### ISSUE TITLE
Selected calendar resets when clicking on more while creating new event

### ISSUE THREAD

**Issue by sedrubal** [owncloud/calendar#425]
### Steps to reproduce
1. Click in Calendar to create a new event
2. Chose one calendar
3. Click on more
### Expected behaviour

The selected calendar should also be selected in the "More" sidebar.
### Actual behaviour

The first calendar in the calendar drop down is selected. This happens only when creating a new event, not while modifying an event.
### Server configuration

**Operating system**: ubuntu

**Web server:** apache2

**Database:** mariadb

**PHP version:** php5

**ownCloud version:** oc 9.0

**Calendar version:** 

**Updated from an older ownCloud or fresh install:** yes

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:** 

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - news: 7.1.2
  - notes: 2.0.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2                                                                            
  - tasks: 0.8.1                                                                               
  - templateeditor: 0.1                                                                        
  - updatenotification: 0.1.0                                                                  
Disabled:                                                                                      
  - external                                                                                   
  - firstrunwizard                                                                             
  - mail                                                                                       
  - user_external                                                                              
  - user_ldap
```

**The content of config/config.php:**

```
this is a frontend fail
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 45.0.1

**Operating system:** Fedora 23
#### Web server error log

```
-
```
#### ownCloud log (data/owncloud.log)

```
-
```
#### Browser log

```
-
```

**Comment by georgehrke** [comment]
duplicate

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/343
