### ISSUE TITLE
remove valarms from objects in read-only shared calendars

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/calendar#429]
@georgehrke 
Back in the old calendar app there was an open pull request made by you that removed the alarm from events in read-only  sharedy calendars.
You postponed this PR due the calendar on OC9 uses another caldav implementation.

Is something like that already possible in OC9 or is it planned?

**Comment by georgehrke** [comment]
No, please raise an issue in http://github.com/owncloud/core/issues

**Comment by georgehrke** [comment]
(core because it's related to the caldav server, which is part of core beginning with ownCloud 9)
