### ISSUE TITLE
Missing calendar options after upgrade

### ISSUE THREAD

**Issue by rahliak** [owncloud/calendar#442]
### Steps to reproduce
1. Open the calendar app in ownCloud
2. Go to the settings or
3. go to the calendar
### Expected behaviour

After opening the settings of the calendar app, I expected the settings as described in the user manual (https://doc.owncloud.org/server/9.0/user_manual/pim/calendar.html)
### Actual behaviour

The settings are very different as described in the manual.
- When creating a new calendar, there are only 8 coulours available - not the 32 colours as described
- The timezone-setting is not visible
- The time-format-setting is not visible
- The "Start week on"-setting is not visible

and the most recent problem:
- The button to get the CalDAV-link is not visible.  There is no way to get the caldav-link.
  (there is only a button to share the calendar, to download the calendar and to delete the calendar - but no button to get the CalDAV-URL). 
  Note: The "pencil"-icon is also not visible.
### Server configuration

**Operating system**:
Debian/Jessie 8.4

**Web server:**
Apache 2.4.10

**Database:**
Mysqll 5.5.47

**PHP version:**
PHP 5.6.19

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0

**Calendar version:** (see ownCloud apps page)
Calendar 1.0

**Updated from an older ownCloud or fresh install:**
Updated

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.1.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_mv: 0.8.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- music: 0.3.10
- notes: 2.0.1
- notifications: 0.2.3
- provisioning_api: 0.4.1
- roundcube: 2.6.1
- shorten: 0.0.15
- systemtags: 0.2
- tasks: 0.9.0
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8dokjp3iuk",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "www.mydomain.org"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/www.mydomain.org\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "proxy": "proxy.provider.com:3128",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "mydomain.org",
        "mail_smtphost": "mail.mydomain.org",
        "mail_smtpsecure": "tls",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "default_language": "de",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "memcache.local": "\OC\Memcache\APCu",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.
### Client configuration

**Browser:**
Firefox / Iceweasel 38.6.0
and Safari on iOS 9.3.1

**Operating system:**
Debian/jessie
and
Apple iOS

**CalDAV-clients:**
caldavsync
and
Apple iOS (native client)
#### Web server error log

Insert your webserver log here
[Sun Apr 10 21:25:13.728098 2016] [ssl:info] [pid 30506](70007)The timeout specified has expired: [client 91.15.183.145:40911] AH01991: SSL input filter read failed.
[Sun Apr 10 21:25:13.935793 2016] [ssl:info] [pid 
![new_calendar](https://cloud.githubusercontent.com/assets/3055675/14412609/92956a34-ff66-11e5-9ccc-44e9fee001ee.png)
![settings](https://cloud.githubusercontent.com/assets/3055675/14412610/92984c22-ff66-11e5-8c76-61616df83bc8.png)

30504] (70007)The timeout specified has expired: [client 91.15.183.145:40908] AH01991: SSL input filter read failed.
[Sun Apr 10 21:25:37.371709 2016] [ssl:info] [pid 23923] [client 91.15.183.145:40913] AH01964: Connection to child 8 established (server www.mydomain.org:443)
[Sun Apr 10 21:25:42.623194 2016] [ssl:info] [pid 23923](70007)The timeout specified has expired: [client 91.15.183.145:40913] AH01991: SSL input filter read failed.
#### ownCloud log (data/owncloud.log)

no actual entries in owncloud.log

Insert your ownCloud log here
16-04-10T18:45:08+00:00"}
{"reqId":"TSAxKXato5uvL\/nxpNWq","remoteAddr":"","app":"core","message":"Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/session\\/memory.php(49): OC\\Session\\Memory->validateSession()\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/security\\/csrf\\/tokenstorage\\/sessionstorage.php(63): OC\\Session\\Memory->set('requesttoken', 'f6mCv2PZmKRUu67...')\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/security\\/csrf\\/csrftokenmanager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('f6mCv2PZmKRUu67...')\n#3 \\/var\\/www\\/owncloud\\/lib\\/public\\/util.php(496): OC\\Security\\CSRF\\CsrfTokenManager->getToken()\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/template.php(75): OCP\\Util::callRegister()\n#5 \\/var\\/www\\/owncloud\\/apps\\/activity\\/lib\\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \\/var\\/www\\/owncloud\\/apps\\/activity\\/lib\\/backgroundjob\\/emailnotification.php(134): OCA\\Activity\\MailQueueHandler->sendEmailToUser('user2', 'user2@mydomain...', 'de', 'Europe\\/Berlin', 1460315706)\n#7 \\/var\\/www\\/owncloud\\/apps\\/activity\\/lib\\/backgroundjob\\/emailnotification.php(94): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1460315706)\n#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/backgroundjob\\/job.php(52): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#9 \\/var\\/www\\/owncloud\\/lib\\/private\\/backgroundjob\\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 \\/var\\/www\\/owncloud\\/cron.php(141): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/session\\/memory.php\",\"Line\":105}","level":3,"time":"2016-04-10T19:15:07+00:00"}
#### Browser log

no browser log available

**Comment by aspdye** [comment]
The documentations for the new calendar and contacts - apps are outdated :grin: 
https://github.com/owncloud/documentation/issues/2278

**Comment by georgehrke** [comment]
> The settings are very different as described in the manual.

Manual is outdated

> The timezone-setting is not visible
> The time-format-setting is not visible
> The "Start week on"-setting is not visible

These settings were removed on purpose and are not determined by the language

> The button to get the CalDAV-link is not visible. There is no way to get the caldav-link. (there is only a button to share the calendar, to download the calendar and to delete the calendar - but no button to get the CalDAV-URL).

will be reintroduced with 1.1

> Note: The "pencil"-icon is also not visible.

Bug, will be fixed with 1.1
