### ISSUE TITLE
All calendars have same color when asset pipeline is enabled

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#451]
tracked upstream: https://github.com/tchwork/jsqueeze/issues/43

**Comment by callmemagnus** [comment]
Fixed upstream in 2.0.5.

**Comment by georgehrke** [comment]
will prepare pull requests in core

**Comment by georgehrke** [comment]
issue in core, closing in favor of https://github.com/owncloud/3rdparty/pull/275
