### ISSUE TITLE
Add issue tracker link to appstore

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#458]
https://apps.owncloud.com/content/show.php/Calendar?content=168707

currently don't has the link to the issue tracker like the contacts app for example:

https://apps.owncloud.com/content/show.php/Contacts?content=168708

Adding such a link hopefully prevents some users from posting issues within the comments of the app

**Comment by georgehrke** [comment]
done :)

**Comment by georgehrke** [comment]
> Adding such a link hopefully prevents some users from posting issues within the comments of the app

You are very optimistic :laughing:

**Comment by ghost** [comment]
Nah, not that optimistic. But there is still some hope that one might notice the link there :-)
