### ISSUE TITLE
Opacity is too much

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#459]
### Steps to reproduce

Open the calendar in webUI
### Expected behaviour

Opacity should be less
### Actual behaviour

Opacity is to much and makes the dates and time almost invisible

![deepinscreenshot20160413000757](https://cloud.githubusercontent.com/assets/4511254/14477072/f1c0ed98-010b-11e6-9519-5a79515a3c5d.png)
### Server configuration

**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.4
**Database:**
Mysql 5.5
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
Updated
**Signing status (ownCloud 9.0 and above):**
No errors
### Client configuration

**Browser:**
Version 49.0.2623.112 (64-bit) Chrome
**Operating system:**
Deepin 15 (Debian)
**CalDAV-clients:**
DavDroid
### Logs

No logs

cc @jancborchardt

**Comment by jancborchardt** [comment]
That is for the dates of the previous month though. It's an indicator for that.

**Comment by enoch85** [comment]
@jancborchardt Let me disagree on that. Take a look here:
![deepinscreenshot20160413112533](https://cloud.githubusercontent.com/assets/4511254/14488879/91b04ff2-016a-11e6-97af-02abc5cd1b33.png)

Do you see any difference between 12 and let's say 19? This is April btw.

**Comment by jancborchardt** [comment]
No, there is no difference as far as I can see. Should there be one?

But the times on the events are wayyy too transparent, that’s true. You want to submit a quick pull request for that?

**Comment by enoch85** [comment]
@jancborchardt 

> Should there be one?
> That is for the dates of the previous month though

Idk, should there? :)

> You want to submit a quick pull request for that?

Sure I could, but I didn't find any opacity setting in the css files?

**Comment by jancborchardt** [comment]
@enoch85 the previous month being the previous full month. 12 and 19 are in the same month.

**Comment by jancborchardt** [comment]
@enoch85 the previous month being the previous full month. 12 and 19 are in the same month.

**Comment by enoch85** [comment]
@jancborchardt Yes, that's right. You just gave an idea of a new enhancement. :)

Anyway, could you point me to what setting that should be changed and I can make a PR out of it?

**Comment by enoch85** [comment]
Thanks @raghunayyar
