### ISSUE TITLE
Fix "Primary CalDAV address" URL

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#461]
### Steps to reproduce
1. Open calendar app
2. Open settings (cogwheel bottom left)
### Expected behaviour

The "Primary CalDAV address" should point to `http://example.com/remote.php/dav/calendars/USERNAME/`
### Actual behaviour

The "Primary CalDAV address" is pointing to `http://example.com/remote.php/dav/`
### Server configuration

**ownCloud version:** 9.0.1

**Calendar version:** 1.1

**Comment by ghost** [comment]
Hi,

the question is also if this address can be used at all? AFAIK Thunderbird can't discover calendars there.

How are other clients (e.g. DAVDroid) handling this?

**Comment by georgehrke** [comment]
AFAIK KOrganizer, Evolution and DavDroid use this URL. Not entirely sure though.
For Thunderbird we reintroduced the caldav link for each calendar with 1.1 :)

**Comment by ghost** [comment]
I'm really not familiar with that stuff. Core for example is also only pointing to:

`http://example.com/remote.php/dav/`

in its .htaccess: https://github.com/owncloud/core/blob/v9.0.1/.htaccess#L56-L57

**Comment by georgehrke** [comment]
we should probably check if the current url is just fine for KOrganizer and co.

**Comment by ghost** [comment]
Ok, i think we could close this one. Just checked remote.php/dav/ and remote.php/caldav and both have the same structure:

```
dav:/remote.php/caldav/> ls
Listing collection `/remote.php/caldav/': succeeded.
Coll:   calendars                              0  Jan  1  1970
```

```
dav:/remote.php/dav/> ls
Listing collection `/remote.php/dav/': succeeded.
Coll:   addressbooks                           0  Jan  1  1970
Coll:   calendars                              0  Jan  1  1970
```

So this was working fine in the past and should also work now.
