### ISSUE TITLE
Events cannot be marked as private

### ISSUE THREAD

**Issue by tagru** [owncloud/calendar#463]
### Steps to reproduce
1. Create event
2. Open details
3. No possibility to mark event as private
### Expected behaviour

Before 9.0 an event could be marked as private, so these marked events would not be seen if the calendar is shared
### Actual behaviour

No field for privacy
### Server configuration

**ownCloud version:9.0.1

**Calendar version:1.1

**Comment by georgehrke** [comment]
see the FAQ

**Comment by georgehrke** [comment]
actually it's not in the FAQ right now, sorry, anyway, this is a bug in core

**Comment by georgehrke** [comment]
https://github.com/owncloud/core/issues/22914
