### ISSUE TITLE
Share box cannot be closed in Owncloud 7

### ISSUE THREAD

**Issue by maethor** [owncloud/calendar#463]
In Owncloud 7, the "share box" cannot be closed. When it is opened and I click on the share button, the share box closes and reopens directly. This is quite anoying because this box hides the following calendars in the list.

I'm using Firefox nightly 33.0a1 on Debian Wheezy and I have the same problem with Chromium 35.

Thanks.

**Comment by jancborchardt** [comment]
This is most likely fixed. If it still occurs, please let us know with more details.
