### ISSUE TITLE
Feature request: set default calendar?

### ISSUE THREAD

**Issue by koenlek** [owncloud/calendar#464]
Is there a way to set your default calendar? 
I use owncloud 9.0.1 with calendar app v1.1 and I am creating appointments form the webinterface.

Since the owncloud 9, my new appointments are by default created in my "contact birthdays" calendar (which is strange on its own, as I don't have the contacts app enabled in owncloud, so it is bound to be empty by default unless I manually fill it?). Could you add a way to change the default calendar from your apps web interface?

**Comment by georgehrke** [comment]
The contacts_calendar being writable is a known bug in https://github.com/owncloud/core
it's supposed to read-only.

closing as dup of https://github.com/owncloud/calendar/issues/133

**Comment by koenlek** [comment]
Thanks for the fast response!
