### ISSUE TITLE
Feature request: exceptions for recurring events

### ISSUE THREAD

**Issue by koenlek** [owncloud/calendar#465]
It is currently impossible to add exceptions to recurring events from the calendar app's webinterface. If I shift the time, it shifts all events in that recurring series. And much worse: if I want to delete 1 occurrence of a recurring event, it deletes the whole series without an extra warning! So trying to skip one meeting for example for some holiday, can easily result in accidentally deleting the whole series without a warning!

This would both be solved by adding a prompt on save/delete, asking if you want:
- To apply to all of series.
- Future only
- (Future for x times)
- This event only

I use owncloud 9.0.1, with calendar app v1.1.

> I omitted the template, as it seems inappropriate for such feature requests...

**Comment by georgehrke** [comment]
please search for existing issues before creating new ones ...

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/50

**Comment by koenlek** [comment]
Thanks for fast response. Apologies for not searching well enough.  I searched for "recurring"... The issue you refer to uses "repeating".
