### ISSUE TITLE
Make current dates more visible and past dates less visible

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#469]
Just as the current design when the past months date aren't as visible as the current month - it would be nice to do the same for dates in the same month.

The current deisgn just makes the past month more "transparent" but I think this should happen for the past days in a month as well.

cc @jancborchardt https://github.com/owncloud/calendar/issues/459#issuecomment-209468953

**Comment by jancborchardt** [comment]
I would say that the dates should be per-month. As said in the other issue, to differentiate past from present+future, we could desaturate the events or make them a bit transparent.

**Comment by enoch85** [comment]
This is merged.
