### ISSUE TITLE
can't import multiple calendars 

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#47]
1 export google calender to ICS format (more than 2 separate calendars)
2 upload to owncloud in the files section
3 Click on calendar, - window pops up to import calendar,
4 Click drop down box and select "create new calendar"
5 let it auto file the name in and click import calendar- all this is done correctly
6 click the x to close the dialog box 
7 click your 2nd calendar you want to import
8 opens the standard import calendar as we've seen before in above steps.
9 Click "create a new calendar"
10 when that is select it is not auto filled like the original one with the name. 
Expect result - it auto fills the name and drop down of color to choose from appears
actual result - it stays on the "create a new calendar" not allowing you to do anything
workaround- click the x. hit f5 to refresh the page. Repeat above steps to import 2nd calendar then it works fine

OC: 5.0.5
Serversoftware: Apache/2.2.23
PHP-Version: 5.3.20
MySQL Server Version: 5.1.68-cll

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
