### ISSUE TITLE
'more' menu is not fully shown in low resolutions

### ISSUE THREAD

**Issue by TecJon** [owncloud/calendar#470]
Resolution: 1366*768
The 'ends' part of the repeating event is behind the 'cancel' button.

![untitled](https://cloud.githubusercontent.com/assets/11375752/14503806/edc1cb58-01b1-11e6-9c1f-2f3acb969020.png)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/395
