### ISSUE TITLE
Shared calendar not displaying in Owncloud 9.0.1 after upgrading from 9.0

### ISSUE THREAD

**Issue by falco22** [owncloud/calendar#474]
Hello,

I've upgrade this morning Owncloud from 9.0 to 9.0.1. In my account I use 3 calendar : personal, family, and contact's birthday.
Personal and birthday displaying fine. "family" is shared (by me) and never display in the month view (the same in day or week view) : on the color case (left to "family") I have just a "progress icon" that's never ended". 
If I create a new appointment, and chose to save it to "family", it's appeared (but only this appointment)

This calendar is shared with our smartphone and is always available with the smartphone, the problem is only on web interface. 
### Steps to reproduce

1.
2.
3.
### Expected behaviour

displaying the shared calendar
### Actual behaviour

Shared calendar is not available in web interface
### Server configuration

**Operating system**:
FreeBSD 9.3-RELEASE-p13

**Web server:**
lighttpd-1.4.39_1 
**Database:**
mysql56-server-5.6.27
**PHP version:**
php56-5.6.20

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.1 (stable)
**Calendar version:** (see ownCloud apps page)
calendar 1.1
**Updated from an older ownCloud or fresh install:**
Updated from 9.0 (and 8.x before)
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

```

**The content of config/config.php:**

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "oc46c7ded0e6",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "myhost.mydomain.org"
        ],
        "datadirectory": "\/usr\/local\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.07",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.5",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**
Mozilla for Firefox 45.0
**Operating system:**
Kubuntu 14.04
**CalDAV-clients:**
on android : caldav sync
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
L'utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place. jquery.min.js:5:17117
TypeError: dt.convertToZone is not a function
b) The network log 

c) The security console log :
Content Security Policy: Les paramètres de la page ont empêché le chargement d'une ressource à self (« script-src https://calypso.recusses.org 'unsafe-eval' »).  calendar
```

**Comment by georgehrke** [comment]
please provide the javascript console log ...

**Comment by falco22** [comment]
I've edited to paste JS console.

Thanks

**Comment by PeterPablo** [comment]
I just updated from 8.2 to 9.0.1 and my personal calendar is not displayed in Chromium 49 (Mac OS):

```
Uncaught (in promise) TypeError: dt.convertToZone is not a function
    at convertTimezoneIfNecessary (https://<myurl>/owncloud/apps/calendar/js/public/app.js?v=5d72cd64b7eea0b7b4c546959a289e77:3037:12)
    at getTime (https://<myurl>/owncloud/apps/calendar/js/public/app.js?v=5d72cd64b7eea0b7b4c546959a289e77:3097:4)
    at https://<myurl>/owncloud/apps/calendar/js/public/app.js?v=5d72cd64b7eea0b7b4c546959a289e77:3178:26
    at Object.forEach (https://<myurl>/owncloud/apps/calendar/js/vendor/angular/angular.js?v=5d72cd64b7eea0b7b4c546959a289e77:321:20)
    at Object.VEvent.getFcEvent (https://<myurl>/owncloud/apps/calendar/js/public/app.js?v=5d72cd64b7eea0b7b4c546959a289e77:3167:12)
    at https://<myurl>/owncloud/apps/calendar/js/public/app.js?v=5d72cd64b7eea0b7b4c546959a289e77:2085:44
```

Apache logs and owncloud.log don't show anything meaningful. Sync over DAV works fine.

**edit:** So this [line](https://github.com/owncloud/calendar/blob/775165240fc90d13ad13bd03014061fc2b3703e8/js/public/app.js#L3037) seems to cause the error.

**Comment by PeterPablo** [comment]
According to [this](http://mozilla-comm.github.io/ical.js/api/ICAL.Time.html#convertToZone) I can't see anything being wrong with the statement. May be the shipped ical.js is outdated and does not provide that function?

**Comment by PeterPablo** [comment]
This patch makes the app functional again, though disables the timezone conversion:

```
root@rpi2:/var/www/owncloud# diff app.js apps/calendar/js/public/app.js
2285c2285
<           end: end.toJSDate(),
---
>           //end: end.toJSDate(),
3037c3037
<           dt = dt.convertToZone(timezone);
---
>           //dt = dt.convertToZone(timezone);
```

@georgehrke, hopefully this helpfs.

**Comment by falco22** [comment]
This patch works for me too

Thanks

**Comment by ghost** [comment]
I have the same issue. 
How can I apply  the patch? I changed the two lines and deleted my browser cache but Owncloud seems to have cached the old js file. Also I de- and activated the app again from the administrator backend.

**Comment by georgehrke** [comment]
Well, breaking timezone conversion is not really a solution 🙈

**Comment by georgehrke** [comment]
We updated the library we use for parsing in the 1.1 update of the calendar. That's probably causing this issue.

I don't think this is really caused by the fact, that the calendar is shared, but simply by some calendar-data in it. I don't know how much sensitive data these calendars contain, but it would tremendously help if one of you could send me the ics file. [developer@georgehrke.com](mailto:developer@georgehrke.com)
Beforehand you can simply open the ics file in a text editor and remove everything that's too private.

**Comment by ghost** [comment]
> Well, breaking timezone conversion is not really a solution :see_no_evil:

You are right. Since you have mentioned it, I found that the setting to change the timezone has gone.
<image removed>

> I don't think this is really caused by the fact, that the calendar is shared, but simply by some calendar-data in it. 

In my case the "Share calendar"-button is missing for all of my six calenders. None of my calendars have been shared yet. I experience the same  issue when I create a new calendar within Owncloud 9.0.1 and the Calendar 1.1 app. That's why I think it has nothing to do with the calendars themselves.
<image removed>

Here's a non personal example calendar which I cannot share (on OC):
<file removed>

**Comment by georgehrke** [comment]
@petmue I think we are talking about completely different issues here. The original issue @falco22 and @PeterPablo talk about is that the events are not even rendered.

The events seemed to be rendered in your case. The missing sharing button is most certainly related to some ad blocking browser extension.

**Comment by ghost** [comment]
> @petmue I think we are talking about completely different issues here. The original issue @falco22 and @PeterPablo talk about is that the events are not even rendered.

Oh, indeed, you were right!!! I am sorry for hijacking this issue.

**Comment by PeterPablo** [comment]
@georgehrke, I certainly wouldn't want to share my whole ics. Could you supply me with a patch that would print out some information to the console/log so I could identify the problematic entry? I would the send you a stripped down ics-file.

**Comment by falco22** [comment]
hello

No problem to send you my ics file but not to post it on github, evenif
it's just sport activites of my childrens :)

Thanks
Fabrice

**Comment by Mikrobit** [comment]
Hello,
I had this same problem and figured a way to pinpoint the problematic event; attached below is a calendar with one such event.
The `EXDATE:20140516` line seems to be the culprit. It's clearly a malformed line that blocks the calendar from being displayed by ical.js . The line should be `EXDATE;VALUE=DATE:20140516` afaict.

I'm pretty sure I didn't create the event using owncloud (maybe it was radicale, maybe google calendar, sorry I can't remember) but I'm also sure I didn't have problems with oc8.

Thanks for your efforts,

Mirko

[test.ics.txt](https://github.com/owncloud/calendar/files/257521/test.ics.txt)

**Comment by deisi** [comment]
Are there more examples needed to fix this?

**Comment by georgehrke** [comment]
should be fixed with #524

**Comment by Sequential-circuits** [comment]
I fixed the problem installing posix support with the command yum install  php70w-process, deleting the calendar folder, and installing the calendar again. Hope this helped

**Comment by deisi** [comment]
any idea how this is called under debian/ubuntu
