### ISSUE TITLE
load the previous and next calendar page in the background to speed up navigation

### ISSUE THREAD

**Issue by schiessle** [owncloud/calendar#476]
I have multiple calendars with many events so that it always takes some seconds if I navigate forward/backward in the months view.

Therefore I had this idea, don't know if it is feasible: Couldn't the calendar load the previous and the next page in the background so that navigating becomes smoother?

**Comment by georgehrke** [comment]
That's definitely something to consider for the future :)
Also actually caching the events in the browser is something to think about in the future.

**Comment by georgehrke** [comment]
Let's close this in favor of a proper Object store.
https://github.com/owncloud/calendar/issues/698
