### ISSUE TITLE
White page at start up

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#479]
Dear All, 
whenever I select the calendar, first it shows a blank white page, with all my individuals calendars enabled (Showing the calendar color). Refreshing the page does not change anything. If I click on one of my calendars (disabling it), all of a sudden all entries show up. Enabling the prior disabled calendar all entries are still on display. If i move to the next month...it still starts with the same procedure - white blank page --->
clicking on one of my  calendars ......

Is this the default behavior??

Regards, hitam4450

### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
It show all entries
### Actual behaviour

Tell us what happens instead
It shows NO entry
### Server configuration

**Operating system**:
DEnian Jessie 8.4
**Web server:**
lighttpd
**Database:**
Mysaql
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.01
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
upgraded
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
please provide the browser log, that's really important ...

**Comment by hitam4450** [comment]
Hi,

sorry I use FF 45.0.1 and I do not know how to recover the browsers log!

**Comment by georgehrke** [comment]
https://lmddgtfy.net/?q=firefox%2045%20access%20error%20console

**Comment by georgehrke** [comment]
needed info not provided, closing ticket.
