### ISSUE TITLE
better rights management

### ISSUE THREAD

**Issue by miko007** [owncloud/calendar#482]
in the current version of the calendar, the right `delete` on shared calendars does affect both, the events in the calendar and the calendar itself.

It would be nice, if those rights were seperate, so one can delete events, but not the whole calendar.

**Comment by georgehrke** [comment]
I'm pretty sure you are referring to the calendar prior to ownCloud 9. (please always use the issue template, so I don't have to guess 😉, there is a reason why it's prefilled when you file an issue)

The calendar app < 1.0 is not supported anymore.
