### ISSUE TITLE
Should the 3-dot menu only show icons or also some text?

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#489]
ownCloud Calendar:
<img width="283" alt="repro1" src="https://cloud.githubusercontent.com/assets/12893462/14744003/fb1dad72-08a4-11e6-9894-c58ceb2e2671.png">

ownCloud Core (Files App):
<img width="311" alt="repro2" src="https://cloud.githubusercontent.com/assets/12893462/14744011/05270642-08a5-11e6-91d1-206305363ad3.png">

What would you say? I think we should use the way the core-guys are doing. I also like the idea to only show the icons, but i think we should only use one design.

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yes, it should definitely be like the menu in core. @georgehrke @raghunayyar can you change that?
