### ISSUE TITLE
contact_birthdays shows only year, not the age

### ISSUE THREAD

**Issue by fireba11** [owncloud/calendar#490]
### Steps to reproduce
1. add a birthday to a contact
2. look at calendar
### Expected behaviour

calendar shows the age of the person celebrating their birthday (it did so in 8.2)
showing age(year) or something might be a good idea too, maybe make it configurable?
### Actual behaviour

calendar shows the birth year
### Server configuration

**Operating system**:
debian 8.3
**Web server:**
apache 2.4.10-10+deb8u4
**Database:**
mysql 14.14
**PHP version:**
5.6.17-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated (removed everythin except config.php and data folder, then installed with web installer
**Where did you install ownCloud from:**
https://download.owncloud.com/download/community/setup-owncloud.php
**Signing status (ownCloud 9.0 and above):**
- core
  - INVALID_HASH
    - .htaccess
    - .user.ini

**List of activated apps:**
Enabled:
    activity: 2.2.1
    calendar: true
    comments: 0.2
    contacts: true
    dav: 0.1.5
    federatedfilesharing: 0.1.0
    federation: 0.0.4
    files: 1.4.4
    files_external: 0.5.2
    files_pdfviewer: 0.8
    files_sharing: 0.9.1
    files_texteditor: 2.1
    files_trashbin: 0.8.0
    files_versions: 1.2.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 14.5.0
    notifications: 0.2.3
    provisioning_api: 0.4.1
    systemtags: 0.2
    templateeditor: 0.1
    updatenotification: 0.1.0

Disabled:
    encryption
    external
    user_external
    user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "**_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "datadirectory": "\/var\/www\/clients\/client1\/web43\/web\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "c1owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "check_for_working_webdav": false,
        "theme": "",
        "trusted_domains": [
            "owncloud.somedomain.com",
            "owncloud.somedomain.com"
        ],
        "secret": "**_REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "somedomain.com",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,90",
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:**
no
**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:**
no
### Client configuration

**Browser:**
FF 45.0.1
**Operating system:**
Win10

**Comment by aspdye** [comment]
Good Call :+1: I think this is something for the core-guys :grin: 

cc @DeepDiver1975

**Comment by georgehrke** [comment]
This one is rather difficult to implement for various reasons:
- instead of one recurring event we would have to create a lot of single events, one for each birthday
- the title of the event is not translatable at the moment

anyway, please raise an issue in https://github.com/owncloud/core/issues

**Comment by ghost** [comment]
> please raise an issue in https://github.com/owncloud/core/issues

Sorry, had pointed the user from core here at the calendar issue tracker: https://github.com/owncloud/core/issues/24217

But is this really a CalDAV backend issue? Thunderbird for example is also just calculation the year on its own so the calendar app could do the same on "client" side?

**Comment by georgehrke** [comment]
The contact_birthdays calendar is generated on the server. For the client it's simply yet another calendar.
No birthday logic in the calendar app whatsoever :) 

Please excuse my brevity and typos.

**Comment by georgehrke** [comment]
And don't be sorry :) 
You couldn't know and your help in the bug tracker is highly appreciated!

Please excuse my brevity and typos.
