### ISSUE TITLE
TypeError: dtend.subtractDate is not a function

### ISSUE THREAD

**Issue by skyYaga** [owncloud/calendar#491]
### Steps to reproduce
1. open calendar application in browser
### Expected behaviour

Calendar Events being loaded
### Actual behaviour

No caledar events are loaded. There is just the empty calendar and the "loading" spinner next to my Personal calendar List item.
It looks like this is not happening to other users.
### Server configuration

**Operating system**:
FreeBSD 10.1-RELEASE-p24

**Web server:**
nginx-1.8.1_2,2

**Database:**
mysql  Ver 14.14 Distrib 5.6.27-75.0 Percona

**PHP version:**
PHP 5.6.20 

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Calendar version:** (see ownCloud apps page)
1.1

**Updated from an older ownCloud or fresh install:**
updated

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.7.1
  - notes: 2.0.1
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.example.com"
        ],
        "datadirectory": "\/usr\/local\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.example.com",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "xxxxxxxx",
        "mail_domain": "xxxxxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxxxxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:**
no
### Client configuration

**Browser:** 
Chrome 50.0.2661.86 (64-bit)
Firefox 45.0.2

**Operating system:**
OS X 10.11.4 (15E65)

**CalDAV-clients:**
#### Web server error log

```
no errors logged
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"MdNraMuVKBqUEJV4XQ93","remoteAddr":"XXX:XXX:XXXX:XXXX","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-23T17:10:46+00:00","method":"POST","url":"\/index.php\/apps\/calendar\/v1\/view","user":"XXXX"}
```
#### Browser log

```
Chrome log:
app.js?v=3a5018d…:3055 Uncaught (in promise) TypeError: dtend.subtractDate is not a function(…)
getTimeForRecurring @ app.js?v=3a5018d…:3055
(anonymous function) @ app.js?v=3a5018d…:3176
forEach @ angular.js?v=3a5018d…:321
VEvent.getFcEvent @ app.js?v=3a5018d…:3167
(anonymous function) @ app.js?v=3a5018d…:2085

Firefox log:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://owncloud.example.com 'unsafe-eval'"). calendar
TypeError: dtend.subtractDate is not a function app.js:3055:18
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:17117
```

**Comment by areteichi** [comment]
As I posted in the other bug report (#466), I managed to fix the problem of the error message `TypeError: dtend.subtractDate is not a function` by modifying the ICS file:

> I finally managed to pinpoint the cause of the problem and was able to fix it!
> 
> The error `TypeError: dtend.subtractDate is not a function app.js:2206:10` was being caused by the way some of the events were saved by Calendar App (presumably in previous versions).
> 
> Some events in my calendar had a value (in the ICS file) that looks like the following:
> `DTSTART;TZID=Europe/Berlin:20160519T010000`
> `DTEND;TZID=Europe/Berlin;VALUE:20160519T020000`
> 
> The problem was basically caused by the part `Berlin;VALUE:`
> 
> In order to fix this problem, DTEND needs to be formatted just like DTSTART. Once I modified the value in the ICS file to look like the following, the problem went away:
> `DTSTART;TZID=Europe/Berlin:20160519T010000`
> `DTEND;TZID=Europe/Berlin:20160519T020000`
