### ISSUE TITLE
Use bigint instead of int for epoch fields

### ISSUE THREAD

**Issue by jknockaert** [owncloud/calendar#492]
Epoch fields like firstoccurence and lastoccurence in the oc_calendarobjects table are defined as int datatype (at least in postgres). That doesn't allow dates beyond 2038. Such dates commonly occur for recurring items without end date, which by some clients are implicitly defined to happen 400 times. So I suggest to use bigint for these fields rather than int.

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues
