### ISSUE TITLE
Calendar doesn't show after upgrade to OC 9.0

### ISSUE THREAD

**Issue by albatros69** [owncloud/calendar#496]
After upgrade to OC9.0 from 8.2.3 (using debian packages from owncloud.org), one of my calendar has a strange behaviour: some events don't show and the icon near the calendar name keeps spinning. I can't find an error anywhere. It affects some particular events I think, as I can navigate in the past or the future and some months or weeks do show.

The same issue is reported in #389 and #466.
### Steps to reproduce

Difficult to say as I don't have precise clue where the problem is
### Expected behaviour

All events should show.
### Actual behaviour

Some days/weeks/months are shown empty with spinning icon never stopping
### Server configuration

**Operating system**: Debian
**Web server:** nginx
**Database:** sqlite
**PHP version:** PHP 5.6.19-0+deb8u1 
**ownCloud version:** 9.0.1
**Calendar version:** 1.1
**Updated from an older ownCloud or fresh install:** from 8.2.3 (debian package too)
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- calendar: true
- comments: 0.2
- contacts: true
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- galleryplus: 15.0.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- gallery
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocf8342f9404",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "<bip>"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cohen.glop.ovh\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.1.3",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/owncloud\/3rdparty",
                "url": "\/3rdparty_apps",
                "writable": false
            }
        ],
        "installed": true,
        "forcessl": true,
        "overwritewebroot": "\/owncloud",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "appstore.experimental.enabled": true,
        "theme": "",
        "mail_from_address": "owncloud",
        "mail_domain": "<bip>",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage,** no
**Are you using encryption:** no
**Are you using an external user-backend** no
### Client configuration

**Browser:** Firefox 45.0.2
**Operating system:** Win 8

**Comment by hitam4450** [comment]
Same problem with me - 2 of my 12 different calendars are always spinning, unless I disable them!!

Regards, hitam4450

**Comment by georgehrke** [comment]
@albatros69 please provide logs, especially the browser log.

**Comment by albatros69** [comment]
Console logs are attached (Firefox). I didn't find a way to extract properly the network logs...
[console.txt](https://github.com/owncloud/calendar/files/239227/console.txt)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/474
