### ISSUE TITLE
eMail-reminder in calender seems to be broken

### ISSUE THREAD

**Issue by toxic-tonic** [owncloud/calendar#497]
Hi,

unfortunatelly the eMail-Reminder function seems to be broken. As I understand it, the calender send an email on the configured time befor an appointment. When i set up an appointment with severel attendees the initial apointment-mail is being send, but no reminder on the configured time.

Thanks in advance

Tobias
### Steps to reproduce
1. configure cron as scheduler
2. add appointment with email-notification
3. at the right time nothing happens
### Expected behaviour

It schould send a email at the configured time.
### Actual behaviour

Nothing happens, no log-entries...
### Server configuration

Debian 8.0

**Web server:**
Apache 2.4.10-10+deb8u4

**Database:**
Mysql 5.5.49-0+deb8u1

**PHP version:**
PHP 5.6.20+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Calendar version:** (see ownCloud apps page)
1.1

**Updated from an older ownCloud or fresh install:**
Fresh install (update also testet)

**Signing status (ownCloud 9.0 and above):**
no problems

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
- calendar: 1.1
- comments: 0.2
- contacts: 1.2.0.0
- dav: 0.1.6
- external: 1.2
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_external: 0.4
  Disabled:
- activity
- encryption
- gallery
- ojsxc
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/srv\/server\/data\/wwwroot\/wwwssl\/oc\/data",
        "overwrite.cli.url": "xxx",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "xxx",
        "mail_domain": "xxx",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpport": "587",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "maintenance": false,
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
FTP

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

Chrome 49.0.2623.112 m

**Operating system:**
Windows 10

**CalDAV-clients:**
none
#### Web server error log

Nothing of interest

Insert your webserver log here
Nothing of interest
#### ownCloud log (data/owncloud.log)

Nothing of interest
#### Browser log

Nothing of interest

**Comment by georgehrke** [comment]
https://github.com/owncloud/core/issues/22734
