### ISSUE TITLE
Release >Latest< instead of >version number<

### ISSUE THREAD

**Issue by enoch85** [owncloud/calendar#500]
It would be convinient for users (me ;) ) that download the calendar to be able to get the latest version instead of tracking the version number. Would this be easy to implement?

**Comment by georgehrke** [comment]
https://help.github.com/articles/linking-to-releases/ 😉

**Comment by georgehrke** [comment]
`curl -s https://api.github.com/repos/owncloud/calendar/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4`

**Comment by enoch85** [comment]
@georgehrke Thanks!
