### ISSUE TITLE
After adding event, must refresh page before I can delete it

### ISSUE THREAD

**Issue by Luticus** [owncloud/calendar#502]
### Steps to reproduce

1.Add event
2.Click event
3.observer, no delete button
4.Refresh page, click event, delete button is there
### Expected behaviour

Tell us what should happen
After adding an event I should be able to delete it without refreshing the page.
### Actual behaviour

Tell us what happens instead
Page must be refreshed before I can delete the event
### Server configuration

**Operating system**:
Debian Jessie amd64
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
updated from 1.0 on down
**Signing status (ownCloud 9.0 and above):**
I have disabled signing due to the external sites app custom icon feature, owncloud and the calendars code have not been altered

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

It's difficult for me to get this right now as I don't have direct access to the server at the moment.  If you really need this to diagnose then let me know and I'll provide it.

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
firefox and chrome
**Operating system:**
mac, debian/linux, windows
**CalDAV-clients:**
davdriod (android), ios, mac calendar, kmail
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Can't reproduce, works just fine for me.
(tested with firefox and chromium on OS X)

**Comment by georgehrke** [comment]
Can you please re-check and make sure you didn't forget to mention some important reproduction steps.

**Comment by Luticus** [comment]
When I click the calendar and attempt to add an event (default settings are fine, I only name it), I then click that event and observe that the red delete button is missing from the popup.  I'm using Chrome on the latest Mac OSX at the moment.  I can try it on firefox using Debian once I get home later today, but I'm pretty sure the issues is the same.  I have also recently updated to Owncloud 9.0.2 successfully, but am still experiencing the issue.  If I refresh the page the button will be there when clicking the event, which is fine for me, but not intuitive for my users.  This happens even when using an admin account (if that matters, which I suspect it doesn't).  It also occurs regardless of which calendar I add the event to, or regardless of whether or not that calendar is shared.

I have also noticed that if I create an event and click that event to edit it, say switch which calendar the event is on from my personal calendar to a shared gaming calendar, the Update button still reads "create" and if I click it, it will update the event but will also create a duplicate event.  It's like the pop up window doesn't get the memo that the event has been created already and is stuck in "create mode" until the page is refreshed.  

Thanks for looking into it, hopefully this info is helpful.

**Comment by Luticus** [comment]
Oh, one more update, It happens regardless of the status of my adblocker/ghostry/etc I've whitelisted my own site on all of them, and have even completely disabled them and the issue still occurs.  Maybe later on I can take some screen shots or even make a small screen capture to demonstrate the problem if I need to.

**Comment by Luticus** [comment]
I can also confirm that this occurs in the mobile interface in firefox on android.

**Comment by georgehrke** [comment]
I'm still not able to reproduce this issue 😕

**Comment by Luticus** [comment]
This still happens on version 1.2.1.  Not sure what's going on with it or why the issue can't be reproduced.  For me it happens even on the mobile firefox on android.  Maybe there's an app conflict or something like that.  I'll post the list of active apps I have soon.

**Comment by Luticus** [comment]
Here's a list of the apps i have installed and their versions:

announcement center 1.2
collaborative tags 0.2
comments 0.2
deleted files 0.8.0
external sites 1.2
external storage support 0.5.2
gallery 14.5.0
mail template editor 0.1
notifications 0.2.3
pdf viewer 0.8.1
provisioning api 0.4.1
share files 0.9.1
text editor 2.1
update notification 0.1.0
versions 1.2.0
bookmarks 0.7
calendar 1.2.1
contacts 1.2.0.0
documents 0.12.0
javascript xmpp chat 3.0.0
news 8.7.5
tasks 0.9.0
epub and comics online reader 7.0.5
extra security 0.2.0
file locking
own note 1.07
passwords 18.0
pint 1.0.1
rainloop 4.15
reader (ebook reader) 0.7.1
videos sublime 0.9.8

**Comment by georgehrke** [comment]
and all of them are enabled? 🙈

**Comment by Luticus** [comment]
They are :).  Turns out this might not be a 1.2.1 issue as I had problems upgrading to 1.2.1. see:  https://github.com/owncloud/calendar/issues/538

Basically I have yet to test this in 1.2.1, even though i thought i was due to a permission issue.

Sorry for the confusion, didn't want people to waste time looking at something that might not even be an issue.  As soon as i can successfully upgrade to 1.2.1 and test it, i will update.

This is still and issue in 1.1 though.

**Comment by Luticus** [comment]
I'm not 100% sure what was causing this issue, it still happened on even the newest version for me.  Oddly though once I migrated the Owncloud server to new hardware reinstalling Debian/Apache/Owncloud/php5/etc from scratch  and porting all configs, data, and databases, this issue went away.  I can only assume it may have been some strange security setting conflict or something that didn't get moved.  I honestly have no idea and that bothers me a bit.  However, whatever the issue was, it was obviously a configuration issue and not an issue with the calendar code itself.  This can be closed.
