### ISSUE TITLE
Year - List all Date Item the next year

### ISSUE THREAD

**Issue by Mannshoch** [owncloud/calendar#504]
Please add a Year list.

In my Mokup the Category Item could be the Category I'm able to add in Thunderbird (Private, Busines, event) or the Calendars I have created on the left. This kind of list could be used for Printouts.

![jahreskalender](https://cloud.githubusercontent.com/assets/7795891/15067034/d2a5b816-136d-11e6-928b-18ac3faa773e.png)

**Comment by georgehrke** [comment]
cc @jancborchardt @raghunayyar

**Comment by georgehrke** [comment]
related to https://github.com/owncloud/calendar/issues/85

**Comment by georgehrke** [comment]
actually it's a dup of #85
