### ISSUE TITLE
Wrong sharing url

### ISSUE THREAD

**Issue by 2edff206** [owncloud/calendar#507]
### Steps to reproduce
1. Select a calendar
2. Click on the share icon
3. 
### Expected behaviour

To get a working sharing url.
### Actual behaviour

You get a wrong sharing url, that does not work. It's shaped like this : "https://IP/owncloud/remote.php/dave.php/dav/calendars/USER/CALNAME/ 
If I go check that url in my browser I get this message : " App not installed: "

I fixed the problem by using the old format of sharing url which is : "https://IP/owncloud/remote.php/caldav/calendars/USER/CALNAME
### Server configuration

**Operating system**: Raspbian

**Web server:** Apache

**Database:** Mysql

**ownCloud version:** 9.0.2

**Calendar version:** 1.1

**Updated from an older ownCloud or fresh install:** updated

**Comment by georgehrke** [comment]
known issue, will be fixed with https://github.com/owncloud/calendar/pull/486

**Comment by georgehrke** [comment]
(Please note that this url is not intended for sharing, it will only work for you)
