### ISSUE TITLE
user deleted birthday calendar by mistake - no recreation available

### ISSUE THREAD

**Issue by mr-gosh** [owncloud/calendar#508]
1. open calendar view
2. delete birthday calendar
3. try to create birthday calendar...
### Expected behaviour

if the birthday calendar is deletable - there should be a way to re-create it
### Actual behaviour

deleted birthday calendars are gone
### Server configuration

**Operating system**:
ubuntu 14.04 64bit

**Web server:**
apache 2.4

**Database:**
mysql

**PHP version:**
php7

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Calendar version:** (see ownCloud apps page)
1.1

**Updated from an older ownCloud or fresh install:**
updates from 9.0.1

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.11
  - news: 8.7.3
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - notes
  - ownnote
  - tasks
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
too sensitive for such a ticket
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
firefox 46

**Operating system:**
ubuntu 16.04

**CalDAV-clients:**
thunderbird
android davdroid
android caldavsync
#### Web server error log

```
gui related problem - son no error log here
```
#### ownCloud log (data/owncloud.log)

```
gui related problem - son no error log here
```
#### Browser log

``````
gui related problem - son no error log here```
``````

**Comment by DeepDiver1975** [comment]
There is an occ command to recreate the birthday calendar

**Comment by aspdye** [comment]
Are they not recreated automaticly :confused:

**Comment by mr-gosh** [comment]
the only thing i found in here
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html#dav-label
was the 

`dav:sync-birthday-calendar    Synchronizes the birthday calendar`

but this doesn't sound like the (re)creation of a that calendar would happen?!?

**Comment by DocSniper** [comment]
@mr-gosh 
Me too, deleted the automatically created birthday calendar. This command did help: 
sudo -u [http-user] [path-to]/php [path-to]/occ dav:sync-birthday-calendar

**Comment by georgehrke** [comment]
@aspdye AFAIK that's supposed to happen when you edit an contact. Though it will only add the edited contact.

**Comment by mr-gosh** [comment]
@sniperle thx - that really worked!

**Comment by aspdye** [comment]
We should make it undeleteable :wink: @georgehrke @DeepDiver1975

**Comment by georgehrke** [comment]
We had a lot of complains in the old calendar that the birthday calendar was not deletable
