### ISSUE TITLE
OC7 - add import function to gear wheel menu

### ISSUE THREAD

**Issue by j-ed** [owncloud/calendar#508]
## Expected behaviour

It should be possible to import a calendar file directly from the gear wheel menu of the calendar app, similar to the contacts app.

![20140731_oc7_contacts_import](https://cloud.githubusercontent.com/assets/2572764/3770141/2f4b08d8-18e7-11e4-9609-59b52796119e.jpg)

## Actual behaviour

To import an external calendar file it need to be uploaded to the file store first using the files app. Then you can click on that file to import it to your calendar.

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.26
ownCloud version: 7.0

#### Client Configuration

Browser: Firefox 31.0
Operating system: Windows 7

**Comment by etiess** [comment]
@georgehrke Do you know when this feature of the rework branch will be integrated in the main one? It's not in OC8 Beta 2.
Thanks!

**Comment by georgehrke** [comment]
current schedule for rework is 8.1

**Comment by jancborchardt** [comment]
Closing as duplicate of https://github.com/owncloud/calendar/issues/197 – let’s continue there.
