### ISSUE TITLE
ownCloud Calendar isn't artsy enough

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/calendar#510]
You know these nice looking, leather-backed organizers? You can sticker the heck out of 'em, make them look all nice and personal. Why can't we have that for the Calendar app? @jancborchardt will hate it but I want my flowers and super hero stickers...

**Comment by georgehrke** [comment]
@jospoortvliet You are a bit late for april fools 😉 

But please, no ugly skeuomorphisms

**Comment by georgehrke** [comment]
We could definitely make it more colorful, but generally I'm quite happy with the design.

**Comment by jospoortvliet** [comment]
well it was as much a joke as it was serious... We have theme support so that can be had easily. Skeumorphisms suck, with you on that one. So not sure if there's any room here.

**Comment by aspdye** [comment]
It should be based on the design of core. It does so - and therefore I like the current design 👍

**Comment by jancborchardt** [comment]
Well, isn’t using emojis that. ;)
