### ISSUE TITLE
“More” sidebar missing scrollbar on small resolutions

### ISSUE THREAD

**Issue by shtrom** [owncloud/calendar#511]
On small-ish resolutions, it is impossible to reach the Attendees/Reminders/Repeating zone as they are obscured by the buttons, with no scrollbar allowing to access them.
### Steps to reproduce
1. Set 1366x768 resolution
2. Go to oC calendar with Firefox under Gnone
3. Create an event, click More
### Expected behaviour

A scrollbar is enabled to access the overflowing area containing the Attendees/Reminders/Repeating bits.
### Actual behaviour

The Attendees/Reminders/Repeating area is inaccessible as it is under the Delete/Cancel/Export/... buttons

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/395
