### ISSUE TITLE
no entry in "Contact birthdays"

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#512]
Hello....

I missed Entry in my calendars "Contact birthdays" after Upgrade. My OC Upgrade Path: 8.2.3 > 9.0.0 > 9.0.1.3 > 9.0.2 . My Contacts (App: Contacts 1.2.0.0) have got Birthday entry but i don`t see it on my calendar. 

**What i have do it before that i create this post:**
1. www-data@raspi:~/owncloud$ ./occ dav:sync-birthday-calendar
..Start birthday calendar sync for ll ussers ...
4 [====================]
_ps. i have only 4 users_

Result: anymore no entry on my calendar

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by ghost** [comment]
Thank you for your Info
