### ISSUE TITLE
[OC7] Can't import ics anymore?

### ISSUE THREAD

**Issue by masterofeye** [owncloud/calendar#513]
Hallo, 

i cant import ics files. There is no dialog to import the calender from the files menu? Its a new fresh install of owncloud. 

Regards MOE

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
