### ISSUE TITLE
OC7 - IE doesn't show the unsharing possibility in calendar

### ISSUE THREAD

**Issue by danielbauer** [owncloud/calendar#515]
Several people have the problem to unshare a calendar, with IE, because the button is not shown ...

![Uploading screen2.jpg . . .]()

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
