### ISSUE TITLE
Add event description input in the small event creation dialog

### ISSUE THREAD

**Issue by shtrom** [owncloud/calendar#516]
### Steps to reproduce
1. Use ownCloud calendar 9
2. Click anywhere on the schedule
3. The small event creation dialog appears
### Expected behaviour

In this dialog, I would expect to be able to input a description, in addition to (or instead of) the location. The location box should perhaps only be a single line input box, while the description would be a multiline textarea.
### Actual behaviour

Only a multiline location input box is visible. It is a bit confusing that the location box is more that one line, as it suggests to the user that it is meant to contain longer text (such as a description)

(PS: Just reporting UI bugs, as I adjust to oC/calendar 9, but I otherwise really like the improvement, much snappier and prettier; well done!)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/421
