### ISSUE TITLE
calDAV Calendar does not show entries on iOS calendar app but on TB/Lightning

### ISSUE THREAD

**Issue by quantenquatsch** [owncloud/calendar#52]
Hey Guys,
I have accessed both of my calendars on owncloud via calDAV from two Thunderbird  Lightning Instances. Everything works fine so far. When I created a calDAV account on my iPhone it shows no error, both calendars appear on calendars list within the calendar app, when displaying the calendar, none of my dates appear. It once worked without any problem, but I did not notice when it stopped except it was even before updating to owncloud 5.0.6. I copied the calDAV links directly from the webinterface, so no typo should be within the iPhone settings. I also double checked the login.

HTTPS is enforced. What other infos do you need?

Regards

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
