### ISSUE TITLE
unknown timezone (Europe/Berlin) back to UTC, due to a missing slash

### ISSUE THREAD

**Issue by raoulblinblin** [owncloud/calendar#521]
### Steps to reproduce
1. open the  calendar with  this address .../index.php/apps/calendar (notice the missing slash at the end)
### Expected behaviour

It should load the same way as .../index.php/apps/calendar/ (with an ending slash)
### Actual behaviour

It loads seemingly fine, but a message says "bad or unknown timezone, back to UTC". and my calendars are GMT+2. It took me some luck to find out that the behaviour changed just with the presence or not of an ending slash
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.2
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
updated
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by leegarrett** [comment]
I can confirm that this exact error happens for me, too. I am confident that this is a recent error.

Adding a trailing slash to /owncloud/apps/calendar works around the problem.

**Comment by jhagerer** [comment]
I can confirm this, too. Kept me busy for some days. I am using the same setup as raoulblinblin.

**Comment by hitam4450** [comment]
Same here........

regards, hitam4450

**Comment by bjoernmainz** [comment]
I can also confirm this. I can also confirm that adding a trailing slash works around this problem.
