### ISSUE TITLE
Automated calendar import in OC9

### ISSUE THREAD

**Issue by albatros69** [owncloud/calendar#522]
I was a user of the script to automate ICS import into a calendar (https://github.com/georgehrke/cl-calendarimport), and this is not compatible with OC9.

Is there a similar feature foreseen in OC9?
If not, what could be the effort to update this script for OC9? (To know if I can try to give a hand)

**Comment by georgehrke** [comment]
What did you use it for? ics files from the web?

**Comment by albatros69** [comment]
Indeed, yes: I was downloading ics files from the web (like school holidays or events) and importing them into calendars

**Comment by georgehrke** [comment]
Ok, then I'll close this issue in favor of https://github.com/owncloud/calendar/issues/132
