### ISSUE TITLE
CalDAV url is still wrong in OC 9.0.2

### ISSUE THREAD

**Issue by davleema** [owncloud/calendar#523]
Looks like the generated CalDAV url is(are) still wrong in OC 9.0.2
- For my personal calendar, I get someting that contains ../dav/dav/...  When trying anyway, Thunderbird refuses to enable this calendar entry (it stays inactive).
  The url looks like this:
  "http://myserver.com/oc9/remote.php/dav/dav/calendars/myusername/personal/"
  Take note of the "/dav/dav/" part.
- The primary caldav address also doesn't work in Thunderbird, it just gives a yellow exclamation mark next to it.
### Steps to reproduce
1. copy Caldav url for personal calendar or primary caldav url
2. add these urls for a new calendar in Thunderbird
3. see how TB refuses to sync or connect to calendar (no error message given, calendar entry in TB  stays inactive) 
### Expected behaviour

TB should sync the calendar
### Actual behaviour

in case of:
- personal caldav url: calendar stays inactive in TB (but no error mesage given)
- primary caldav url: yellow exclamation mark (no error message)

Now, for my personal calendar, if I remove the extra "/dav" from the url, then it does work properly. 
So, it looks like there is one "dav" too many in the url generated for the personal calendar.
### Server configuration

**Operating system**: Slackware Linux 14.1 x64

**Web server:** Apache 2.4.20

**Database:** MariaDB 5.5.47

**PHP version:** 5.6.20

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Calendar version:** (see ownCloud apps page)
1.1

**Updated from an older ownCloud or fresh install:**
update from 9.0

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.4
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
sftp

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**
Firefox 46
**Operating system:**
Slackware 14.1 x64
**CalDAV-clients:**
Thunderbird 45.0
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Calendar app is updated independently from ownCloud.
Fix will be released on Tuesday

**Comment by davleema** [comment]
Let's hope so, this is keeping me from using OC 9 in production.
