### ISSUE TITLE
[Calendar 1.2] Importing ICS as new calendar no longer works

### ISSUE THREAD

**Issue by areteichi** [owncloud/calendar#532]
### Steps to reproduce
1. Install Calendar 1.2 on ownCloud 9.0.2
2. Import an ICS file (from Calendar 0.8.2)
3. Select "New Calendar"
### Expected behaviour

It should be possible to import ICS data as a new calendar.
### Actual behaviour

The import process hangs at "Import scheduled"
### Server configuration

**Operating system**:
Debian 6

**Web server:**
Shared Hosting

**Database:**
MySQL 5.5.47

**PHP version:**
 PHP 5.6

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2

**Calendar version:** (see ownCloud apps page)
1.2

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Signing status (ownCloud 9.0 and above):**
Signed

**Comment by georgehrke** [comment]
Can't reproduce, please use the **entire** issue template and also provide logs.

**Comment by georgehrke** [comment]
related to https://github.com/owncloud/calendar/pull/526

**Comment by georgehrke** [comment]
just released 1.2.1 which should solve this issue
