### ISSUE TITLE
Give an option to hide the user's name who the calendar is shared from

### ISSUE THREAD

**Issue by RikuXan** [owncloud/calendar#548]
Would it be possible to add an option that changes the calendar's display name in the left sidebar of the calendar overview screen, so that it does not display the calendar's owner for shared calendars?

For somewhat long calendar names, the name display results in the text being cut off by the sidebar which looks sloppy. Alternatively, the display name could also be line wrapped to solve this.

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues
