### ISSUE TITLE
[Question] Howto Filter for category with script

### ISSUE THREAD

**Issue by Mannshoch** [owncloud/calendar#549]
I use following PHP-Script I found [here](https://statuscode.ch/2015/06/Combining-ownCloud-and-Google-calendar-for-public-room-availability/.)

How could I Filter the calendar to only get Calendar entries with Category "public" ?

```
<?php

require_once('/PATHtoOWNCLOUD/3rdparty/autoload.php');
use Sabre\VObject;

$remoteHost = 'http://example.com';
$calendarName = 'CALENDARNAME';
$username = 'USERNAME';
$password = 'PASSWORD';

$curl = curl_init($remoteHost . '/PATH/'.$username.'/'.$calendarName.'?export');
curl_setopt($curl, CURLOPT_USERPWD, $username . ":" . $password);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_VERBOSE, true);
$ics = curl_exec($curl);
curl_close($curl);

$calendar = VObject\Reader::read($ics);
$calendar->{'X-WR-CALNAME'} = 'Unser Kalender';

file_put_contents('/PATHtoFILE/public.ics', $calendar->serialize());
```

**Comment by georgehrke** [comment]
Check in:

```
// Replace all SUMMARY fields with a value of "Reserved"
foreach($calendar->children() as $children) {
    if($children instanceof VObject\Component\VEvent) {
        $children->SUMMARY = 'Reserved';
    }
}
```

if `$children->CATEGORIES` contains public.

**Comment by Mannshoch** [comment]
My knowledge about PHP is really fresh so maybe I have problems I shouldn't have.
Did I understood right, that I have to do it like this?

```
foreach($calendar->children() as $children) {
    if(($children->CATEGORIES contains 'public') === false){
        $children->remove();
    }
}
```

It seems to do not work. Maybe `remove` is not the right but i was not able to find the correct way to remove.

**Comment by georgehrke** [comment]
AFAIK `$children->CATEGORIES` is an array. You should be able to do: `in_array('public', $children->CATEGORIES)`.
http://php.net/manual/en/function.in-array.php

**Comment by Mannshoch** [comment]
thanks for the hint.

I detected a [Stackoverflow](http://stackoverflow.com/a/26524231) hint to filter and it use in_array, but it seems to do not have any effect on the ICS output.

```
$allowed = ['public'];
$children1 = array_filter(
    $children->CATEGORIES,
    function ($key) use ($allowed) {
        return in_array($key, $allowed);
    },
    ARRAY_FILTER_USE_KEY
);
$children = $children1;
```

The resulting ICS file looks like this, and also contain the second Event which do not contain public as category:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//SabreDAV//SabreDAV//EN
CALSCALE:GREGORIAN
X-WR-CALNAME:Abonnieren
X-APPLE-CALENDAR-COLOR:#CC317C
BEGIN:VEVENT
LAST-MODIFIED:20160520T114001Z
DTSTAMP:20160520T114001Z
UID:20160506T130150CEST-2739uW0BJP
SUMMARY: A Summary
CATEGORIES:public
CATEGORIES:other categories
DTSTART:20160525T190000
DESCRIPTION:A description
LOCATION:A location
URL:An URL
X-MOZ-GENERATION:1
END:VEVENT
BEGIN:VEVENT
UID:20160506T130150CEST-2778uefHCn
DTSTAMP:20160506T110150Z
CATEGORIES:An Other Categorie
DESCRIPTION:A Description
DTSTART:20160905T193000
LOCATION: something
SUMMARY:A Summary
URL:An URL
END:VEVENT
... 
```

**Comment by georgehrke** [comment]
@Mannshoch Did you find a solution? :)

**Comment by Mannshoch** [comment]
No. I was not able to get help and get how to do it myself with PHP. Maybe its also a time problem and its not bother me enough to let me free some time to learn how to do it. 

(I  export the calendar with cron to use it with the "amr-ical-events-list" plugin in Wordpress.)

**Comment by georgehrke** [comment]
Okay, please ask on the user mailing list or on the forums. :)
Will close this ticket for now.
