### ISSUE TITLE
Wrap calendar name in the sidebar

### ISSUE THREAD

**Issue by RikuXan** [owncloud/calendar#551]
I [recently suggested the addition](https://github.com/owncloud/calendar/issues/548) of an option to not show the name of a calendar's sharer in the calendar app's sidebar due to it looking ugly when being longer than the available space for the calendar name. This was closed and I was told to re-open it on the owncloud/core repo. One of the developers there suggested that such a fix would be not much more than a band-aid to my actual problem.

Therefore I would like to suggest that the calendar name (displayName) on the main overview's sidebar should line-wrap when to long for the sidebar's width. I also think it would look better to add a space between calendar and sharer name `"calendarName(sharerName)" -> "calendarName (sharerName)"`.

**Comment by georgehrke** [comment]
Please link me to the issue in core

**Comment by RikuXan** [comment]
[Sure](https://github.com/owncloud/core/issues/24747)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/core/issues/22176
