### ISSUE TITLE
Left navigation bar styling issue

### ISSUE THREAD

**Issue by onny** [owncloud/calendar#552]
### Steps to reproduce
1. Open the calendar app
2. Create as many calendars until the vertical space of the left navigation is exceeded
3. Now the last entries on the bottom starts overlapping
### Expected behaviour

Left navigation menu should be scrollable in case there are too many entries or the screen size is too small
### Actual behaviour

There seems to be some styling issues in the sidebar ...
![2016-05-21-125934_swaygrab](https://cloud.githubusercontent.com/assets/757752/15448167/7022fb6a-1f5a-11e6-9dcc-c5532be608d4.png)
### Server configuration

**Operating system**: ArchLinux x74

**Web server:** nginx 1.10.0

**Database:** mysql-server 5.5.47

**PHP version:** php-fpm 7.0.6

**ownCloud version:** 9.0.2

**Calendar version:** 1.2.2
**Updated from an older ownCloud or fresh install:** Updated from older Owncloud version
### Client configuration

**Browser:** firefox 46.0.1
**Operating system:** ArchLinux x64

**Comment by georgehrke** [comment]
@raghunayyar please take a look :)

**Comment by onny** [comment]
Looks like this bug is fixed with version 1.2.2. Thanks a lot!

**Comment by georgehrke** [comment]
Okay 🤔
