### ISSUE TITLE
Time looks ungly on mac

### ISSUE THREAD

**Issue by brantje** [owncloud/calendar#554]
![screen shot 2014-09-11 at 10 56 33](https://cloud.githubusercontent.com/assets/2758767/4231486/a8661990-3991-11e4-8aee-a83f09ee7b48.png)
Can we change the input type from time to text?
Apple messes up the display.

**Comment by brantje** [comment]
I've only got an Apple device at work, and can't do ownCloud this at work. 
Sorry. But we can test with some test tools?

**Comment by raghunayyar** [comment]
Self assigning. I have a mac.
