### ISSUE TITLE
Feature request: Subscribe to public calendars

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#555]
How about subscribing to public - or private -  available calendars at different intervals e.g. hourly, daily, weekly monthly ??

regards, hitam4450

**Comment by georgehrke** [comment]
Duplicate .....

**Comment by georgehrke** [comment]
Seriously, please start searching for existing issues before you create new ones ........

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/132
