### ISSUE TITLE
Add button to README telling us about outdated deps 

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#56]

**Comment by dominicrico** [comment]
There are three different services for that type of badges. 
- [Gemnasium](http://gemnasium.com)
- [VersionEye](https://www.versioneye.com)
- [David](https://david-dm.org/)

The thing about David is that they only support NPM deps, no bower deps and the package.json must be in the root folder of the repo. The others support both, but one of the owners must register it self there to grand one of the services the right to read the package.json, which maybe needs to be in the root folder (but I dont really know).

**Comment by georgehrke** [comment]
In core we go with VersionEye, so it's probably the best way to go with this one.

@DeepDiver1975 Can you please setup VersionEye for us? :)

**Comment by georgehrke** [comment]
ping @DeepDiver1975 :)

**Comment by georgehrke** [comment]
done
