### ISSUE TITLE
Etag missing in CalDav synchronisation

### ISSUE THREAD

**Issue by albatros69** [owncloud/calendar#560]
I'm using the DAVDroid client to sync with owncloud and I'm getting the attached error on the client, which prevent the sync to work.

The only reference I found on the issue is: https://forums.bitfire.at/topic/808/owncloud-fails-to-sync-contacts-received-multi-get-response-without-etag/5

How could I investigate further, first to workaround the issue (i.e. make the sync working again), and secondly to find where the culprit is?

[Erreur.txt](https://github.com/owncloud/calendar/files/288949/Erreur.txt)

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by georgehrke** [comment]
also use the entire issue template please ...
