### ISSUE TITLE
Birthday Calendar renaming and color changing not remembered

### ISSUE THREAD

**Issue by ManOki** [owncloud/calendar#561]
### Steps to reproduce
1. open calendar app
2. click "three dots" settings of contact_birthdays
3. change name or color
4. name and color is instantly changed
5. refresh page
### Expected behaviour

name and color stay changed
### Actual behaviour

name and color have old values again
### Server configuration

ownCloud version: 9.0.2
Calendar version: 1.2.2
Updated from an older ownCloud and contact app
Signing status: all valid, nothing changed
### Client configuration

Browser: Firefox

currently, birthday calendar is read-only. so the overall behaviour is somehow correct, but might be not expected at first for new users.

"contact_birthdays" appears in Subscription section.

**Comment by georgehrke** [comment]
please use the entire [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

You didn't even mention what version you use ...

**Comment by georgehrke** [comment]
Does the calendar appear in the Calendar or Subscription section?

**Comment by ManOki** [comment]
sorry, updated my post.

**Comment by raimund-schluessler** [comment]
This is likely the same issue as https://github.com/owncloud/calendar/issues/399. A `PROPPATCH` is not allowed to the `contact_birthdays` calendar. At least this happens for me when trying to change the color.

**Comment by georgehrke** [comment]
Yes, closing as dup
