### ISSUE TITLE
Cant create/delete events in some cases in some browsers

### ISSUE THREAD

**Issue by otbe** [owncloud/calendar#563]
Hi,

I think there is a problem with the headers that are sent by the calendar client within owncloud.
### Steps to reproduce
1. Try to create an event in Safari (9.1.1) and owncloud (9.0.2)
2. Try to delete an event in Chrome (50)
### Expected behavior

It should work.
### Actual behavior

It does not work. :P
### Server configuration

**ownCloud version:** 9.0.2
**Calendar version:** 1.2.2

Let me try to explain what happens:
If I add an event to my default calendar in Safari it appears in the GUI and I get an (console) exception:

`PUT http://myHost/remote.php/dav/calendars/<user>/defaultcalendar/hhl9o6wk84o547f4hwwoa3.ics 412 Precondition failed` 

with this response:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified and the resource did not exist</s:message>
  <s:header>If-Match</s:header>
</d:error>
```

with this If\* Headers:

```
If-Match    null
```

There are no entries in owncloud logs only the nginx complains about it (412).
With chrome the creation process works but the url is a bit different:

```
PUT http://myHost/remote.php/dav/calendars/<user>/defaultcalendar/ownCloud-lw1h6iteu7mc8wpg8ihllq5mixde5c0qtcgqrme5b2gw1xlxr.ics
```

The problem comes back in chrome if I try to delete an event.

I use the nginx config from https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-example-configuration

Whats wrong with my setup? In older versions of owncloud & calendar it works as expected.

Thanks!

**Comment by georgehrke** [comment]
For some reason it tries to update an event instead of creating one. 😕

**Comment by otbe** [comment]
Update:
I tried to debug this issue a bit, but can't reproduce it anymore. Urls seems to be identical now in chrome and safari. Both PUT for new events and it simply works.

Really strange, because I did nothing on the server side. Problem was present for several weeks, but now it's gone. 

Maybe this could be closed for now

**Comment by alexjustesen** [comment]
I'm having the same issue currently, identical setup. Won't workin Chrome v50

**Comment by georgehrke** [comment]
@alexjustesen What exactly doesn't work in Chrome50?

**Comment by alexjustesen** [comment]
@georgehrke I have no option to be able to create events other than importing. Clicking anywhere in the calendar doesn't trigger anything.

**Comment by georgehrke** [comment]
@alexjustesen So you don't even see the dialog when selecting a time range?
That's a different issue.
Please report a new issue using the **entire issue template** and providing **all logs** asked for.

**Comment by georgehrke** [comment]
closing this issue as it was not reproducible and disappeared on the user's side.
