### ISSUE TITLE
No "UNTIL" field for recurring events

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/calendar#569]
There is no possibility to create a recurring event until a specific date. I think that is needed for many, many use cases, isn't it?

**Comment by georgehrke** [comment]
Please search for issues before creating new ones ...
Having to deal with duplicate issues is really annoying and nothing but a waste of time 😉 

<img width="1031" alt="issues_ _owncloud-calendar_safari_technology_preview__today_at_2_16_36_pm" src="https://cloud.githubusercontent.com/assets/1250540/15894040/db7ef18e-2d83-11e6-8689-2e91891b17bc.png">

**Comment by scriptPilot** [comment]
Sorry, I did only search for "recurring" ... my mistake!

**Comment by scriptPilot** [comment]
#484
