### ISSUE TITLE
Reminder type is "Audio alarm" by default; sync problems

### ISSUE THREAD

**Issue by rgugliel** [owncloud/calendar#570]
### Steps to reproduce
1. Add an event
2. Click "More..."
3. Add a reminder
### Expected behaviour

The default reminder type should be popup (or we should be able to chose the default value once and for all).
### Actual behaviour

The default reminder type is "Audio alarm". This is as problem because it doesn't sync with some programs (for example Lightning).
### Server configuration

**Operating system**: Ubuntu 14.04.4 LTS
**Web server:** Apache

**Database:** SQLite

**PHP version:** 5.6.22-4+deb.sury.org~trusty+

**ownCloud version:** 9.0.2

**Calendar version:** 1.2.2

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:** 
Enabled:
- activity: 2.2.1
- calendar: 1.2.2
- comments: 0.2
- contacts: 1.3.0.0
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- tasks: 0.9.1
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "**********_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "owncloud.rafaelguglielmetti.ch"
        ],
        "datadirectory": "\/home\/**_***_\/www-dev\/**_**_\/owncloud\/data",
        "overwrite.cli.url": "**_*******h",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO
### Client configuration

**Browser:** Firefox 46.0.1

**Operating system:** Linux Mint 17.3

**CalDAV-clients:** Boxer (on Android), Lightning (on Thunderbird)

**Comment by georgehrke** [comment]
> The default reminder type is "Audio alarm". This is as problem because it doesn't sync with some programs (for example Lightning).

Can you explain why? Is there any ticket you can refer me to?

**Comment by rgugliel** [comment]
The fact that audio is default is shown in the next picture:
![audio](https://cloud.githubusercontent.com/assets/4578468/15922758/b0500146-2e29-11e6-8007-3edcf3bf738e.png)

By default Lightning sync the reminders which are "popup" I tried the two versions.

**Comment by georgehrke** [comment]
I know that audio is the default reminder 😉
But can you explain why Lightning allegedly has a problem syncing Audio alarms?

**Comment by rgugliel** [comment]
Ooops, sorry.
I don't know but Lighning has such a problem. However, the different calendar apps I tried (Lightning, Google web calendar, two different apps on Android) all use the "popup" format by default so it'll would be interesting to chose in my opinion.

**Comment by georgehrke** [comment]
> I don't know but Lighning has such a problem.

If Lightning is not able to sync Audio alarms you should report a bug there ;)

There is some issue about being able to set a default alarm: https://github.com/owncloud/calendar/issues/119

**Comment by rgugliel** [comment]
I still don't understand why OC calendar uses a format no one use by default...

But, still: https://bugzilla.mozilla.org/show_bug.cgi?id=1279190

**Comment by georgehrke** [comment]
> I still don't understand why OC calendar uses a format no one use by default...

That's something to discuss in #119 😉
