### ISSUE TITLE
Share event on the calendar

### ISSUE THREAD

**Issue by FilipeDanielGS** [owncloud/calendar#572]
I use ownCloud 8.2.5 (stable) with Calendar 0.8.2.
I'm having trouble to create events and share the calendar.
I create the event and saved, after I enter the event, in the Share tab by clicking "email" nothing happens.
What could it be?

**Comment by georgehrke** [comment]
Calendar 0.8.2 is not supported anymore, please update to ownCloud 9 and use the calendar 1.2

**Comment by FilipeDanielGS** [comment]
Hello,
OwnCloud updated to 9 and the schedule for 1.2. Perfect!
The update gives me the option to send enventos, however when the user will register the email in personal perfial, the registration field is impossible. What can happen?

**Comment by georgehrke** [comment]
>  the registration field is impossible

Do you mean, that the email field in personal settings is disabled?

You probably use a user backend (like LDAP) and the email address needs to be configured in the backend.

**Comment by FilipeDanielGS** [comment]
The Active Directory account in the email is registered, but I can not view the email in owncloud

**Comment by georgehrke** [comment]
Probably just a misconfiguration.
But the calendar repo is not the right place for issues with AD.
Please consider the user mailing list or ask in the forums :)

**Comment by FilipeDanielGS** [comment]
Thank you for your help. Redid the global catalog and was ...
