### ISSUE TITLE
Selected calendar = Preselected calendar for new event

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/calendar#573]
If click on a calender in the list on the left and after that create a new event, the selected calendar left should be the preselected calendar for the new event as well. Especially if it is the only visisble calendar to that time.

**Comment by georgehrke** [comment]
This doesn't really fit into the general ux concept of ownCloud. Clicking an item always triggers an action.
Clicking a day opens editor for new event, clicking an event opens editor, clicking a calendar triggers visibility.

And you don't save a lot of time.
Your concept:
- click calendar in sidebar
- select time range in calendar view

Current concept:
- select time range in calendar view
- select calendar in editor's dropdown

Not sure what you are trying to achieve, but this might be related to https://github.com/owncloud/calendar/issues/133 ?

cc @jancborchardt @raghunayyar

**Comment by georgehrke** [comment]
#133 is, besides being able to sort the calendars, mostly about being able to define a default calendar, by dragging it to the first position in the list.

**Comment by scriptPilot** [comment]
For example, in Google you can click in two different ways:
- on the colored point in front of the calendar name >> calendar visiblity toggle
- on the calendar name >> will set this calendar as preselected one

Use case:

For business I click first on business calendar, after that enter several business related appointments. After that I click on the sports calendar and enter all sport team releated events.

That is the same behaviour as in Outlook or Google for example :-)

#133 could be a kind of Workaround...

**Comment by georgehrke** [comment]
Closing because it doesn't fit into the UI concept.
