### ISSUE TITLE
Email visible to the guest of an event

### ISSUE THREAD

**Issue by FilipeDanielGS** [owncloud/calendar#574]
When creating a calendar event and invite a participant via email, the guest receives as sender SMTP registered in owncloud.
Is there a way the event creator's email address go to the guest?

**Comment by georgehrke** [comment]
So, first of all:
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

Second:
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) 
You didn't even mention what version you use, not helpful 😉 

Third:
This is a dup of https://github.com/owncloud/core/issues/23578#issuecomment-224881001
