### ISSUE TITLE
duplicate entries after update calendar via import ics

### ISSUE THREAD

**Issue by christoph5180** [owncloud/calendar#575]
Owncloud Version 9.0.2 
Calendar Version 1.2.2
### Steps to reproduce
1. import ics file to new calendar
2. take the same file to update the new calendar
3. now all entries are double

this is since the update of owncloud 8 to 9

on owncloud 8 the calendar app ask on import what happen with exists entries (I think there was an option to override exists entries). owncloud 9 do not ask.

**Comment by georgehrke** [comment]
This is not possible in a performant manner with ownCloud 9 or later.
