### ISSUE TITLE
Call to a member function __get() on a non-object

### ISSUE THREAD

**Issue by Timbo1a** [owncloud/calendar#575]
Hi,

I tried to import an .ICS file exported another calendar.
I clicked on the uploaded ICS and nothing happend.

So I opended the browser console and got this successfull request:
http://server/index.php/apps/calendar/ajax/import/dialog.php [HTTP/1.1 200 OK 183ms]

The logfile says:
Call to a member function __get() on a non-object at /pathtoOwncloud/apps/calendar/lib/import.php#363 

Setup:
Browser: Chrome/Firefox
Server: Debian 7 64, Apache2/fcgi/suexec
Tested in OC 7.0 and 7.02

I also have an error in the network resource view, 404 jquery.min.js
dunno whats up there,but heres the message:
Request URL:http://server/core/js/jquery-1.10.0.min.map
Request Method:GET
Status Code:404 Not Found

Here is the head of the ICS File:
BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
PRODID:www.example.com

BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE

BEGIN:VEVENT
UID:0x0E1AFAB12D67014D9620F6139B3AF671
SUMMARY:Something
DTSTART;TZID=Europe/Berlin:20140922T094500
DTEND;TZID=Europe/Berlin:20140922T111500
SEQUENCE:0
X-MOZ-GENERATION:1
DTSTAMP:20140925T100744
LOCATION:HX-6406
ORGANIZER;CN="Mr. X"
CATEGORY: (V)
DESCRIPTION:
CLASS:PUBLIC
END:VEVENT
and so on....

Some data in this text are faked.

Greets

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
