### ISSUE TITLE
Release of calendar Version 1.3 ????

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#577]
When will calendar 1.3 be released ??

regards, hitam4450

**Comment by georgehrke** [comment]
I had only very little time to work on the calendar the last couple of weekends and the other maintainer has no time at all in the moment.
Maybe next week, maybe next month, can't tell

**Comment by hitam4450** [comment]
What is the use of fixed and given release dates, then ????

**Comment by georgehrke** [comment]
It doesn't make sense to release a new version when only 1 or 2 issues where fixed ...

Instead of crying around here: Contribute and help bring the calendar forward!
