### ISSUE TITLE
not updated calendar 

### ISSUE THREAD

**Issue by verissimomoraes** [owncloud/calendar#578]
### Steps to reproduce
1. create event 
2. invite other user onwclound
3. check calendar the other user , not be updated 
### Expected behaviour

other user receive email in the rainloop, contender invite , and aceit it,  be update calendars 
same happnes in the others clients email , outtlook , gmail ..
### Actual behaviour

other user receive email , containing invite , but not have foramting html , but have file.ics
this only happens in rainloop  , the others users,  outlook , gmail and tanderbird its ok.
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9
**Calendar version:** (see ownCloud apps page)
1.2
**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Can you please try to rephrase your bug report. I'm sorry, but it's very difficult to understand.

**Comment by verissimomoraes** [comment]
to create event in the calendar, inviting participants using email client rainloop, the invitation is not presented with the html formatting.

that same user getting at gmail, the invitation is presented with the html formatting.

**Comment by georgehrke** [comment]
Okay, that looks like a bug in our CalDAV server.

Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by verissimomoraes** [comment]
thanks !
