### ISSUE TITLE
Activation or deactivation of calender beyond fifth position fails

### ISSUE THREAD

**Issue by laodzu** [owncloud/calendar#579]
When more than five calendars are available, it is not possible to activate or deactive any of the calenders beyond the fitfth position in the list.  As far as I can see no activation event is posted and so no change happens.
This is especially unfortunate when one deactivated calender gets pushed beyond this limit by newly available calenders.  I currently cannot find any way to enable such a calender again at all.

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
