### ISSUE TITLE
Re-enabling Calendar app should always enable all calendars

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#580]
When re-enabling the Calendar app (after it was disabled due to an update) the Personal / default calendar does not seem to be enabled, which makes you think the data is gone.

Hence on re-enabling, all calendars should be visible. (Or if in some way you can save which were visible before.)

@georgehrke @raghunayyar 

See https://twitter.com/hanno/status/743365900909174784 cc @hannob

**Comment by georgehrke** [comment]
Okay 😕 

Sounds confusing. will check

**Comment by georgehrke** [comment]
@jancborchardt Should it really enable **all** calendars or just enable the ones that used be visible prior to the update?

**Comment by jancborchardt** [comment]
Ideally those visible prior to the update

**Comment by blizzz** [comment]
This issue got some publicity (at least it is related): https://www.bitblokes.de/2016/07/nextcloud-9-update-bringt-enterprise-funktionen-und-client-fuer-ios/

**Comment by raimund-schluessler** [comment]
Maybe one should also enable a calendar when an entry is added?

**Comment by georgehrke** [comment]
@raimund-schluessler There is some issue for that.

The default calendar not enabled issue was already fixed iirc, let me double check though

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar/issues/291

**Comment by jancborchardt** [comment]
@georgehrke then make sure it's also fixed for other Calendars which were enabled before. ;) When in doubt, it's better to enable all than just the default one.

**Comment by georgehrke** [comment]
Yes, the title of #291 is misleading.
This is just about enabling calendars that are neither enabled nor disabled in the db.
