### ISSUE TITLE
Provide freebusy interface on calendars

### ISSUE THREAD

**Issue by gjanssens** [owncloud/calendar#582]
Freebusy information allows calendar apps to more intelligently propose dates for events based on the availability of the selected participants.

It's like sharing your calendar with others, however it will only show when you are busy, not the details for each event.

It would be great if the owncloud calendar app would have an interface to publish this information based on the events data it has.

From searching a bit through the owncloud code it looks like sabredav has some support for it, but I didn't find whether the code alse uses it and does publish freebusy information. If it does, I am only missing the documentation on how to use it. If not it would be great to have this implemented.

Thank you.

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues
