### ISSUE TITLE
 [Request] add Ical Feed import

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/calendar#583]
Hello,

this is only a Feature Request.
Can you add some Settings that it would be possible to import an Ical Feed? 

That is an Project but didn´t work anymore:

https://gist.github.com/mammuth/74c1daed04f661dec641

best regards

Lars

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/132 is a better solution than manually importing ical feed
