### ISSUE TITLE
Wrong Timezone in Calendar.

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/calendar#584]
### Steps to reproduce
1. create Calendar
2. Import Calendar from Google
3. click on one Entry
### Expected behaviour

showing the Calendar Entrys in GMT+2 Europe/Berlin
### Actual behaviour

When you click on one entry it shows the entry in UTC not local Time.
But when i add an new entry in Owncloud it shows the correct Timezone
![issue_timezone](https://cloud.githubusercontent.com/assets/3295104/16179258/44e2e290-3660-11e6-8693-a5f270bc1d8f.png)
on my Android Smartphone and Thunderbird it shows the correct time.
![thunderbrid](https://cloud.githubusercontent.com/assets/3295104/16179281/c698181e-3660-11e6-9d9b-7e9c5e2ad562.png)

```
lars@h2530151:~/httpdocs/owncloud/config$ date
So 19. Jun 21:00:13 CEST 2016
```
### Server configuration

**Operating system**:
ubuntu 14.04 LTS
**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23
**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
7.07
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Calendar version:** (see ownCloud apps page)
1.2.2
**Updated from an older ownCloud or fresh install:**
Fresh installation
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - bookmarks: 0.7
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.1
  - music: 0.3.11
  - news: 8.8.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - shorten: 0.0.15
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendarplus
  - encryption
  - external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocernowp783d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-surfer.eu"
        ],
        "datadirectory": "\/mnt\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud-surfer.eu",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "maintenance": false,
        "dbname": "owncloud2",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "lars",
        "mail_smtpmode": "php",
        "mail_domain": "cloud-surfer.eu",
        "loglevel": 0
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Google Chrome Version 51.0.2704.103 m (64-bit)
**Operating system:**
Windows 10 (64bit)
**CalDAV-clients:**
#### Web server error log

```
no errors
```
#### ownCloud log (data/owncloud.log) But not related to this issue it shows the correct date

```
Debug   files_antivirus Scan started File: 1352Account: Lars Path: Lars/files/Bildersammlung/Aufnahmen Dezember Oberpfalz 2014/amberg1.JPG  2016-06-19T21:01:14+02:00
Debug   cron    Run job with ID 12  2016-06-19T21:01:14+02:00
Debug   cron    Finished job with ID 13 2016-06-19T21:01:14+02:00

```
### the Part of the imported ICS file from my Google Calendar (it´s only the part with the "nachtdienst" Entry and the Timezone Settings from the ics file

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Anjas Arbeit
X-WR-TIMEZONE:Europe/Berlin
X-WR-CALDESC:Dienstplan von Anja
.
.
.
STATUS:CONFIRMED
SUMMARY:Nachtdienst
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT1H0M0S
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTART:20160618T173000Z
DTEND:20160619T050000Z
DTSTAMP:20160619T182033Z
UID:8654af4d-d1e2-4a14-a2cd-3c747e69e2a3
CREATED:20160525T062916Z
DESCRIPTION:
LAST-MODIFIED:20160531T105838Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
```

would be cool when anyone can help.

**Comment by georgehrke** [comment]
> the Part of the imported ICS file from my Google Calendar (it´s only the part with the "nachtdienst" Entry and the Timezone Settings from the ics file

Well, not really 😉 

```
STATUS:CONFIRMED
SUMMARY:Nachtdienst
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT1H0M0S
END:VALARM
END:VEVENT
```

... is the end of some event

and 

```
BEGIN:VEVENT
DTSTART:20160618T173000Z
DTEND:20160619T050000Z
DTSTAMP:20160619T182033Z
UID:8654af4d-d1e2-4a14-a2cd-3c747e69e2a3
CREATED:20160525T062916Z
DESCRIPTION:
LAST-MODIFIED:20160531T105838Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
```

is the incomplete beginning of another event

no timezone data

**Comment by georgehrke** [comment]
Please open the calendar in your browser, open the JS Console and type in `jstz.determine().name();`

**Comment by georgehrke** [comment]
> When you click on one entry it shows the entry in UTC not local Time.

Well, the explanation is pretty simple.
The time information in the event is UTC: `DTSTART:20160618T173000Z`
That's what the `Z` at the end means.

**Comment by Happyfeet01** [comment]
sorry,

is it an export problem from Google? 

```
BEGIN:VEVENT
DTSTART:20160617T173000Z
DTEND:20160618T050000Z
DTSTAMP:20160619T182033Z
UID:0763beb1-b226-442f-971e-4ce9db2abcf7
CREATED:20160525T062805Z
DESCRIPTION:
LAST-MODIFIED:20160531T105832Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Nachtdienst
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT1H0M0S
END:VALARM
END:VEVENT
```

**Comment by georgehrke** [comment]
> Please open the calendar in your browser, open the JS Console and type in jstz.determine().name();

never mind

**Comment by Happyfeet01** [comment]
jstz.determine().name();
"Europe/Berlin"

**Comment by georgehrke** [comment]
As far as I can tell the time displayed in the actual calendar view is correct, right?

Then this is no bug. The raw calendar data you posted doesn't say it's Europe/Berlin. All the time data in there is given in UTC. That's why we display UTC in the editor. You can change the timezone when you click on advanced or "Mehr ..."

**Comment by Happyfeet01** [comment]
thanks for your help
