### ISSUE TITLE
Owncloud Share button not working on owncloud 6

### ISSUE THREAD

**Issue by malaysianboy** [owncloud/calendar#591]
Please help...my owncloud 6 share button..does not work..when i click it nothing happens..

Please help...

Any php debugging 

Thanks a million

Im new here

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
