### ISSUE TITLE
Make it possible to skip popover

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#597]
there should be an option to skip the popover and always open the sidebar for editing.

Default setting should be to open the popover first.

**Comment by tcitworld** [comment]
If there's multiple configuration items like this one, maybe we can use `settings#getConfig` and `settings#setConfig` (with key and value parameters) instead of a route for each configuration item we have.

**Comment by tcitworld** [comment]
Made it at https://github.com/owncloud/calendar/pull/652
