### ISSUE TITLE
Add to calendar instead of replacing, when importing

### ISSUE THREAD

**Issue by mdavis-xyz** [owncloud/calendar#598]
### Steps to reproduce

Click Settings > Import Calendar
### Expected behaviour

Back in the older version where you had to import calendars from the file browser, when selecting which calendar to import the ics file to, you could choose to either _delete_ all the events in the calendar and start fresh, or _add_ to all the events in the calendar. I want both options.
### Actual behaviour

There is no choice.
There is not even any text informing the user that if they import an ics into an existing calendar, everything currently in that calendar will be deleted.

![screenshot from 2016-06-29 12 38 01](https://cloud.githubusercontent.com/assets/7035647/16438943/09a9a44a-3df7-11e6-9713-4f582896bfd5.png)
### Server configuration

**Operating system**: Debian 8.5 Jessie

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** PHP 5.6.20-0+deb8u1

**ownCloud version:** 9.0

**Calendar version:** 1.2.2

**Updated from an older ownCloud or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):**  What does that mean?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

For the above, I see nothing. My browser shows a blank page. Not an error page. Just white.
My OC is at example.com/owncloud. I tried 
- http://example.com/index.php/settings/integrity/failed
- http://example.com/owncloud/index.php/settings/integrity/failed 
- http://example.com/owncloud/settings/integrity/failed 

The debugger console in my browser says the following when I try to visit that link: 

> Load denied by X-Frame-Options: https://www.mdavis.xyz/owncloud/index.php/settings/integrity/failed does not permit cross-origin framing.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - ownnote: 1.08
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocgpligctmz2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.1.1.200",
            "www.mdavis.xyz",
            "mdavis.xyz"
        ],
        "datadirectory": "\/media\/Maxtor\/owncloud",
        "overwrite.cli.url": "http:\/\/10.1.1.200\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "beaglebone",
        "mail_smtpmode": "php",
        "mail_domain": "mdavis.xyz",
        "forcessl": true,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "singleuser": false,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

```

**Are you using external storage, if yes which one:** local USB hard drive

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** I don't know what this means, so I guess that's a no
### Client configuration

**Browser:** Firefox 47.0

**Operating system:** Linux Mint 17.3

**CalDAV-clients:** Thunderbird 38.8.0 with Lightning 4.0.5.2, CalDav Sync Adapter (Android)
#### ownCloud log (data/owncloud.log)

```
{"reqId":"tNyWXOgPjLh9TcY4h31E","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:01:44+00:00"}
{"reqId":"tNyWXOgPjLh9TcY4h31E","remoteAddr":"10.1.1.2","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2016-02-07T10:01:46+00:00"}
{"reqId":"bGtnGf30MR0XctpWoy0c","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:04:02+00:00"}
{"reqId":"PgUCF3KMcARqC+gyrFi5","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:06:21+00:00"}
{"reqId":"UXTOFkw7kQlJfxGObX0O","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:07:04+00:00"}

```

**Comment by georgehrke** [comment]
Nothing is deleted when you import an ics into a calendar.

Dialog thing is a dup of https://github.com/owncloud/calendar/issues/326
