### ISSUE TITLE
Share calendars with visibility type option

### ISSUE THREAD

**Issue by noromamai** [owncloud/calendar#600]
feature request

Add an option when sharing a calendar (and or when creating events) to share the calendar (or event) as a busy indicator only. So some people/groups who the calendar is shared with will only see that user is unavailable when they should not have to see any details of the event.

**Comment by georgehrke** [comment]
With ownCloud 9.1 you will be able to show certain events busy only or hide them. Is that what you mean?

**Comment by noromamai** [comment]
wow. very quick. yes, that's exactly what i mean. the feature was 
present in the calendar app of oc8., but only for events. it could be 
nice to be able to share a whole calendar with option of showing busy 
only. then we would not have to set it for each event (especially if it 
will be the same as in oc8 where you had to create the event first 
before you could set visibility). For sharing calendars of course, you 
would only need 1 option to show busy or not. If you want to hide, then 
don't share at all. the show/busy/hide option when creating events would 
be an override of the default behaviour selected when sharing the calendar.

**Comment by georgehrke** [comment]
As said earlier the option for single events will be brought back with ownCloud 9.1
The option for sharing calendars won't be implemented in the way you suggested it, because there is an better way.
The server already provides free busy calendars for all users. We just need to add this to the attendee gui in the events editor.

**Comment by noromamai** [comment]
ok, thanks for the info. i have updated to 9.1 beta 2 and can see the 
busy/hide option now.

thanks

**Comment by jancborchardt** [comment]
@georgehrke is this back btw? cc @oparoz for info

**Comment by georgehrke** [comment]
For events: yes

**Comment by HalisCz** [comment]
> The server already provides free busy calendars for all users. We just need to add this to the attendee gui in the events editor.

Is there any estimation when this will be ready?
