### ISSUE TITLE
e-mail notification of meeting invitation

### ISSUE THREAD

**Issue by brianjmurrell** [owncloud/calendar#603]
### Steps to reproduce
1. Schedule a meeting with somebody who is not a user on the OC instance being used to create the meeting
### Expected behaviour

Non-local (to the local OC instance) meeting invitees should get an invitation in their e-mail with an ICS attachment that allows them to add the meeting to their own calendar.
### Actual behaviour

Non-local users have no idea that you have invited them to the meeting.  They miss the meeting and get written up by their boss.
### Server configuration

**Operating system:** Linux (but it's orthogonal)

**Web server:** Apache (but it's orthogonal)

**Database:** MySQL (but it's orthogonal)

**PHP version:** 5.4.16 (but it's orthogonal)

**ownCloud version:** 9.0.2

**Calendar version:** 1.2.2

**Updated from an older ownCloud or fresh install:** updated from 8.2.x

**Signing status (ownCloud 9.0 and above):**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4 
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - user_ldap: 0.8.0
Disabled:
  - encryption   
  - external
  - files_external
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "log_type": "owncloud",
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "updatechecker": false,
        "check_for_working_htaccess": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/lib\/owncloud",
        "apps_paths": [
            {
                "path": "\/usr\/share\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },   
            {
                "path": "\/var\/lib\/owncloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.example.com",
            "www.example.com"
        ],
        "overwrite.cli.url": "http:\/\/owncloud.example.com\/owncloud",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbhost": "linux.example.com",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "version": "9.0.2.2",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": false,
        "loglevel": 1,
        "log_authfailip": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "example.com",
        "mail_smtphost": "smtp.example.com",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:**
I don't think so (but it's orthogonal)

**Are you using encryption:**
I don't think so (but it's orthogonal)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No (but it's orthogonal)
### Client configuration

**Browser:**
Chrome (but it's orthogonal)

**Operating system:**
Linux (but it's orthogonal)

**CalDAV-clients:**
Evolution, Android  (but it's orthogonal)
### Logs

Logs can be supplied if necessary but this feels like a complete feature gap, not a bug or configuration issue.  I hope I can be proven wrong about that.

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by brianjmurrell** [comment]
https://github.com/owncloud/core/issues/23600 for anyone who comes here looking.
