### ISSUE TITLE
Calendar Export Returns Blank Page

### ISSUE THREAD

**Issue by Ben-Atherton** [owncloud/calendar#611]
### Steps to reproduce
1. Click on the export calendar button
### Expected behaviour

The calendar should export to an ICS file
### Actual behaviour

A 500 error is returned
### Server configuration

**Operating system**: Ubuntu 14.04
**Web server:** NGINX 1.11.1
**Database:** SQLite 3.8.2
**PHP version:** 5.6.23
**ownCloud version:** 9.0.2
**Calendar version:** 1.2.2
**Updated from an older ownCloud or fresh install:** Updated from older version
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**
Activity 2.2.1
Collaborative tags 0.2
Comments 0.2
Deleted files 0.8.0
Federation 0.0.4
First Run Wizard 1.1
Gallery 14.5.0
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8.1
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8
Calendar 1.2.2
Tasks 0.9.1

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc0ehvhhlr4f',
  'passwordsalt' => 'XXXXX',
  'secret' => 'XXXXX',
  'trusted_domains' => 
  array (
    0 => 'mydomain.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://mydomain.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXX',
  'dbpassword' => 'XXXXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** No
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Chrome 51 and Firefox 47
**Operating system:** Windows 7, Windows 10 and OSX El Capitan
**CalDAV-clients:**
#### Web server error log

```
2016/07/11 09:07:13 [error] 8955#8955: *2303 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function Sabre\VObject\mb_strcut() in /var/www/owncloud/3rdparty/sabre/vobject/lib/Property.php on line 247" while reading response header from upstream, client: 194.247.240.50, server: localhost, request: "GET /owncloud/remote.php/dav/calendars/Ben/personal?export HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php5.6-fpm.sock:", host: "mydomain.com"
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"wjr5eicXKcbL17zt563k","remoteAddr":"XXX.XXX.XXX.XX","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-07-11T08:19:09+00:00","method":"POST","url":"\/owncloud\/index.php\/heartbeat","user":"Ben"}
```
#### Browser log

```
Insert your browser log here, this could for example include:

No errors
```

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues

**Comment by georgehrke** [comment]
please check if you have the mbstring php extension installed before reporting this in core
