### ISSUE TITLE
Wrong or missleading description of repeated Dates:

### ISSUE THREAD

**Issue by zanglerecke** [owncloud/calendar#612]
### Steps to reproduce
1. try to add repeated events:
### Expected behaviour

I would like to set an repeated event, an have to fill in
for evry day:
(German:Wiederhole immer ... ) i think it is "repeat evry ... " 
what sould i put in??? Friday? second? = 2.... 
please help the user.... 

as well as the reported issue with UNTIL: DATE would be nice so i dont have to calculate how many dates there. [(https://github.com/owncloud/calendar/issues/484)]

**ownCloud version:9.0.3

**Calendar version:1.2.2

**Updated from an older ownCloud**

**Comment by georgehrke** [comment]
every day is 1
every second day is 2 
...

**Comment by zanglerecke** [comment]
i know that, but it would be nice, if it is prefilled or selectable.
and: those type of sentence wouldn’t work in german translation...
or: evry monday?
and: in what sould i fill in for evry (mo-fr) but not sa/sun? (in android app it is selectable... )

that is more a design-issue, than an bug...

**Comment by georgehrke** [comment]
> and: in what sould i fill in for evry (mo-fr) but not sa/sun? (in android app it is selectable... )

That's simply not possible at the moment.
A more advanced repeating events editor is in work though

**Comment by zanglerecke** [comment]
ok- so it isnt realy ..."closed" ;)
