### ISSUE TITLE
Changing Start-Time of recurring events with exlusions corrupt exclusions

### ISSUE THREAD

**Issue by LiamHD** [owncloud/calendar#620]
### Steps to reproduce
1. Create a recurring event with start and end time.
2. Delete one instance of that event series (e.g. via CalDAV-Client - as the WebUI does not allow this)
3. Change start-time
### Expected behaviour

All instances should change their start-time and excluded / deleted instances should stay excluded / deleted
### Actual behaviour

The excluded / deleted instances re-occur. What really happens is that the 
EXDATE entries don't change their start-time accordingly but new EXDATE entries are created.
See my example:

EXDATE;TZID=Europe/Berlin:20160822T190000
EXDATE;TZID=Europe/Berlin:20160822T193000
EXDATE;TZID=Europe/Berlin:20160829T190000
EXDATE;TZID=Europe/Berlin:20160829T193000

Instead of 

EXDATE;TZID=Europe/Berlin:20160822T193000
EXDATE;TZID=Europe/Berlin:20160829T193000
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
NextCloud 9.0.50
**Calendar version:** (see ownCloud apps page)
1.2.2
**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
fixed in #920
