### ISSUE TITLE
Email invitation for events should come from the user's email address, not server's

### ISSUE THREAD

**Issue by fracture-point** [owncloud/calendar#621]
### Steps to reproduce

Using OC 9.0.3 + Calendar 1.2.2, invite someone to calendar event.  
The outbound email "From" address shows as the server from, configured in 
Admin-->Email Server-->From Address.

The email should come from the user's configured email address, not the server.  This is especially confusing when the OC instance is host for a number of unrelated domains.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

Operating system:
Ubuntu 14.04
Web server:
Apache 2.4.7
Database:
MariaDB 10.0.26
PHP version:
php 5.5.9
ownCloud version: (see ownCloud admin page)
9.0.3
Contacts version: (see ownCloud apps page)
1.3.1.0 (calendar = 1.2.2)
Updated from an older ownCloud or fresh install:
Updated from 8.2.2
Signing status (ownCloud 9.0 and above):

No errors have been found.

List of activated apps:
Enabled:

activity: 2.2.1
calendar: 1.2.2
comments: 0.2
contacts: 1.3.1.0
dav: 0.1.6
federatedfilesharing: 0.1.0
federation: 0.0.4
files: 1.4.4
files_pdfviewer: 0.8.1
files_sharing: 0.9.1
files_texteditor: 2.1
files_trashbin: 0.8.0
files_versions: 1.2.0
files_videoplayer: 0.9.8
gallery: 14.5.0
notifications: 0.2.3
provisioning_api: 0.4.1
systemtags: 0.2
tasks: 0.8.1
updatenotification: 0.1.0 Disabled:
bookmarks
encryption
external
files_antivirus
files_external
firstrunwizard
news
notes
templateeditor
user_external
user_ldap

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Chrome / Safari
**Operating system:**
OS X El Cap
**CalDAV-clients:**
#### Web server error log

N/A
#### ownCloud log (data/owncloud.log)

N/A
#### Browser log

N/A

**Comment by georgehrke** [comment]
Beginning with ownCloud 9 the CalDAV server became part of ownCloud's core and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in ownCloud’s core repo: https://github.com/owncloud/core/issues
