### ISSUE TITLE
uiCalendarConfig.calendars.calendar is undefined

### ISSUE THREAD

**Issue by arivasvera** [owncloud/calendar#625]
### Steps to reproduce
1. install calendar on owncloud 9.0.1
2. go to http://myowncloud.com/apps/calendar
3. get error on app.js#214

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

**Comment by georgehrke** [comment]
closing due to missing feedback
