### ISSUE TITLE
Do not display events in Firefox in Windows.

### ISSUE THREAD

**Issue by z707** [owncloud/calendar#630]
### Steps to reproduce
1. Open Calendar in Firefox (last, ESR versions) and do not see events.
2. Open Calendar in other browser and find events.
3. Open Calendar in linux in Firefox and find events.

### Server configuration
**Operating system**:
Debian 7
**Web server:**
nginx-1.6.2
**Database:**
mysql-5.5
**PHP version:**
5.4.35

**ownCloud version:** (see ownCloud admin page)
7.0.3 (7.0.2)

**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
only core
**The content of config/config.php:**
```php
{
    ...
    'datadirectory' => '/var/www/owncloud/data',
    'dbtype' => 'mysql',                        
    'version' => '7.0.3.4',                     
    'dbname' => 'owncloud',                     
    'dbhost' => 'localhost',                    
    'dbtableprefix' => 'oc_',                   
    'dbuser' => 'owncloud',                     
    'dbpassword' => 'pass',           
    'installed' => true,                        
    'forcessl' => true,                         
    'loglevel' => '0',                          
    'maintenance' => false,                     
    'theme' => '',
}                              
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows (7, 8.1) 64b
#### Web server error log
```
no record
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"54798079866c8","app":"core","message":"OC\\Tags::loadTags, tags: Array\n(\n    [16] => Birthday\n    [17] => Business\n    [18] => Call\n    [19] => Clients\n    [20] => Deliverer\n    [21] => Holidays\n    [22] => Ideas\n    [23] => Journey\n    [24] => Jubilee\n    [25] => Meeting\n    [26] => Other\n    [27] => Personal\n    [28] => Projects\n    [29] => Questions\n    [30] => Work\n)\n","level":0,"time":"2014-11-29T08:14:49+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/js\/l10n.php"}
{"reqId":"54798079866c8","app":"core","message":"OC\\Tags::loadTags, tags: Array\n(\n    [16] => Birthday\n    [17] => Business\n    [18] => Call\n    [19] => Clients\n    [20] => Deliverer\n    [21] => Holidays\n    [22] => Ideas\n    [23] => Journey\n    [24] => Jubilee\n    [25] => Meeting\n    [26] => Other\n    [27] => Personal\n    [28] => Projects\n    [29] => Questions\n    [30] => Work\n)\n","level":0,"time":"2014-11-29T08:14:49+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/js\/l10n.php"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1
https://myserver/core/js/jquery-1.10.0.min.js?v=cbc57cda2e2cc589a81013d0c1193537 is being assigned a //# sourceMappingURL, but already has one Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6
Content Security Policy: The page's settings blocked the loading of a resource: An attempt to execute inline scripts has been blocked calendar window.controllers is deprecated. Do not use it for UA detection. ace.js:1716
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.0.min.js:5
```

**Comment by hallvors** [comment]
Maybe the "Content Security Policy: The page's settings blocked the loading of a resource" error causes this? Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1122445 or some related issue?

**Comment by georgehrke** [comment]
I can still not reproduce this. It works fine for me. Please post a full list of enabled apps.

**Comment by georgehrke** [comment]
> Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1122445 or some related issue?

That issue might actually be related, but if it's a bug in firefox I don't see much we can do.

**Comment by hallvors** [comment]
I could not reproduce either (trying to look into it because it was reported in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1108308 ). I tried to review the paths loading, but saw none that had capital characters that might trigger the CSP bug I was thinking of. (Might be some other CSP bugs though.. That error doesn't seem to appear in the console when it works for me.)

**Comment by z707** [comment]
With last versions owncloud (7.0.4) and firefox (35.0.1) all work - events are displayed. I have not changed anything - just update.
