### ISSUE TITLE
Show Description field in quick-add event creation

### ISSUE THREAD

**Issue by spoorun** [owncloud/calendar#632]
Behaviour from most users is to regularly use the Description field when quickly entering event details.
(For example notes about what to wear, who's coming, or cutting and pasting details from an email address for later consideration).
At present, the Description field does not show and the event has to be opened in full to enter the details. This significantly increase the time and effort involved in creating a quick event.

**Comment by georgehrke** [comment]
see https://github.com/owncloud/calendar/pull/579
