### ISSUE TITLE
Add additional repeating options

### ISSUE THREAD

**Issue by spoorun** [owncloud/calendar#634]
The following are very common options for repeating events:

Fortnight
4 weeks
Quarter

To preserve the simplicity, they could be placed below the existing options.
So a User would scroll down to see them, if required. If not required, they would not have any impact on the visual or practical simplicity of the App. So we would only gain by adding them.

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar/issues/223
