### ISSUE TITLE
Calendar does not load after upgrade to 1.3

### ISSUE THREAD

**Issue by MariusBluem** [owncloud/calendar#637]
### Actual behavior

The Calendar does not load after the update to 1.3. It shows only some basic UI elements. Neither the calendars nor any other components are loaded.
![issue_cal_edit](https://cloud.githubusercontent.com/assets/19711361/17084549/def6d30c-51c0-11e6-8900-e3faa8c03430.png)
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache 
**Database:**
MySQL
**PHP version:**
7.0.8
**ownCloud version:** (see ownCloud admin page)
Nextcloud 😈 9.0.53
**Calendar version:** (see ownCloud apps page)
1.3
**Updated from an older ownCloud or fresh install:**
updated from 9.0.52 ; calendar updated from previous version too
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Default Nextcloud-components
Calendar (1.3.0)
Contacts (1.3.1.0)
Collabora Online (1.1.3)
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'cloud.***',
  ),
  'datadirectory' => '/var/www/vhosts/cloud.***/httpdocs/data',
  'overwrite.cli.url' => 'https://cloud.***',
  'dbtype' => 'mysql',
  'version' => '9.0.53.0',
  'dbname' => 'nextcloud_****',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud_****',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'appstore.experimental.enabled' => false,
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
);
```
### Client configuration

**Browser:**
Safari 
**Operating system:**
OS X El Capitan; iOS 9.3;
### Logs

Nothing special in the Nextcloud-Log. I could provide more details later ... currently on road 😁

**Comment by georgehrke** [comment]
Please provide js error logs, works just fine for me on your demo instance

**Comment by georgehrke** [comment]
GRMPF.
FUCKING SAFARI
It's really the new IE.

**Comment by georgehrke** [comment]
It's crying about the `const` keyword.
IT'S FUCKING 2016 APPLE

**Comment by MariusBluem** [comment]
The Requested JS Log output .. With Warnings and Errors: 😜 

`[Warning] Unexpected CSS token: : (fixes.css, line 108)
[Warning] Unexpected CSS token: : (style.css, line 91)
[Warning] Invalid CSS property declaration at: ; (styles.css, line 19)
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
    (anonyme Funktion) (app.js:393)
[Error] Error: [$injector:modulerr] Failed to instantiate module Calendar due to:
[$injector:nomod] Module 'Calendar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=Calendar
https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:68:32
https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:2075:32
ensure@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:1999:45
module@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:2073:20
https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:4608:35
forEach@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:321:24
loadModules@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:4592:12
createInjector@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:4514:30
doBootstrap@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:1751:34
bootstrap@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:1772:23
angularInit@https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:1657:14
https://cloud.lineone.io/apps/calendar/js/vendor/angular/angular.js?v=91d8f0478ca65f26d4901a3054b96260:31468:16
c@https://cloud.lineone.io/core/vendor/jquery/jquery.min.js?v=91d8f0478ca65f26d4901a3054b96260:4:26041
fireWith@https://cloud.lineone.io/core/vendor/jquery/jquery.min.js?v=91d8f0478ca65f26d4901a3054b96260:4:26841
ready@https://cloud.lineone.io/core/vendor/jquery/jquery.min.js?v=91d8f0478ca65f26d4901a3054b96260:4:3316
q@https://cloud.lineone.io/core/vendor/jquery/jquery.min.js?v=91d8f0478ca65f26d4901a3054b96260:4:722
http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=Calendar&p1=%5B%24injector%3Anomod%5D%20Module%20'Calendar'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.7%2F%24injector%2Fnomod%3Fp0%3DCalendar%0Ahttps%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A68%3A32%0Ahttps%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A2075%3A32%0Aensure%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A1999%3A45%0Amodule%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A2073%3A20%0Ahttps%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4608%3A35%0AforEach%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A321%3A24%0AloadModules%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4592%3A12%0AcreateInjector%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4514%3A30%0AdoBootstrap%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A1751%3A34%0Abootstrap%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A1772%3A23%0AangularInit%40https%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A1657%3A14%0Ahttps%3A%2F%2Fcloud.lineone.io%2Fapps%2Fcalendar%2Fjs%2Fvendor%2Fangular%2Fangular.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A31468%3A16%0Ac%40https%3A%2F%2Fcloud.lineone.io%2Fcore%2Fvendor%2Fjquery%2Fjquery.min.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4%3A26041%0AfireWith%40https%3A%2F%2Fcloud.lineone.io%2Fcore%2Fvendor%2Fjquery%2Fjquery.min.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4%3A26841%0Aready%40https%3A%2F%2Fcloud.lineone.io%2Fcore%2Fvendor%2Fjquery%2Fjquery.min.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4%3A3316%0Aq%40https%3A%2F%2Fcloud.lineone.io%2Fcore%2Fvendor%2Fjquery%2Fjquery.min.js%3Fv%3D91d8f0478ca65f26d4901a3054b96260%3A4%3A722
    (anonyme Funktion) (angular.js:4632)
    forEach (angular.js:321)
    loadModules (angular.js:4592)
    createInjector (angular.js:4514)
    doBootstrap (angular.js:1751)
    bootstrap (angular.js:1772)
    angularInit (angular.js:1657)
    (anonyme Funktion) (angular.js:31468)
    c (jquery.min.js:4:26042)
    fireWith (jquery.min.js:4:26842)
    ready (jquery.min.js:4:3317)
    q (jquery.min.js:4:723)`

**Comment by georgehrke** [comment]
Any chance you can use a different browser?
I'm close to dropping support for this fucking piece of crap

**Comment by MariusBluem** [comment]
Supporting Safari is a must! ...Not because of my MacBook, but I think i am not the only apple fanboy using Safari also on iPad and iPhone ...where it is also not working 😁

**Comment by georgehrke** [comment]
meh, okay.
But I will drop support for this shit in the first release after macOS sierra and iOS 10.

(Edit: Shit = Safari 9, Safari 10 has fine ES6 support)

**Comment by MariusBluem** [comment]
Mhmm.. Why are you waiting until Sierra and iOS 10? Do you hope it will be better then, or ...?

**Comment by georgehrke** [comment]
Cause Sierra and iOS 10 will come with Safari 10
https://kangax.github.io/compat-table/es6/

**Comment by MariusBluem** [comment]
Nice 👍 Totally agree with you. I think supporting only the latest Firefox, Chrome and Safari is current practice anyway. Safari 10 will be also out for El Capitan, so users with an older Mac will not stay in the rain ☔

**Comment by MariusBluem** [comment]
Any plan how to fix this 😁

**Comment by georgehrke** [comment]
> Any plan how to fix this 😁 

Yes, I'm on it.
Expect 1.3.1 within the next two hours

**Comment by MariusBluem** [comment]
You're great 💪

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/pull/638

**Comment by MariusBluem** [comment]
Fix is merged with d729852

**Comment by georgehrke** [comment]
1.3.1 is out and live on the App Store

**Comment by georgehrke** [comment]
@mar1u5 Don't forget to delete the demo account 😉

**Comment by MariusBluem** [comment]
Already done :stuck_out_tongue_winking_eye:
