### ISSUE TITLE
OC9.0.4 - calendar 1.3.1.0 - not all occurencies of repeated events are shown

### ISSUE THREAD

**Issue by j-ed** [owncloud/calendar#639]
## Expected behavior

All occurrences of repeating events should be shown when using the calendar app.
## Current behavior

Some of the occurrences of repeating events are not shown in the calendar app, although they are correctly shown in Thunderbird-Lightning, on an Android phone or on an iPhone.

In my specific case I was able to pin-down the effect to the following calendar entry, which is not shown on July 25th 2016:

```
BEGIN:VEVENT
CREATED:20151212T175930Z
LAST-MODIFIED:20160724T100002Z
DTSTAMP:20160724T100002Z
UID:2a967df4-347a-4ec7-861d-48b25116bd4c
SUMMARY:Papier (blau)
RRULE:FREQ=WEEKLY;UNTIL=20161212;INTERVAL=4;BYDAY=MO
X-MOZ-LASTACK:20160724T100002Z
DTSTART;VALUE=DATE:20160307
DTEND;VALUE=DATE:20160308
TRANSP:TRANSPARENT
LOCATION:NE
CLASS:PUBLIC
SEQUENCE:1
X-MOZ-GENERATION:7
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT12H
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
```

This might be related to the following issues:
https://github.com/owncloud/calendar/issues/542
https://github.com/owncloud/calendar/issues/480
#### Server Configuration

OS: Linux 3.2.81
Web server: Apache2 2.4.23
Database: MariaDB 5.5.46
PHP version: 5.6.21
ownCloud version: 9.0.4
Calendar app version: 1.3.1.0
#### Client Configuration

Browser: Thunderbird 45.2.0/Lightning 4.0.7
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
> RRULE:FREQ=WEEKLY;UNTIL=20161212;INTERVAL=4;BYDAY=MO

BYDAY rule was implemented in #918
