### ISSUE TITLE
Deleting calendar doesn't refresh calendarview to hide events

### ISSUE THREAD

**Issue by tcitworld** [owncloud/calendar#645]
### Steps to reproduce
1. Add events to a calendar
2. Delete the calendar while events are on that view
### Expected behaviour

Events from that calendar should be gone
### Actual behaviour

Events stayed on the calendar view, until I refreshed the page

[...]
#### ownCloud log (data/owncloud.log)

Nothing relevant
#### Browser log

No errors.

**Comment by tcitworld** [comment]
@georgehrke Do you know if that ever did work ?

**Comment by tcitworld** [comment]
For some reason `$scope.$watchCollection` inside CalController doesn't get triggered.

**Comment by georgehrke** [comment]
> @georgehrke Do you know if that ever did work ?

Yes, it did
