### ISSUE TITLE
Could not find resource calendar/js/public/app.js

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/calendar#654]
Installed oC stable9, but i managed to install the old calendar app, but later replaced it with the current. Now i got issues. 
From browser dev console:
Error: [$injector:modulerr] Failed to instantiate module Calendar due to:
[$injector:nomod] Module 'Calendar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=Calendar

oC log shows:
"app":"calendar","message":"Could not find resource file \"\/apps3\/calendar\/js\/public\/app.js\"

Might be caching issue, but it's a shared hosting so i can't easily clear the cache.

Any hints @georgehrke ?

Thanks.

**Comment by georgehrke** [comment]
don't use git
it's not meant for production
