### ISSUE TITLE
Hiding a calendar needs a refresh after creation to work

### ISSUE THREAD

**Issue by tcitworld** [owncloud/calendar#656]
### Steps to reproduce
1. Create a calendar or use an existing calendar
2. Create an event for this calendar
3. Toggle (hide) the calendar visibility
### Expected behaviour

Events should be hidden
### Actual behaviour

Events are not hidden.

When the calendar is shown again, the same event is added again.
![oc_calendar_duplication_bug](https://cloud.githubusercontent.com/assets/2197836/17294226/c2b9856e-57f5-11e6-8d64-435d2d4c3bbe.png)

This doesn't happen with a refresh after the event is created.

**Comment by georgehrke** [comment]
The problem is that we use fullCalendar's `renderEvent` to display the new / updated event.
https://github.com/owncloud/calendar/blob/master/js/app/controllers/calcontroller.js#L68

The event is not associated with the calendar and therefore not hidden, when the calendar is hidden.

**Comment by georgehrke** [comment]
In the long run I would like to introduce an object store to cache objects and not make fullcalendar send the caldav requests

**Comment by georgehrke** [comment]
With fullcalendar 2.8 we can actually refresh certain event sources instead of all.
This is probably the way to go for now.
http://fullcalendar.io/docs/event_data/refetchEventSources/
