### ISSUE TITLE
Caldav sync breaking in 7.0.4.2

### ISSUE THREAD

**Issue by omnitec** [owncloud/calendar#657]
Encounting a problem with a caldav sync operation:

[Sun Dec 21 15:58:38.155572 2014] [php5:error] [pid 3110] [client 206.197.251.252:52396] PHP Fatal error: require_once(): Failed opening required '/u/owncloud/apps/calendar/sabre/main.php' (include_path='/u/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/u/owncloud/lib/private:/u/owncloud/config:/u/owncloud/3rdparty:/u/owncloud/apps:/u/owncloud/lib:.:/usr/share/php5:/usr/share/php5/PEAR:/u/owncloud:/u/owncloud/apps/search_lucene/3rdparty') in /u/owncloud/remote.php on line 52

Originally applied the update to try and fix the problem, .. so I cannot be certain the problem started in 7.0.4. Just reinstalled, copied over config.php & moved the data directory, same issue. Web UI works just fine, all apps, .. no caldav.

Seems like something is broken in the config? Pointers for troubleshooting?

TIA!!

Lee

**Comment by RealRancor** [comment]
Hi,

which URL are you using for syncing your calendars?

**Comment by j-ed** [comment]
Am 1. Januar 2015 14:14:13 MEZ, schrieb RealRancor <notifications@github.com>:
>Hi,
>
>which URL are you using for syncing your calendars?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/657#issuecomment-68486357

Try this one:

https://<server-name>/owncloud/remote.php/caldav/calendars/<user-name>/<calendar-name>/
-- 
Mail: juergen.edner@telejeck.de
GPG key available

**Comment by delumerlino** [comment]
Have the same problem with fresh new install of oc_8.
cardav works fine, but not caldav
Tried https://<server-name>/owncloud/remote.php/caldav/calendars/<user-name>/<calendar-name>/ and https://<server-name>/owncloud/remote.php/caldav/calendars/<user-name>/defaultcalendar/ but nothing...

**Comment by georgehrke** [comment]
> Tried https:///owncloud/remote.php/caldav/calendars/// and https:///owncloud/remote.php/caldav/calendars//defaultcalendar/ 

How those links are supposed to work? There is a username missing

https:///owncloud/remote.php/caldav/calendars/<username>/
https:///owncloud/remote.php/caldav/calendars/<username>/defaultcalendar/

**Comment by georgehrke** [comment]
and client do you use?

**Comment by delumerlino** [comment]
Sorry but not copied well...
I was meaning https://server-nam>/owncloud/remote.php/caldav/calendars/user-name/calendar-name/ and https://server-nam>/owncloud/remote.php/caldav/calendars/user-name/personal/

I use free caldav sync adapter (https://play.google.com/store/apps/details?id=org.gege.caldavsyncadapter&hl=it) for Android. It was working till 7.0.4.2....

**Comment by georgehrke** [comment]
do you use some user-backend?

**Comment by delumerlino** [comment]
nope...

**Comment by georgehrke** [comment]
do you have the same fatal error, as the original reporter posted?

What way did you install ownCloud?

**Comment by delumerlino** [comment]
I have no errors on oc..
It was installed from repository (apt-get install owncloud)

**Comment by georgehrke** [comment]
what does a typical username look like?

Does caldav sync adapter provide any useful error message?

**Comment by georgehrke** [comment]
please enable the debug mode in ownCloud (see admin doc how to). There simply must be an error message.

**Comment by delumerlino** [comment]
My string is:
https://owncloud.somwhere/owncloud/remote.php/caldav/calendars/andrea/personal/

Client gives me only "wrong url"

**Comment by georgehrke** [comment]
what web server do you use? please post the vhost config.

**Comment by georgehrke** [comment]
seems related to https://github.com/gggard/AndroidCaldavSyncAdapater/issues/82

**Comment by delumerlino** [comment]
I use turion dual core, 4gb ram, ubuntu 14.04, owncloud 8.0.
system is in debug mode but nothing logged..

**Comment by georgehrke** [comment]
with web-server I meant is it apache or nginx or smth like that? please post the config of the vhost then

**Comment by delumerlino** [comment]
it runs on apache2.


<VirtualHost _default_:port>      
      ServerName Owncloud:port
      ServerAdmin webmaster@localhost
      DocumentRoot /var/www

        <Directory /var/www/owncloud>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                Allow from all
                # add any possibly required additional directives here
                # e.g. the Satisfy directive (see below for details):
                Satisfy Any
        </Directory>

        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>

        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>
#   SSL Engine Switch:
		#   Enable/Disable SSL for this virtual host.
		SSLEngine on

		#   A self-signed (snakeoil) certificate can be created by installing
		#   the ssl-cert package. See
		#   /usr/share/doc/apache2/README.Debian.gz for more info.
		#   If both key and certificate are stored in the same file, only the
		#   SSLCertificateFile directive is needed.
                SSLCertificateFile /etc/apache2/ssl/owncloud.pem
                SSLCertificateKeyFile /etc/apache2/ssl/owncloud.key


</VirtualHost>

**Comment by delumerlino** [comment]
solved....don't ask me how but now it works....changed....nothing...
Thank you!

**Comment by georgehrke** [comment]
closing as @delumerlino 's problem is solved and the original reporter never responded to any question.
