### ISSUE TITLE
Events in shared calendars are not sync on IPhone

### ISSUE THREAD

**Issue by Marco4223** [owncloud/calendar#660]
### Steps to reproduce
1. Create 3 accounts  (i.e. Peter Paul and Marry)
2. Peter shared his calendar with Paul and Marry.
3. Login to Owncloud website as Paul. Create an event (called Test1) in there private calendar and one in the shared calendar of Peter (called Test2).
4. Sync with IPhone

Result:
In the calendar of the webside ->
 Test1 visible
 Test2 visible

On IPhone ->
 Test1 visible
 Test2 NOT visible

### Expected behaviour
Shared calendar should be sync to IPhone

### Actual behaviour
Only private calendar are sync to IPhone

### Server configuration
Debian Weezly

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4.35

**ownCloud version:** (see ownCloud admin page)
7.0.4

### Client configuration
**Operating system:**
IOS 8.1.2

**Sync-Uri:
 https://[my.web.uri]/owncloud/remote.php/caldav/principals/Paul/

**Comment by igramul** [comment]
I have a similar issue with shared calendars.

OS: Ubuntu Server 14.04 LTS
Webserver: Apache/2.4.7 (Ubuntu) 
Database: MariaDB
PHP: Version 5.5.9-1ubuntu4.5
ownCloud version: 7.0.4 (stable)
iOS Version: 6.1.6

**Comment by georgehrke** [comment]
can't reproduce, tried multiple times

**Comment by foudfou** [comment]
I had to install the Contacts for OC8 app.

**Comment by georgehrke** [comment]
> I had to install the Contacts for OC8 app.

That's a different issue

> Original issue

can't reproduce, closing
