### ISSUE TITLE
Timezone "None" doesn't work

### ISSUE THREAD

**Issue by wrexroad** [owncloud/calendar#664]
### Steps to reproduce
1. Create a new event by clicking a date on the calendar.
2. Click the "More" option.
3. Select global timezone "None".
### Expected behaviour

Who knows? "None" is pretty ambiguous for a timezone.
### Actual behaviour

TimezoneService tries to get the listing for the "FLOATING" timezone:

```
GET [OWNCLOUDSERVER]/apps/calendar/v1/timezones/FLOATING.ics 404 (Not Found)
```

The 404 response is the processed as a timezone and subsequent selections of "None" result in a broken promise. Tears and heartbreak are sure to follow:

```
Uncaught (in promise)
  Object {data: "<!DOCTYPE html>↵<!--[if lte IE 8]><html class="ng-…ll your data            </p>
  </footer>↵  </body>↵</html>↵", status: 404, config: Object, statusText: "Not Found"}

```
### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
Nextcloud 9.0.53 (stable)
**Calendar version:** (see ownCloud apps page)
1.3.1 (Also tested on GitHub master branch commit 8addb4).
**Updated from an older ownCloud or fresh install:**
Freshly built from GitHub repo.
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```
### Client configuration

**Browser:**
Chrome
**Operating system:**
Fedora 24
#### Browser log

See Above

**Comment by georgehrke** [comment]
We should probably rename it to floating though
