### ISSUE TITLE
Calendars not synced as expected with Windows Phone 8.1

### ISSUE THREAD

**Issue by rockman73** [owncloud/calendar#664]
Using mailinabox project which includes owncloud 7.0.4 (stable) and Z-Push. 

I've added my owncloud account to Windows Phone 8.1 using Exchange ActiveSync settings. Mail and Contacts appear to sync. Calendars do not sync as expected. What I see synced on my phone is just one single Birthday Calendar that I don't see in owncloud. I expect to see my primary calendar with events synced. I also have one shared calendar that does not sync either.

**Comment by georgehrke** [comment]
first of all: please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)
please be precise how you setup the calendar sync on your phone.

second, as I don't have a windows phone device: please setup an ownCloud __without mailinabox__, just ownCloud, and try to reproduce the error. If you can't reproduce it, report a bug at mailinabox.

**Comment by georgehrke** [comment]
> Exchange ActiveSync settings

That has nothing to do with caldav, right? then report a bug at mailinabox right away please.
