### ISSUE TITLE
*.ics contains invalid data: Event did not have a UID!

### ISSUE THREAD

**Issue by beyerservice** [owncloud/calendar#666]
in my owncloud.log I get this message:
```
{"app":"calendar","message":"Event (owncloud-77a76a56b805ca7eb70388a01c22ef35.ics) contains invalid data: Event did not have a UID!","level":2,"time":"2015-01-09T13:31:06+00:00"}
```
after a look in to mysql-db I found this in table oc_clndr_objects / calenderdata
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.6.4
UID:6a9951c187
BEGIN:VEVENT
...
```

So why is it not a valid UID?
what can I do to repair this?

Problem is: syncing with Sony Tablet does NOT work. My sync-app (CalDAV-sync-beta) is crashing, but only on this Sony crap... working well with asus tablet and AOSP-ROM...

I get this messages to while displaying with Calender-App from owncloud.

while syning from my other phone I get this:
```
{"app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-09T14:20:19+00:00"}
```
It would be nice to get some information WHAT object this is...

what I tried to solve this issue:
1. exporting calender
2. importing in another one
3. importing in outlook
4. exporting from outlook and reimporting in a new calender (all with this Calender-App)

no success...

**Comment by georgehrke** [comment]
the event does not contain a UID, 

> Problem is: syncing with Sony Tablet does NOT work. My sync-app (CalDAV-sync-beta) is crashing, but only on this Sony crap... working well with asus tablet and AOSP-ROM...

please contact the caldav sync beta developers and ask them to add proper support for caldav errors

**Comment by beyerservice** [comment]
I am talking about opening owncloud Calender app!
so this has nothing to do wiith my sync app on my tablet, because i get first errors with your web app!
so please help me and not close this issue.

**Comment by beyerservice** [comment]
comment 2: I will remove that tablet thing from my issue. BEcause thats not the point.

**Comment by georgehrke** [comment]
Well, in the description you said that the caldav app is crashing. It's the expected behaviour, that the calendar logs an error message, when one event is broken

**Comment by georgehrke** [comment]
> Invalid VObject. Document ended prematurely.

There are some known issues with 4 byte unicode chars. Does this particular object contain such chars. If yes, please try to remove them

**Comment by beyerservice** [comment]
yes, I am sorry about that, because that has nothing to do with owncloud.
My first error I get while using Calender Web-App from Owncloud 7.0.4.
and I did not post hole VEVENT, because there is an UID: there.
so why did it said, there is no UID?

**Comment by beyerservice** [comment]
this is the hole vevent:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.6.4
UID:6a9951c187
BEGIN:VEVENT
SUMMARY:*04 Seebeben ind. Ozean 100t Tote / *08 unangekündigter Sturm 
 Abflugschneise 5.15 - 5.30h Containerdach 6.00h Anruf Anne 
DTSTART:20141226T010000Z
DTEND;VALUE=DATE-TIME:20141226T020000Z
RRULE:FREQ=YEARLY;INTERVAL=1
CLASS:DEFAULT
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT10M
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by georgehrke** [comment]
there must be an UID inside BEGIN:VEVENT ... END:VEVENT, the UID inside your example is outside BEGIN:VEVENT ... END:UID

**Comment by georgehrke** [comment]
this calendar data is simply not valid

**Comment by beyerservice** [comment]
ok that helped me a lot.
just wondering who this mess ... :-)
So to make it valig I have to move this UID into BEGIN:VEVENT?

**Comment by georgehrke** [comment]
> So to make it valig I have to move this UID into BEGIN:VEVENT?

yes, that should help

**Comment by beyerservice** [comment]
worked. thank you!
