### ISSUE TITLE
Online calendar app does not load any calendar

### ISSUE THREAD

**Issue by giovi321** [owncloud/calendar#669]
After upgrading to oc9.1, the online calendar app does not load any calendar and I cannot create a new one (I see the gray loading circle spinning). However, through caldav i can add events to the existing calendars.

**Comment by nielsha** [comment]
I have the same issue. When trying to add an event, I get the message "Please create a calendar first."

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
and please provide the javascript browser log!

**Comment by nielsha** [comment]
I just tried to access the calendar using Chrome and I had no problem. Before I was using Internet Explorer 11. In Chrome it seems to Work like a charm :)

**Comment by georgehrke** [comment]
Internet explorer is not supported

**Comment by georgehrke** [comment]
closing under the assumption that @giovi321 was trying a non-supported browser as well.
Please speak up if that's not the case and you are using latest firefox, latest safari or latest chromium
