### ISSUE TITLE
General import improvements

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/calendar#67]
I shouldn't be manually closing the DialogModel when the last issue is closed.

**Comment by georgehrke** [comment]
- [ ] make sure you can't close import dialog with esc, because that would abort importing
- [ ] Also automatically close when errors happened?

**Comment by georgehrke** [comment]
Moving to Alpha 2 due to open questions.

**Comment by georgehrke** [comment]
- [ ] disable import button while another import dialog is currently open

**Comment by georgehrke** [comment]
- [ ] close import dialog automatically if all imports succeeded
