### ISSUE TITLE
OC 7: Can't delete one event from a repeating event list in the calender

### ISSUE THREAD

**Issue by Bellum45** [owncloud/calendar#670]
It isn't possible to delete one event from a list of repeating events

ownCloud 7.0.4
Firefox 35
Windows 7

**Comment by georgehrke** [comment]
dup

**Comment by georgehrke** [comment]
please search for existing bug reports before creating new ones

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/calendar/issues/67 as searching for "repeating" or "recurring" don't lead to this duplicate.
