### ISSUE TITLE
High CPU use on server when calendar added to Thunderbird mail client

### ISSUE THREAD

**Issue by papezg** [owncloud/calendar#672]
Steps to reproduce

1. Add iOS/MAC OS CalDAV link to TB calendars

Expected behaviour
Normal sync of events, low CPU usage

Actual behaviour
Events not synced, server CPU usage going beserk

Server configuration

Operating system: Ubuntu 14.04.01 LTE
Web server: nginx 1.4.6
Database: MySQL 5.5
PHP version: 5.5
ownCloud version: 7.0.4

Updated from an older ownCloud or fresh install: FRESH install

List of activated apps:
Calendar, contacts, bookmarks, files

The content of config/config.php:
<?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'xxxxx.xxxxx.eu',
  ),
  'datadirectory' => '/xxxx/xxxxx',
  'overwrite.cli.url' => 'https://xxxxx.xxxxx.eu',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'forcessl' => true,
);

Are you using external storage, if yes which one: local/smb/sftp/...
NO

Are you using encryption: yes/no
NO

Client configuration
Mac OS, Thunderbird 31.4+ Lightening client 3.3.2

Operating system:
Mac OS 10.10

Logs

xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:44 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:44 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:44 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:44 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:44 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:44 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:44 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:44 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:44 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:45 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:45 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:46 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:46 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - xxxxx [15/Jan/2015:19:12:47 +0100] "PROPFIND /remote.php/caldav/principals/xxxxx/ HTTP/1.1" 207 1069 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"
xxx.xxx.xxx.xxx - - [15/Jan/2015:19:12:47 +0100] "OPTIONS /remote.php/caldav/principals/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"

Web server error log
Empty

ownCloud log (data/owncloud.log)
Empty

**Comment by georgehrke** [comment]
please use ```http://ADDRESS/remote.php/caldav``` as described in our doc: http://doc.owncloud.org/server/7.0/user_manual/pim/calendar.html?highlight=caldav

If thunderbird dosses your server, that's a bug in thunderbird

**Comment by FreddieWitherden** [comment]
I experienced a similar problem with my installation.  However, I explicitly followed the documentation and used the URL recommended for Mozilla Lightning:

 `` https://ADDRESS/remote.php/caldav/calendars/USERNAME/CALENDARNAME``

looking at the server logs shows a similar case of ``OPTIONS`` and ``PROPFIND`` requests.  However, the Thunderbird logs show:

    Timestamp: 01/03/15 22:41:22
    Error: junk after document element
    Source File: moz-nullprincipal:{b69b6af5-bc06-4af5-b23b-ceeeaca876c3}
    Line: 2, Column: 1
    Source Code:
    <b>Fatal error</b>:  Class 'OCA\Contacts\App' not found in <b>/path/htdocs/apps/calendar/lib/sabre/backend.php</b> on line <b>63</b><br />

There can be no doubt that Thunderbird is in the wrong by DOS'ing the server.  However, returning an HTTP 2xx code for a fatal error is possibly a bug/uncaught corner case in the Calendar plugin.
