### ISSUE TITLE
Validate date/time range when creating event?

### ISSUE THREAD

**Issue by wrexroad** [owncloud/calendar#672]
I noticed that there is nothing stopping a user from creating an event that ends before it starts. When events are created they are run though a validator which could check for this. Another option would be to watch the of `dtstart.value` and `dtend.value` in `EditorController` and when they are changed, force them to be in order. Is this something worth implementing?

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/245
