### ISSUE TITLE
Calendar does not work

### ISSUE THREAD

**Issue by tapete** [owncloud/calendar#673]
Creating new events in the calendar does not work. Disabling the calendar app does not work. 

Owncloud version: 9.x
Ubuntu server
apache, mysql, php newest version.
Fresh install of owncloud

WTF???

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by tapete** [comment]
I have bugs over and over and it seems to be not realistic to report all these bugs using the template. Is there anyone who successfully installed owncloud without any bugs in the logfile and with a working calendar app?

**Comment by georgehrke** [comment]
I can not help you without the issue template. Your current bug report is lacking lots of important information

**Comment by raghunayyar** [comment]
I am closing this issue as of now, please elaborate on the exact issue you are making. I will re-open it. Thx.
