### ISSUE TITLE
OC8 alpha2: can't enable Calendar app

### ISSUE THREAD

**Issue by davleema** [owncloud/calendar#674]
### Steps to reproduce
1. log in as admin user
2. click the Apps+ icon in the left top menu 
3. In the left sidebar, click the Recommended aps
4. Browse the list for the Calendar app
5. When found, click the Enable button

### Expected behaviour
I expect the Calendar app to be installed.

### Actual behaviour
I get the following error message: App does not provide an info.xml file
Fwiw, this error is received upon any app I try to enable, so not limited to the Calendar app.

### Server configuration
**Operating system**:
Slackware Linux 14.1 x64

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 5.5.40

**PHP version:**
5.5.19

**ownCloud version:** (see ownCloud admin page)
8 alpha 2

**Updated from an older ownCloud or fresh install:**
updated from 8  alpha 1

**List of activated apps:**
only the default apps

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'octgvzn2tj6m',
  'trusted_domains' => 
  array (
    0 => 'aivpc80',
  ),
  'datadirectory' => '/home/oc8data/',
  'overwrite.cli.url' => 'http://aivpc80/owc8',
  'dbtype' => 'mysql',
  'version' => '8.0.0.2',
  'dbname' => 'oc8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc8admin',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox 35

**Operating system:**
Slackware Linux 14.1 x64

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0220b61331696a03f19a5fcf37656e6b","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: httpHelper at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#47","level":3,"time":"2015-01-14T11:03:21+00:00"}
{"reqId":"0220b61331696a03f19a5fcf37656e6b","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: config at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#49","level":3,"time":"2015-01-14T11:03:21+00:00"}
{"reqId":"0220b61331696a03f19a5fcf37656e6b","remoteAddr":"134.184.28.72","app":"PHP","message":"Call to a member function getValue() on a non-object at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#84","level":3,"time":"2015-01-14T11:03:21+00:00"}
{"reqId":"cf2fa1b298831f5714693d6d5dddb0d8","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-16T13:21:53+00:00"}
{"reqId":"cf2fa1b298831f5714693d6d5dddb0d8","remoteAddr":"134.184.28.72","app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/usr\/local\/apache2\/htdocs\/owncloud8\/apps\/updater\/update.php on line 27 and defined at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#46","level":3,"time":"2015-01-16T13:21:53+00:00"}
{"reqId":"cf2fa1b298831f5714693d6d5dddb0d8","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: httpHelper at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#47","level":3,"time":"2015-01-16T13:21:53+00:00"}
{"reqId":"cf2fa1b298831f5714693d6d5dddb0d8","remoteAddr":"134.184.28.72","app":"PHP","message":"Undefined variable: config at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#49","level":3,"time":"2015-01-16T13:21:53+00:00"}
{"reqId":"cf2fa1b298831f5714693d6d5dddb0d8","remoteAddr":"134.184.28.72","app":"PHP","message":"Call to a member function getValue() on a non-object at \/usr\/local\/apache2\/htdocs\/owncloud8\/lib\/private\/updater.php#84","level":3,"time":"2015-01-16T13:21:53+00:00"}
{"reqId":"bca25e3c31af5ed65f4abac9bdca3cd8","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-16T15:48:57+00:00"}
{"reqId":"6c190f9a148485010bb1dabeb19c26bc","remoteAddr":"134.184.28.72","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-01-16T15:52:47+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
from what source did you install ownCloud 8 alpha?
If it's a tar/zip: Is there a folder calendar inside the apps folder?

**Comment by georgehrke** [comment]
The error message you posted looks like ownCloud tries to download ownCloud from the App Store, but there in the App Store there is only an empty package.

**Comment by davleema** [comment]
Downloaded  from the link in the announcement forum. There is no calendar app in the apps folder.

On January 16, 2015 5:12:23 PM CET, Georg Ehrke <notifications@github.com> wrote:
>from what source did you install ownCloud 8 alpha?
>If it's a tar/zip: Is there a folder calendar inside the apps folder?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/674#issuecomment-70276796

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by georgehrke** [comment]
What announcement forum?

**Comment by georgehrke** [comment]
> There is no calendar app in the apps folder.

Then it's no bug in the calendar app :smile:

**Comment by davleema** [comment]
If so, then what is the problem?

On January 16, 2015 6:37:56 PM CET, Georg Ehrke <notifications@github.com> wrote:
>> There is no calendar app in the apps folder.
>
>Then it's no bug in the calendar app :smile: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/674#issuecomment-70290718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by georgehrke** [comment]
download the calendar app from github and put it into apps https://github.com/owncloud/calendar/archive/master.zip

**Comment by davleema** [comment]
The Owncloud user forums.

On January 16, 2015 6:37:35 PM CET, Georg Ehrke <notifications@github.com> wrote:
>What announcement forum?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/674#issuecomment-70290654

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davleema** [comment]
Ok, I will try that.

On January 16, 2015 6:40:41 PM CET, Georg Ehrke <notifications@github.com> wrote:
>download the calendar app from github and put it into apps
>https://github.com/owncloud/calendar/archive/master.zip
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/674#issuecomment-70291110

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JSoko** [comment]
Have a look here:
owncloud/core#13543
