### ISSUE TITLE
"CREATED", "DTSTAMP", and "LAST-MODIFIED" are not in UTC 

### ISSUE THREAD

**Issue by wrexroad** [owncloud/calendar#675]
According to https://tools.ietf.org/html/rfc5545#section-3.8.7.1 the CREATED property (as well as DTSTAMP and LAST-MODIFIED" must be specified in UTC. However, it appears they are assigned using the users local time with the timezone left floating.

**Comment by georgehrke** [comment]
let's merge this with https://github.com/owncloud/calendar/issues/657

**Comment by wrexroad** [comment]
Ah! I searched for duplicates by looking for "CREATED" and "DTSTAMP". Adding LAST-MODIFIED to the issue was an after thought and I forgot to search for it. Sorry!
