### ISSUE TITLE
Full editable calendars in user group even though calendars are marked as not shareable and not editable (only in Version 7.0.4)

### ISSUE THREAD

**Issue by JeTim** [owncloud/calendar#678]
Describtion: First I have generate 2 users A, B which join the user group xy. A and B have next to their default calender (in german: "Persönlich") a second calender, user A, calender A and user B, calender B. These both calenders are shared with the group xy whith the options "not shareable" and "not editable". Until here it works fine. If I log in as A or B I can see calendar of the other groub member but cannot edit it. But if I generate a third user C in the group xy the group permissions becomes crazy, if I log in now as A,B or C I can edit, delete, create appointments in calendars at least of one of the other group members!!
In a second installation of owncloud (Version 7.0.2) I performed the test with 5 users in one group and it worked fine. The users of the group can see the calendars of the other members but do not have full access.
For both owncloud installations I use the same admin settings. Could it be a bug in 7.0.4 ?
![2 users](https://cloud.githubusercontent.com/assets/10629443/5853363/47efce62-a223-11e4-9f38-906d14bce64d.JPG)
![3 users](https://cloud.githubusercontent.com/assets/10629443/5853364/47f18590-a223-11e4-9023-d9821a7fdc85.JPG)
![users](https://cloud.githubusercontent.com/assets/10629443/5853365/47f4a018-a223-11e4-977b-62e32dd0d8e7.JPG)

**Comment by georgehrke** [comment]
duplicate

**Comment by georgehrke** [comment]
please search for existing bugs before creating new ones. The original issue is still on __page 1__ when you open the issue tracker!
