### ISSUE TITLE
blank page on NextCloud 10 Beta

### ISSUE THREAD

**Issue by Tealk** [owncloud/calendar#679]
### Expected behaviour

See The Calendar
### Actual behaviour

See a blank page and some strange in the left bar
![kalender](https://cloud.githubusercontent.com/assets/12276250/17432270/ad0464bc-5afe-11e6-94af-122830e8a6dd.jpg)
### Server configuration

**Operating system**:
Debian GNU/Linux 8.5 (jessie)
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
NextCloud10Beta
**Calendar version:** (see ownCloud apps page)
1.3.1
**Updated from an older ownCloud or fresh install:**
Upgrade from Nextcloud 9.0.53
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**

Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- calendar: 1.3.1
- comments: 0.3.0
- contacts: 1.3.1.0
- dav: 0.2.5
- direct_menu: 0.8.1
- encryption: 1.3.0
- external: true
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- news: 8.8.0
- notifications: 0.3.0
- ownbackup: 0.3.8
- password_policy: 1.0.0
- provisioning_api: 0.5.0
- registration: 0.2.1
- systemtags: 0.3.0
- tasks: 0.9.2
- templateeditor: 0.1
- theming: 0.2.0
- updatenotification: 0.2.1
  Disabled:
- files_external
- gallery
- user_external
- user_ldap
- user_saml

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "anzah.cloud"
        ],
        "datadirectory": "\/home\/anzahcloud",
        "overwrite.cli.url": "https:\/\/anzah.cloud",
        "dbtype": "mysql",
        "version": "9.1.0.13",
        "dbname": "anzahcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "log_type": "owncloud",
        "logfile": "\/home\/anzahcloud\/nextcloud.log",
        "loglevel": 3,
        "syslog_tag": "ownCloud",
        "logdateformat": "d.m.y H:i:s",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": 104857600,
        "overwritehost": "anzah.cloud:443",
        "overwriteprotocol": "https",
        "versions_retention_obligation": "auto, 120",
        "trashbin_retention_obligation": "auto, 60",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "anzah.cloud",
        "maintenance": false,
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_filesize_image": 50,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "blacklisted_files": [
            ".htaccess"
        ],
        "minimum.supported.desktop.version": "2.1.0",
        "assetdirectory": "\/var\/www\/nextcloud",
        "activity_expire_days": 365,
        "htaccess.RewriteBase": "\/"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**
Vivaldi
**Operating system:**
Window 10
**CalDAV-clients:**
iPhone, Thunderbird
#### Web server error log

None
#### ownCloud log (data/owncloud.log)

None

**Comment by georgehrke** [comment]
Vivaldi is not supported
Please try Chrome or Firefox

**Comment by tcitworld** [comment]
And please check browser logs (Ctrl+Maj+K on firefox, Ctrl+Maj+J on Chrome).

**Comment by Tealk** [comment]
I use Vivaldi now a long Time and it run fine all the time. First the Upgrade to 10 has brake the calendar.
Firefox and Chrome show me exactly the same page like my screenshot

what exactly should I check in the browser log?

**Comment by georgehrke** [comment]
just paste the browser log here

**Comment by Tealk** [comment]
```
JQMIGRATE: Migrate is installed, version 1.4.0jquery-migrate.min.js:2:542
SyntaxError: expected expression, got '*'angular.js:310:1
TypeError: angular is undefined
angular-route.js:3:5
ReferenceError: angular is not defined
ui-bootstrap.min.js:7:4
ReferenceError: angular is not defined
ui-bootstrap-tpls.min.js:7:4
ReferenceError: angular is not defined
calendar.js:1:1
ReferenceError: angular is not defined
app.js:1:227

```

**Comment by georgehrke** [comment]
Where did you install the calendar from?

**Comment by Tealk** [comment]
from the apps tab in nextcloud

**Comment by georgehrke** [comment]
Why is the apps menu in the top in your screenshot?

**Comment by georgehrke** [comment]
I just setup 10 beta in a Docker container and it works just fine for me:
<img width="1299" alt="calendar - nextcloud chromium today at 12 44 27 pm" src="https://cloud.githubusercontent.com/assets/1250540/17434394/7ace5492-5b0a-11e6-9452-5f8d9fa3a159.png">

**Comment by Tealk** [comment]
its a app with name direct_menu

**Comment by georgehrke** [comment]
Apparently it conflicts with another app. Please try to disable the other apps one by one until it finally works and report a bug report at the app that breaks the calendar

**Comment by tcitworld** [comment]
Also, please try uninstalling the app and installing it back.

**Comment by Tealk** [comment]
i have disable all other apps but i have the same problem

if i disable the all and uninstall it i geht the message that i sould update calender 1.3.1 to 1.3.1 oO
how i uninstall it clearly? Remove the folder from apps folder?

**Comment by georgehrke** [comment]
remove it from `/var/www/nextcloud/apps` or wherever you installed nextcloud

**Comment by Tealk** [comment]
![1_3_1](https://cloud.githubusercontent.com/assets/12276250/17434622/bd5f65c0-5b0b-11e6-8554-f09ca213d6aa.jpg)
![apps](https://cloud.githubusercontent.com/assets/12276250/17434625/bff60d2a-5b0b-11e6-91a1-ceaf612d6f2e.jpg)

Im confused

**Comment by georgehrke** [comment]
Then just click `Aktivieren`

**Comment by Tealk** [comment]
ok now i have disable and reinstall it but i have the same issue

**Comment by georgehrke** [comment]
> `SyntaxError: expected expression, got '*'angular.js:310:1`

Your browser does not support angular?!
Please list the browsers including the version numbers you tested

We only aim to support the very latest version of Firefox, Safari and Chrome/Chromium

**Comment by Tealk** [comment]
i have use firefox 48.0 for browser log

**Comment by georgehrke** [comment]
<img width="1333" alt="calendar - nextcloud firefox today at 1 04 16 pm" src="https://cloud.githubusercontent.com/assets/1250540/17434857/2267bdc2-5b0d-11e6-9ba2-ef3eedf6094b.png">
Works just fine for me

**Comment by georgehrke** [comment]
also tried both german formal and informal

**Comment by Tealk** [comment]
I would like if it would work for me, what you mean with formal?

**Comment by georgehrke** [comment]
formal = Sie
informal = Du

**Comment by georgehrke** [comment]
can you give me a test account?

**Comment by Tealk** [comment]
have test it with englisch too, the same problem
acc and pw is test123

**Comment by georgehrke** [comment]
<img width="1916" alt="kalender - nextcloud chromium today at 1 10 55 pm" src="https://cloud.githubusercontent.com/assets/1250540/17435033/55657cc2-5b0e-11e6-8735-fb3465549379.png">
The `angular.js` in your setup is completely fucked up oO

**Comment by Tealk** [comment]
and now? upload it manually?

**Comment by georgehrke** [comment]
I just double checked. The angularJS in the archive on apps.owncloud.com is just fine.

@Tealk144 Do you use some kind of reverse proxy?

**Comment by Tealk** [comment]
could it be a problem by cloudflare Minify JS?

**Comment by georgehrke** [comment]
I suspect cloudflare-nginx might be causing this issue

**Comment by georgehrke** [comment]
yes

**Comment by georgehrke** [comment]
If you really require minified JS and CSS I'd advice you to use Nextcloud's native minifier
see https://docs.nextcloud.com/server/9/admin_manual/configuration_server/js_css_asset_management_configuration.html?highlight=asset

**Comment by georgehrke** [comment]
It seems to work now 😉

**Comment by Tealk** [comment]
i have set up cloudflare recently, as you mentioned javascript i have remember that i have read it on cloudflare

Yes thank you verry much
