### ISSUE TITLE
Misleading documentation on adding Calendar to Thunderbird

### ISSUE THREAD

**Issue by reckart** [owncloud/calendar#682]
The documentation says (http://doc.owncloud.org/server/7.0/user_manual/pim/calendar.html#synchronizing-calendars-using-caldav)

```
To access your ownCloud calendars using CalDAV-compatible programs like Kontact, Evolution, or Thunderbird, you would use the following URL:

http://ADDRESS/remote.php/caldav
```

Unless I am mistaken, Thunderbird does not support CalDAV without the Lightning Addon. A few lines later, the documentation mentions Lightning explicitly.

The rest of the lines in that section are not helpful at all when OwnCloud is using an AD as it's user-base, because the users are all represented by UUID and not usernames and users have no idea what their UUIDs are. It would be nice to talk about the "CalDAV link" button next to the calendar name and how to use it.

Btw. I found that OwnCloud calendars can be subscribed to using Outlook (read-only) if one adds "?export" to that CalDAV link. That information could be added as well.

**Comment by georgehrke** [comment]
please reopen in https://github.com/owncloud/documentation

**Comment by reckart** [comment]
Reopened as: https://github.com/owncloud/documentation/issues/778
