### ISSUE TITLE
requesting feature - agenda view in calendar

### ISSUE THREAD

**Issue by vacy** [owncloud/calendar#684]
Hi guys,

i really would like to see an agenda feature in the calendar app.
I like to utilize it in KDE's kontact and my mobile app "acalendar".
Please take a look at "https://www.drupal.org/project/agenda" to see what the feature means to be.

Thank you.
Florian

**Comment by georgehrke** [comment]
so basically a list view?
https://github.com/owncloud/calendar/issues/85

**Comment by vacy** [comment]
Oh, well done. Thats it :-)
