### ISSUE TITLE
owncloud 7.0.4: Can't hide calendars shared by other users in the web interface

### ISSUE THREAD

**Issue by rstalder** [owncloud/calendar#684]
My own calendars can be hidden in the web interface by clicking on the calendar. This is not possible with calendars shared with me by other users.

This bug applies to owncloud 7.0.4, community edition.

**Comment by RealRancor** [comment]
Hi,

duplicate of: https://github.com/owncloud/calendar/issues/492, https://github.com/owncloud/calendar/issues/21
