### ISSUE TITLE
Sharing for events broken on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/calendar#685]
When editing an event and clicking on the share tab and searching for a user:

```json
{"reqId":"dbd301f1e669dc5ae76c34fe26e04a8f","remoteAddr":"::1","app":"OCP\\Share","message":"Sharing backend for  not found","level":3,"time":"2015-01-26T08:54:16+00:00"}
{"reqId":"dbd301f1e669dc5ae76c34fe26e04a8f","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"Freigabe-Backend f\\u00fcr  nicht gefunden\",\"Code\":0,\"Trace\":\"#0 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/lib\\\/public\\\/share.php(317): OC\\\\Share\\\\Share::getBackend(NULL)\\n#1 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/core\\\/ajax\\\/share.php(297): OCP\\\\Share::getBackend(NULL)\\n#2 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/Users\\\/lreschke...')\\n#3 [internal function]: __lambda_func(Array)\\n#4 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_586', Array)\\n#5 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/core\\\/ajax\\\/shar...')\\n#6 \\\/Users\\\/lreschke\\\/Programming\\\/core\\\/index.php(28): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/Users\\\/lreschke\\\/Programming\\\/core\\\/lib\\\/private\\\/share\\\/share.php\",\"Line\":1205}","level":4,"time":"2015-01-26T08:54:16+00:00"}
```

**Comment by georgehrke** [comment]
@schiesbn Do you have an idea what could cause this error message.
Seems like the calendar's appinfo/app.php is never called.

**Comment by georgehrke** [comment]
ping @schiesbn

**Comment by georgehrke** [comment]
@PVince81 Could this be related to your pr for only loading apps on demand. Do I need to add something to the info.xml to enable sharing?

**Comment by PVince81** [comment]
I don't remember any such change. @icewind1991 do you know anything ?

**Comment by georgehrke** [comment]
ping @schiesbn @icewind1991

**Comment by length5** [comment]
See: http://forum.owncloud.org/viewtopic.php?f=31&t=26408
Are any logs needed? I can provide some in addition to what is in that forum post.

**Comment by georgehrke** [comment]
ping @schiesbn @icewind1991

**Comment by length5** [comment]
What's weird is that new events cannot be shared individually. An existing event remains shared. An existing calendar also remains shared. I haven't tried a new calendar, but I'd guess it doesn't. I can see events in a shared calendar via the regular web page as well as through CalDAV even though the event doesn't show it as shared either to an individual or show that the calendar is shared.

**Comment by length5** [comment]
A few more people have chimed in on the forum thread saying they are experiencing the same issue... Any progress being made?

**Comment by aksu358** [comment]
Hi,  I'm also having this problem.  Upgrading to OC8 seemed to break something.  Any info I can give to help?
- Alex

**Comment by Luticus** [comment]
I am also experiencing this issue since upgrading to OC8.  When I go to enter a user to share with the auto complete feature doesn't appear and even if I correctly type the name I still don't see the event as properly shared.  This feature worked perfectly under OC7

**Comment by Luticus** [comment]
Not sure if it helps but I see this: "TypeError: $(...).offset(...) is undefined calendar.js:120:25" in my FireFox developer console.

**Comment by aksu358** [comment]
I got:
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/"

When clicking on a calendar item.

**Comment by master-pago** [comment]
I am experiencing the same under OC8. Worked under OC7. 
Urgent fix would be appreciated!

**Comment by georgehrke** [comment]
Please stop asking when this will be fixed. You only spam my inbox and which means that I have less time to look into this!

**Comment by georgehrke** [comment]
for ref: https://github.com/owncloud/calendar/issues/745#issuecomment-77765363

**Comment by master-pago** [comment]
@georgehrke I don't want to disturb you, but I really need a solution. Is there any way we can speed up this? I would love to donate something for your development work as well!

**Comment by aksu358** [comment]
Hi,
As with Master-Pago, I would be interested to know how to help with this bug.  The issue was reported in January, and now in April I see from that there is no milestone and no assignee for this bug.  I understand you probably have other things going on, but this bug, for me, is close to being a deal-breaker.  If I can help, please let me know how.

BR : Alex

**Comment by georgehrke** [comment]
master: bd1069b
stable8: 7cadce0

**Comment by juanjgit** [comment]
Thank you @georgehrke for solving the issue. Have 100 bits on me @ChangeTip

**Comment by changetip** [comment]
Hi @georgehrke, @juanjgit sent you a Bitcoin tip worth 100 bits, and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/702408)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by master-pago** [comment]
Thanks a lot @georgehrke for fixing this! The next beer is on me, I just sent $5 @ChangeTip

**Comment by changetip** [comment]
Hi @georgehrke, @master-pago sent you a Bitcoin tip worth 21,126 bits ($5.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/705673)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by aksu358** [comment]
Awesome - thanks guys!!

**Comment by PVince81** [comment]
@georgehrke the stable8 backport broke events on stable8, see https://github.com/owncloud/calendar/issues/769
