### ISSUE TITLE
Calendar not displaying after Upgrade to 1.3.2

### ISSUE THREAD

**Issue by nineff** [owncloud/calendar#686]
### Steps to reproduce

Upgrade owncloud-app-calendar package on ARCH to latest version. I'm however not sure if this is the real cause of the error. However it worked before the update.
I suspect it's due to these missing files (see error log below):
"/owncloud/apps/calendar/css/public/app.css" 
"/owncloud/apps/calendar/js/public/app.js" 
"/owncloud/apps/calendar/css/public/app.css" 
### Expected behaviour

Calendar should display
### Actual behaviour

The Calendar page loads, but only the left panel shows up and it only contains dislocated functionless buttons. See attached screenshot: ![error](https://cloud.githubusercontent.com/assets/3100873/17464147/adb7d35a-5cd7-11e6-8aca-a0623069e1a6.png)
### Server configuration

**Operating system**: 
Linux myhostname 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

**Web server:**
 Apache/2.4.23 (Unix)

**Database:**
MariaDB 10.1.16

**PHP version:**
PHP 7.0.9 

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Calendar version:** (see ownCloud apps page)
1.3.2

**Updated from an older ownCloud or fresh install:**
Updated Calendar from either 1.3.1 or 1.2.2 (Sorry, don't remember which version I had previously)

**Signing status (ownCloud 9.0 and above):**
no errors

**List of activated apps:**
Enabled:
- activity: 2.3.2
- calendar: 1.3.2
- comments: 0.3.0
- contacts: 1.3.1.0
- dav: 0.2.5
- documents: 0.13.0
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1

Disabled:
- encryption
- external
- files_antivirus
- files_external
- galleryplus
- music
- user_external
- user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc07qb15y2st",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/usr\/share\/webapps\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:**
no
### Client configuration

**Browser:**
all of them
**Operating system:**
does not matter, but tested only on WIN10
**CalDAV-clients:**
They seem to still work
#### Web server error log

```
-- Reboot --
Jul 31 13:31:56 meinARCHserver systemd[1]: Started Apache Web Server.
Aug 07 11:25:14 meinARCHserver systemd[1]: Stopping Apache Web Server...
Aug 07 11:25:16 meinARCHserver systemd[1]: httpd.service: Killing process 456 (httpd) with signal SIGKILL.
Aug 07 11:25:16 meinARCHserver systemd[1]: httpd.service: Killing process 465 (httpd) with signal SIGKILL.
Aug 07 11:25:16 meinARCHserver systemd[1]: httpd.service: Killing process 504 (httpd) with signal SIGKILL.
Aug 07 11:25:16 meinARCHserver systemd[1]: httpd.service: Killing process 19663  (httpd) with signal SIGKILL.

Aug 07 11:25:16 meinARCHserver systemd[1]: httpd.service: Killing process 19686  (httpd) with signal SIGKILL.

Aug 07 11:25:16 meinARCHserver systemd[1]: Stopped Apache Web Server.
-- Reboot --
Aug 07 11:26:27 meinARCHserver systemd[1]: Started Apache Web Server.
Aug 07 11:27:58 meinARCHserver systemd[1]: Stopping Apache Web Server...
Aug 07 11:27:58 meinARCHserver systemd[1]: httpd.service: Killing process 502 (httpd) with signal SIGKILL.
Aug 07 11:27:58 meinARCHserver systemd[1]: Stopped Apache Web Server.
Aug 07 11:27:58 meinARCHserver systemd[1]: Started Apache Web Server.

```
#### ownCloud log (data/owncloud.log)

`{"reqId":"qgWOOX4mQwHwrsvJVO8t","remoteAddr":"*****","app":"PHP","message":"Uncaught Error: Class 'OCP\\Lock\\ILockingProvider' not found in \/usr\/share\/webapps\/owncloud\/lib\/private\/Files\/View.php:1150\nStack trace:\n#0 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#1 \/usr\/share\/webapps\/owncloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#2 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#3 {main}\n  thrown at \/usr\/share\/webapps\/owncloud\/lib\/private\/Files\/View.php#1150","level":3,"time":"2016-08-05T13:40:59+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/USA\/DSC_0523.jpg","user":"niko"}
{"reqId":"59EeLjHdYi7xh0o39754","remoteAddr":"****","app":"core","message":"starting upgrade from 9.1.0.15 to 9.1.0.15","level":0,"time":"2016-08-07T11:22:29+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=EhViGH8Ae28aJQURG1AbGBUqDwMZHABhYQY9HjAvKh8%3D%3AcQ%2Fq15H%2B5PkiU5JtQKxJcnmTRLqwfhzoe%2FmDX2%2F8ViU%3D","user":"--"}
{"reqId":"GEL1ATo8EpYlx2PV0GII","remoteAddr":"*****","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"niko\"}","level":4,"time":"2016-08-07T11:23:32+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"niko"}
{"reqId":"xyrvNyGoqgfD0mhHMLsp","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T11:24:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"xyrvNyGoqgfD0mhHMLsp","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T11:24:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"q8l5ZSA5tCbO755WsGKA","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T11:24:18+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"q8l5ZSA5tCbO755WsGKA","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T11:24:18+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"JaeQsPRLTZesF5bbBZOv","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T11:27:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"JaeQsPRLTZesF5bbBZOv","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T11:27:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"x++xgiSJYvTDF\/rfHOGH","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T11:28:05+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"x++xgiSJYvTDF\/rfHOGH","remoteAddr":"******","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T11:28:05+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"vp4\/qSNfNdyAw\/zoqSmJ","remoteAddr":"*****","app":"core","message":"Could not get application: cURL error 28: Operation timed out after 20000 milliseconds with 0 out of 0 bytes received","level":3,"time":"2016-08-07T13:40:42+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"niko"}
{"reqId":"5aXA2ogNGWlw6FpVGTHI","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T15:26:22+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"5aXA2ogNGWlw6FpVGTHI","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T15:26:22+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"MjRGk7Dd\/E\/l1fF1e5fQ","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T17:34:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"MjRGk7Dd\/E\/l1fF1e5fQ","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T17:34:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"AqYsJtJeukAmoLNuUXDg","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T17:43:18+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"AqYsJtJeukAmoLNuUXDg","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T17:43:18+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"oIMVxLKhxks11Ng2\/sL3","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/public\/app.js\"","level":3,"time":"2016-08-07T18:01:09+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
{"reqId":"oIMVxLKhxks11Ng2\/sL3","remoteAddr":"*****","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/css\/public\/app.css\"","level":3,"time":"2016-08-07T18:01:09+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"niko"}
`

**Comment by georgehrke** [comment]
> owncloud-app-calendar package on ARCH

Please contact the maintainer, they need to update their build script.

**Comment by georgehrke** [comment]
@p5n Please use the calendar.tar.gz attached to each release
https://github.com/owncloud/calendar/releases

Also it's AGPL, not GPL 😉

**Comment by p5n** [comment]
owncloud-app-calendar-1:1.3.2-2 should be better, thank you
