### ISSUE TITLE
(Shared) calendar deletion and confirmation

### ISSUE THREAD

**Issue by shtrom** [owncloud/calendar#689]
Hi, this is two linked problems that I ran into when sharing my calendar with a reckless clicker:
1. I gave them edit rights, which apparently gave them the right to completely delete the calendar
2. When clicking the Delete icon (bin), the calendar is directly deleted, without asking for confirmation or giving a warning.

What I would have expected:
1. To give deletion permissions separately (or just that they are only accessible to the owner)
2. That a warning/confirmation message is displayed before irremediably deleting the calendar.

Lucky I set up weekly backups (:

**Comment by georgehrke** [comment]
these are two issues, both dups, will search for original issues asap
