### ISSUE TITLE
other user's calendar is listed with my calendars and can be reshared

### ISSUE THREAD

**Issue by torsten-winkler** [owncloud/calendar#691]
### Steps to reproduce
1. create calendar
2. share calendar with other user, check "can edit"
3. log in as other user, go to calendar list
### Expected behaviour

The shared calendar should be listed under "subscriptions". Also, it should not be possible to re-share the calendar if re-sharing is disabled globally in the server prefs.
### Actual behaviour

The shared calendar is listed under the user's own calendars. It is possible to re-share the calendar even when re-sharing is prohibited by the admin. See screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/15922846/17551499/c5ab7370-5efa-11e6-9974-0ca59401d269.png)
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache 2.4
**Database:**
MySQL
**PHP version:**
5
**ownCloud version:** (see ownCloud admin page)
9.0.4 (9.1 tested as well)
**Calendar version:** (see ownCloud apps page)
1.3.2
**Updated from an older ownCloud or fresh install:**
frequently updated
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**
Firefox or Chrome
**Operating system:**
Linux / Ubuntu or MS Windows
**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Subscriptions are read-only calendars, that's why it appears under the ordinary calendar list.
The allow reshare setting in the admin settings has nothing to do with caldav and carddav sharing.

Please raise an issue in Core (https://github.com/owncloud/core/issues) if you dislike this behavior
