### ISSUE TITLE
GUI Issue: OCC Doesn't Limit number of events displayed in cells while in month view

### ISSUE THREAD

**Issue by aproposnix** [owncloud/calendar#693]
I'm currently migrating from Google Calendar to Owncloud (thanks to all the devs for making this possible). One of the things I use Google Calendar for is keeping a calendar of my all of my phone calls (from Android). I manged to get my call log to synchronize with owncloud calendar but I've come across a GUI issue.

When you have multiple (read many) calendar events in a day, the OC calendar app (in the month view) will expand the cells to accommodate the extra information. This looks terrible and makes it hard to read the calendar. It would be better if there was limit on the number of entries to show. For those calendar cells which exceed the limit, there could be a link for "see more" which would open the calendar in day view (seems the easiest way) or could open up a pop-up with the full list of events.

EDIT: The option to open in day view will not work as the events show no detail (and because most calls are less than 15 minutes they are displayed as thin lines). See issue #256. This may be relevant to issue #359 as well. 

EDIT 2: It should be noted that when you have lots of events in a single day it breaks the entire month view. For example, in the image below you see a lot of events which expands the cell. When I made that screen it was the beginning of the month. Now, because of the cell, when i open in month view it only shows the begining of the month. Everything below that week needs to be scrolled down to view. You cannot see the month view on one screen. 

here's an example of how it looks now: 
![selection_007](https://cloud.githubusercontent.com/assets/6204273/5987463/e3d9a330-a92a-11e4-8355-42de85822e60.png)

**Comment by georgehrke** [comment]
upstream issue, will be fixed once we update to full calendar 2
