### ISSUE TITLE
QR Code for CalDAV urls

### ISSUE THREAD

**Issue by mkubik** [owncloud/calendar#694]
It would help to have the rather long urls being represented as QR codes in the UI so that one can just scan them on mobile devices. 

Personally, I have 4 or 5 calendars and it's somewhat annoying  to re-type the url over and over again. Sure, I copy the first URL and paste and add the calendar name, but that is more or less URL guessing, which might not work in all cases. OC luckily has predictable URLs but I'm not sure how long this will be true.

There's a bunch of online QR code generators out there, so that it might make sense to make it configurable ins some way to use different ones.

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/578
