### ISSUE TITLE
Can not sent Calendar events by email

### ISSUE THREAD

**Issue by christianlx** [owncloud/calendar#698]
As suggested by the Core Team, I reopened here.

Hi Owncloud devs,
I've a stranged behaviour whith sharing calendar events and mail notification.
When i share an event to another user and "send email", notification is sent to me, but not to my contact.
I found an old post where someone had the problem on 6.x version. I'm using a 7.0.4.

Is it a bug or configuration mistake ?

**Comment by georgehrke** [comment]
> I  found an old post where someone had the problem on 6.x version

duplicate

**Comment by christianlx** [comment]
When I said "found an old post" it's on a forum, not in the bug tracker. This behaviour does not seem to be corrected in the 7.x version

**Comment by georgehrke** [comment]
there is also a bug report in this bug tracker, if i remember correctly this will be fixed with oC 8

**Comment by georgehrke** [comment]
and if you open new bug reports, please use the issue template as asked in our contribution guidelines
