### ISSUE TITLE
Feature Request: Enable Calendar Selection also for Other Users' Calendars

### ISSUE THREAD

**Issue by martinstut** [owncloud/calendar#699]
## Context
When using the web client, in the list of calendars in the left pane, each line (calendar) contains a square, filled with the colour of the calendar. In the documentation (http://doc.owncloud.org/server/7.0/user_manual/pim/calendar.html) this is referred to as Calendar Selection. 
For each of your own calendars, you can click on its Calendar Selection square, toggling the visibility of this calendar's appointments in the main pane. This is good.
## Observed Behaviour
On *other* user's calendars, when you click on the Calendar Selection square, nothing happens. You always see all calendars you have read access to.
### Impact
In an office with 10+ users, each of whom shares his calendar read-only to all other users, your web calendar view contains the intermixed appointments of 10+ people, possibly all in the same colour, making it very hard to tell which appointment belongs to which calendar.
This issue is *the* main show stopper when thinking of suggesting OwnCloud to offices looking for an in-house calendaring server less complex than eGroupWare or MS Exchange.
## Desired Behaviour:
On all calendars, *especially those you do not own*, do show/hide the calendar when clicking on its Calendar Selection square. Showing/Hiding a calendar on the web interface must not modify its visibility to CalDAV sync clients.
### Bonus
Remember the shown/hidden calendars across sessions.
If that's inadequately difficult to implement, start with showing only your own calendars and no other calendars.
### Extra Bonus
Offer group icons to click on, toggling the view of all calendars of the group represented by the icon.

**Comment by georgehrke** [comment]
duplicate

**Comment by martinstut** [comment]
Duplicate to which number? I've spent an hour browsing the issue list and didn't find this topic mentioned.

Greetings
--
Martin Stut, Marburg
Tel. 06421-953639, mobil 0177-3221470, Threema: 6B2F6M58
Am Smartphone verfasst. Bitte Kürze und Tippfehler entschuldigen.

Am 2. Februar 2015 21:48:37 MEZ, schrieb Georg Ehrke <notifications@github.com>:

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/21
