### ISSUE TITLE
implement calendar-sharing

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#7]

**Comment by georgehrke** [comment]
removed milestone, we first need a milestone for #46. This will be taken care of in a later sprint.

**Comment by georgehrke** [comment]
We will also need some GUI for accepting a shared calendar.

**Comment by georgehrke** [comment]
maybe we should drop the cruds logic in favor of two properties: writable & shareable

**Comment by georgehrke** [comment]
I will add a `share` function to the CalendarService. It'll look like this:
`
CalendarService.share(calendar, shareType, shareWith, writable);
`
CalendarService will contain two constants for the shareType. one for users and one for groups.

Furthermore I'll extend the calendar object. I'll add a `sharedWith` property that roughly looks like this:
```js
sharedWith: {
users: [{id: 'georg', 'displayname': 'Georg Ehrke', writable: true}],
groups: []
}
```

**Comment by DeepDiver1975** [comment]
> We will also need some GUI for accepting a shared calendar.

not for now - the sharing behaviour as currently implemented in core (shipped 9.0) will auto-accept sharing requests.

we can add this for a later stage - 9.1 maybe

**Comment by georgehrke** [comment]
> not for now - the sharing behaviour as currently implemented in core (shipped 9.0) will auto-accept sharing requests.

less work for now, awesome :)

**Comment by tomneedham** [comment]
@DeepDiver1975 Is there a ticket for tracking the Calendar Sharing DAV extension in core?

**Comment by tomneedham** [comment]
> maybe we should drop the cruds logic in favor of two properties: writable & shareable

Who makes the call on this? @jancborchardt / @PVince81 ? From a users POV it does simplify things. 

Also @georgehrke No share by link?

**Comment by DeepDiver1975** [comment]
Calendar sharing PR is wip in core ... Will finish today ...

**Comment by DeepDiver1975** [comment]
No link share for now. 
Dropping cruds: go for it

**Comment by jancborchardt** [comment]
I’m also totally fine with dropping CRUDS here. It’s even questionable if it’s needed in Files, so no need to have it here unless someone puts down the skrilla to implement it.

**Comment by DeepDiver1975** [comment]
we are fully on webdav - so we have full webdav acls.

With respect to sharing a calendar can be shared rw or readonly

**Comment by tomneedham** [comment]
Cool, so we can just have a 'can edit' checkbox ?

**Comment by jancborchardt** [comment]
@tomneedham yup. And »can share«, but maybe it even makes sense to simplify further and combine that with the edit functionality. That is, if you can edit, you can also share. What do you think @DeepDiver1975 @georgehrke?

**Comment by georgehrke** [comment]
> And »can share«

I don't get the point of »can share«. If you can read it, you can also export it, import it into a new calendar and share that one. There is no real point in disallowing resharing.

Also I'm not sure if caldav sharing allows to prohibit resharing.

**Comment by jancborchardt** [comment]
Sure, I’m also totally fine with that. In fact I’m glad we’re challenging the mass of settings to keep it super simple … as you know. ;D

**Comment by tomneedham** [comment]
Totally agree with the above. It runs along the lines of giving false ideas to the user about how there data is protected. Cool cool, I'll get on this tomorrow. @georgehrke Whats the status of the CalendarService and object stuff?

**Comment by jancborchardt** [comment]
@tomneedham cool to have you on board! :)

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar-rework/pull/122

**Comment by tomneedham** [comment]
Are remote user shares possible / out of scope? @DeepDiver1975 ?

**Comment by georgehrke** [comment]
> Are remote user shares possible / out of scope?

AFAIK definitely not for ownCloud 9.0
