### ISSUE TITLE
Repeat every 'Work day'

### ISSUE THREAD

**Issue by aquemy** [owncloud/calendar#700]
Hi,

In the previous calendar app, it was possible to specify the repetitions of an event during the work days, i.e. excluding the week-end.
Unless I am blind as a mole, I cannot see this option anymore.

Would it be possible to add it back? It is very useful to define work routine and currently the only way I found is to setup a weekly event 5 times, one for each work day.

Regards,

**Comment by georgehrke** [comment]
will close in favor of https://github.com/owncloud/calendar/issues/223

**Comment by georgehrke** [comment]
It was indeed not reimplemented yet. We will discuss #223 at the conf next month and we will implement a full-featured editor for the repeating setting shortly afterwords
