### ISSUE TITLE
URI in hexa decimal form

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/calendar#705]
An imported calendar's URI shows up as hex:
  displayname: work
          uri: A72E8474-1717-4826-9992-05A89A6A332A
       active: 1
         ctag: 11
calendarorder: 2
calendarcolor: #808000
     timezone: BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN

@georgehrke

**Comment by georgehrke** [comment]
not a bug, if there is nothing proper to generate a uri from, it generates a random uri. You only need the uri once (if at all) to setup the caldav client.
