### ISSUE TITLE
Calendar missing after update to Owncloud 8

### ISSUE THREAD

**Issue by MBurchard** [owncloud/calendar#706]
Minutes ago I received the update to Owncloud 8 from Ubuntu apt.  
After apt-get upgrade and Opening Owncloud in the Browser, the Calender and the Contacts App is not available anymore.  
It's also not visible under Apps and therefore can't be activated there.  
Where is it?  
How can I get it back?  
How can this happen with a stable version?

**Comment by georgehrke** [comment]
In the apps overview, there is an app called Calendar 8.0. Install it.
If you can't see it, please enable the app store. (take a look in the admin doc if you don't know how.)

**Comment by MBurchard** [comment]
Thank you
