### ISSUE TITLE
Calendar entries created in the application should contain VERSION element

### ISSUE THREAD

**Issue by juristi** [owncloud/calendar#706]
### Steps to reproduce
1. Create a new event on the calendar web page
2. Open the created event and export it as .ics
3. Run the .ics file through [icalendar validator](http://icalendar.org/validator.html)
4. The file is missing the mandatory ([RFC5545 3.7.4](https://tools.ietf.org/html/rfc5545#section-3.7.4)) VERSION element.
### Expected behaviour

The calendar should create valid icalendar entries.
### Actual behaviour

The entries created by the calendar do not conform to the specification. The entries created for example in Sailfish calendar/CalDAV client are fine.
### Workaround

I hacked the format on my own instance by adding the following line in [calendar/js/app/service/icalfactory.js](https://github.com/owncloud/calendar/blob/master/js/app/service/icalfactory.js):

``` js
app.service('ICalFactory', [function () {
        'use strict';

        // creates a new ICAL root element with a product id property

        return {
                new: function _new() {
                        var root = new ICAL.Component(['vcalendar', [], []]);

                        var version = angular.element('#fullcalendar').attr('data-appVersion');
                        root.updatePropertyWithValue('prodid', '-//ownCloud calendar v' + version);
+                        root.updatePropertyWithValue('version', '2.0');

                        return root;
                }
        };
}]);
```
### Server configuration

**Operating system**: Linux Debian Jessie
**Web server:** nginx 1.10.1
**Database:** PostgreSQL 9.4.9
**PHP version:** 5.6.24-0+deb8u1
**ownCloud version:** 9.1.0
**Calendar version:** 1.3.2

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.3.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external
  - user_ldap
```
### Client configuration

**Browser:** Firefox 47.0.1
**Operating system:** Windows 10

**Comment by georgehrke** [comment]
let's add a calscale as well

**Comment by georgehrke** [comment]
@juristi Do you mind testing https://github.com/owncloud/calendar/pull/707 ? :)

**Comment by juristi** [comment]
Not a problem. Will try it out this evening.

I guess replacing the ICalFactory in the already built app.js with the fixed version is good enough?

**Comment by georgehrke** [comment]
yes :)
thx!

**Comment by juristi** [comment]
"Success! No errors found."

Working fine with #707 :)

**Comment by georgehrke** [comment]
thx for testing! :)
