### ISSUE TITLE
[Solved] - Missing Repeating Events after update 7.0.4 -> 8.0.0 (on Phone via Caldav-sync)

### ISSUE THREAD

**Issue by eggithub** [owncloud/calendar#707]
Hi,

I don't know is this is an ownCloud 8 or Caldav-Sync App related issue on my android Phone. I'm missing repeating event for calendars, either with or without end date.

OS: Android 4.3
Cal Apps: Stock Android Calendar, Business Calendar (Pro en 2.0)
Sync App: Caldav_sync (Marten Gajda)

Will contact Marten Gajda as well...

Any of you experiencing same issue?

Thunderbird with Lightning works fine btw...

greetz!

**Comment by georgehrke** [comment]
> Any of you experiencing same issue?

no, and there has been almost no changes from ownCloud calendar 7.0.4 -> 8.0, so this is most likely a bug in Caldav sync.

**Comment by eggithub** [comment]
After an update of Google Calendar on Android today, all probs seem to be solved.

Caldav_sync seems to be working properly.

tested on a number op Calendar apps.

Solved it seems
