### ISSUE TITLE
Error Log: PHP Class 'OCA\Contacts\App' not found

### ISSUE THREAD

**Issue by JB1985** [owncloud/calendar#708]
Hi, 

i have owncloud 8.0.0-5 from Debian. 

Error:
PHP Fatal error:  Class 'OCA\\Contacts\\App' not found in /var/www/owncloud/apps/calendar/lib/sabre/backend.php on line 63

Line 63:                         $app = new \OCA\Contacts\App();

**Comment by georgehrke** [comment]
is the contacts app enabled?

**Comment by JB1985** [comment]
Ok, this is the mistake.

Missing Contacts App from Bug #14033
