### ISSUE TITLE
ldap uuid in calendar

### ISSUE THREAD

**Issue by JacekZ** [owncloud/calendar#71]
Hi,
I' ve got one suggestion to replace ldap uuid with "display name" attribute in "edit an event" window. In "share" tab in event properties there are " Shared with    9e7a3c30-023111e2-9721c17b-5c10dea9 (user)" and "Shared via calendar c23d8201-023111e2-9721c17b-5c10dea9 (user)". "It's little unreadable :(

**Comment by jancborchardt** [comment]
Because of the date I assume this is fixed. If the issue still occurs please open a new one, with the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) filled out.
