### ISSUE TITLE
OC8 - Hide the Share Calendar from other users

### ISSUE THREAD

**Issue by Nocxelp** [owncloud/calendar#710]
If you have 5 shared calendar your calendar view is full of events.
But you cant hide the shared calendar from the others.

thanks,
nocxelp

**Comment by georgehrke** [comment]
duplicate

**Comment by flotho** [comment]
@georgehrke duplicate of which one?

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/21
