### ISSUE TITLE
Calendar doesn't load on older Mozilla engine browser (Pale Moon)

### ISSUE THREAD

**Issue by mikelupe** [owncloud/calendar#711]
### Steps to reproduce
1. Manually upgrade OC 9.0.2 to NC 9.0.53 (successful)
2. Activate calendar app (successful)
3. Use Pale Moon 26.3.3 browser (older Mozilla engine for Mozilla Sync service), go to calendar app 
### Expected behaviour

Default Calendar and entries should show up. In Pale Moon it doesn't. With newer mozilla engine e.g. FF >= 47.x it's ok.
### Actual behaviour

With PaleMoon 26.3.3 loading icon keeps turning, "Delault calendar" entry doesn't even show up. Same happens on a clean nextcloud 9.0.53 installation. 

NOTE: With Firefox = >47.0.x it works, so it must be older engine issue. PaleMoon is needed for own MozillaSync service app on NC.
### Server configuration

Deb Jessie 8.5
Apache2
MariaDB

**Calendar version:** (see the apps page)
1.3.2

**Updated from an older installed version or fresh install:**
Updated from oc 9.0.2 - but on a clean nc 9.0.53 same issue.
### Client configuration

PaleMoon 26.3.3   (Firefox >= 47.x it works)

**Operating system:**
Windows / Linux

**Comment by tcitworld** [comment]
Can you give us your browser logs please ?

**Comment by mikelupe** [comment]
Sure - log of calendar app trigger in webui attached.
Is that enough?

[CalendarAppOlderMozillaEngine.txt](https://github.com/owncloud/calendar/files/424395/CalendarAppOlderMozillaEngine.txt)

**Comment by georgehrke** [comment]
We only support the latest version of Firefox, Safari and Chrome/Chromium.

> Sure - log of calendar app trigger in webui attached.
> Is that enough?

Is there something like a dedicated console for Javascript errors in Pale Moon?
The last request in your logs is:
`[10:00:56.957] PROPFIND https://dom.domain.tld/remote.php/dav/calendars/mihnea/ [HTTP/1.1 207 Multi-Status 69ms]`

There are supposed to be a bunch of other requests after that one. I guess there is some JS error.

**Comment by mikelupe** [comment]
QupZilla-Version: 1.8.9 / WebKit-Version: 538.1 same issue. 

I didn't have that before. So that basically would mean, I must give up using my own MozzillaSync service?

I will attach some other loginfos later, when I got more time.

**Comment by mikelupe** [comment]
New log (net, css, js, security & logging). Don't think I can pull out more.

I had a similar problem on PaleMoon with an ovirt virtualization Webui, after an update it worked again. So possibly there's a kind of workaround. I could ask the ovirt guys. Who knows, perhaps it tangents the same issue.

[NewFullLog_CalendarAppOlderMozillaEngine.txt](https://github.com/owncloud/calendar/files/424802/NewFullLog_CalendarAppOlderMozillaEngine.txt)

**Comment by tcitworld** [comment]
Still nothing much relevant inside the logs, sorry.

> So that basically would mean, I must give up using my own MozzillaSync service?

Just saying, it is still possible to install the Mozilla Sync Service yourself.

**Comment by mikelupe** [comment]
Well, I have the OC MozillaSync app, which worked fine for the last couple of months. It's basically a SyncServer. PaleMoon simply connects to that one. Firefox is a hassle concerning MozillaSync, last time I researched, it wasn't possible, or only with much troubles.

If this means I have to find another solution, I'll have to stick with it (grr). But mentioning new compatibility dependencies should be officially mentioned.

**Comment by tcitworld** [comment]
> But mentioning new compatibility dependencies should be officially mentioned.

Well it's mentioned on the front page : 

> # Supported Browsers
> - Latest Firefox
> - Latest Chrome/Chromium
> - Latest Safari
> 
> We don't support Internet Explorer or Egde. Patches for IE8+ and Edge are accepted though.

**Comment by mikelupe** [comment]
Ok, my bad sorry. Still a bummer.

Edge.... oookayy ;)
