### ISSUE TITLE
CalDAV syncing of LDAP-backed users returning 405 error on OC8

### ISSUE THREAD

**Issue by logomancer** [owncloud/calendar#712]
Since upgrading from 7.0.4 to 8.0.0, I've been having some difficulty with CalDAV syncing with a user backed by LDAP. Every time I try, the server gives a 405 error. Syncing with a normal DB-backed user works normally. Also of interest: Sync adapters previously set up with LDAP users can't sync calendars, reporting 404 errors. It's like the calendars aren't there anymore, but I can access them via the web interface.

**System Details**
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9
MySQL 5.5.41
Owncloud 8.0.0-7
Calendar App 0.6.4
Using DAVDroid 0.6.11 to sync

**Comment by georgehrke** [comment]
@blizzz any idea?

**Comment by georgehrke** [comment]
Do webdav and carddav still work?

**Comment by logomancer** [comment]
WebDAV works, CardDAV doesn't; it's doing the same thing as CalDAV. I filed a separate bug in the contacts app regarding my issue with CardDAV.

**Comment by minneyar** [comment]
I'm seeing similar issues.  I had CardDAV and CalDAV clients working perfectly with Owncloud 7, and I have users backed by LDAP.  Existing DAVdroid clients are getting sync errors, and I can't add new clients.

I have a similar configuration to the original poster (Ubuntu 14.04), but I've tested it using both Apache 2.4.7 and nginx 1.4.6.  When a client tries to sync contacts, I see this in the nginx access log:

```x.x.x.x - preed [10/Feb/2015:18:54:06 -0600] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 529 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
x.x.x.x - preed [10/Feb/2015:18:54:07 -0600] "PROPFIND /owncloud/remote.php/carddav/addressbooks/482b3a96-80be-1031-8d8d-9b001c6c70d4/contacts/ HTTP/1.1" 207 7965 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:54:08 -0600] "GET /owncloud/remote.php/carddav/addressbooks/482b3a96-80be-1031-8d8d-9b001c6c70d4/contacts/contacts HTTP/1.1" 404 268 "-" "DAVdroid/0.6.11"```

I can verify that the web interface looks fine, and if I manually get a CardDAV link for the address book in question, it matches the URL that the client is retrieving.  If I go to the URL manually in my web browser, I get an XML error message that has the following bit of information near the top:

```
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "addressbooks/482b3a96-80be-1031-8d8d-9b001c6c70d4/contacts"</s:message>
```

Syncing a calendar has the same issue.  For good measure, here's the relevant log lines:
```x.x.x.x - preed [10/Feb/2015:18:59:37 -0600] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 529 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
x.x.x.x - preed [10/Feb/2015:18:59:41 -0600] "PROPFIND /owncloud/remote.php/caldav/calendars/482b3a96-80be-1031-8d8d-9b001c6c70d4/defaultcalendar/ HTTP/1.1" 207 10178 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:59:42 -0600] "GET /owncloud/remote.php/caldav/calendars/482b3a96-80be-1031-8d8d-9b001c6c70d4/defaultcalendar/defaultcalendar HTTP/1.1" 404 279 "-" "DAVdroid/0.6.11"```

When I try to set up a new account with DAVdroid, I see log messages like so:

```x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /.well-known/carddav HTTP/1.1" 302 169 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /owncloud/remote.php/carddav/ HTTP/1.1" 207 397 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /owncloud HTTP/1.1" 405 181 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /.well-known/caldav HTTP/1.1" 302 169 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /owncloud/remote.php/caldav/ HTTP/1.1" 207 435 "-" "DAVdroid/0.6.11"
x.x.x.x - preed [10/Feb/2015:18:58:21 -0600] "PROPFIND /owncloud HTTP/1.1" 405 181 "-" "DAVdroid/0.6.11"```

It seems like here, it's stopping when the client tries to do PROPFIND on /owncloud and get a 405 response.  I've spent several hours trying to figure out where the 405 could be coming from and have had no luck; I've seen other people recommend server configuration or PHP changes to fix that, but none of that has worked for me, and the fact that I'm seeing the same behavior in both Apache and nginx makes me think it's coming from Owncloud.

**Comment by jniewerth** [comment]
I had the same problem, but could solve it by patching lib/private/connector/sabre as follows:

I removed:
```php
        public function getCurrentUser() {
                $user = OC_User::getUser();
                if($user && $this->isDavAuthenticated($user)) {
                        return $user;
                }
                return null;
        }
´´´

and replaced it with:
```php
    public function getCurrentUser() {
                $user = OC_User::getUser();
                return $user; 
     }
´´´

But this is only a quick HACK to get it going again. Unfortunately I currently do not have the time to investigate this further.

**Comment by rysiekpl** [comment]
I can confirm the issue; LDAP-backed users' calendars do not seem to work properly in OC 8. Apart from the `Sabre\DAVACL\Exception\NeedPrivileges` exception, also PROPFIND against `https://owncloud.hackerspace.pl/remote.php/caldav/` fails to return any calendars.

I believe this is all related to the UUIDs used as LDAp-backed users' identifiers internally in OC. Users backed by OCs internal db are not affected.

**Comment by rysiekpl** [comment]
Might be related to: https://github.com/owncloud/core/issues/14048?

**Comment by chris-se** [comment]
Yes, it's related to owncloud/core#14048, I've found a fix and posted it there.

**Comment by rysiekpl** [comment]
I ca confirm that the fix works.

**Comment by georgehrke** [comment]
@jniewerth If you had to patch smth in /lib/private/..., please write a bug report in core.

**Comment by johnwoltman** [comment]
I'm still having this issue, even though https://github.com/owncloud/core/issues/14048 is closed.

**Comment by georgehrke** [comment]
@johnwoltman please use the issue template as described in our contribution guidelines ...

**Comment by georgehrke** [comment]
@johnwoltman If carddav is broken as well?

**Comment by johnwoltman** [comment]
Yes, CardDAV is broken too.

My environment is:
Centos 7.0.1406
Apache 2.4.6
PHP 5.4.16
OpenLDAP 2.4.39
Postgresql 9.3.6
Calendar App 0.6.4

The clients are a mix of owncloud web apps, iOS, and OS X iCal.  The users are all from an LDAP system.

Here's the error message received when using a browser to visit the link: https://gist.github.com/johnwoltman/000ecbb5dccdcd055415

**Comment by georgehrke** [comment]
Then I'm almost sure that it's an issue with the auth provider that's part of core. so please comment there

**Comment by georgehrke** [comment]
(and use the issue template please)

**Comment by georgehrke** [comment]
99% sure it's an issue in core, closing
