### ISSUE TITLE
Personal calendar doesn't have a color

### ISSUE THREAD

**Issue by tcitworld** [owncloud/calendar#712]
### Steps to reproduce
1. Create a new account
2. Go to the calendar app
### Expected behaviour

Calendar automatically created "Personal" should have a color (next to it in the list)
### Actual behaviour

Doesn't have a color

Events created do have a color though.

**Comment by georgehrke** [comment]
```
    <d:displayname>Personal</d:displayname>
    <cal:calendar-description/>
    <cal:calendar-timezone/>
    <x1:calendar-order xmlns:x1="http://apple.com/ns/ical/">0</x1:calendar-order>
    <x1:calendar-color xmlns:x1="http://apple.com/ns/ical/"/>
    <cal:supported-calendar-component-set>
     <cal:comp name="VEVENT"/>
     <cal:comp name="VTODO"/>
    </cal:supported-calendar-component-set>
```

calendar-color is set but doesn't have any value

**Comment by georgehrke** [comment]
Therefore `simple.color` is just an empty string
https://github.com/owncloud/calendar/blob/master/js/app/service/calendarservice.js#L481

**Comment by tcitworld** [comment]
This could be corrected in _core_ too. Should it provide default color `#1d2d44` ?

**Comment by georgehrke** [comment]
Hm, maybe.
But the calendar should be able to handle the empty property anyway.

**Comment by tcitworld** [comment]
Will handle empty string here too then.
