### ISSUE TITLE
Day/week view optimization suggestion

### ISSUE THREAD

**Issue by lukas-buergi** [owncloud/calendar#713]
Currently events are placed on a linear vertical time axis in those views. I think this is not optimal. There are some subtle and less subtle ways this could be improved.

The goal is always to get a better overview of the events in the selected day/week with as little scrolling as possible.

The first three ideas are probably relatively simple for both users and developers, while the 4. and last is an optimization algorithm which tries to combine the compactness of a pure list view with the clarity and overview which the linear arrangement provides. If the latter is too complicated in your opinion, well, at least I had fun making it up. Anyone who finds a problem with it, please tell. Those sorting stuff into fixed spaces problems aren't that easy. 

While I would like to help make improvements actually possible, I fear I won't be much use because I have very little experience with PHP/JS. But if you think my ideas are good and would be willing to help point me at the right portions of code and the like, I would like to try. I do have some programming experience in general.
1. In day view only, use multiple columns on wide screens in an attempt to fit the whole day on one screen without scrolling (becomes less effective but not utterly useless if 3 is implemented).
2. In week view, skip days without events. For work calendars, this is often the weekend, or if a calendar contains free time activities, week days often won't contain events for people who work full time. Make this visible to the user with a heavier vertical line (maybe jagged or dotted or in another color?) where a day was omitted. 
3. Cut off the time before the first event and after the last: As long as there are only full day-long events (which are exempt from any such calculation) and events not spanning more than one day, this is simple. In week view, the extrema of first/last time for each day are taken and applied for all days the same. When events which are not full-day span multiple days it's less obvious what to do and there seem to be two possibilities for algorithms which also work with this:
   - switch this feature off on the given day/week (i.e. do "earliest time of day which is contained in any event" for the early cut off and respectively for the late cut off)
   - or ignore the middle parts of those events for the purpose of the cutoff. Then the cutoff point calculation is: "minimum of ( beginning time of any event on this day _or_ end time of any event on that day minus some margin so the title of the event which ends at that point still fits between the cut off and the end time of the event). This latter possibility can be improved by adding a symbol (maybe some kind of arrow?) at the the point where an event wraps to the next day respectively continues from the former day. This would also be a good idea on the current implementation without changing anything else.
4. Do away with any pretence of a linear scale (or any scale, really), keeping only relative ordering of the beginning and end points. This can be seen as an extension/generalization of the previous suggestion. I'm always assuming the week view, but it also simplifies to an improved list view for single days using exactly the same methods. It seems the easiest to me to describe my idea by giving an algorithm which displays the view I mean:
   - Generate events for all continuous spans of time where there is no event, named as the amount of free time they represent (ex.: "25min free" or "6h free"). Those are not saved into the calendar, just generated for displaying. They can either span the whole 24-hour day (so the first of those events is always from midnight to the first real event and the last from the last real event to midnight) or start at the same time as the earliest real event and end at the same time as the latest real event (doesn't change a lot, the latter can be up to two lines of text shorter for some arrangements of events). They are only generated for days which contain at least one real event.
   - Get a list of all beginning and end times of events in the day/week.
   - Sort it and remove duplicates
   - Consider rounding (not for displaying rounded numbers, but for the placement of the events). Needs more consideration. Don't round for now.
   - Use this list for the height of the basic table (or table-like structure, I don't necessarily mean this in the sense of html tables, use whatever is already being used for the calendar view) which will contain the events. The point of this table is to keep the relative ordering, so one event which is earlier in the day than an other also _looks_ like that in week view. It doesn't have fixed field heights. The table needs 2*n-1 rows where n is the amount of distinct times from the aforementioned list. The first row is for labelling the first time, the next for events starting at that time, the third for labelling the second time and so on, with the last row for labelling the time when the last event ends. The table needs n(i) columns for each day i where n is the maximum number of simultaneous events on day i (ex.: empty day has n=0, day without overlapping events n=1).
   - Put all the events in that table (display just their name for now, maybe inside the same kind of rounded boxes as now):
   - Vertically each event uses the cells within it's timespan, excluding cells for it's beginning and starting time.
   - Horizontally each event takes one cell at least, but more if because of simultaneous events more than one is available. Event placement on days where n(i)>1 works like this:
   - For each event (on that day), get the number of events overlapping with it. Call that number l(event).
   - Sort events by starting time
   - Place first event in list in the leftmost empty cell at the right vertical position, using n(i)-l(event)-1 more horizontal cells to the right too. Remove event from list. Repeat this bullet point.
   - Now the events are all placed (this works, doesn't it? should check in some more rigorous way).
   - In the cells vertically between the events, add the time. Maybe also in the same rounded rectangle box, but with a different color.
   - Now that the basic structure is fixed, we can still add more information from other fields of the events for maximum information density.
   - Take a list of all events.
   - Remove any events for which all information is already displayed.
   - Sort them with current height as first criteria (high to low), and as a second criteria (also high to low) minimum additional height which needs to be added in order to add more information (what exactly is useful additional information?)
   - Try to add a piece of information about the last event in the list to the table. If that's not possible without adding scrollbars (or the table is too large already), continue to next bullet point, otherwise remove the event from the end of the list, put it in the new correct place and repeat this bullet point.
   - Now the height of no event can be increased anymore. Go through all events and add all the information which fits without increasing the height of the event.
   - Done.

No I don't know whether this last one is worth it. Would be fun, though. Will go over it again tomorrow to check for stupidities...

**Comment by georgehrke** [comment]
please report this upstream at fullcalendar :)

http://fullcalendar.io/wiki/Contributing/

**Comment by lukas-buergi** [comment]
Oh, thanks, hadn't actually looked into it enough to notice there was an upstream, sorry.
