### ISSUE TITLE
 Undefined index: REQUEST_URI

### ISSUE THREAD

**Issue by tony5** [owncloud/calendar#714]
I am running debian 7
everything was working fine with OC 7.0.4
after upgrading to OC 8.0 I get an error in my logs that is triggered everytime cron runs.
the error is:
 Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41 
I never had this error on OC 7.0.4
I have tried to disable/remove/reinstall but I still get the same error.
other people have done a fresh install and get the error as well.

any advice?
take care

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by Panoptis** [comment]
Same here
Error PHP Undefined index: REQUEST_URI at /var/www/virtual/.../apps/calendar/appinfo/app.php#41
Calendar app seems to work fine though.
OC 8.0 (stable)
PHP 5.6.5 on CentOS

**Comment by georgehrke** [comment]
@Panoptis please use the issue template. I need more information for this!

**Comment by georgehrke** [comment]
>  cron runs.

What does the cron call look like?

**Comment by tony5** [comment]
### Steps to reproduce
1. upgrade OC from 7.0.4 to OC 8.0
2. Reinstall the app
3. do a fresh install

### Expected behaviour
Tell us what should happen
the error  Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41 should not be in the logs

### Actual behaviour
 Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41 is in the logs and run by system cron every 15 minutes.

### Server configuration
debian 7

**Web server:**
apache2
**Database:**
mysql
**PHP version:**
PHP Version 5.4.36-0+deb7u3
**ownCloud version:** (see ownCloud admin page)
 ownCloud 8.0 (stable) 
**Updated from an older ownCloud or fresh install:**
yes 7.0.4
**List of activated apps:**
Activity 1.2.0, Calendar 0.6.4,
Contacts 0.3.0.18, 
Deleted files 0.6.2, 
Documents 0.9.0, 
External storage support 0.2.3,
Mail Template Editor 0.1
First Run Wizard 1.1
File Locking
News 5.2.2
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.0
Text Editor 0.4
Updater 0.4
Versions 1.0.5
Video Viewer 0.1.3
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '#######',
  'passwordsalt' => '#########',
  'trusted_domains' => 
  array (
    0 => '192.*.*.*',
    1 => '*.*.org',
    2 => 'owncloud.*.*',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://192.*.*.*/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'me',
  'dbpassword' => 'me_pass',
  'installed' => true,
  'preview_libreoffice_path' => '/usr/local/bin/libreoffice',
  'enable_previews' => true,
  'preview_max_scale_factor' => 1,
  'overwritewebroot' => '/owncloud',
  'forcessl' => true,
  'loglevel' => 2,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'me1',
  'mail_domain' => '*.com',
  'mail_smtphost' => 'smtp.com',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'me',
  'mail_smtppassword' => 'pass',
  'theme' => '',
  'maintenance' => false,

);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
firefox/chrome
**Operating system:**
ubuntu/android
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

Insert your ownCloud log here
{"reqId":"###############","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-11T19:45:01+00:00"}


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Can you try replacing calendar/appinfo/app.php line 41:
``` 
$url = OC::$server->getRequest()->server['REQUEST_URI'];
```
with:
```
$url = @OC::$server->getRequest()->server['REQUEST_URI'];
```

**Comment by tony5** [comment]
cron is run with:
# crontab -u www-data -l
*/15  *  *  *  * php -f /var/www/owncloud/cron.php > /dev/null 2>&1

it looks as if
$url = @OC::$server->getRequest()->server['REQUEST_URI'];
has fixed this issue. thank you for a wondefull app and great support you provide with it.

I will keep an eye on it and post back after a few cron cycles if the problem persists

**Comment by Panoptis** [comment]
before:
```
Error	PHP	Undefined index: REQUEST_URI at /var/www/virtual/panoptis/owncloud/apps/calendar/appinfo/app.php#41	2015-02-11T20:10:02+00:00
```

line 41 replaced with:
```
$url = @OC::$server->getRequest()->server['REQUEST_URI'];
```
The error seems to be gone, waited two cron runs.

Thanks!

**Comment by georgehrke** [comment]
cool, will add the fix to the next release. Thx for testing

**Comment by tiku01** [comment]
The issue https://github.com/owncloud/calendar/issues/715 was marked as a duplicate. Note that the author there suggests a different solution. In the forum (https://forum.owncloud.org/viewtopic.php?t=26296&p=79253#p79314) he (I assume it is the same author) argues "Note that masking errors with '@' is generally bad idea." without further explanation. So possibly his solution has some benefits?

**Comment by georgehrke** [comment]
The forum is not a place to suggest patches. I'm not (and I won't be) active in the forum and if people want me to take a look at patches, they should send pull requests. 

> "Note that masking errors with '@' is generally bad idea."

It's an acceptable solution in this case. The error only comes up when the cron job runs. Usually `REQUEST_URI` is set when accessing owncloud via web or *dav.

**Comment by jhf2442** [comment]
This is still not fixed in 8.0.2 -> when will it reach the main codebase ?

**Comment by georgehrke** [comment]
Since ownCloud 8 the calendar app is not released with the standard packages but over the app store. Those, the release cycles of the calendar are independent from ownCloud's release cycles.

**Comment by jhf2442** [comment]
many thanks for your quick feedback !

**Comment by temmokan** [comment]
It was on forum who was against masking errors with '@' prefix.

> It's an acceptable solution in this case

I doubt that masking errors, instead of eliminating them, is more acceptable, but the developer has final word anyway.

**Comment by cjacobsen** [comment]
In the CLI php enviroment, $_SERVER['REQUEST_URI'] is never available.
So, this bug only affects when you use cron.php from crontab. The ajax and webcron are not affected.
Am i right?

**Comment by cjacobsen** [comment]
I think php_sapi_name() is a better solution in this case.

```
# php -r 'echo php_sapi_name()."\n";'
cli
#
```

**Comment by neitsab** [comment]
@temmokan and anybody wondering about how this ended: PR #752 was merged on 18 March 2015 with a different fix than simply masking the error with @. It should be part of the next 8.0.3 release :-)

**Comment by temmokan** [comment]
@neitsab Great, so I hope Calendar will work better when I upgrade to 8. Thanks.

**Comment by RealRancor** [comment]
@temmokan Why "work better"? AFAIK the message here is just a cosmetic issue which shouldn't cause any issues.

**Comment by temmokan** [comment]
@RealRancor Code working *without* any error/warning messages, even "cosmetic" (which in fact do not exist) is by definition better. It's strange to see programmer that thinks errors are acceptable, whichever negligible they are.

That's in any case up to developer, whether to leave the code untidy or whether to make it clean.

**Comment by RealRancor** [comment]
You have written "work better" not only "better" :wink:

**Comment by temmokan** [comment]
@RealRancor "If you have nothing to do, don't do it here".

You have understood me perfectly. I assume you don't think that writing code that reports warnings are mentioned above is fine. I don't think this is acceptable. Dixi.

**Comment by georgehrke** [comment]
> That's in any case up to developer, whether to leave the code untidy or whether to make it clean.

You are very welcome to send pull requests, if you don't like how things are implemented and think you have a better solution ;)

**Comment by RealRancor** [comment]
@temmokan
I think you don't get my point:

I'm just have written this above because you have written:
> so I hope Calendar will work better when I upgrade to 8
and i'm trying to point you to the fact that this change in here don't fix anything. If you have problems those are not related to this change.

**Comment by temmokan** [comment]
@RealRancor Are we talking about the same? About masking error messages instead of changing the code to eliminate possibility of these messages? While "it's an acceptable solution in this case"  approach is considered fine, one should expect much more serious problems.

Once again. Developer(s) have already expressed their position. I don't think there's something to discuss in this given case.

**Comment by RealRancor** [comment]
No, we're not talking about the same. I'm talking about this:

> so I hope Calendar will work better when I upgrade to 8

**Comment by temmokan** [comment]
@RealRancor There's no problem with fix 752. If it's used in 8.*, there should be no problem of this kind.

**Comment by neitsab** [comment]
Can we reopen this issue please? I just upgraded to 8.0.3 and still have this error on cron invocation. 

#774 and #779 were closed because duplicates of this issue, which is itself closed...

Here goes the template:

### Steps to reproduce
1. Update to 8.0.3
2. Enable the calendar app
3. Check the logs on next cron invocation

### Expected behaviour
No errors in log :)

### Actual behaviour
Error message `{PHP} Undefined index: REQUEST_URI at /usr/share/webapps/owncloud/apps/calendar/appinfo/app.php#41` appears on every cron invocation.

### Server configuration
**Operating system**: Arch Linux

**Web server:** nginx 1.8.0

**Database:** mysql  Ver 15.1 Distrib 10.0.17-MariaDB, for Linux (i686) using readline 5.1

**PHP version:** PHP 5.6.8 (cli) (built: Apr 20 2015 09:26:53), Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies served by uWSGI 2.0.10

**ownCloud version:** (see ownCloud admin page) 8.0.3 (git)

**Updated from an older ownCloud or fresh install:** Updated from 8.0.2

**List of activated apps:**
* Files
* Contacts
* Calendar
* Documents

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'appcodechecker' => false,
  'log_type' => 'syslog',
  'logfile' => 'owncloud.log',
  'loglevel' => 2,
  'logdateformat' => 'c',
  'logtimezone' => 'Europe/Paris',
  'log_query' => false,
  'log_rotate_size' => false,
  'secret' => 'xxx,
);
```

**Are you using external storage, if yes which one:** Nope

**Are you using encryption:** no

### Client configuration
Unrelated

### Logs
#### Web server error log
```
None
```

#### ownCloud log (data/owncloud.log)
From systemd-journald (not using data/owncloud.log):
```
mai 02 12:45:00 arch-medion uwsgi[533]: Sat May  2 12:45:00 2015 - [uwsgi-cron] running "/usr/bin/php -c /etc/uwsgi/cron-php.ini -f /usr/share/webapps/owncloud/cron.php" (pid 997)
mai 02 12:45:00 arch-medion ownCloud[997]: {PHP} Undefined index: REQUEST_URI at /usr/share/webapps/owncloud/apps/calendar/appinfo/app.php#41
mai 02 12:45:01 arch-medion uwsgi[533]: [uwsgi-cron] command "/usr/bin/php -c /etc/uwsgi/cron-php.ini -f /usr/share/webapps/owncloud/cron.php" running with pid 997 exited after 1 second(s)
```
Repeats every 15 minutes on every cron.php invocation.

#### uWSGI config
[cron settings](https://uwsgi-docs.readthedocs.org/en/latest/Cron.html#new-syntax-for-cron-options):
```uwsgi
cron2 = minute=-15,unique=1 /usr/bin/php -c /etc/uwsgi/cron-php.ini -f /usr/share/webapps/owncloud/cron.php
```

`/etc/uwsgi/cron-php.ini` defines the PHP environment uWSGI cron is running in, which is maintained in sync with ownCloud PHP environment defined in `/etc/uwsgi/owncloud.ini`. Relevant parts:

```uwsgi
## uwsgi-specific options
php-sapi-name = apache
php-docroot = /usr/share/webapps/owncloud
php-allowed-ext = .php
php-index = index.php

## modified php.ini options
php-set = open_basedir=/tmp/:/usr/share/webapps/:/etc/webapps/:/home/owncloud/
php-set = expose_php=false
php-set = post_max_size=10000M
php-set = upload_max_filesize=10000M
php-set = extension=gd.so
php-set = extension=iconv.so
php-set = extension=xmlrpc.so
php-set = extension=zip.so
php-set = extension=pdo_mysql.so
php-set = extension=mysql.so
php-set = extension=bz2.so
php-set = extension=intl.so
php-set = extension=mcrypt.so
php-set = extension=openssl.so
php-set = extension=exif.so
php-set = date.timezone=Europe/Paris
cache2 = name=mysessions,items=1000
php-set = session.save_handler=uwsgi
php-set = session.save_path=mysessions
php-set = zend_extension=opcache.so
php-set = extension=apcu.so
php-set = apc.ttl=7200
```
I'm trying to modify some options in my PHP env to see if it comes from my mildly restrictive setting, but please can someone state whether they're still affected by this bug and if so reopen it?

**Comment by RealRancor** [comment]
@neitsab 
Since OC8 the calendar app is not shipped anymore so OC 8.0.3 can't fix this.

**Comment by neitsab** [comment]
I did notice the split between owncloud core and apps, but as I updated both owncloud and owncloud-app-calendar to 8.0.3 I thought this update would contain #752 from March 18th.

So this isn't the case?

**Comment by georgehrke** [comment]
The calendar is only updated via the App Store. I don't know why there is an owncloud-appl-calendar anyway. That's an arch packaging issue

**Comment by RealRancor** [comment]
Yes, only the core apps should be provided by the packages like seen at the official repository at OBS:

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/Debian_8.0/all/

**Comment by georgehrke** [comment]
@neitsab Do you use some AUR or are those packages in the standard repos?

**Comment by neitsab** [comment]
@georgehrke All my owncloud-related packages comes from the official repos, which are built from the GitHub sources. [Here is the PKGBUILD for owncloud-app-calendar](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/owncloud-app-calendar), which highlights that the package is built without any patch from this very repository (line 14). Those are the same sources as the App Store uses right?

So package provenance isn't relevant here I believe; it's just that I have both OC core and calendar app at version 8.0.3 and that the bug is still present.

**Comment by neitsab** [comment]
@RealRancor Why is where I got the packages from relevant for this bug report, *as long as they are vanilla builds of the latest release*?

**Comment by RealRancor** [comment]
Sorry, but you're mixing the version of ownCloud (8.0.3) with the version of the calendar app. OC 8.0.3 hasn't shipped a new version of the calendar app.

**Comment by georgehrke** [comment]
@RealRancor But apparently arch does, also that's not how the ownCloud community wants it to be.

**Comment by georgehrke** [comment]
The reason why the arch package still has this bug is that the fix has not been backported to stable8 and is only in master. will backport it soon

**Comment by neitsab** [comment]
@RealRancor Yes, sorry I just saw that. So to clarify:
- enabled calendar app version reports to be 0.6.4 (in the "Application" app)
- recommended calendar version reports to be 0.6.4 as well, just has the "Calendar 8.0" tag different.

I tried to upload screenshots but GitHub is giving me a "something went really wrong" error... But anyway I guess you get it.

@georgehrke All right, if that's how upstream wants it to be I guess Arch maintainer will follow. He did make a comment at the time of the switch to split packages that he might drop them at some point. I'll open a bug report linking here to see what he thinks of it.

> The reason why the arch package still has this bug is that the fix has not been backported to stable8 and is only in master. will backport it soon

Great, thank you, that's the explanation I wanted to have! So App Store versions use the master branch or are they also lacking the fix?

**Comment by georgehrke** [comment]
> Great, thank you, that's the explanation I wanted to have! So App Store versions use the master branch or are they also lacking the fix?

The app store version also use stable8. But we can't just release a new versions. We need lot's of testing before publishing new versions.

**Comment by neitsab** [comment]
> The app store version also use stable8. But we can't just release a new versions. We need lot's of testing before publishing new versions.

You're right, now that I'm thinking of it I realize my comment was misguided. But I had in mind [this comment](https://github.com/owncloud/calendar/issues/714#issuecomment-80362542) you made earlier in this thread (18th March):
> Edit: an update for the calendar is planned very soon.

This is why I believed so firmly that the fix would be in 8.0.3 :)

Maybe you could set a milestone for this bug report so that users refered here will know approximately when it will land?

**Comment by PeterPablo** [comment]
I also see this in the log after updating to 8.0.3 from 8.0.2. Does it make sense to keep the issue open until the fix is available in the stable branches?

**Comment by binarykitchen** [comment]
```
{"reqId":"440d3afc80c7f411e040b0cb528c8a6a","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-05-06T01:00:01+00:00"}
```

Still happens on v8.0.3

**Comment by RealRancor** [comment]
Yes, because its not fixed in OC 8.0.3 as discussed in the comments above yours

**Comment by fossxplorer** [comment]
I'm also using stable8 and experience the samme issue:
"PHP","message":"Undefined index: REQUEST_URI at /apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-05-15...

**Comment by RealRancor** [comment]
Hi,

as discussed above its fixed when a new version of the calendar app is released.

**Comment by georgehrke** [comment]
stable8: https://github.com/owncloud/calendar/commit/3e4a1e1a241479c2c3c5be60379c520c421ce8c0

**Comment by jancborchardt** [comment]
@georgehrke there has been no reason to lock this issue. Please unlock it again, and don’t use locking lightly.

**Comment by georgehrke** [comment]
I use locking lightly, but people kept spamming, because they were too lazy to read the previous comments ...

**Comment by binarykitchen** [comment]
It is still happening with the latest v8.0.4.2

**Comment by neitsab** [comment]
@binarykitchen: did you upgrade both core and calendar application? I've upgraded and don't see this issue anymore.

**Comment by RealRancor** [comment]
@neitsab @neitsab 
OC 8.0.4 doesn't ship an updated calendar for the reasons already posted here:

https://github.com/owncloud/calendar/issues/714#issuecomment-98465345 , https://github.com/owncloud/calendar/issues/714#issuecomment-98468020

so this can't be fixed currently as no new version app was released yet as stated already at this issue.

@jancborchardt 

The locking of this issue is fully understandable. There where issues at core which got locked for minor reasons...

**Comment by neitsab** [comment]
@RealRancor That's weird.

As outlined in [my comment above](https://github.com/owncloud/calendar/issues/714#issuecomment-98467043), the package I use to get the calendar app on Arch [is built from GitHub releases](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/owncloud-app-calendar#n14), which happen to offer a [8.0.4 version](https://github.com/owncloud/calendar/releases/tag/v8.0.4) from two days ago. This is why I said I had "upgraded both packages": our maintainer had rebuilt `owncloud{,-app-calendar}` against the new release.

However [when compared against the 8.0.3 version](https://github.com/owncloud/calendar/compare/v8.0.4...v8.0.3) (which I was previously using), calendar-8.0.4 doesn't differ at all indeed.

- Why the tagged releases then? To be in sync with core?
- And more importantly, how come this error disappeared from my logs if calendar-8.0.4 doesn't bring anything new compared to 8.0.3?

I had new stuff related to owncloud/core/issues/13357, but not the pesky `REQUEST_URI` message. I can confirm that after a whole day of cron invocations, this error doesn't flood my log anymore (thanks btw!).

**Comment by RealRancor** [comment]
@neitsab 
Sure, if Arch is packaging against git then you get the fix as this is included in 8.0.4 tag. But all non-arch users like @binarykitchen are getting the update from the appstore which contains an version released on Feb. 2015: https://apps.owncloud.com/content/show.php/Calendar+8.0?content=168707

**Comment by georgehrke** [comment]
> Why the tagged releases then? To be in sync with core?

Yes, actually for legacy reasons I think

> And more importantly, how come this error disappeared from my logs if calendar-8.0.4 doesn't bring anything new compared to 8.0.3?

That seems like a bug in GitHub. If you select the tag 8.0.4, it shows that the latest commit was the one that fixed this issue. https://github.com/owncloud/calendar/tree/v8.0.4

**Comment by neitsab** [comment]
Ha, I was just editing my comment to reflect the discovery of 3e4a1e1 (indeed github interface is tricky on that one), which explains the situation.

Anyway, I'll stop posting on this issue because my case is indeed quite distro-specific. Thanks.

**Comment by RealRancor** [comment]
Btw. the arch guys shouldn't build their packages against github tags until the final version of oC is announced here: https://owncloud.org/changelog/

Until the final announcement the tags are a WIP according to https://github.com/owncloud/core/issues/16743 . If a build is done before the final announcement Arch can ship packages which are differs from the final package.

**Comment by neitsab** [comment]
--> Reported on Arch bug tracker [here](https://bugs.archlinux.org/task/45227).

**Comment by RealRancor** [comment]
@neitsab Thanks :+1: 
But just to clarify: I'm not upstream, just a contributor trying to clarify some stuff / giving support.

**Comment by binarykitchen** [comment]
Okay, makes sense now. For now, what should I do? Wait until v8.0.5 is out for Ubuntu I can update with apt-get?

**Comment by RealRancor** [comment]
Hi,

8.0.5 is also not fixing this issue as the calendar app us not bound to the oC version as stated several times in this thread. Just ignore the logentries until a new version of the calendar app is released.

**Comment by sorglos** [comment]
[Calendar v8.0.4](https://github.com/owncloud/calendar/releases/tag/v8.0.4) – released four days ago – fixes this issue. ;-)

**Comment by enoch85** [comment]
Still seeing this in 8.1.

```
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35
```

**Comment by RealRancor** [comment]
@enoch85

```
/apps/contacts/
```

:wink:

Issue for the contacts app is here: https://github.com/owncloud/contacts/issues/972
