### ISSUE TITLE
Reminder for contact birthdays

### ISSUE THREAD

**Issue by escoand** [owncloud/calendar#715]
### Expected behaviour

It would be nice to have the possibility to set reminders for birthday events in general and also for only specific birthday events.
### Actual behaviour

There is no way to add a reminder for one specific birthday nor for the events in general.
### Server configuration

**Server version:** 9.0.53
**Calendar version:** 1.3.2

**Comment by escoand** [comment]
Maybe belongs to #119

**Comment by georgehrke** [comment]
The birthday calendar is generated by the server.
Please raise the issue in the core repo.
