### ISSUE TITLE
"Undefined index: REQUEST_URI" in appinfo/app.php

### ISSUE THREAD

**Issue by temmokan** [owncloud/calendar#715]
OC version: 8.0 (stable)

Line 43 of appinfo/app.php contains string

    $url = OC::$server->getRequest()->server['REQUEST_URI'];

which causes spurious "Undefined index: REQUEST_URI" when Cron tasks are run. Proposed solution: replace the above with

    $_request = OC::$server->getRequest();
    $url = isset($_request->server['REQUEST_URI']) ? $_request->server['REQUEST_URI'] : "";

with possible handling this case in better manner (instead of returning empty string).

**Comment by RealRancor** [comment]
Dup of: https://github.com/owncloud/calendar/issues/714
