### ISSUE TITLE
php l10n themes strings are not fetched by the app

### ISSUE THREAD

**Issue by tcitworld** [owncloud/calendar#716]
When trying to extend the existing translations from this app with a custom theme [1], it seems the .json files are not fetched.
I did a `var_dump()` inside [`core`](https://github.com/owncloud/core/blob/master/lib/private/L10N/Factory.php#L300) to see what translation files are fetched when loading the app and there were only :
- lib
- core
- apps/files
- apps/federatedfilesharing
- apps/contacts

The .js translation file is correctly fetched though, since inline js translations work.

This may be a _core_ issue.

[1] In order to demo public-sharing with French localization.

**Comment by tcitworld** [comment]
What I did to try to translate the app through a new theme.
- Create a new theme folder and add it to `config/config.php`
- Create `<themename>/calendar/l10n/fr.json` and  `<themename>/calendar/l10n/fr.js`

`fr.json` content : 

```
{
    "translations": {
        "Share link": "Partager par lien public",
        "Public access": "Accès public",
        "Email link to person" : "Envoyer le lien par courriel",
        "CalDAV address for clients": "Adresse CalDAV pour les clients",
        "WebDAV address for subscriptions": "Adresse WebDAV pour les abonnements",
        "Iframe to integrate": "Code pour intégrer une iframe",
        "Publish URL": "URL publique",
        "Skip simple event editor": "Passer l'éditeur simplifié d'événements"
    },
    "pluralForm" :"nplurals=2; plural=(n > 1);"
}
```

Can someone confirm this ?

**Comment by georgehrke** [comment]
I'm not even sure if extending the translations via themes is supported.

Is this documented somewhere?

**Comment by tcitworld** [comment]
Here : https://doc.owncloud.org/server/9.0/developer_manual/core/theming.html

**Comment by georgehrke** [comment]
Hm, I have really no clue.
Anyway, I don't think this is an issue in the calendar.
Can you please reopen in core? :)
