### ISSUE TITLE
OC 8.0.0. Calendar: PUT does not return etag

### ISSUE THREAD

**Issue by B-Aerts** [owncloud/calendar#716]
### Steps to reproduce
1. install OC locally
2. create user (admin or regular), acivate calendar app
3. execute "raw" HTTP CalDAV compliant PUT statement for a VEVENT in PHP through Curl :
      curl_setopt($ch, CURLOPT_URL, $theUrl) ;

      curl_setopt($ch, CURLOPT_USERAGENT, "PHP cURL Client" ) ;
      curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY ) ;
      curl_setopt($ch, CURLOPT_USERPWD, $theUsr . ":" . $thePwd ) ;
      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $theMethod); 
      curl_setopt($ch, CURLOPT_HTTPHEADER, $curlHeaders ) ; // string array "header: value"
      curl_setopt($ch, CURLOPT_TIMEOUT, 15 ) ;
      curl_setopt($ch, CURLOPT_VERBOSE, true ) ;
      curl_setopt($ch, CURLOPT_HEADER, true ) ; 
      curl_setopt($ch, CURLINFO_HEADER_OUT, true ); 
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true ) ; 
      curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true ) ; 
      curl_setopt($ch, CURLOPT_MAXREDIRS, 5) ;  
      curl_setopt($ch, CURLOPT_POSTFIELDS, $theBody) ; // iCalendar string

HTTP-Request:

PUT /owncloud/remote.php/caldav/calendars/aladdin/personal/bertaerts.ics HTTP/1.1
Authorization: Basic ####################=
User-Agent: PHP cURL Client
Host: localhost
Accept: */*
Content-type: text/calendar; charset=utf-8
If-none-match: "*"
Content-Length: 463

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//kigkonsult.se//NONSGML kigkonsult.se iCalcreator 2.10.23//
METHOD:PUBLISH
X-WR-CALNAME:Calendar Sample
X-WR-CALDESC:Calendar Description
X-WR-RELCALID:X4YJM-U50G9-GVVP5-CMYPC
X-WR-TIMEZONE:Europe/Brussels
BEGIN:VEVENT
UID:aladdin@1A50H-LFFQD-5CDLR-N9NIZ
DTSTAMP:20150212T202923Z
DTSTART:20150212T212500
DTEND:20150212T232500
SUMMARY:generated iCal UID=aladdin@1A50H-LFFQD-5CDLR-N9NIZ
END:VEVENT
END:VCALENDAR

HTTP-Response:

HTTP/1.1 401 Unauthorized
Date: Thu, 12 Feb 2015 20:29:23 GMT
Server: Apache/2.2.26 (Unix) DAV/2 PHP/5.4.30 mod_ssl/2.2.26 OpenSSL/0.9.8za
X-Powered-By: PHP/5.4.30
Set-Cookie: ocumdd8rlefd=a20fd340643ccab61ce23cdaf0f5e385; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
WWW-Authenticate: Basic realm="ownCloud"
Content-Length: 292
Content-Type: application/xml; charset=utf-8

HTTP/1.1 201 Created
Date: Thu, 12 Feb 2015 20:29:23 GMT
Server: Apache/2.2.26 (Unix) DAV/2 PHP/5.4.30 mod_ssl/2.2.26 OpenSSL/0.9.8za
X-Powered-By: PHP/5.4.30
Set-Cookie: ocumdd8rlefd=d7ebc9f4b02d2c1173ca3ea47797dc70; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
Set-Cookie: ocumdd8rlefd=45c12b2e8fe465eb7f7a6c36a2e5be24; path=/owncloud; HttpOnly
Content-Length: 0
Content-Type: text/html

### Expected behaviour
I'd expect the response headers to contain an "Etag: ....." line, used to check against unnoticed updates later on.
SabreDAV by default returns an Etag (tried the same against a Fruux server, and confirmed in SabreDAV mailing list)

### Actual behaviour
No Etag returned (though GET does return an etag ...)

### Server configuration
**Operating system**: Mac OS X 10.9.5

**Web server:** : Apache 2

**Database:** Sqlite

**PHP version:** PHP 5.4.30

**ownCloud version:** (see ownCloud admin page) OwnCloud 8.0.0. - but also with OC 7.0.4

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Calendar

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocumdd8rlefd',
  'passwordsalt' => '###################',
  'secret' => '##############################',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/Users/######/Documents/htdocs/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
);

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

### Client configuration
**Browser:** FireFox 35.0.1

**Operating system:** Mac OS X

#### ownCloud log (data/owncloud.log)
{"reqId":"b3f44eb38ed1b7eb5ca6cc81b7a9188b","remoteAddr":"::1","app":"PHP","message":"touch(): Unable to create file \/Users\/#####\/Documents\/htdocs\/owncloud\/data\/owncloud.log because No such file or directory at \/Users\/#####\/Documents\/htdocs\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-02-10T20:37:51+00:00"}

**Comment by georgehrke** [comment]
> SabreDAV by default returns an Etag (tried the same against a Fruux server, and confirmed in SabreDAV mailing list)

In newer releases. We are using an older SabreDav version.
ownCloud 8.1 will probably release the most recent sabredav version.

closing as upstream issue.
