### ISSUE TITLE
CalDAV syncing error 500

### ISSUE THREAD

**Issue by z707** [owncloud/calendar#718]
After upgrade OC to 8 Caldav Sync on my android phone getting error 500.
I try recreate my connection on phone and getting "Invalid server answer".
In owncloud log this:
```
{"reqId":"40031c1797709ff0c6e6e22a83c2dcba","remoteAddr":"192.168.1.1","app":"PHP","message":"Class 'OCA\\Contacts\\App' not found at \/var\/www\/owncloud\/apps\/calendar\/lib\/sabre\/backend.php#63","level":3,"time":"2015-02-15T07:41:07+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/z707\/"}
```
I use port number in URL OC (https://myhost:8083).

**Comment by RealRancor** [comment]
Hi,

have you updated the calendar and contacts app to the ones for OC8? The old ones from OC7 are incompatible.

**Comment by RealRancor** [comment]
Yes, you're running the old version. The backend.php from OC7 is not shipped anymore in OC8:

https://github.com/owncloud/calendar/tree/v8.0.0/lib/share

**Comment by z707** [comment]
Yes, I updated calendar app from github v8.0.0.tar.gz.
In admin interface shown Calendar 0.6.4.

**Comment by RealRancor** [comment]
As the error message contains references to the contacts app have you also upgraded this?

**Comment by z707** [comment]
I have not installed the app Contacts.

**Comment by RealRancor** [comment]
Then we have the reason why this fails. Seems you still have enabled the contacts app in your database but not the file in place on your filesystem:

https://github.com/owncloud/calendar/blob/master/lib/sabre/backend.php#L61

Try to disable the contacts app with the occ command line (see documentation).

**Comment by z707** [comment]
>Seems you still have enabled the contacts app in your database but not the file in place on your filesystem
Yes, before update the contacts app was enabled.
I disabled in command line the contacts app and got sync calendars with phone, thanks.
In admin interface button "Disable" equivalent this action?
