### ISSUE TITLE
Default timezone of calendar is 'abidjan'

### ISSUE THREAD

**Issue by dragetd** [owncloud/calendar#719]
The default timezone on my new OC 8.0 installation is 'Abidjan', eventho my default timezone for PHP is set to 'Europe/Berlin'

### Server configuration
**Operating system**:
Debian Wheezy
(packages up-to-date 14.02.2015)

**Web server:**
apache2.2

**Database:**
postgresql

**PHP version:**
PHP Version 5.4.36-0+deb7u3

**ownCloud version:** (see ownCloud admin page)
8.0

**Updated from an older ownCloud or fresh install:**
Saw same behavoir on a fresh install and updated installation.

**Browser:**
Firefox

**Comment by RealRancor** [comment]
Hi,

the timezone should be detected automatically based on your browser:

http://doc.owncloud.org/server/8.0/user_manual/pim/calendar.html#calendar-app-faq

Have you disabled this detection?

**Comment by dragetd** [comment]
Yes, I do block querying the location. So the only reason for the calendar app to request the location is to detect the timezone? Isn't there a more elegant way? Or a fallback… I could imagine a lot of people generally block location requests when they see no real reason for this.

**Comment by georgehrke** [comment]
abidjan ain't the default timezone, it just displays the first in the list if none is selected

**Comment by georgehrke** [comment]
please test https://github.com/owncloud/calendar/commit/0dc4cebc4763493d9a4f36a5308489890e59c685

**Comment by dragetd** [comment]
Tested the change.

It does set a default timezone and gives at least some sort of meaningfull default instead of a wrongly displayed timezone.

But date_default_timezone_get() returns UTC if no timezone is set in the ini file according to the documentation ( http://php.net/manual/de/function.date-default-timezone-get.php ). And infact, my default timezone for new users are now UTC. Not sure is this is a good choice / what implications this will have.

http://php.net/manual/en/function.date-default-timezone-get.php

**Comment by georgehrke** [comment]
But UTC was the default all the time, if no timezone was set. So now it's displayed correctly
