### ISSUE TITLE
information about calendar owner

### ISSUE THREAD

**Issue by JacekZ** [owncloud/calendar#72]
Is there possibility to  add information about who share specific calendar with us?? I see other users's calendar, but I cant notice information who is owner of that calendar.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo

**Comment by lebherz** [comment]
Sorry... this plugin is too buggy.
Now I try the pluscalendar and all stuff worked here. 
try this: https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560
