### ISSUE TITLE
Caldav after upgrade to OC8 not working, returns http error 500 (internal server error)

### ISSUE THREAD

**Issue by mscheutz** [owncloud/calendar#720]
After upgrade to OC8 from OC7 the caldav links stopped working and any attempt to connect to OC8 result in an internal server error with code 500.  Creating a new user (as some have suggested) does not work.  Nor is the problem a problem of case sensitive URLs, user names or passwords. Different variants of the URL did not work either.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
can't reproduce, will close as long as no more infos are provided

**Comment by mscheutz** [comment]
OK, will do, but you'll need to reopen the bug report, closing it right
away does not help

On Mon, 2015-02-16 at 07:01 -0800, Georg Ehrke wrote:
> please use the issue template as described in our contributing
> guidelines
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

-- 
Matthias Scheutz, Ph.D. Ph.D.
-------------------------------------------------
Professor, Cognitive Science and Computer Science
Bernard M. Gordon Senior Faculty Fellow
Director, Human-Robot Interaction Laboratory
Department of Computer Science
Tufts University, Medford, MA 02155, USA

**Comment by mscheutz** [comment]
### Steps to reproduce
1. Upgrade from OC7 to OC8
2. Try to add a caldav entry on any device
3. Received error, and in general, no connection to the owncloud calendar possible

### Expected behaviour

The new calendar entry should show up

### Actual behaviour

Http error message 500 (Internal server error)

### Server configuration

RHEL 6

**Web server:**

httpd-2.2.15-39.el6.x86_64

**Database:**

sqlite-3.6.20-1.el6.x86_64

**PHP version:**

php55w-5.5.21-1.w6.x86_64

**ownCloud version:** (see ownCloud admin page)

ownCloud 8.0 (stable) 

**Updated from an older ownCloud or fresh install:**

Updated from OC 7

**List of activated apps:**

Activity 1.2.0, Calendar 0.6.4, Deleted Files 0.6.2, Documents 0.9.0, First Run Wizard 1.1, PDF Viewer 0.7, Pictures 0.6.0, Share Files 0.6.0, Text Editor 0.4, Updater 0.4, Versions 1.0.5, Video Viewer 0.1.3 

**The content of config/config.php:**

<?php $CONFIG = array (
  'instanceid' => 'oc705da2195f',
  'datadirectory' => '/home/htdocs/ocdata',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '2',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxx',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' =>
        ' --headless --nologo --nofirststartwizard --invisible --norestore '.
        '-convert-to pdf -outdir ',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

### Client configuration
**Browser:**

Evolution (evolution-3.12.10-1.fc21.x86_64), but problems are also with Mac included Calendar

**Operating system:**

Fedora 21

### Logs
#### Web server error log
...
IP1  - User1 [16/Feb/2015:16:38:04 -0500] "PROPFIND /owncloud/remote.php/webdav HTTP/1.1" 207 5523
IP1 - User1 [16/Feb/2015:16:38:05 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 519
IP1 - User1 [16/Feb/2015:16:38:35 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 3355
IP1 - User1 [16/Feb/2015:16:38:35 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 519
IP1 - User1 [16/Feb/2015:16:39:05 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 3355
IP1 - User1 [16/Feb/2015:16:39:06 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 519
IP1 - User1 [16/Feb/2015:16:39:35 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 3355
IP1 - User1 [16/Feb/2015:16:39:36 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 519
IP2 - - [16/Feb/2015:16:39:57 -0500] "PROPFIND /owncloud/remote.php/caldav/principals/User2/ HTTP/1.1"$
IP2 - User2 [16/Feb/2015:16:39:57 -0500] "PROPFIND /owncloud/remote.php/caldav/principals/User2/ HTTP$
IP2 - User2 [16/Feb/2015:16:39:58 -0500] "OPTIONS /owncloud/remote.php/caldav/principals/User2 HTTP/$
IP2 - - [16/Feb/2015:16:39:58 -0500] "REPORT /owncloud/remote.php/caldav/principals/ HTTP/1.1" 401 292
IP2 - User2 [16/Feb/2015:16:39:58 -0500] "REPORT /owncloud/remote.php/caldav/principals/ HTTP/1.1" 200$
IP2 - - [16/Feb/2015:16:39:59 -0500] "PROPFIND /owncloud/remote.php/caldav/calendars/User2/ HTTP/1.1" $
IP2 - User2 [16/Feb/2015:16:39:59 -0500] "PROPFIND /owncloud/remote.php/caldav/calendars/User2/ HTTP/$
IP2 - User2 [16/Feb/2015:16:39:59 -0500] "PROPFIND /owncloud/remote.php/caldav/principals/User2/ HTTP$
IP2 - User2 [16/Feb/2015:16:40:00 -0500] "PROPFIND /owncloud/remote.php/caldav/principals/ HTTP/1.1" 2$
IP2 - - [16/Feb/2015:16:40:00 -0500] "PROPFIND / HTTP/1.1" 405 320
IP2 - - [16/Feb/2015:16:40:00 -0500] "PROPFIND /principals/ HTTP/1.1" 405 321
IP1 - User1 [16/Feb/2015:16:40:05 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 3355
IP1 - User1 [16/Feb/2015:16:40:07 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 519
...

#### ownCloud log (data/owncloud.log)
...
{"reqId":"07da139b63bc8bc92beee763eb03d22e","remoteAddr":"IP2","app":"PHP","message":"Class 'OCA\\Contacts\\App' not found at \/var\/www\/html\/owncloud\/apps\/calendar\/lib\/sabre\/backend.php#63","level":3,"time":"2015-02-16T12:48:01+00:00"}
{"reqId":"61b6b10a95e767a8edcd7d65e3ba21db","remoteAddr":"IP1","app":"PHP","message":"Class 'OCA\\Contacts\\App' not found at \/var\/www\/html\/owncloud\/apps\/calendar\/lib\/sabre\/backend.php#63","level":3,"time":"2015-02-16T12:58:47+00:00"}
ownCloud 8.0 (stable) 
...
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
please see https://github.com/owncloud/calendar/issues/718#issuecomment-74427067

**Comment by mscheutz** [comment]
Thanks Georg, that worked (i.e., I enabled the Contacts app in the web interface) and now the calendar works again.
