### ISSUE TITLE
Disabling a shared calendar disables it for all accounts

### ISSUE THREAD

**Issue by maethor** [owncloud/calendar#721]
### Steps to reproduce

1. Share a calendar with user "foo"
2. Disable it (clicking on the colored square)
3. Logout and login as "foo"
4. The calendar is disabled, and there is no way to display it…

### Expected behaviour

The user "foo" should see the calendar, and should be able to enable/disable it for himself.

### Actual behaviour

The calendar is disabled, and there is no way to display it except waiting for the owner to re-enable it.

### Server configuration
**Operating system**:

Debian Wheezy

**Web server:**

NGinX

**Database:**

Postgres

**PHP version:**

5.4

**ownCloud version:** (see ownCloud admin page)

Bug reproduced on 7.0.4.2 and 8.0.

**Updated from an older ownCloud or fresh install:**

Updated from Oc6.

**List of activated apps:**

Only basic apps: contacts, calendar, photo, documents.

**Comment by georgehrke** [comment]
Does the following patch fix the issue for you?

https://github.com/owncloud/calendar/commit/3559ebf0c6d1178eb59cf11b5496bcf3002cff16

**Comment by maethor** [comment]
At least on Oc8, it fixes the major bug, yes. When the owner disables the calendar, it is no more disabled for the users it is shared with. I can't test on Oc7 right now.

With that said, the second part of the bug may be a feature request. A user should be able to disable a calendar even if he is not the owner. Hiding calendar is an important feature to make space and focus an the important at the moment. Do you think I should write another ticket ?

Thanks.

**Comment by georgehrke** [comment]
> Do you think I should write another ticket ?

please don't. there already is one.

**Comment by maethor** [comment]
Ok. Thanks.

**Comment by jas4711** [comment]
I just ran into the second part of this bug -- not being able to disable a calendar that have been shared with me.  Any ideas on how to resolve that?  Thanks!

**Comment by nblock** [comment]
I just came across the second part too. It would be great if shared calendars could be disabled/enabled at wish.

**Comment by ikarus13** [comment]
Do you think I should write another ticket ?
please don't. there already is one.

Where is this ticket?, can't find it.
Is there a workaround to hide a shared calender?
If not, this function is like spam :-(

**Comment by georgehrke** [comment]
> Where is this ticket?, can't find it.

https://github.com/owncloud/calendar/issues/21

> Is there a workaround to hide a shared calendar?

Nope
