### ISSUE TITLE
LDAP users: UUID instead of displayName on Calendar app

### ISSUE THREAD

**Issue by stepansantalov** [owncloud/calendar#722]
### Steps to reproduce
1. Enable LDAP auth
2. Share calendar, begin to type username to share with, see the UUIDs instead of displayName.
   Btw the search is made by displayName.
   Click share.
3. See the UUIDs in properties of calendar.
### Expected behaviour

displayNames from LDAP catalog should be displayed .
### Actual behaviour

The UUIDs are displayed.
### Server configuration

I believe it does not matters:
Debian jessie 8.1
Apache/2.4.10 (Debian)
PostgreSQL 9.4.8
PHP 5.6.20-0+deb8u1

reprodices on 
ownCloud 9.1.0 (stable), 
nextcloud-10.0.0

I believe it is just a wrong variable was used. The fix must be pretty easy.

**Comment by georgehrke** [comment]
known issue, please use the search first ;)

**Comment by stepansantalov** [comment]
I did, but no solution found. Please show me, if if there is one.

**Comment by georgehrke** [comment]
<img width="1039" alt="search results safari technology preview today at 6 02 32 pm" src="https://cloud.githubusercontent.com/assets/1250540/18058028/c7a9748e-6e12-11e6-8a84-ac7d4bbaf481.png">
😉

**Comment by stepansantalov** [comment]
I've seen this one. Was thinking i've missed something. Thank you.
