### ISSUE TITLE
Disable reminders on shares calendars

### ISSUE THREAD

**Issue by escoand** [owncloud/calendar#724]
Expected behaviour

It would be nice to have the possibility to en-/disable reminders on shared calendars.
I switched all my calendar data to nextcloud but now my wife is complaining about getting Al's the notification from my calendar. The other way around is also annoying.

Actual behaviour

There is no way to disabled the reminders of shared calendars.

Server configuration

Server version: 9.0.53
Calendar version: 1.3.2

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/635
