### ISSUE TITLE
Page not redirected properly on Calendar 1.3.3

### ISSUE THREAD

**Issue by yannlossouarn** [owncloud/calendar#725]
### Steps to reproduce
1. Use Owncloud with Nginx
2. Upgrade Calendar to 1.3.3
3. Click on the Agenda item in Owncloud main menu
### Expected behaviour

Calendar app should display
### Actual behaviour

After a few seconds, the browser shows an error message telling the page is not properly redirected. Nginx logs show a sequence of 303 Redirect like a  ping-pong:
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/
GET /login?redirect_url=%252Fapps%252Fcalendar%252F
GET /apps/calendar/

Requesting /index.php/apps/calendar/ instead of /apps/calendar/ works. I feel there is something about URL rewriting, but I do not know what 
### Server configuration

**Operating system**:
OSMC (~Rasbian)

**Web server:**
Nginx 1.6.2
Conf is exactly the same as the "webroot" one here, except that I had to comment out the "fastcgi_request_buffering off;" line, because it caused an error on my Nginx version:
https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html

**Database:**
MySQL 5.5.50

**PHP version:**
PHP-FPM 5.6.24

**Server version:**
9.1.0

**Calendar version:** (see the apps page)
1.3.3

**Updated from an older installed version or fresh install:**
Updated, 
**Signing status (ownCloud/Nextcloud 9.0 and above):**
Owncloud

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**Comment by georgehrke** [comment]
That's either a bug in your nginx conf or in the ownCloud server.
Please report a bug in http://github.com/owncloud/core/issues
