### ISSUE TITLE
it can not be seen the create/change/edit  checkbox

### ISSUE THREAD

**Issue by rapid01** [owncloud/calendar#726]
### Steps to reproduce
1. go to Calendar
2. click share button
3. select: can edit 
4. you can`t see  create/change/edit checkbox 
### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/21352245/18142350/c4cdcece-6f82-11e6-8332-dc549e1b1b84.png)
### Actual behaviour

I can see the  create/change/edit  checkbox
### Server configuration

CentOS7

**Web server:**
Apache
**Database:*
**PHP version:**
php-5.4.16-36.1.el7_2.1.x86_64
**Server version:** (see your admin page)
ownCloud 9.1.0 (stable)
**Calendar version:** (see the apps page)
Calendar  1.3.3
**Updated from an older installed version or fresh install:**
Update
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: true
  - comments: 0.3.0
  - dav: 0.2.5
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ojsxc: 3.0.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_external
  - mail
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

```


Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**
chrome, edge
**Operating system:**
linux , windows 10
**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### Log file (data/owncloud.log)

```
Insert your ownCloud.log file here
```

**Comment by georgehrke** [comment]
these three options were removed in favor of a simple can edit

**Comment by georgehrke** [comment]
The implementation of ownCloud 9 and above relies on the official caldav sharing standard. That standard does not support can create and can delete

**Comment by rapid01** [comment]
Thanks for your fast answer.
