### ISSUE TITLE
disable notifications for shared calenders in iOS and Thunderbird lightning

### ISSUE THREAD

**Issue by JB1985** [owncloud/calendar#726]
It seems to be a very old bug in sharing calendars.

Here is a forums thread that explain the problem.
-> http://forum.owncloud.org/viewtopic.php?f=26&t=19409

I have no way to disable remember notifications from other users, when you work with group permissions.

I only can disable the calander from all users, but that cant be the solution. 

This is in iOS and Lightning Thunderbird.

Using Owncloud8.

**Comment by georgehrke** [comment]
duplicate

**Comment by georgehrke** [comment]
please help testing https://github.com/owncloud/calendar/pull/668

**Comment by georgehrke** [comment]
> It seems to be a very old bug in sharing calendars.

Not actually a bug in sharing. Sharing is supposed not to modify the data. ownCloud doesn't trigger reminders, those reminders are triggered by the clients (in your case iOS and lightning). Those clients should have a feature to disable reminders on a per-calendar basis. So please send a feature request there.

**Comment by JB1985** [comment]
I will test #668
