### ISSUE TITLE
Easy national holidays calendar subscription

### ISSUE THREAD

**Issue by matlag** [owncloud/calendar#728]
There is currently no "easy" way to add national holidays for lambda users. One has to find a calendar online and then import it.

It would be nice if that was just the matter of ticking a box to get the local national holidays.
### Expected behaviour

A simple tick box adds or removes the national holidays calendar matching the user's local zone.
### Actual behaviour

Users have to download and manually import national holidays calendars.

**Comment by MariusBluem** [comment]
Thank you for your report. I think it is a good idea to do this, but it is definitely not an issue over here (the calendar-frontend app) ... It is an issue in the CalDAV Server (which holds the calendars) ... Can I ask you for opening an issue in the core/server?

https://github.com/nextcloud/server
https://github.com/owncloud/core

Thanks! Please research for existing issues there. I am currently in train, so I am not able to do too many research on that 😅
