### ISSUE TITLE
The supplied iCalendar datetime value is incorrect

### ISSUE THREAD

**Issue by alexara** [owncloud/calendar#729]
### Steps to reproduce
1. Download ics file: 

More example calendars can be found here:

1. Remove the txt postfix
2. Import it to an existing calendar of your OC/NC
### Expected behaviour

Import without any issues as Thunderbird Lightning 47.0 does it and display the appointments correctly.
### Actual behaviour

A warning (!)  occurs beside the upload button which says:
"The file contains objects which are not compatible."

The calendar is not shown. Appointments of another calendar were put to Tuesday instead of Monday.  
The log states: `The supplied iCalendar datetime value is incorrect`
### Question

Why is the error message only found in the internal OC server log and not shown to the user at the front end?
### Further notes

Uploading and importing works with other calendars, eg. with those I created on Nextcloud,  downloaded and reimported to a new calendar.                                                                                       
### Server configuration

**Operating system**: Debian 8

**Web server:** NginX

**Database:** MySQL 

**PHP version:** 5.6.24

**Server version:** NC 10

**Calendar version:** 1.3.3

**Updated from an older installed version or fresh install:** Update

**Signing status (ownCloud/Nextcloud 9.0 and above):** Signed
### File integrity check

All good.
### Config.php (censored)

`<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'cache_path' => '',
  'datadirectory' => '',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/nextcloud',
  'updater.release.channel' => 'stable',
);
`
### Client configuration

**Browser:** FF48.0

**Operating system:** Arch

**CalDAV-clients:** Thunderbird Lightning 47.0
#### Web server error log

```
 "PUT /nextcloud/remote.php/dav/calendars/user/calendar-name/ownCloud-aa3213fmkuq15f9kory58.ics HTTP/1.1" 500 246 "-" "  
```
#### Log file (data/owncloud.log)

```
{"reqId":"a0TH6lNjevBvOgiKmtKM","remoteAddr":"108.19.80.100","app":"webdav","message":"Exception: {\"Message\":\"The supplied iCalendar datetime value is incorrect: --T::\",\"Exception\":\"LogicException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/DateTimeParser.php(188): Sabre\\\\VObject\\\\DateTimeParser::parseDateTime('--T::', Object(DateTimeZone))\\n#1 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Property\\\/ICalendar\\\/DateTime.php(172): Sabre\\\\VObject\\\\DateTimeParser::parse('--T::', Object(DateTimeZone))\\n#2 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Recur\\\/EventIterator.php(154): Sabre\\\\VObject\\\\Property\\\\ICalendar\\\\DateTime->getDateTimes(Object(DateTimeZone))\\n#3 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1354): Sabre\\\\VObject\\\\Recur\\\\EventIterator->__construct(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar), '278011420260')\\n#4 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(617): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getDenormalizedData('BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(199): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->createCalendarObject('25', 'ownCloud-aa3213...', 'BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): Sabre\\\\CalDAV\\\\Calendar->createFile('ownCloud-aa3213...', 'BEGIN:VCALENDAR...')\\n#7 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('calendars\\\/user\\\/...', Resource id #88, NULL)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#11 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(184): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/domai...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.tld\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/DateTimeParser.php\",\"Line\":40,\"User\":\"user\"}","level":4,"time":"2016-09-02T09:36:18+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/dav\/calendars\/user\/calendar\/ownCloud-aa3213fmkuq15f9kory58.ics","user":"user"}
```

**Comment by georgehrke** [comment]
I'm almost certainly sure that it's related to the empty `EXDATE`: `EXDATE;TZID=Europe/Berlin:` ...
I don't think that's valid.

**Comment by DeepDiver1975** [comment]
invalid data - nothing we can do -> close

**Comment by dketterer** [comment]
I have the same issue.
I validated my ics File against this validator: https://icalendar.org/validator.html

Could you please reference the standard you have implemented or used in a library?

**Comment by Julian1998** [comment]
@dketterer I guess we are using RFC 5545

**Comment by DeepDiver1975** [comment]
@dketterer please share your ics file - but please remove personal information before posting publicly in here.
