### ISSUE TITLE
Month name is shown as "undefined"

### ISSUE THREAD

**Issue by vedranmiletic** [owncloud/calendar#730]
### Steps to reproduce
1. Open the Calendar app.
2. Use the Month view.
### Expected behaviour

Month name should be displayed correctly, e.g. "September 2016".
### Actual behaviour

Month name is shown as "undefined 2016".
### Server configuration

**Operating system:**
Fedora 25

**Web server:**
Apache 2.4.23

**Database:**
PostgreSQL 9.5.4

**PHP version:**
7.0.10

**Server version:** (see your admin page)
Nextcloud 10.0 (stable)

**Calendar version:** (see the apps page)
Calendar 1.3.3

**Updated from an older installed version or fresh install:**
Updated from Nextcloud 9.0.53

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- bookmarks: 0.9.0
- calendar: 1.3.3
- comments: 1.0.0
- contacts: 1.3.1.0
- dav: 1.0.0
- documents: 0.13.1
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- serverinfo: 1.1.1
- survey_client: 0.1.5
- systemtags: 1.0.2
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- workflowengine: 1.0.1
  Disabled:
- encryption
- external
- files_accesscontrol
- files_automatedtagging
- files_external
- files_retention
- user_external
- user_ldap
- user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocrme1da2m3y",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "\/srv\/nextcloud\/data",
        "version": "9.1.0.16",
        "dbtype": "pgsql",
        "dbname": "**_REMOVED SENSITIVE VALUE**_",
        "dbhost": "**_REMOVED SENSITIVE VALUE**_",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "overwrite.cli.url": "**_REMOVED SENSITIVE VALUE**_",
        "htaccess.RewriteBase": "\/"
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:**
Firefox 48.0.1

**Operating system:**
Linux

**CalDAV-clients:**
#### Web server error log

Does not show anything related
#### Log file (data/owncloud.log)

Does not show anything related
#### Browser log

JQMIGRATE: Migrate is installed, version 1.4.0jquery-migrate.min.js:2:542

**Comment by tcitworld** [comment]
Is the user's language correctly set to English ?

**Comment by vedranmiletic** [comment]
No, it's set to Croatian. Names of the days of the week are translated correctly.

Is translation missing? Shouldn't the English string be shown if the translation is missing?

**Comment by tcitworld** [comment]
It should indeed be shown. Can you change the user's language to see if English (or an other language) works properly ?

**Comment by vedranmiletic** [comment]
After switching to English, the correct month name is shown.

**Comment by georgehrke** [comment]
@vedranmiletic Does this apply to all month names when the language is set to Croatian or only september?

**Comment by vedranmiletic** [comment]
All months.

**Comment by georgehrke** [comment]
Reproducible.
For the record: the language is called "hrvatski"

**Comment by georgehrke** [comment]
I deem this an issue in moment.js
Reported upstream: https://github.com/moment/moment/issues/3434

**Comment by georgehrke** [comment]
This is an issue in Nextcloud. The used version of moment.js needs to be updated.
I will take care. :)

**Comment by georgehrke** [comment]
I created a pull request in the nextcloud server to fix this issue: https://github.com/nextcloud/server/pull/1405

**Comment by vedranmiletic** [comment]
Thanks!
