### ISSUE TITLE
Owbcloud/Nextcloud and contacts (iOS 5.1.1)

### ISSUE THREAD

**Issue by GH16** [owncloud/calendar#731]
I have an iPad1 with the last iOS version (5.1.1) installed.

I am not able to add my Owncloud/Nextcloud (https connection) contacts (Contacts 1.3.1.0) with the iOS contact App.

The issue is known for Owncloud and Nextcloud versions.

I know that there could be an workaround (use HTTP instead of HTTPS and use the port 443) but I don't trust the workaround and I want to have a HTTPS connection.

It would be great if I can use my Owncloud/Nextcloud contacts also with my iPad1 (iOS 5.1.1)

Thank you in advance for your support and best regards
GH16

**Comment by georgehrke** [comment]
wrong repo :wink:

**Comment by georgehrke** [comment]
and please use the issue template when reporting this in the contacts repo

**Comment by georgehrke** [comment]
Actually, this is an issue in the carddav server. Please report it in https://github.com/owncloud/core
