### ISSUE TITLE
State of the rework branch

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#731]
I wonder what the state of Calendar is with the ominous rework branch … how much more work do you want to put into it before merging it / before it becomes unmergeable?

There hasn’t really been much work done on it and currently contributors can’t really join cause it’s not sure if master will be replaced, or if rework will ever see the light of day.

Please make a clear stance on this and work towards it @georgehrke @raghunayyar 

cc @DeepDiver1975

**Comment by georgehrke** [comment]
We are currently finishing implementing stuff that's on master. Our current milestone is end of march.

**Comment by georgehrke** [comment]
> There hasn’t really been much work done on it.

Not much work done on what exactly?

**Comment by jancborchardt** [comment]
Ok, so I didn’t see https://github.com/owncloud/calendar/issues/558 – would be good to put that in the readme.
