### ISSUE TITLE
Calendar keeps on "searchin" on android web view

### ISSUE THREAD

**Issue by cerisara** [owncloud/calendar#732]
When accessing the calendar on any android browser, it's never shown, because the browser kees on "looking for" calendars, and seems like it never finds any.
Otherwise, everything works fine on ubuntu, through caldav...

### Steps to reproduce
1. Fresh install of owncloud 9.1 on ubuntu 14 server
2. Create a calendar for user X on the server
3. On Android, login as the same user and browse to the calendar
### Expected behaviour

Should be able to view the user calendar
### Actual behaviour

The user calendar is never shown on the android browser: Just below the "New calendar" button, the small turning circle that indicates a "download in progress" keeps on turning and never stops.

I tried on two different android phones, both with the stock browser + the chrome browser + the lightning browser: always the same behavior.

Otherwise, the calendar is synced via caldav fine. It's also visible fine on ubuntu browser.

I've looked at the javascript console on android, but nothing special.

**Comment by tcitworld** [comment]
Can you test through Firefox on android to check if it's a browser issue ?

**Comment by cerisara** [comment]
I don't know for firefox, but I've tested on a third phoen with android 5.1: in that case, the stock browser did not even connect at all (CSRV error or something, don't remember), but the chrome browser just worked, even for the calendar !

For the record, the two previous tested phones were running android 4.4.2. I'll try on one of these phones to install firefox and test.

Thanks !

**Comment by georgehrke** [comment]
Right now we only support the latest version of Chrome/Chromium, Firefox and Safari.
The stock android browser is kind of not supported ...
I don't even have an Android device I could use for testing and QA

Android 4.4 doesn't even have support for Promises ...
http://caniuse.com/#search=Promise
Supporting it would be a nightmare :/

**Comment by tcitworld** [comment]
@georgehrke OP tested on Chrome Android Browser though.

**Comment by georgehrke** [comment]
He said that chrome worked in his last comment though:

> did not even connect at all (CSRV error or something, don't remember), but the chrome browser just worked, even for the calendar !

**Comment by cerisara** [comment]
yes, chrome worked on android 5.1 but not on android 4.2.2

**Comment by tcitworld** [comment]
Yup, we need the Chrome version on android 4.2.

**Comment by cerisara** [comment]
on android 4.4, chrome is v 34.0.1847.114

**Comment by georgehrke** [comment]
Okay, I guess we can try looking into chrome 34 to see what causes the error.
generally speaking I would just recommend to use the DavDroid app in combination with the stock android calendar.
The calendar app has not been optimized for mobile usage yet.

**Comment by cerisara** [comment]
OK, the caldav sync is fine for me !
Thanks for the nice calendar app !

**Comment by cerisara** [comment]
Finally, I also tried with Firefox on Android 4.2.2, and the calendar app seems to work fine but... that's the general owncloud web view that has issues, e.g., the File pop-down menu does not work, so it's actually very hard to access the calendar. All in all, web access to owncloud looks like very problematic on Android 4.2.2, and I now think it's probably not worth the effort: may be better to try and developing an app, plus syncing of course...

I'm fine with closing the issue...
Thanks !
