### ISSUE TITLE
Can't share any calendar after upgrade 7.0.4 to 8.0

### ISSUE THREAD

**Issue by papezg** [owncloud/calendar#732]
After upgrading owncloud to 8.0 from 7.0.4 none of the user can't share calendars or events. Old already shared events and calendar remains.

**Comment by papezg** [comment]
Log:
Error	core	App directory already exists	2015-02-19T10:24:38+00:00
Warning	OCP\Share	Sharing backend OC_Share_Backend_Event not registered, OC_Share_Backend_Event is already registered for event	2015-02-19T10:24:04+00:00
Warning	OCP\Share	Sharing backend OC_Share_Backend_Calendar not registered, OC_Share_Backend_Calendar is already registered for calendar	2015-02-19T10:24:04+00:00

**Comment by RealRancor** [comment]
Have you deleted all files and folders except /data/ and /config/ before the upgrade?

**Comment by georgehrke** [comment]
Additional to @RealRancor's question: Did you install Calendar 8.0 from the apps management or are you still using an old version?

**Comment by papezg** [comment]
Didn't delete any folders before upgrade. Installed Calendar 8.0 from apps using version 0.6.4.

**Comment by georgehrke** [comment]
please use the issue template as described in our contributing guidelines in the core repo. This bug report is missing lots of information

**Comment by papezg** [comment]
### Steps to reproduce
1.Open calendar app
2. Observe no icon for sharing and no way of sharing calendar


### Expected behaviour
Sharing icon available and sharing enabled

### Actual behaviour
No sharing option available

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Nginx 1.6.2

**Database:**
MySQL 5.5

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
8.0.0

**Updated from an older ownCloud or fresh install:**
Updated from 7.0.4

**List of activated apps:**
Activity, Bookmarks, Calendar, contacts, Pictures, PDF viewer Share files, updater, versions.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
No external storage

**Are you using encryption:** yes/no
no encryption

**Comment by georgehrke** [comment]
> No sharing option available

Do you have ad-block installed? Please disable it for ownCloud.

**Comment by papezg** [comment]
disabling ad-block did the trick!
