### ISSUE TITLE
All day event only on working days [Improvement]

### ISSUE THREAD

**Issue by bentalexanderhaase** [owncloud/calendar#733]
### Expected behaviour

When adding a new "all day event" over a greater timespan (e.g. four weeks) one should be able to select the weekdays in which this even occurs. (e.g. only Monday - Friday // Monday - Saturday etc.). This is especially important when this app is used for business.
### Actual behaviour

All day events are added over the whole time span, no option to specify the days.
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** nginx/1.11.3

**Database:** MariaDB 10.1.17

**PHP version:** PHP 7.0.10-2+deb.sury.org~xenial+1

**Server version:** Nextcloud 10.0 (Stable)

**Calendar version:** 1.3.3

**Updated from an older installed version or fresh install:** Upgraded from OC9 to NC9 --> Update NC9 to NC10

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar/issues/223
