### ISSUE TITLE
404 "Invalid VObject. Document ended prematurely."

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/calendar#734]
I get a ```"Invalid VObject. Document ended prematurely."``` error when syncing a specific calendar. Other calendars sync without any issues.

I found out that the exception is thrown in ```3rdparty/sabre/vobject/lib/Sabre/VObject/Reader.php```. However, I could not debug the event that is causing this failure. Is there any (easy) way to debug this?

### Steps to reproduce
1. sync calendar using DAVdroid (android) or Evolution (gnome/linux)

### Expected behaviour
clients should be able to sync all calendars

### Actual behaviour
Clients get a 404 Responce

### Server configuration
**Operating system**:
Debian 7.8 x64

**Web server:**

    Server version: Apache/2.2.22 (Debian)
    Server built:   Dec 23 2014 22:48:29

**Database:**

    mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

**PHP version:**

    PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**ownCloud version:**
ownCloud 8.0 (stable)
installed via debian-repo

**Updated from an older ownCloud or fresh install:**
migrated (from 6 to 7 to 8)

**List of activated apps:**
- Calendar
- Contacts
- Documents
- Mail
- News

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc7434cf7ac3',
  'passwordsalt' => 'xxx',
  'datadirectory' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'xxx',
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'appcodechecker' => false,
  'secret' => 'xxx',
  'forceSSLforSubdomains' => false,
  'mail_from_address' => 'xxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxx',
  'loglevel' => 0,
);
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
nothing
```

#### Apache access log (/var/log/apache2/access.log)
```
x.x.x.x - username [22/Feb/2015:15:10:10 +0100] "PROPFIND /remote.php/caldav/calendars/username/calendar/ HTTP/1.1" 207 1571 "-" "Evolution/3.12.9"
x.x.x.x - username [22/Feb/2015:15:10:11 +0100] "REPORT /remote.php/caldav/calendars/username/calendar/ HTTP/1.1" 500 9379 "-" "Evolution/3.12.9"
x.x.x.x - username [22/Feb/2015:15:10:11 +0100] "PROPFIND /remote.php/caldav/calendars/username/calendar/ HTTP/1.1" 207 1571 "-" "Evolution/3.12.9"
x.x.x.x - username [22/Feb/2015:15:10:12 +0100] "REPORT /remote.php/caldav/calendars/username/calendar/ HTTP/1.1" 500 9379 "-" "Evolution/3.12.9"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"7c73ff73f1b251651618758af09a8927","remoteAddr":"x.x.x.x","app":"remote","message":"Invalid VObject. Document ended prematurely.","level":4,"time":"2015-02-22T14:10:11+00:00"}
{"reqId":"7c73ff73f1b251651618758af09a8927","remoteAddr":"x.x.x.x","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone (\/freeassociation.sourceforge.net\/Tzfile\/Europe\/Vienna) at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2015-02-22T14:10:11+00:00"}
{"reqId":"948d23c7ec9da7f49bf6af0c18aaac3f","remoteAddr":"91.115.46.240","app":"remote","message":"Invalid VObject. Document ended prematurely.","level":4,"time":"2015-02-22T14:10:12+00:00"}
```

**Comment by georgehrke** [comment]
if you enable debug mode, owncloud should log the id of the broken event

**Comment by georgehrke** [comment]
> clients should be able to sync all calendars

If the client crashes, it's always a bug in the client. A client is must not crash at any time.

**Comment by wurstchristoph** [comment]
I have enabled debug mode as described here https://doc.owncloud.org/server/8.0/developer_manual/general/debugging.html

Unfortunately, I do not get further information about which event is causing this exception. Where should I find the id?

The timezone error is described here https://github.com/owncloud/core/issues/4428

**Comment by georgehrke** [comment]
> Where should I find the id?

please provide the content of owncloud.log

> The timezone error is described here owncloud/core#4428

That's a bug in PHP, as said in my last comment there.

**Comment by wurstchristoph** [comment]
Those three lines are logged whenever Evolution refreshes the calendar:
```
{"reqId":"5fb0c8e4213b4885680e30083d834711","remoteAddr":"x.x.x.x","app":"remote","message":"Invalid VObject. Document ended prematurely.","level":4,"time":"2015-02-22T16:28:01+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/username\/calendarname\/"}
{"reqId":"5fb0c8e4213b4885680e30083d834711","remoteAddr":"x.x.x.x","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone (\/freeassociation.sourceforge.net\/Tzfile\/Europe\/Vienna) at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2015-02-22T16:28:01+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/username\/calendarname\/"}
{"reqId":"66d5f1c6353978f69bf0f67dd8a4c178","remoteAddr":"x.x.x.x","app":"remote","message":"Invalid VObject. Document ended prematurely.","level":4,"time":"2015-02-22T16:28:02+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/username\/calendarname\/"}
```

**Comment by georgehrke** [comment]
is there an additional log message when you use davDroid, as you described in https://github.com/bitfireAT/davdroid/issues/443?

**Comment by wurstchristoph** [comment]
No, I just get
```
{"reqId":"1239668877c9d1780ca9f45c552be2bc","remoteAddr":"x.x.x.x","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-02-22T16:59:36+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/username\/calendarname\/"}
```
