### ISSUE TITLE
OC8: Andorid CalDav Apps fails after upgrade to OC8

### ISSUE THREAD

**Issue by rkifo** [owncloud/calendar#736]
Hi, 

After upgrade from Owncloud 7 to Owncloud 8, CalDav Sync Android apps can't synchronize....

"Invalid server answer"

Thank you!!

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
Additionally please try to gather more information from the caldav sync client. I don't own an android device and can't test this.

**Comment by j-ed** [comment]
CalDAV synchronization works fine on my Android device with CalendarSync app after upgrading to OC8, so I doesn't seem to be a general problem.

**Comment by rkifo** [comment]
### Steps to reproduce
1. Configure new account in Android device wih CalDavSync
2. "Invalid server answer" is received.

### Expected behaviour
App syncs calendars.

### Actual behaviour
"Invalid server answer" is recieved from 2 CalDav Android apps.

### Server configuration

**Operating system**: Debian 7

**Web server: Apache/2.2.22 

**Database: mysql  Ver 15.1 Distrib 5.5.42-MariaDB

**PHP version: PHP 5.4.36-0+deb7u3

**ownCloud version:Owncloud 8

**Updated from an older ownCloud or fresh install: Updated from OC7

**List of activated apps: Defaults + Calendar + Passman 

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocxxxxxx7206',
  'passwordsalt' => 'dd0xxxxx1a7xxxxxxxxxxxe2f0f0b3f38',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxxx',
    1 => 'xxxxxxxxxxxxxxx:443',
  ),
  'datadirectory' => '/datos/www/enlanube.mooo.com/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'xxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxxx',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'root',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'pintonoir',
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
);

**Are you using external storage, if yes which one: NO.

**Are you using encryption: NO

**Are you using an external user-backend, if yes which one: NO

### Client configuration
**Operating system: Android 4.4.2
**App: CalDav Sync Adapter 1.8.1

**Comment by georgehrke** [comment]
please provide server error logs and owncloud.log ...

**Comment by georgehrke** [comment]
please also post the relevant part of the server's access.log

**Comment by rkifo** [comment]
Hi,

Relevant parts of logs:

error.log from Apache:

[Mon Feb 23 15:47:55 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/users (None could be negotiated)., referer: https://domain/index.php/apps/files/
[Mon Feb 23 15:47:57 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/users (None could be negotiated)., referer: https://domain/index.php/settings/users
[Mon Feb 23 15:47:57 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/ajax/geteveryonecount (None could be negotiated)., referer: https://domain/index.php/settings/users
[Mon Feb 23 15:48:04 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/users (None could be negotiated)., referer: https://domain/index.php/settings/users
[Mon Feb 23 15:48:11 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/users (None could be negotiated)., referer: https://domain/index.php/settings/users
[Tue Feb 24 02:24:08 2015] [error] [client 217.112.97.187] File does not exist: /datos/www/domain/vtigercrm
[Tue Feb 24 05:27:27 2015] [error] Hostname 81.61.128.139 provided via SNI and hostname domain provided via HTTP are different
[Tue Feb 24 11:08:16 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/apps (None could be negotiated)., referer: https://domain/index.php/apps/calendar/
[Tue Feb 24 11:08:17 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/apps (None could be negotiated)., referer: https://domain/index.php/settings/apps
[Tue Feb 24 11:08:17 2015] [error] [client 213.73.39.123] Negotiation: discovered file(s) matching request: /datos/www/domain/settings/apps (None could be negotiated)., referer: https://domain/index.php/settings/apps
[Tue Feb 24 23:38:53 2015] [error] [client 217.112.97.187] File does not exist: /datos/www/domain/vtigercrm

And from owncloud.log:

{"reqId":"043da7a001b3e00cd134d937555f72a9","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T10:15:01+00:00","method":"--","url":"--"}
{"reqId":"fc8b95f186610d1b727992191b743aeb","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T10:30:01+00:00","method":"--","url":"--"}
{"reqId":"19c87022a396ecc6155d947b27923576","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T10:45:01+00:00","method":"--","url":"--"}
{"reqId":"0825c34162608e9d60c1cf8d0cac6275","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T11:00:02+00:00","method":"--","url":"--"}
{"reqId":"efc17bdc69bfdd5d95fb012fff51b4a1","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T11:15:01+00:00","method":"--","url":"--"}
{"reqId":"6b6397920565a794f64cd8f64192560d","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/datos\/www\/domain\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-02-25T11:30:02+00:00","method":"--","url":"--"}
{"reqId":"48d94c3880b84478816bbc52ceaba902","remoteAddr":"213.73.37.103","app":"PHP","message":"Class 'OCA\\Contacts\\App' not found at \/datos\/www\/domain\/apps\/calendar\/lib\/sabre\/backend.php#63","level":3,"time":"2015-02-25T11:30:53+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/ruben\/"

Apache Acces.log relevant:

XXX.73.39.123 - - [25/Feb/2015:12:35:06 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=2&start=1422226800&end=1425855600 HTTP/1.1" 200 4563 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:35:06 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=4&start=1422226800&end=1425855600 HTTP/1.1" 200 3219 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:35:06 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=shared_events&start=1422226800&end=1425855600&_=1424852367566 HTTP/1.1" 200 2531 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:35:06 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=3&start=1422226800&end=1425855600 HTTP/1.1" 200 2499 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:40:07 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=2&start=1422226800&end=1425855600 HTTP/1.1" 200 4563 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:40:07 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=4&start=1422226800&end=1425855600 HTTP/1.1" 200 3219 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:40:07 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=3&start=1422226800&end=1425855600 HTTP/1.1" 200 2499 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:40:07 +0100] "GET /index.php/apps/calendar/ajax/events.php?calendar_id=shared_events&start=1422226800&end=1425855600&_=1424852367567 HTTP/1.1" 200 2531 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"
XXX.73.39.123 - - [25/Feb/2015:12:43:31 +0100] "POST /index.php/heartbeat HTTP/1.1" 200 1093 "https://domain/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"

Thank you!!!

**Comment by georgehrke** [comment]
> `Class 'OCA\Contacts\App' not found at \/datos\/www\/domain\/apps\/calendar\/lib\/sabre\/backend.php#63`

please take a look at https://github.com/owncloud/calendar/issues/718#issuecomment-74427067

**Comment by rkifo** [comment]
Great!

Execute this: "./occ app:disable contacts" solves my problem.

Thank you!
