### ISSUE TITLE
Moving Forward: Events Editor

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/calendar#74]
Since, we are deciding to get rid of jQuery UI in core, its time to drop it in the events editor in calendar too. We will be using angular popover for the same, which calls for a relatively big change in UI for the editor. I spent the last couple of days trying different calendar apps, which primarily follow two approaches. 
1. They put everything within the editor  though segregate between the different sections with toggles. (Apple, Fantastical)
2. They keep the minimal changes in the editor but take the advanced options to a different GUI altogether. (Google Calendar)

Both have it's upsides and downsides, so I really want to have it certain which way we are heading with a discussion. Since, calendar is a complex application I broke it down into 2 components : 
1. Primary components include the parts of the editor which are important at their face value.
   - Title of the event
   - Calendar it is a part of.
   - All day or not (if not, from when to when)
   - Location
   - Description of the event.
2. Secondary components includes everything else, that can be clubbed into advanced options. I really think giving them on the face is too much for a user to grasp. These contain:
   - Repeating events (if yes, then the fixed repeating parameters or custom parameters)
   - Alarms
   - Sharing / Attendees. 

I have mockups for both approaches. Will fine tune them a bit and post them here. What do you think @georgehrke @jancborchardt, I really would like some inputs here.

**Comment by georgehrke** [comment]
I'd appreciate the first approach.

**Comment by raimund-schluessler** [comment]
I would also vote for the first approach and toggling between different sections similar as it is done with the right sidebar in the files app. However, a mockup would be nice :smiley:

**Comment by raghunayyar** [comment]
Something very basic I made with what I had in mind. The text converts to input fields on clicking the edit button which is visible on hovering them. Do we like to proceed in this direction? The upside is its very consistent with the Files App. 
<img width="343" alt="screen shot 2015-12-04 at 11 39 20 pm" src="https://cloud.githubusercontent.com/assets/992488/11597213/6baa13ba-9ae0-11e5-8528-0b8ae0aae027.png">

**Comment by raimund-schluessler** [comment]
Showing the edit buttons on hover makes it impossible to use on a touch device as there is no hover function. You could probably just make the options editable after clicking/tapping on them. Have a look at the tasks app, you simply click the title and the input field is shown.

Otherwise I think this is the right direction to proceed.

**Comment by georgehrke** [comment]
I like this approach, especially the idea of putting it into a sidebar, but I don't like this edit button thing either.
Why change between text and input? Let's just use inputs.

**Comment by georgehrke** [comment]
@raghunayyar Where do you want to put the add-attendee and add-alarm buttons?

**Comment by jancborchardt** [comment]
If we do use the sidebar, that should be our detail view. The main info like title, time and calendar should always be available superfast as a popover directly where you clicked.

**Comment by raghunayyar** [comment]
@jancborchardt agreed, I will do another more detailed mockup this time. Do you think the popover should be used to edit information (the basic info) or we use the sidebar to do all the editing?

**Comment by jancborchardt** [comment]
The basic info should be shown and possible to edit directly in the popover – which solves the majority of cases. The sidebar should only be needed for advanced stuff, because it’s a more invasive element and a slight context switch.

**Comment by georgehrke** [comment]
I think this popover should also contain some hint if the event has attendees or alarms

**Comment by jancborchardt** [comment]
Yeah, but only an icon which could then on click open the sidebar.

The event block itself in the calendar should also already have an alarm or attendee icon to signify that. Most other calendars do that too, next to the title.

**Comment by raghunayyar** [comment]
@jancborchardt I will develop a mockup based on these inputs asap.
