### ISSUE TITLE
Invalid VObject. Document ended prematurely.

### ISSUE THREAD

**Issue by jpfeifer** [owncloud/calendar#743]
I can't synchronize my calendars on Android.

### Steps to reproduce
I installed a fresh copy of owncloud 8 with a mysql backend. Then I imported my calendar entries from owncloud 7. These entries are private so unfortunatley I can't sent it. I could sent a sample entry, if I would know which one causes the issue.

### Expected behaviour
My calendar app (CalDAV Sync https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib) on android synchronizes all calendar entries.

### Actual behaviour
My calendar app stop synchronization does not complete, because of a 500 Internal Server Error. This leaves my calendar incomplete and I might miss an apointment. ;)

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS
**Web server:** Apache/2.4.7
**Database:** mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:** PHP 5.5.9-1ubuntu4.6
**ownCloud version:** ownCloud 8.0 (stable)
**Updated from an older ownCloud or fresh install:** Fresh install
**List of activated apps:** Activity 1.2.0, Calendar 0.6.4, Contacts 0.3.0.18, WebDAV user backend 1.1.0.1, Video Viewer 0.1.3, Versions 1.0.5, Updater 0.4, Text Editor 0.4, Share Files 0.6.0, Provisioning API 0.2, Pictures 0.6.0, PDF Viewer 0.7, Mail Template Editor 0.1, First Run Wizard 1.1, File Locking, Deleted files 0.6.2

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc10s0jz5zzd',
  'passwordsalt' => 'secret',
  'secret' => 'secret',
  'trusted_domains' =>
  array (
    0 => 'h2310028.stratoserver.net',
  ),
  'datadirectory' => '/var/www/oc/data',
  'overwrite.cli.url' => 'http://h2310028.stratoserver.net/oc',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'secret',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 1,
);
```

**Are you using external storage, if yes which one:** No
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Google Chrome
**Operating system:** Android 4.4

#### ownCloud log (data/owncloud.log)
```
{"reqId":"f80ce822fa43cba3460c821c1c498628","remoteAddr":"95.112.248.59","app":"remote","message":"Invalid VObject. Document ended prematurely.","level":4,"time":"2015-03-03T00:11:44+00:00"}
```

**Comment by georgehrke** [comment]
> "Invalid VObject. Document ended prematurely."

Means that one event is broken. If you enable the debug mode, ownCloud should log the id of the broken event.

**Comment by jpfeifer** [comment]
Cool thanks I'll check it out. 

What breaks an event? What is the criteria for an event to be broken?

**Comment by jpfeifer** [comment]
Thanks for the info. I was able to see the incorret dataset in the logs and then took a look at it with:

```
select id, uri, summary, calendardata from oc_clndr_objects where uri = 'owncloud-faultyics';
```

For some reason this particular entry was only existing with half the entry. It was missing all end elements (END:VALARM, END:VEVENT and END:VCALENDAR).

This one faulty entry was causing a whole calendar NOT to be synchronized. Maybe one a wrong entry could be ignored? Or does it depend on the app using the api how to deal with this?

This issue is resolved. Thanks :)
