### ISSUE TITLE
Calendar shares being deleted

### ISSUE THREAD

**Issue by USSkuba** [owncloud/calendar#744]
Hello,

I have admin privileges.

I have shared several calendar events with other groups, set the sharing permissions to just read, who no authority to edit, share or delete. 

The calendar events can still be deleted by the other groups.

I have tried deleting the shared calendar and recreated the calendar and events, reset the share and permissions. 

They are still able to delete events.

Ubuntu 14.04 LTS
Apache 2.4.7
ownCloud 7.0.4
SQLite

**Comment by georgehrke** [comment]
dup

**Comment by USSkuba** [comment]
@georgehrke could you point me to the primary?

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/619

**Comment by USSkuba** [comment]
Thank you.
