### ISSUE TITLE
Problem sharing calendar

### ISSUE THREAD

**Issue by vinny74man** [owncloud/calendar#745]
Hi when I create a shared event in the logs I get these errors:

Error	PHP	Illegal offset type at /var/www/owncloud/apps/calendar/templates/part.showevent.php#202	2015-03-08T10:29:06+00:00
Error	PHP	Illegal offset type at /var/www/owncloud/apps/calendar/templates/part.showevent.php#163	2015-03-08T10:29:06+00:00
Error	PHP	Undefined index: at /var/www/owncloud/apps/calendar/templates/part.showevent.php#54	2015-03-08T10:29:06+00:00

P.S. This is a translation online

Thank You

**Comment by georgehrke** [comment]
please use the issue template as described in our contributing guidelines (see core)

**Comment by vinny74man** [comment]
OK 
After creating an event on the calendar I click on share, and I write with who I want to share, but do not share anything.

Instead it should share with the user or the group that I have chosen.

Ubuntu 64 servers
apache2
MySQL 5.5
php 5.5.9
owncloud 8.0 stable

<?php
$CONFIG = array (
  'instanceid' => 'ocxgf8k6zl9h',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '127.0.0.1',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '127.0.0.1',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => 1,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'php',
);

using encryption: yes

These logs are the error messages

Error	PHP	Illegal offset type at /var/www/owncloud/apps/calendar/templates/part.showevent.php#202	2015-03-08T10:29:06+00:00
Error	PHP	Illegal offset type at /var/www/owncloud/apps/calendar/templates/part.showevent.php#163	2015-03-08T10:29:06+00:00
Error	PHP	Undefined index: at /var/www/owncloud/apps/calendar/templates/part.showevent.php#54	2015-03-08T10:29:06+00:00

Fatal	index	Exception: {"Message":"Motore di condivisione di non trovato","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/share.php(317): OC\\Share\\Share::getBackend(NULL)\n#1 \/var\/www\/owncloud\/core\/ajax\/share.php(297): OCP\\Share::getBackend(NULL)\n#2 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#3 [internal function]: __lambda_func(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_672', Array)\n#5 \/var\/www\/owncloud\/lib\/base.php(763): OC\\Route\\Router->match('\/core\/ajax\/shar...')\n#6 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#7 {main}","File":"\/var\/www\/owncloud\/lib\/private\/share\/share.php","Line":1226}	2015-03-08T18:15:04+00:00
Error	OCP\Share	Sharing backend for not found	2015-03-08T18:15:04+00:00
Error	PHP	Undefined index: itemType at /var/www/owncloud/core/ajax/share.php#297

**Comment by master-pago** [comment]
I installed OwnCloud 8.0 Community Edition from the scratch and migrated data from 7.0.1, activated the calandar app afterwards.
Sadly, I have the same problem as described. Apparently, with the (rough?) migration from core to 3rd party app of the calandar app, some functions where damaged. 
A fast solution would be appreciated.

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/685#issuecomment-77874777

**Comment by mancyborg** [comment]
Hi, same issue here. Was this fixed ? Any ETA ? Should I downgrade to OC 7 ?
Thank you.

**Comment by kurush-mamushka** [comment]
Please provide update if any...

**Comment by georgehrke** [comment]
As I said, this is a dup of #685, check #685 for updates ;)

**Comment by kurush-mamushka** [comment]
Oh, sorry. Thank you
