### ISSUE TITLE
Do not create 'personal' default-calendar when no clanendar exists

### ISSUE THREAD

**Issue by dragetd** [owncloud/calendar#746]
Owncloud 8

The default bahvoir is to create a new calandar called 'personal' if there is no other calendar. This is done *every* time if there is no calendar.
If the user deletes the default calendar and returns to the app, it is created again for no transparent reason to the user (he might think that the delete function is broken).

It would make more sense, to create this calendar through the 'frist time using OwnCloud' app that is started by default, when logging in for the first time. Then then user could delete it if he wants to.

Please tell me your thoughts about this. Incase you do not like this feature request and want to keep the old bahvior, I'd like to add one suggestion (naming it 'Private') and bugreport (code ignores existing shared calendars)… but these issues I would only open if you want to keep the existing bahvior. :-)

**Comment by georgehrke** [comment]
> If the user deletes the default calendar and returns to the app, it is created again for no transparent reason to the user (he might think that the delete function is broken).

Calendar app can't be used without a calendar. You just need a calendar. Therefore this is the intended behaviour. 

> code ignores existing shared calendars

That's intended, because the shared calendar may not be writable.

**Comment by dragetd** [comment]
Why can't the calendar app not be used without a calendar?

And in what limbo-state would the app then be the moment after deleting the default calendar?

The whole thing came up for me since I am using three owncloud instances (university, private and a friends one) with different calendars and such synced to my android. The friends/university OC are just for shared calendars. I have my 'own' personal calendar in my OC… this results in a calendar overview in android with several personal and private and local and whatnot calendars.

And I did not find any way to disable/remove the personal calendars which I do not use.

**Comment by Yamakaky** [comment]
+1, I have exactly the same problem.
