### ISSUE TITLE
OC 8: Calendar Sharing not possible

### ISSUE THREAD

**Issue by aneng** [owncloud/calendar#747]
After a Upgrade from OC 7.04 to 8.0 I´m not able to share a calendar anymore. I miss the icons...

![No Sharing](http://alexanderneng.de/shares/myivFkDkUr/Screen-Shot-2015-03-10-23-20-11.png)

The general ability to share is enable: 

![Share-Menu](http://alexanderneng.de/shares/A8H5vNnLwh/Screen-Shot-2015-03-10-23-26-30.png)

Is it a Bug, or am I holding it wrong?

**Comment by georgehrke** [comment]
try disabling adblock

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/calendar/issues/679

**Comment by aneng** [comment]
AdBlock was it. 

Thanks a lot.
