### ISSUE TITLE
Calendar Feature Request - Private Appointments

### ISSUE THREAD

**Issue by waleedkh** [owncloud/calendar#748]
It would be great if you could set private appointments in Outlook and it syncs across devices with this permission. 

This will be a very useful feature when sharing personal calendars.

**Comment by georgehrke** [comment]
we supposed ical classes (aka set to private, busy). If outlook doesn't please send a feature request to MS

**Comment by waleedkh** [comment]
Outlook has this feature available but would like to know if the calendar feature could understand the setting and sync the permission so that it shows as private when another person views it.
Is this possible?

**Comment by georgehrke** [comment]
I don't know how this feature works in outlook and I don't have outlook to test it. Just create an event with the private feature in outlook, export it, open it in a text-editor. If it contains `CLASS:PRIVATE` or `CLASS:CONFIDENTIAL` it'll work, otherwise it won't.
