### ISSUE TITLE
Feature request: ability to hide calendars

### ISSUE THREAD

**Issue by steckerhalter** [owncloud/calendar#748]
Currently calendars are fixed in order and we are dealing with many shared calendars which makes the handling a bit awkward. So I have these feature requests:
- Ability to hide individual calendars from the app-navigation

I also find it a bit confusing that read-only calendars are listed under "Subscriptions" and once they are read-write they move to the top list. Maybe this could be solved via some kind of mark rather than with to separate lists?

**Comment by phsc84** [comment]
Rearrange calendars is already addressed in #133.

**Comment by georgehrke** [comment]
and you can already hide calendars. just click them.

**Comment by steckerhalter** [comment]
@georgehrke That's not what I meant though. i meant hiding them from the app-navigation, not from the calendar view.

**Comment by steckerhalter** [comment]
@phsc thanks, I changed the title/description

**Comment by georgehrke** [comment]
> i meant hiding them from the app-navigation, not from the calendar view.

Why would you want to hide them from the calendar list? If you want to unshare them you can simply delete them.

**Comment by steckerhalter** [comment]
@georgehrke We are working with groups. So our people share their calendars with our group so we can all see them. Some of these calendars I will possibly not need for quite some time but I don't want to unshare them as well since then the person that shared it would have to share it again (and that maybe for many people over and over which is not practical).

Thinking about it again, the feature to rearrange calendars could potentially solve this as well, if it is possible to move uninteresting calendars to the bottom. But if there are two lists like now it won't work well since I would have some important calendars in the subscription list.

We are managing rooms as well via calendars. Imagine 20 calendars and you have 10 of them on top of the list you don't care much for and have mostly turned off (but sometimes you will need them still).

Do you understand?
