### ISSUE TITLE
Calendar share icon not visible on Pale Moon browser

### ISSUE THREAD

**Issue by abranson** [owncloud/calendar#750]
On Owncloud 8.0.1, using the latest version of the Pale Moon browser (25.2.1), the share icon doesn't show next to calendars, and so calendars cannot be shared. It is visible and functioning normally for the same account when viewed on Firefox 36.

**Comment by georgehrke** [comment]
Is Ad-block installed? please disable it.

**Comment by georgehrke** [comment]
Nevertheless, we, at least the calendar, don't aim to support every minor browser. If something works in other browsers, but not in pale moon, please report a bug there.

**Comment by abranson** [comment]
Yes, it was the adblock, thanks. It works fine now. I would strongly encourage official support for Pale Moon - it's a fork of Firefox from before it tried to become Chrome, and as such it still supports the old mozilla weave sync protocol, which means you can synchronize it with the ownCloud mozilla sync plugin. It may be a minor browser, but it has a definite kinship with ownCloud.
