### ISSUE TITLE
Thunderbird + Lightning Not Displaying Shared Calendars

### ISSUE THREAD

**Issue by irny** [owncloud/calendar#751]
Hi all,

Just wondering if anyone can shed some light on this little issue.

I've got OwnCloud running with about 6 users plus an admin. These users form a group and every user's calendar is shared with the group. Thus, any user can see everyone else.

If I sync up User 1 with Calendar on Mac it works fine. I can see/edit their calendar as well as all the other users' (read-only). The colours even come out different. Lovely.

If I sync up User 1 with Thunderbird+Lightning on Windows (or Mac), though, I can only see User 1's calendar. Where have the shared calendars wandered off to? I was trying to avoid setting up all the other accounts as read-only.

Am I missing something here, or is this a bug/compatibility issue?

Thanks, Sarah

**Comment by georgehrke** [comment]
What url did you use to setup caldav in thunderbird?

**Comment by irny** [comment]
The one recommend in the documentation, so: 

https://ADDRESS/remote.php/caldav/calendars/USERNAME/CALENDARNAME

**Comment by georgehrke** [comment]
you have to do the same for each shared calendar.

**Comment by irny** [comment]
Ah, righto. I was assuming it'd just show up, as it does in Calendar on Mac. My bad. Thanks for the info.
