### ISSUE TITLE
Undeclared static property at appinfo/app.php#L37

### ISSUE THREAD

**Issue by marc0s** [owncloud/calendar#754]
I upgraded yesterday my setup to latest master branches of core and apps, including contacts and calendar.

When enabling the calendar app I got the following error:

```Fatal error: Access to undeclared static property: Sabre\VObject\Property::$classMap in /srv/http/owncloud/calendar.git/appinfo/app.php on line 37```

Any help will be appreciated.

Thanks!

**Comment by georgehrke** [comment]
We did an major update for sabredav in core. The calendar app still needs some adjustments, we are working on. 

> I upgraded yesterday my setup to latest master branches

I hope you're not using it in production :stuck_out_tongue_winking_eye:

**Comment by marc0s** [comment]
@georgehrke actually I am. But I also tried to use `stable8` branches and failed with the same error. Is that also expected? Do you think it should work on `stable8`? If so, I can do more testing.

**Comment by georgehrke** [comment]
You are not supposed to use master in production. Never ever! 
It should be fixed if you use stable8 of core as well (and don't forget the `git submodule update` inside core)

**Comment by marc0s** [comment]
Ok, confirmed it works with `stable8`, I probably missed something yesterday night with the rush :)
I was used to a kind of stability with `master` and never mind.
Got it working now, thanks @georgehrke! Will stay with `stable8` ;)
