### ISSUE TITLE
Can't delete single date in repeated calendar entry

### ISSUE THREAD

**Issue by scroom** [owncloud/calendar#755]
### Steps to reproduce
1. Delete a single date in repeated calendar entry
### Expected behaviour

I should be asked whether I want to delete this single event or all the repeated calendar entries.
### Actual behaviour

All repeated calendar entries get deleted.
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** mySQL

**PHP version:** PHP 5.5.9-1ubuntu4.17 (cli)

**Server version:** 9.0.4 (stable)

**Calendar version:** 1.4.0

If you need more information please don't hesitate to ask.

**Comment by Delor3an91** [comment]
Hi,

A single event in a repeated calendar entry may be deleted in iOS native calendar app and it works great. Why such a function can't be implemented in Owncloud calendar app ?

Same problem if I want to modify a repeated event from attempt to confirmed, it will modify all the occurences...

Best Regards

**Comment by raretrack** [comment]
I would also support this enhancement to the calendar. It is the one thing that is preventing me from migrating from Gmail's Calendar to ownCloud.

**Comment by b3niup** [comment]
+1

**Comment by toefel1** [comment]
Same thing here. Sorry to say so: this is a MUST HAVE for calendar-apps like this one. I have tested this behaviour on the actual version, no better than in oC 9.x.
PLEASE make this happen. The oC-calender is practically of no use without this!

**Comment by DeepDiver1975** [comment]
implemented in 1.5.8 - see the rc [calendar-1.5.8-rc1.tar.gz](https://github.com/owncloud/calendar/files/2093329/calendar.tar.gz)
