### ISSUE TITLE
Calendar event sharing not working

### ISSUE THREAD

**Issue by mancyborg** [owncloud/calendar#756]
Hi sorry if double posting but there is some confusion and I would like to understand the situation, or get some confirmations:

On OC 8 I can't share events / clicking on Share -> 'Send Email' does nothing). Was this fixed ? Any ETA ? Does this occur also in the commercial edition of OC ? Should I downgrade to OC 7 ?

Thank you.

**Comment by georgehrke** [comment]
> On OC 8 I can't share events / clicking on Share -> 'Send Email' does nothing). Was this fixed ?

Not yet.

>Any ETA ?

No, whenever I find enough time to fix it.

> Does this occur also in the commercial edition of OC ?

The Calendar app is not part of the commercial edition

**Comment by mancyborg** [comment]
Should I downgrade to OC 7 ?

**Comment by georgehrke** [comment]
That's your decision. I don't know your requirements.

**Comment by mancyborg** [comment]
I need address book sync, calendar sync and calendar events sharing, that's all.

**Comment by georgehrke** [comment]
Sharing calendars is working. The only issue is with sharing single events. If you heavily rely on sharing single events you might want to consider downgrading

**Comment by mancyborg** [comment]
np I'll downgrade, also I didn't know that OC 7 (and it looks like also 6) are maintained and get updates. nice!
