### ISSUE TITLE
Strange behavior of calendar app in OC 7.0.4 (stable)

### ISSUE THREAD

**Issue by DaemonLion** [owncloud/calendar#759]
I have a user that shared calendar to group and disabled editing of this calendar but any user still can add events to this calendar... Is it normal, or I'm doing something wrong ?
I've checked documentation and posted this question into irc channel but still can't find the answer, maybe It's a bug that was fixed in newer releases ?

**Comment by georgehrke** [comment]
duplicate, unknown cause, seems to be fixed with oc 8 though

**Comment by DaemonLion** [comment]
thank you, I will try to upgrade !
