### ISSUE TITLE
Left navigation doesn’t collapse on mobile

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#76]
For some reason the normal app navigation doesn’t collapse on mobile. The toggle shows but the navigation also still stays.

Anything you do differently from the default app HTML?

**Comment by raghunayyar** [comment]
@jancborchardt self assigning. I will check this over the weekend.

**Comment by georgehrke** [comment]
The question is how we want to deal with mobile anyway?

afaik full calendar is barely working on mobile, so just show a more or less working full calendar or rather some instructions on how to setup caldav on your mobile device (with an option to proceed to full calendar)?

**Comment by jancborchardt** [comment]
I'd say it works fine, or at least good enough that we should show the actual interface instead of only instructions to set up Caldav.

Keep in mind mobile is not only very small smartphone screens but also tablets etc. If it doesn't work, switching to the Agenda view will do.
