### ISSUE TITLE
Calendar does not work with current master

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#760]
When installing Calendar on current master, the ownCloud breaks. You get a whitescreen with errors.

Error on master branch:
```
Fatal error: Access to undeclared static property:
Sabre\VObject\Property::$classMap
in /home/jan/owncloud/apps/calendar/appinfo/app.php on line 37
```

Error on rework branch:
```
 Fatal error: Class OCA\Calendar\Backend\Contact\Calendar
contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
(OCA\Calendar\ICalendarAPI::hasUpdated)
in /home/jan/owncloud/apps/calendar/backend/contact/calendar.php on line 150
```

@georgehrke @raghunayyar @jbtbnl @schiesbn

**Comment by georgehrke** [comment]
> Fatal error: Access to undeclared static property:
Sabre\VObject\Property::$classMap
in /home/jan/owncloud/apps/calendar/appinfo/app.php on line 37

related to the upgrade of sabredav, on it, tracked in https://github.com/owncloud/calendar/pull/722

>  Fatal error: Class OCA\Calendar\Backend\Contact\Calendar
contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
(OCA\Calendar\ICalendarAPI::hasUpdated)
in /home/jan/owncloud/apps/calendar/backend/contact/calendar.php on line 150

Known as well, already on it.
