### ISSUE TITLE
feature: Hide shared calendars

### ISSUE THREAD

**Issue by mbogner** [owncloud/calendar#761]
I'm able to hide all my own calendars and set colors for them. But in my installation we have a lot of shared calendars which I can't hide in my view. It would be great if I could hide all shared calendars like my own ones in my view.
I know there is already an issue about colors of shared calendars: But changing the color of a shared calendar for my view would be really really great.

**Comment by georgehrke** [comment]
dup https://github.com/owncloud/calendar/issues/21
