### ISSUE TITLE
Caldav sync fails with Fantastical 2

### ISSUE THREAD

**Issue by chihoko** [owncloud/calendar#762]
### Steps to reproduce
1. Configure Fantastical 2 with caldav calandar
2. Open Fantastical 2

### Expected behaviour
Fantastical 2 calendar syncs with Owncloud via Caldav

### Actual behaviour
Error in Fantastical 2 - 'Request failed with status code 404'

### Server configuration
**Operating system**: Centos 6.5

**Web server:** Apache

**Database:** mysql

**PHP version:** 5.5.23

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** 

Activity 1.2.0
Calendar 0.6.4
Contacts 0.3.0.18
First Run Wizard 1.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.1
Text Editor 0.4
Updater 0.4
Video Viewer 0.1.3

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc994hj73qba',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => 'owncloud.domain.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'version' => '8.0.2.0',
  'installed' => true,
  'forcessl' => true,
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => 25,
  'timezone' => 'Europe/Rome',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'log_authfailip' => true,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Rome',
  'secret' => '',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** OSX 10.10.2

#### Web server error log
```
No web server error
```

#### ownCloud log (data/owncloud.log)
```
No errors in owncloud.log
```

#### Browser log
```
N/A
```

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

AFAIK this issue is related to the birthday calendar and it will be fixed an the next fantastical version. 
Does it work for you if you disable the contacts app?

**Comment by chihoko** [comment]
Thanks, yes it works if I disable the contacts app. Can you confirm that this is a Fantastical bug and will only be fixed in the next version of Fantastical and not the next version of Owncloud?

**Comment by georgehrke** [comment]
> that this is a Fantastical bug 

Not 100% a bug in fanstastical, but suboptimal error handling. The Fantastical devs told me that it will be fixed with the next version (of fantastical)

**Comment by RealRancor** [comment]
Hi,

the current beta has already fixed this according to:

https://forum.owncloud.org/viewtopic.php?f=21&t=27365
