### ISSUE TITLE
problem whith remote access caldav and carddav server and All Events occurrence are delete when I delete an event occurence whithout confirmation

### ISSUE THREAD

**Issue by Battant** [owncloud/calendar#764]
Hello
1.
I have configure remote access for contact and calendar on my iPhone 5 whith ios 8 but my contact and calendar data is not synchronized.
On Mac OS 10.10 I have tried to connect the adressebook (carddav) and calendar (cadaver) I have no error with carddav on Mac OS 10.10 but the cadave own cloud server it seams don't compatible with Mac OS.
2. In the owncloud calendar module, if I try to remove an event occurrence in a recurrence event, it seams that all event occurrences is deleted without alert message such as :
Do you want remove this occurrence or all next occurrences ?
This event
All next event

Could you implement this function 

Thanks for your support 

Best regards

Battant

**Comment by georgehrke** [comment]
> 1.
I have configure remote access for contact and calendar on my iPhone 5 whith ios 8 but my contact and calendar data is not synchronized.
On Mac OS 10.10 I have tried to connect the adressebook (carddav) and calendar (cadaver) I have no error with carddav on Mac OS 10.10 but the cadave own cloud server it seams don't compatible with Mac OS.

please use the issue template as described in our contributing guidelines


> 2. In the owncloud calendar module, if I try to remove an event occurrence in a recurrence event, it seams that all event occurrences is deleted without alert message such as :
Do you want remove this occurrence or all next occurrences ?

duplicate

please ping me, when you updated your post, will reopen then
