### ISSUE TITLE
No default calendar for new ownCloud 9.1.1 user

### ISSUE THREAD

**Issue by Pazu** [owncloud/calendar#765]
If I create a new user on ownCloud 9.1.1, then enable the Contacts app for that user, the user appears to have no default contacts list; at least, none is visible under settings, and trying to access it by CardDAV via 'https://example.com/remote.php/dav/addressbooks/users/foo/default/' fails.

Is that expected behavior, or a bug? Should the user then create a contacts list named 'default' or is there some other recommendation for the name of a "default" contacts list?

(If this is a bug, I'll follow up with the template material.)

**Comment by Pazu** [comment]
I did a little more experimenting, and observed the following.
1. If I create a user, normally a contacts list called "Contacts" is created for the user, and is available via CalDAV as "https://example.com/remote.php/dav/addressbooks/users/foo/contacts/".
2. If I create a user who can see a shared contacts list (for example, at time of account creation is added to a group with which a calendar was previously shared), then this default "Contacts" list is not created for that user. If the shared list is read-only, then the user cannot create any contacts until they create a list of their own.

**Comment by DeepDiver1975** [comment]
> If I create a new user on ownCloud 9.1.1, then enable the Contacts app for that user, the user appears to have no default contacts list; at least, none is visible under settings, and trying to access it by CardDAV via 'https://example.com/remote.php/dav/addressbooks/users/foo/default/' fails.
> 
> Is that expected behavior, or a bug? Should the user then create a contacts list named 'default' or is there some other recommendation for the name of a "default" contacts list?

this should all go into the contacts repo - anyway - looks like a core issue to me

**Comment by DeepDiver1975** [comment]
this was fixed some time back -> closing
