### ISSUE TITLE
All Events occurrence are delete when I delete an event occurence whithout confirmation

### ISSUE THREAD

**Issue by Battant** [owncloud/calendar#765]
Description : All ocurrence of an event are delete if you delete an occurrence.
To reprocuce this issus
1. Create a new event whith a recurrence.
2 Select an occurrence and delete it
Actual result :
All occurrences are autocratically deleted whithout confirmation
Result expended
Alert message It's A recurrent event. Do you want to delete this occurrence or this occurrence and next occurrences

Is it possible to implement this function ?

Thanks for your support

Best regards

Battant

**Comment by georgehrke** [comment]
duplicate, there already is an issue for that in this bug tracker!

**Comment by Battant** [comment]
Server configuration
Owncloud 8 server
Pho 5.4 is on
MySQL
More info on www.kreativmedia.ch hebergement mutualise hebrgement d'application
Client configuration
Owncloud for Mac OS, windows and Ubuntu 14.04 Lts 64 bit

could you send me the bug duplecated link about calendar recurrence ?

Could you help me plese
Best regards

Battant.
