### ISSUE TITLE
My data is never synchronize betwin my iphon or mac whith my owncloud carddav and caldav server

### ISSUE THREAD

**Issue by Battant** [owncloud/calendar#766]
Hello,

I tried to synchronize my iphone 5 (ios) 8.3

I have configured the caldav and carddav server

Actual result :
No card or event are send from my iphone to the owncloud 8 carddav and caldav server

2 On my mac whith mac os 10.10, is I tried to configure the carddav server and caldav connection.
1: open online service
2. chose other.
3. chose carddav or caldav
4. Follow the sssistant instructions

If I configure carddav, I have no error message but whith the carddav server, Icalendar show me an error message. it seems incompatibale.

Note : My data is never send from my iphone to owncloud server

Could you help me please ?

Thanks for your support

Best regards

Battant

**Comment by georgehrke** [comment]
please use the issue template in https://github.com/owncloud/calendar/issues/764 and please stop posting the same issue over and over again. For christ's sake ...

**Comment by Battant** [comment]
Hello george

Sorry i don't Knie thé templste url.

I havé repost my Thor last issus as a different templat to hop that is good

Could you correct my issue and delete the duplicate issues

Thanks by adventure 

Best regards

Battant

**Comment by georgehrke** [comment]
that's the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by Battant** [comment]
Step to reproduce :
1. On iPhone go to settings
2. Chose mail calendar contact
3. Chose add account
Chose carddav or caldav

3. Configure the carddav and caldav server
On Mac OS 
Chose Apple ment
System preference online account
Configure cadave and carddav server. Follow instruction
Actual result
The data store on the iPhone is never synchronized whith owncloud  8 server
On my Mac OS 10.10I open the calendar appointed a message say me that the server is incompatible
Expend result
I can synchronized my data whith owncloud  server Mac OS Ubuntu 14.04 
and Mac OS

Server configuration
Owncloud 8 server
Pho 5.4 is on
MySQL
More info on www.kreativmedia.ch hebergement mutualise hebrgement d'application
Client configuration
Owncloud for Mac OS, windows and Ubuntu 14.04 Lts 64 bit

Could you help me plese
Meat regards

Battant

**Comment by georgehrke** [comment]
please use the entire script, also provide log files, and tell me what url you used to setup caldav on your iOS device
