### ISSUE TITLE
[Enhance]Hide/Activate Calendar shared by others

### ISSUE THREAD

**Issue by flotho** [owncloud/calendar#768]
Hy,

From now it looks like hiding a calendar is linked to the calendar but It should be also linked to the user.

## Expected behaviour

Create a calendar and chare it to anyone. Other people should be able to hide your calendar so that it will be easier to plan their own activity.

## Observed behaviour

Only the creator of the calendar could hide/activate. Additionnally, when he do this, it's also hidden for other people.

regards

**Comment by georgehrke** [comment]
duplicate

**Comment by flotho** [comment]
Hy @georgehrke I didn't found which one is the duplicate.
Could you lead me  or reference the issue in this post

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/issues/21

**Comment by flotho** [comment]
@georgehrke , Thanks
