### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by jknockaert** [owncloud/calendar#769]
When updating to 1.4.1 I get an invalid certificate warning. The integrity scan says:

```
Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.
```

**Comment by ghost** [comment]
@jknockaert This is an issue of the nextcloud calendar app reported here: https://github.com/nextcloud/calendar/issues/196

**Comment by jknockaert** [comment]
Nop, am not using Nextcloud nowhere.

**Comment by ghost** [comment]
You're still using the nextcloud app here. The previous maintainer of https://github.com/owncloud/calendar just have published the app from https://github.com/nextcloud/calendar to ownCloud users. This will change again in the next time as discussed here: https://github.com/owncloud/calendar/pull/759#issuecomment-258811198

**Comment by jknockaert** [comment]
OK, pls stop this BS. I'll simply close this one.

**Comment by DeepDiver1975** [comment]
Do I understand correctly that the used certificate is causing issues for all owncloud instances?

**Comment by ghost** [comment]
@DeepDiver1975 Yes, see also e.g. the comments on https://apps.owncloud.com/content/show.php/Calendar?content=168707

**Comment by georgehrke** [comment]
@RealRancor I tried to fix the cert issue.
Can you validate that calendar2.tar.gz works? 

https://github.com/nextcloud/calendar/releases/tag/v1.4.1

**Comment by ghost** [comment]
@georgehrke Just commented a few seconds in https://github.com/nextcloud/calendar/issues/196#issuecomment-262801971

Works now as expected, thanks for the quick fix.

**Comment by georgehrke** [comment]
Can ownCloud handle the name `<appname>2.tar.gz` or will that cause issues itself?

**Comment by DeepDiver1975** [comment]
> Can ownCloud handle the name 2.tar.gz or will that cause issues itself?

As far as I can tell this should work ...... let's test ...

**Comment by ghost** [comment]
From my experience the download name doesn't  matter, just the app name in the archive which needs to match the appid.

**Comment by georgehrke** [comment]
Okay, I will link apps.owncloud.com to the `calendar2.tar.gz`

**Comment by georgehrke** [comment]
Someone of you has to change the links, apparently I can't edit the calendar app anymore ...

**Comment by DeepDiver1975** [comment]
> Someone of you has to change the links, apparently I can't edit the calendar app anymore ...

let me have a look ...

**Comment by georgehrke** [comment]
9.1 is fixed, 9.0 still points to calendar.tar.gz

**Comment by DeepDiver1975** [comment]
> 9.1 is fixed, 9.0 still points to calendar.tar.gz

fixed as well

**Comment by DeepDiver1975** [comment]
@jknockaert @RealRancor can you verify that this has been solved for you?

@georgehrke thanks a lot for the fix and the fast response :heart:

**Comment by cdamken** [comment]
@DeepDiver1975 I updated the app, and the developers are not shown:
Calendar 1.4.1
by [object Object],[object Object],[object Object] (AGPL-licensed) 

I'm using version 9.1.2

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I updated the app, and the developers are not shown:
> Calendar 1.4.1
> by [object Object],[object Object],[object Object] (AGPL-licensed)

Something we need to have a look at within our app management page to properly behave on multiple author tags in info.xml

**Comment by cdamken** [comment]
Thanks
