### ISSUE TITLE
synchronisation of my shared calendar and tasks not functional any more

### ISSUE THREAD

**Issue by flolerchi** [owncloud/calendar#773]
I have recognized, that the synchronisation of my shared calendar and my shared tasks over my android devices are not working anymore. My own parts of my shared calendar and tasks are synchronized, but not the updates of the user I have shared with.

Could someone support me on this?

### Steps to reproduce
1. Android calendar and task sync from calendar of the owners mobil device is functional
2. If updating calendar and task on shared users android device --> updates form owners calendar will be taken over
3. If adding calendar entries or task on android device of the shared user in the shared calendar or task list - the owncloud calender and task will not be updated
Hint: both device settings are same and were already running before updating to the newest calendar version

### Expected behaviour
Synchronisation of shared user should also work

### Actual behaviour
Synchronisation of shared user is not functional

### Server configuration
**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
**Web server:**
Server version: Apache/2.4.12 (Ubuntu)
Server built:   Jul 15 2016 15:32:10
**Database:**
mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper
**PHP version:**
PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
**Server version:** (see your admin page)
Owncloud version 9.1.2
**Calendar version:** (see the apps page)
Calendar version 1.4.1
**Updated from an older installed version or fresh install:**
updated from an older version
**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.
**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: true
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: 16.11.0
  - ownnote: 1.08
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - music
  - news
  - provisioning_api
  - user_external
  - user_ldap
**The content of config/config.php:**
{
    "system": {
        "maintenance": false,
        "instanceid": "ochohkpam790",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "serverhome",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/FLO-Raid\/88_owncloud",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "asset-pipeline.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "en",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "session_lifetime": 86400,
        "session_keepalive": false,
        "trashbin_auto_expire": false,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "htaccess.RewriteBase": "\/owncloud"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "1.1.2",
            "ocsid": "173921",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1201"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.7",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "contacts": {
            "backend_ldap": "false",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1454860391.145",
            "lastcron": "1481367636",
            "lastupdateResult": "[]",
            "lastupdatedat": "1481310903",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_default_expire_date": "no"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.7",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.12.0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_chunk_size": "1024",
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_mode": "executable",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "157439",
            "signed": "true",
            "types": "filesystem"
        },
        "files_external": {
            "\/Dropbox": "1455031354",
            "allow_user_mounting": "no",
            "enabled": "yes",
            "installed_version": "0.6.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "florian": {
            "documents": "save_path"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.1.0",
            "ocsid": "169116",
            "signed": "true",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.12",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "news": {
            "enabled": "no",
            "installed_version": "8.8.0",
            "ocsid": "168040",
            "types": ""
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.1",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "16.11.0",
            "ocsid": "170674",
            "types": ""
        },
        "ownnote": {
            "enabled": "yes",
            "installed_version": "1.08",
            "types": ""
        },
        "pdflintview": {
            "enabled": "no",
            "installed_version": "1.0",
            "ocsid": "169202",
            "types": "type"
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "[\"admin\"]",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.4.1",
            "contacts": "1.5.1",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "ownbackup": "16.11.0",
            "tasks": "0.9.3",
            "types": ""
        }
    }
}
**Are you using external storage, if yes which one:**
no
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:**
no
### Client configuration
**Browser:** Firefox 50.0.2
**Operating system:** Android 6.0.1
**CalDAV-clients:**
CalDAV-Sync v0.4.27 by Marten Gajda
JB Workaround CalDAV-Sync v1.4 by Marten Gajda
#### Web server error log
[Sat Dec 10 10:53:36.261487 2016] [:error] [pid 8990] [client 82.113.121.133:10870] script '/var/www/html/groupdav.php' not found or unable to stat
[Sat Dec 10 10:53:37.221271 2016] [:error] [pid 8990] [client 82.113.121.133:10870] script '/var/www/html/remote.php' not found or unable to stat
[Sat Dec 10 10:56:59.701979 2016] [:error] [pid 9025] [client 82.113.121.133:24387] script '/var/www/html/groupdav.php' not found or unable to stat
[Sat Dec 10 10:57:00.715745 2016] [:error] [pid 9025] [client 82.113.121.133:24387] script '/var/www/html/remote.php' not found or unable to stat
[Sat Dec 10 10:57:02.607656 2016] [:error] [pid 8782] [client 192.168.178.24:48080] script '/var/www/html/groupdav.php' not found or unable to stat
[Sat Dec 10 10:57:02.709737 2016] [:error] [pid 8782] [client 192.168.178.24:48080] script '/var/www/html/remote.php' not found or unable to stat
[Sat Dec 10 10:58:08.810453 2016] [autoindex:error] [pid 9029] [client 82.113.121.133:20055] AH01276: Cannot serve directory /var/www/owncloud/: No matching DirectoryIndex (none) found, and server-generated directory index forbidden by Options directive
[Sat Dec 10 11:00:27.147312 2016] [autoindex:error] [pid 9055] [client 192.168.178.29:54138] AH01276: Cannot serve directory /var/www/owncloud/: No matching DirectoryIndex (none) found, and server-generated directory index forbidden by Options directive

#### Log file (data/owncloud.log)
{"reqId":"7pZncsZXfNstx50Aaxy9","remoteAddr":"192.168.178.29","app":"OCP\\Share","message":"Sharing backend for principals not found","level":3,"time":"2016-12-10T11:26:07+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=c&perPage=200&itemType=principals","user":"florian"}
{"reqId":"2NxYsNcGM8j6JTm99Pgx","remoteAddr":"192.168.178.29","app":"OCP\\Share","message":"Sharing backend for principals not found","level":3,"time":"2016-12-10T11:26:07+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=ch&perPage=200&itemType=principals","user":"florian"}
{"reqId":"vPFM5PMNE12\/u8PfOk2i","remoteAddr":"192.168.178.29","app":"OCP\\Share","message":"Sharing backend for principals not found","level":3,"time":"2016-12-10T11:26:08+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=chr&perPage=200&itemType=principals","user":"florian"}
{"reqId":"4bx3hgf\/2uHCBZz3XLXZ","remoteAddr":"192.168.178.29","app":"OCP\\Share","message":"Sharing backend for principals not found","level":3,"time":"2016-12-10T11:26:08+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=chri&perPage=200&itemType=principals","user":"florian"}

**Comment by ghost** [comment]
@flolerchi This is still the wrong place. Please use https://central.owncloud.org/ as advised for getting support with such broken environments.

**Comment by flolerchi** [comment]
https://central.owncloud.org/t/synchronisation-of-my-shared-calendar-and-tasks-not-functional-any-more/4470?u=flolerchi
