### ISSUE TITLE
Missing author names on apps overview

### ISSUE THREAD

**Issue by sushidave** [owncloud/calendar#774]
Just upgraded to version 1.4.1 and the author's names are missing in the apps overview. Instead, it shows this:

Calendar 1.4.1
von [object Object],[object Object],[object Object] (AGPL-lizensiert) 

### Steps to reproduce
1. Open the apps page -> activated apps are listed
2. Klick the upgrade button of the calendar app and wait until finished
3. Read what it says beneath the calendar app title.

### Expected behaviour
(The names of the authors should appear.)

### Actual behaviour
von [object Object],[object Object],[object Object] (AGPL-lizensiert) 

### Server configuration
**Database:**
mysql 10.0.27

**PHP version:**
5.6.26

**Server version:** (see your admin page)
Nextcloud 10.0 (stable)

**Calendar version:** (see the apps page)
1.4.1

**Updated from an older installed version or fresh install:**
updated

**Comment by cdaecke** [comment]
I can confirm the exact same behaviour with ownCloud 9.1.3 (stable).

**Comment by amigosdapoli-admin** [comment]
Justed updated to ownCloud 9 and the same thing happened. Anyone found the solution for this problem?

**Comment by fernandosjp** [comment]
Just update to owncloud 9 and the same thing happened. Anyone found the solution?

**Comment by DeepDiver1975** [comment]
afaik this is fixed -> close
