### ISSUE TITLE
/remote.php/caldav/ returns 500 Internal server error

### ISSUE THREAD

**Issue by bbalon** [owncloud/calendar#777]
### Steps to reproduce
1. https://server/owncloud/remote.php/caldav/

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system:** CentOS Linux release 7.0.1406 (Core)

**Web server:** 2.4.6-19.el7.centos

**Database:** mariadb-5.5.41-2.el7_0 or sqlite-3.7.17-4.el7

**PHP version:** PHP 5.6.7 (cli) (built: Mar 21 2015 15:53:28)

**ownCloud version:** ownCloud 8.0.3 (git) / ownCloud 8.0.3 (stable)

**Updated from an older ownCloud or fresh install:** tried both

**List of activated apps:** 
* Calendar
* Contacts
* Deleted files
* Share files
* Versions

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '522a323ee1990',
  'passwordsalt' => '',
  'datadirectory' => '/opt/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'cloud.laly.si',
    1 => 'share.it4biz.si',
  ),
  'secret' => '',
  'forcessl' => true,
  'loglevel' => 3,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Mac OS X, Linux, Android

#### Web server error log
[:error] [pid 14453] [client 92.37.89.107:53275] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/cloud.laly.si/apps/calendar/sabre/main.php' (include_path='/var/www/html/cloud.laly.si/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/cloud.laly.si/3rdparty/pear/pear_exception:/var/www/html/cloud.laly.si/3rdparty/pear/archive_tar:/var/www/html/cloud.laly.si/lib/private:/var/www/html/cloud.laly.si/config:/var/www/html/cloud.laly.si/3rdparty:/var/www/html/cloud.laly.si/apps:/var/www/html/cloud.laly.si/lib:.:/usr/share/pear:/usr/share/php:/var/www/html/cloud.laly.si') in /var/www/html/cloud.laly.si/remote.php on line 54

#### ownCloud log (data/owncloud.log)
{"reqId":"e30f7707aeead8b99d5badc40ddb2c5b","remoteAddr":"92.37.89.107","app":"PHP","message":"require_once(\/var\/www\/html\/cloud.laly.si\/apps\/calendar\/sabre\/main.php): failed to open stream: No such file or directory at \/var\/www\/html\/cloud.laly.si\/remote.php#54","level":3,"time":"2015-04-26T12:55:41+00:00"}
{"reqId":"e30f7707aeead8b99d5badc40ddb2c5b","remoteAddr":"92.37.89.107","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/cloud.laly.si\/apps\/calendar\/sabre\/main.php' (include_path='\/var\/www\/html\/cloud.laly.si\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/cloud.laly.si\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/cloud.laly.si\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/cloud.laly.si\/lib\/private:\/var\/www\/html\/cloud.laly.si\/config:\/var\/www\/html\/cloud.laly.si\/3rdparty:\/var\/www\/html\/cloud.laly.si\/apps:\/var\/www\/html\/cloud.laly.si\/lib:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/cloud.laly.si') at \/var\/www\/html\/cloud.laly.si\/remote.php#54","level":3,"time":"2015-04-26T12:55:41+00:00"}

#### Browser log
"NetworkError: 500 Internal Server Error - https://cloud.laly.si/remote.php/caldav/"

**Comment by georgehrke** [comment]
please be more specific about the reproduction steps ...
As you seem to use git (which is not recommended in production!), tell us what branches every cloned repo is using

**Comment by bbalon** [comment]
I tried many thing before I reported this bug, and git was only one of them.
Problem started after I upgraded to owncloud version 8.0.2.

Today I created new instance from scratch, downloaded owncloud 8.0.2 and download and enabled calendar from app.owncloud.org and result was the same. I cannot access caldav.
It works with version 7.x, if I configure it from scratch.
If I revert application back to 7.x and leave database at 8.0.3.4 I still have same issue.

**Comment by georgehrke** [comment]
is card broken as well?

**Comment by bbalon** [comment]
No, carddav works OK.

**Comment by bbalon** [comment]
I configured new instance again today and 8.0.2 works.
Now I have to figure out why my stopped working after upgrade.

**Comment by bbalon** [comment]
I tested it again.

I reverted my ownclound to 7.0.5 from backup. Caldav works OK.
I did upgrade to 8.0.2 (stable, not git), downloaded Calendar version 8.0.2 from git (apps webpage ins not working for me today) and result is the same.

Upgrade breaks caldav for me somehow.

**Comment by bbalon** [comment]
I tried upgrading clean install of 7.0.5 and upgrade it to 8.0.2 and it works fine.
Looks like there is something specific about my configuration.

**Comment by bbalon** [comment]
I fixed problem. It was my mistake.
Looks like when I upgraded to version 8.0.2 and calendar app was not enabled by default I downloaded calendar app from master repository from github and enabled it. It didn't work and I realized that master version is 0.10.24, and version I need is 0.6.4 (for OwnCloud 8.0.2), but looks like configuration in database didn't delete when I removed version 0.10.24:

This is compare of nonworking database to working one:
```
< INSERT INTO `oc_appconfig` VALUES ('calendar','installed_version','0.10.24');
---
> INSERT INTO `oc_appconfig` VALUES ('calendar','installed_version','0.6.4');
45,47c96,98
< INSERT INTO `oc_appconfig` VALUES ('core','lastupdatedat','1430135584');
< INSERT INTO `oc_appconfig` VALUES ('core','public_caldav','calendar/sharing/public.php');
< INSERT INTO `oc_appconfig` VALUES ('core','public_calendar','calendar/sharing/public.php');
---
> INSERT INTO `oc_appconfig` VALUES ('core','lastupdatedat','1430136806');
> INSERT INTO `oc_appconfig` VALUES ('core','public_caldav','calendar/share.php');
> INSERT INTO `oc_appconfig` VALUES ('core','public_calendar','calendar/share.php');
52,53c103,104
< INSERT INTO `oc_appconfig` VALUES ('core','remote_caldav','calendar/sabre/main.php');
< INSERT INTO `oc_appconfig` VALUES ('core','remote_calendar','calendar/sabre/main.php');
---
> INSERT INTO `oc_appconfig` VALUES ('core','remote_caldav','calendar/appinfo/remote.php');
> INSERT INTO `oc_appconfig` VALUES ('core','remote_calendar','calendar/appinfo/remote.php');
```

I fixed this database entries and not it is working fine.

Thanks.

**Comment by tietjen** [comment]
@bbalon thank you for your explanation. You saved my day :-)

**Comment by bennidi** [comment]
I had the same problem. In a fresh oc 8.0.2 installation with the latest master (0.6.4) from calendar app there where the wrong calendar settings in the db. The path points to /sabre/.. which is missing and should be /appinfo/remote.php
