### ISSUE TITLE
Edit an event erase Title, Location & Desciption

### ISSUE THREAD

**Issue by RaSKoR** [owncloud/calendar#778]
### Steps to reproduce
1. Create an event
2. Edit it from web interface

### Expected behaviour
The event title, description and location input should be fill with the datas

### Actual behaviour
The 3 inputs are empty

### Server configuration
**Operating system**:
Debian 7.7
**Web server:**
Apache2 2.2.22-13+deb7u3
**Database:**
Sqlite3
**PHP version:**
PHP 5 5.4.35-0+deb7u2

**ownCloud version:** (see ownCloud admin page)
8.1 alpha 1 (git)
**Updated from an older ownCloud or fresh install:**
Fresh Install
**List of activated apps:**
Calendar, contacts.
**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'ocpb8ggpexhw',
  'trusted_domains' => 
  array (
    0 => 'x.x.x.x',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://x.x.x.x/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'emkim',
  'mail_domain' => 'x.x.x.x',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'smtp.x.x.x.x',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Firefox ESR 31.6.0
**Operating system:**
Debian 8.0

### Fix
To fix it  I added these lines into /apps/calendar/ajax/event/edit.form.php file at line 37 : 
```
$summary = $vevent->__get('SUMMARY');
$location = $vevent->__get('LOCATION');
$description = $vevent->__get('DESCRIPTION');
```

**Comment by georgehrke** [comment]
please use the issue template,
you didn't even mentioned the version you use ...

**Comment by RaSKoR** [comment]
Sorry, I edited my first post with the template.

**Comment by georgehrke** [comment]
master: 998caf3
stable8.1: 0c4723a
