### ISSUE TITLE
Undefined index on Cron

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/calendar#779]
I've set up a cronjob every 15 minutes, Calendar causes an error in my logfile every 15 minutes now:

Error	PHP	Undefined index: REQUEST_URI at /var/www/xxx/owncloud/apps/calendar/appinfo/app.php#41	2015-04-27T13:15:01+00:00

I'm running PHP 5.5.22 on my server. Can i provide any important information else?

**Comment by georgehrke** [comment]
Dup, please close this issue and search for closed issues containing REQUEST_URI 

Please excuse my brevity and typos.

**Comment by stefan-niedermann** [comment]
#714
