### ISSUE TITLE
calDav Calendar sync fails with akonadi (Error 500) (empty $dt)

### ISSUE THREAD

**Issue by sedrubal** [owncloud/calendar#781]
like it is described in #780 the latest akonadi (Ubuntu 15.04) handles sync errors differently than before. In my case the sync with `OC8.0.2` breakes with `error 500` and in owncloud log I can see:

```json
{"reqId":"<id>","remoteAddr":"<ip>","app":"PHP","message":"Uninitialized string offset: 0 at \/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/DateTimeParser.php#170","level":3,"time":"2015-04-29T22:03:52+00:00"}
{"reqId":"<id>","remoteAddr":"<ip>","app":"PHP","message":"Uninitialized string offset: 0 at \/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/DateTimeParser.php#170","level":3,"time":"2015-04-29T22:03:52+00:00"}
{"reqId":"<id>","remoteAddr":"<ip>","app":"remote","message":"The supplied iCalendar datetime value is incorrect: ","level":4,"time":"2015-04-29T22:03:52+00:00"}
```

The problem here is, that `/3rdparty/sabre/vobject/lib\/Sabre/VObject/DateTimeParser.php` gets an empty (`""`) datetime (`$dt`) in `function parseDateTime` (line 28).

How can this happen?

If I return a random (but valid) date inset of throwing an error, the sync is working properly...

```php
return new \DateTime('2015-01-01 12:00:00', new \DateTimeZone('UTC'));
```

@georgehrke said in #557 that this is an upstream issue. But maybe this could help to avoid this problem.

**Comment by georgehrke** [comment]
no, we are not going to patch around 3rpdarty libs. this must be fixed in upstream.

**Comment by georgehrke** [comment]
upstream issue

**Comment by sedrubal** [comment]
ok, I thought that it might be an issue, that this function gets empty parameters...

**Comment by georgehrke** [comment]
> ok, I thought that it might be an issue, that this function gets empty parameters...

That's in issue within sabre/vobject. We only pass raw calendar data to sabre/vobject.
