### ISSUE TITLE
restore calendar (mysql - sqlite)

### ISSUE THREAD

**Issue by 466** [owncloud/calendar#781]
Using mysql database for owncloud, where does this app save the contacts to?

I had to reinstall everything from scratch, choosing sqlite3 over mysql results in quite an empty calendar .... .
As i do have my database directory (/var/lib/mysql) from my previous installation, is there an easy way, getting my calendar back?

**Comment by DeepDiver1975** [comment]
same as in https://github.com/owncloud/contacts/issues/571 - but in the table oc_calendar_objects
