### ISSUE TITLE
Uploading ICS file with multiple events fails with : "400 Bad Request"

### ISSUE THREAD

**Issue by miguelclean** [owncloud/calendar#783]
When I try uploading ics files to my calendar with *cadaver* (http://www.webdav.org/cadaver/) I get a "400 Bad Request" response, if the *ics* file contains more than one event. (i.e. multiple events with different UID's). It works fine as long as there is only one event (or all events share the same UID). 

Am I expected to upload each event in a seperate *ics* file?

owncloud 8.0.3
cadaver 0.23.3

**cadaver session log**

miguel@miguel-quad:~$ cat **basic.ics**
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART:20150513T010000Z
DTEND:20150513T030000Z
DTSTAMP:20150505T114502Z
**UID:3h5hpvsseeg3a95ee46vbkgqng@google.com**
CREATED:20150501T201643Z
LAST-MODIFIED:20150501T201643Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:SRM 659
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART:20150505T150000Z
DTEND:20150505T170000Z
DTSTAMP:20150505T114502Z
**UID:4h5hpvsseeg3a95ee46vbkgqng@google.com**
CREATED:20150501T201512Z
LAST-MODIFIED:20150501T201547Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:SRM 658
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

miguel@miguel-quad:~$ cat **basic2.ics**
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART:20150513T010000Z
DTEND:20150513T030000Z
DTSTAMP:20150505T114502Z
**UID:3h5hpvsseeg3a95ee46vbkgqng@google.com**
CREATED:20150501T201643Z
LAST-MODIFIED:20150501T201643Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:SRM 659
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART:20150505T150000Z
DTEND:20150505T170000Z
DTSTAMP:20150505T114502Z
**UID:3h5hpvsseeg3a95ee46vbkgqng@google.com**
CREATED:20150501T201512Z
LAST-MODIFIED:20150501T201547Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:SRM 658
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

miguel@miguel-quad:~$ cadaver  https://secure.xxxxxx.com/owncloud/remote.php/caldav/calendars/miguel/test

Authentication required for ownCloud on server `secure.xxxxxx.com':
Username: miguel
Password: 

dav:/owncloud/remote.php/caldav/calendars/miguel/test/> mput basic.ics basic2.ics

Uploading **basic.ics** to `/owncloud/remote.php/caldav/calendars/miguel/test/basic.ics':
Progress: [=============================>] 100.0% of 584 bytes **failed**:
**400 Bad request**

Uploading **basic2.ics** to `/owncloud/remote.php/caldav/calendars/miguel/test/basic2.ics':
Progress: [=============================>] 100.0% of 584 bytes **succeeded**.

**Comment by georgehrke** [comment]
> Am I expected to upload each event in a seperate ics file?

Yes, you are.
