### ISSUE TITLE
Unable to create new event on Android phones

### ISSUE THREAD

**Issue by landmine** [owncloud/calendar#783]
### Steps to reproduce
1.  Open Calendar on Android phone
2.  On Month, Week or Day view, tap any open area.

### Expected behaviour
New event editor modal should open.

### Actual behaviour
Nothing.

Event editor opens correctly when an existing event is tapped, but there appears to be no way to create a new event on an Android phone (tested on LG G3 and Moto X Pure)

### Server configuration
**Operating system**:
RedHat

**Web server:**
apache

**Database:**
mysql5

**PHP version:**
5.4.45

**Server version:** (see your admin page)
9.1.4 (stable)

**Calendar version:** (see the apps page)
1.4.1

**Updated from an older installed version or fresh install:**
updated from 8.2.10

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Android (marshmallow)

**Comment by landmine** [comment]
I tested on an iPod Touch running iOS 10, and got the same results: tapping an open time slot fails to open a new event interface.  Thank you!

**Comment by DeepDiver1975** [comment]
this is more related to the backend - please reopen in the core repo - https://github.com/owncloud/core
