### ISSUE TITLE
Calendar app spamming oC error log with "Undefined index: REQUEST_URI"

### ISSUE THREAD

**Issue by geez0x1** [owncloud/calendar#785]
The Calendar app is spamming my ownCloud (8.0.3) error log with the following message:
```
Undefined index: REQUEST_URI at /usr/share/owncloud/apps/calendar/appinfo/app.php#41
```
I'm using it with Thunderbird+Lightning addon. It appears to do this 1-2 times every sync happens. It doesn't seem to cause any problems otherwise, although it makes it harder to see other errors in my log I'm trying to debug :)

**Comment by georgehrke** [comment]
duplicate, please search for existing issues (both open and closed) before creating new ones ...

**Comment by geez0x1** [comment]
Sorry, the default behaviour is to search in open bugs and as such I didn't find it.
