### ISSUE TITLE
OC8: Multiple calendars - No UserId hover on?/ Deletion issue / View on/off issue

### ISSUE THREAD

**Issue by GazzaC** [owncloud/calendar#786]
When viewing multiple calendars that are share to a user, one has no idea which calendar belongs to which user? Also if you delete a calendar shared to you it deletes it for the original user. 
If you want to keep a calendar but not view it for the time being, one cannot turn off the view. If have permission to turn off the view, it actually toggles the active/inactive calendar in the database. A view/no view feature need to be added for multiple calendar views

**Comment by RealRancor** [comment]
> Also if you delete a calendar shared to you it deletes it for the original user. 

See: https://github.com/owncloud/calendar/pull/495

> A view/no view feature need to be added for multiple calendar views

See: https://github.com/owncloud/calendar/issues/21

**Comment by georgehrke** [comment]
@RealRancor thx for searching the related issues :)

**Comment by GazzaC** [comment]
Thanks @RealRancor  I didnt see anything about knowing which Calendar belongs to which user. If you hover over a calendar it should show you the Username of the UserID how shared it to you? Would be a useful feature I think, especially in cluttered Calendars @georgehrke
