### ISSUE TITLE
event from iPhone won't be synced to ownCloud Calendar

### ISSUE THREAD

**Issue by skriesch** [owncloud/calendar#787]
ownCloud 9.1.4 with Calendar

### Steps to reproduce
1. Add a Calendar to ownCloud
2. Give somebody write access to this Calendar
3. This person (with write access) syncs the Calendar to the iPhone.
4. This person wants to add an event to the Calendar via iPhone.
5. Data won't be synced to the ownCloud.
6. This person has got only write access via Web GUI.

### Expected behaviour
The person with write access can sync his data from his iPhone to the Calendar on ownCloud.

### Actual behaviour
Data won't be synced to ownCloud. The person hasn't got write access to the shared calendar via iPhone.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:**

**Database:** MySQL

**PHP version:**

**Server version:** 9.1.4

**Calendar version:** latest

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**List of activated apps:** Calendar (most important app)

**Comment by DeepDiver1975** [comment]
anything in error log?

**Comment by skriesch** [comment]
We didn't find anything in the error log of the ownCloud server. It is reproducible everywhere.
I heard about this issue at Chemnitzer LinuxTage and other events, too.
Use 2 mobile devices and share your calendar!

**Comment by DeepDiver1975** [comment]
> Use 2 mobile devices and share your calendar!

Doing this for many years since owncloud 5 and various calendar versions.
So I need more information about this.

Anyway .... calendar sync is part of core -> reopen in https://github.com/owncloud/core

**Comment by skriesch** [comment]
Seems it is fixed with 10.0.1:
https://github.com/owncloud/core/issues/26667
