### ISSUE TITLE
Should be able to follow "Webcal feeds"

### ISSUE THREAD

**Issue by multani** [owncloud/calendar#787]
There are some websites which expose events I'm registered to as "Webcal feeds", which are actually plain HTTP links towards .ics files.

ownCloud Calendar should be able to follow these events directly using the URL provided.

A bonus point would be to also export these events as CalDAV calendars so they are automatically discovered and imported when I sync my calendars with external applications (such as mobile phones, etc.)

**Comment by georgehrke** [comment]
duplicate

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/calendar/issues/192

**Comment by denysvitali** [comment]
"It's still in development" - on Aug 10, 2013

+1, that would be awesome
