### ISSUE TITLE
Invalid tzdata for Asia/Magadan

### ISSUE THREAD

**Issue by LebedinskySA** [owncloud/calendar#788]
I create an event on the phone at 22:30
![screenshot_2015-05-11-22-17-08](https://cloud.githubusercontent.com/assets/12394295/7565021/626fce72-f827-11e4-8980-bf9da685ee72.png)

However, the server calendar time shifts for 2 hours
![screenshot1](https://cloud.githubusercontent.com/assets/12394295/7565043/8f2eb7d4-f827-11e4-92d8-e50c238a03fe.png)

**Comment by georgehrke** [comment]
What timezone is set in the calendar settings?

**Comment by LebedinskySA** [comment]
Asia/Magadan
12 мая 2015 г. 2:02 AM пользователь "Georg Ehrke" <notifications@github.com>
написал:

**Comment by georgehrke** [comment]
can you please post the ics file

**Comment by LebedinskySA** [comment]
No problems. Exported from owncloud

BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.6.4
X-WR-CALNAME:Personal
BEGIN:VEVENT
DTSTAMP:20141221T031954Z
UID:20141221T031954Z-19941@3a6b18de230db921
DTSTART;TZID=Asia/Magadan:20141222T100000
DTEND;TZID=Asia/Magadan:20141222T110000
SUMMARY:Сервисное обслуживание Nissan
STATUS:CONFIRMED
ORGANIZER:mailto:df49.ru%20cal
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=CHAIR;PARTSTAT=ACCEPTED:mailto:df49.ru%20ca
 l
ATTENDEE;CN=stanislav@df49.ru;CUTYPE=INDIVIDUAL;ROLE=OPT-PARTICIPANT;PARTST
 AT=ACCEPTED:mailto:stanislav@df49.ru
LAST-MODIFIED:20141221T031954Z
BEGIN:VALARM
TRIGGER:-PT120M
ACTION:DISPLAY
DESCRIPTION:Сервисное обслуживание Nissan
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20141222T234310Z
UID:bf12a5d876
DTSTART;TZID=Asia/Magadan:20141225T080000
DTEND;TZID=Asia/Magadan:20141225T084000
SUMMARY:Сервисное обслуживание Ford
STATUS:TENTATIVE
LAST-MODIFIED:20141222T234310Z
BEGIN:VALARM
TRIGGER:-PT1440M
ACTION:DISPLAY
DESCRIPTION:Сервисное обслуживание Ford
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP;VALUE=DATE-TIME:20141230T083128Z
UID:20141225T221643Z-18089@3a6b18de230db921
DTSTART;VALUE=DATE-TIME;TZID=Asia/Magadan:20150105T100000
DTEND;VALUE=DATE-TIME;TZID=Asia/Magadan:20150105T110000
SUMMARY:Сервисное обслуживание Ford
LOCATION:Автосалон Nissan
STATUS:CONFIRMED
ORGANIZER:mailto:df49.ru%20cal
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=CHAIR;PARTSTAT=ACCEPTED:mailto:df49.ru%20ca
 l
LAST-MODIFIED;VALUE=DATE-TIME:20141230T083128Z
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER:-PT1440M
ACTION:DISPLAY
DESCRIPTION:Сервисное обслуживание Ford
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP;VALUE=DATE-TIME:20141230T083157Z
UID:20141227T145115Z-1414@3a6b18de230db921
DTSTART;VALUE=DATE-TIME;TZID=Asia/Magadan:20150109T100000
DTEND;VALUE=DATE-TIME;TZID=Asia/Magadan:20150109T110000
SUMMARY:Сервисное обслуживание Nissan
LOCATION:Пролетарская
STATUS:CONFIRMED
ORGANIZER:mailto:df49.ru%20cal
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=CHAIR;PARTSTAT=ACCEPTED:mailto:df49.ru%20ca
 l
LAST-MODIFIED;VALUE=DATE-TIME:20141230T083157Z
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER:-PT60M
ACTION:DISPLAY
DESCRIPTION:Сервисное обслуживание Nissan
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP;VALUE=DATE-TIME:20150123T041300Z
UID:20150123T040806Z-26116@ff002875acab6862
DTSTART;VALUE=DATE-TIME;TZID=Asia/Magadan:20150123T143000
DTEND;VALUE=DATE-TIME;TZID=Asia/Magadan:20150123T173000
SUMMARY:Testing
STATUS:CONFIRMED
TRANSP:TRANSPARENT
ORGANIZER:mailto:DF49%20личное
LAST-MODIFIED;VALUE=DATE-TIME:20150123T041300Z
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER:-PT2880M
ACTION:DISPLAY
DESCRIPTION:Testing
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20150314T233921Z
UID:20150314T233921Z-5445@185c563a603f6a69
DTSTART;TZID=Asia/Magadan:20150318T210000
DTEND;TZID=Asia/Magadan:20150318T220000
SUMMARY:Позвонить Паше по маслу
STATUS:CONFIRMED
ORGANIZER:mailto:stanislav@df49.ru
LAST-MODIFIED:20150314T233921Z
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Позвонить Паше по маслу
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20150511T120038Z
UID:20150511T120038Z-6461@185c563a603f6a69
DTSTART;TZID=Asia/Magadan:20150512T003000
DTEND;TZID=Asia/Magadan:20150512T013000
SUMMARY:Лол
STATUS:CONFIRMED
ORGANIZER:mailto:stanislav@df49.ru
LAST-MODIFIED:20150511T120038Z
BEGIN:VALARM
TRIGGER:-PT2880M
ACTION:DISPLAY
DESCRIPTION:Лол
END:VALARM
BEGIN:VALARM
TRIGGER:-PT1440M
ACTION:DISPLAY
DESCRIPTION:Лол
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by LebedinskySA** [comment]
In the fall of Magadan changed time shifted 2 hours ago.

**Comment by georgehrke** [comment]
> In the fall of Magadan changed time shifted 2 hours ago.

Ok, then you need to update the timezone-data on your server.  Not an issue in ownCloud.

**Comment by LebedinskySA** [comment]
On the server that's right, and synchronized through the carcass. I just suggested that the problem might be in it.

**Comment by LebedinskySA** [comment]
The calendar on the phone all right. In the browser, not the right time.

**Comment by georgehrke** [comment]
That might be the case, but ownCloud doesn't store any information like the offset of Asia/Magadan. If the offset was (permanently) changed in fall, you need to make sure that you have the latest packages for php and tzdata. And the tzdata stuff has nothing todo with ntp.

**Comment by LebedinskySA** [comment]
The server is configured correctly. I guarantee 100%. The problem may be in Android?

**Comment by LebedinskySA** [comment]
Tested calendar with iPad. Everything is fine. The problem in Android. Thank you for your participation.
