### ISSUE TITLE
Allowed memory size of 192MiB exhausted 

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/calendar#789]
How much memory does calendar and contacts requests need with oC? The amount of 192MiB does not seem to be enough obviously. We have quite some users syncing their cal and carddav data and want to keep memory assigned at a minimal level for each of the PHP processes!
Using stable7!

Here is the log:

2015/05/15 10:14:14 [error] 1411#0: *13257933 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 5477 bytes) in /var/www/oc/3rdparty/sabre/vobject/lib/Sabre/VObject/Reader.php on line 154" while reading response header from upstream, client: IP4, server: example.com, request: "REPORT /remote.php/caldav/calendars/user34/contact_birthdays/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/oc.sock:", host: "example.com"

2015/05/15 10:17:28 [error] 1409#0: *13267849 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getDateTime() on a non-object in /var/www/oc/3rdparty/sabre/vobject/lib/Sabre/VObject/Component/VEvent.php on line 44" while reading response header from upstream, client: IP2, server: example.com, request: "REPORT /remote.php/caldav/calendars/user55/feiertage_shared_by_xyz/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/oc.sock:", host: "example.com"

2015/05/15 10:19:18 [error] 1417#0: *13273373 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 5477 bytes) in /var/www/oc/3rdparty/sabre/vobject/lib/Sabre/VObject/Reader.php on line 154" while reading response header from upstream, client: IP, server: example.com, request: "REPORT /remote.php/caldav/calendars/user34/contact_birthdays/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/oc.sock:", host: "example.com"

2015/05/15 10:21:34 [error] 1408#0: *13280647 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getDateTime() on a non-object in /var/www/oc/3rdparty/sabre/vobject/lib/Sabre/VObject/Component/VEvent.php on line 44" while reading response header from upstream, client: IP2, server: example.com, request: "REPORT /remote.php/caldav/calendars/user55/feiertage_shared_by_xyz/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/oc.sock:", host: "example.com"

**Comment by georgehrke** [comment]
That highly depends on the number of events, I can't tell how much memory is needed, but apparently 192MiB is not enough

**Comment by georgehrke** [comment]
please assign more to fix the issue
