### ISSUE TITLE
calendars not available: Column not found: 1054 Unknown column 'publicuri' in 'field list'

### ISSUE THREAD

**Issue by mika** [owncloud/calendar#790]
### Steps to reproduce
1. Upgrade from owncloud v9.1.5-1.1 to v10.0.0-1.1
2. Upgrade calendar market app to latest market version v1.4.2
3. Visit calendar page of any user

### Expected behaviour
Calendars being available :)

### Actual behaviour
No calendars shown, instead owncloud log contains the following error message:

```
[...] Column not found: 1054 Unknown column 'publicuri' in 'field list' [...]
```

### Server configuration
**Operating system**: Debian/jessie 8.7

**Web server:** Apache 2.4.10-10+deb8u8

**Database:** MySQL 5.5.55-0+deb8u1

**PHP version:** 5.6.30+dfsg-0+deb8u1

**Server version:** 10.0.0 (stable)

**Calendar version:** 1.4.2

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.3
  - calendar: 1.4.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.2
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - federation: 0.1.0
  - files: 1.5.1   
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - external
  - files_antivirus
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oca2fehmtvi5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "[snip].info"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/[snip].info\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** TLS/SSL

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox/Iceweasel + Chromium

**Operating system:** Debian/jessie

**CalDAV-clients:** Thunderbird, Android

#### Log file (data/owncloud.log)
```
{"reqId": [...] "Exception: {\"Message\":\"An exception occurred while executing 'SELECT `publicuri` FROM `oc_dav_shares` WHERE (`resourceid` = ?) AND (`access` = ?)' with params [\\\"8\\\", 4]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'publicuri' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): 
[...]
```

**Comment by dennisbaaten** [comment]
I've got the same problem within similar environment.

**Comment by maxppc** [comment]
Same enviroment just using Chrome 57.0.2987.133 as browser.
The select points to **oc_dav_shares** table which have **principaluri** as meaningful column as far as I can see.

**Comment by synapticvoid** [comment]
Same here!

**Comment by Niduroki** [comment]
Also have this problem. Looks like something went wrong with the migrations for the DAV app here:
https://github.com/owncloud/core/blob/master/apps/dav/appinfo/Migrations/Version20170116150538.php#L510

@VicDeo you know something about this?

**Comment by DeepDiver1975** [comment]
core issue https://github.com/owncloud/core/issues/27754

**Comment by VicDeo** [comment]
@Kondou-ger Nice to meet you :)
Is it for a clean install or migration from 9.1.x?
This table is created if it doesn't exist:
```
if (!$schema->hasTable("{$this->prefix}dav_shares")) {
```

**Comment by Niduroki** [comment]
@VicDeo It's a migration from 9.1.0 for me, so the table does exist before, without the `publicuri` column by the looks of it.

**Comment by VicDeo** [comment]
Please test https://github.com/owncloud/core/pull/27756
