### ISSUE TITLE
Calendar Broken After Upgrade 9.1 -> 10.0

### ISSUE THREAD

**Issue by keassol** [owncloud/calendar#791]
### Steps to reproduce
1. Upgrade Owncloud fron 9.1 to 10.0
2. Enable/Upgrade Calendar App=
3. Browse to Calendar

### Expected behaviour
Calendar to load

### Actual behaviour
Calendar page loads but no calendars or event load, stays on spinner

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
MariaDB 10.1.22

**PHP version:**
PHP 5.6.30-10+deb.sury.org~trusty+2

**Server version:** (see your admin page)
10.0.0.12

**Calendar version:** (see the apps page)
1.4.2

**Updated from an older installed version or fresh install:**
Update

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```


No errors have been found.

```
Enabled:
  - activity: 2.3.3
  - calendar: true
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.8
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - grauphel: 0.6.4
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - files_antivirus
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "XXXXXXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXX"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "XXXXXXX",
        "mail_smtpmode": "php",
        "mail_domain": "XXXXXXX",
        "theme": "",
        "maintenance": false,
        "loglevel": 8,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud8",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "\/owncloud",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APC"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no 

### Client configuration
**Browser:**
FF 53.0 - also Cant access from Thunderbird Lightening 52.0.1 

**Operating system:**
All also:  Win 7 Pro up to date

**CalDAV-clients:**
Thunderbird Lightening 52.0.1 

#### Web server error log
--- none ---

#### Log file (data/owncloud.log)
{"reqId":"Ai9lzXeHLNLGkMuE3wK5","level":4,"time":"2017-04-27T19:11:27+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"XXX","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/calendars\/XXX\/","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `publicuri` FROM `oc_dav_shares` WHERE (`resourceid` = ?) AND (`access` = ?)' with params [\\\"4\\\", 4]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'publicuri' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `publicu...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `publicu...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `publicu...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1644): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(267): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getPublishStatus(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Publishing\\\/PublishPlugin.php(117): OCA\\\\DAV\\\\CalDAV\\\\Calendar->getPublishStatus()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropFind.php(98): OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\PublishPlugin->OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\{closure}()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Publishing\\\/PublishPlugin.php(124): Sabre\\\\DAV\\\\PropFind->handle('{http:\\\/\\\/calenda...', Object(Closure))\\n#10 [internal function]: OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\PublishPlugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('calendars\\\/XXXX', Array, 1)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#16 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(226): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"XXXX\"}"}
{"reqId":"PnR3NkG9sKCay14QDMlm","level":4,"time":"2017-04-27T19:24:09+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"XXX","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/calendars\/XXX\/","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `publicuri` FROM `oc_dav_shares` WHERE (`resourceid` = ?) AND (`access` = ?)' with params [\\\"4\\\", 4]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'publicuri' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `publicu...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `publicu...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `publicu...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1644): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(267): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getPublishStatus(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Publishing\\\/PublishPlugin.php(117): OCA\\\\DAV\\\\CalDAV\\\\Calendar->getPublishStatus()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropFind.php(98): OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\PublishPlugin->OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\{closure}()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Publishing\\\/PublishPlugin.php(124): Sabre\\\\DAV\\\\PropFind->handle('{http:\\\/\\\/calenda...', Object(Closure))\\n#10 [internal function]: OCA\\\\DAV\\\\CalDAV\\\\Publishing\\\\PublishPlugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('calendars\\\/XXXX', Array, 1)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#16 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(226): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"XXXX\"}"}

#### Browser log
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
uncaught exception: CalDAV client could not be initialized - Querying calendars failed  (unknown)

**Comment by keassol** [comment]
Additional Note: Error log I saw Unknown column 'publicuri' in 'field list'

Looking the the table oc_dav_shares there is a column named "principaluri" but no column named "publicuri"

**Comment by keassol** [comment]
Additional Note: Error log I saw Unknown column 'publicuri' in 'field list'

Looking the the table Calendar Broken After Upgrade 9.1 -> 10.0 · Issue #791 · owncloud/calendar

**Comment by cploeger** [comment]
I have the same issue running Ubuntu 16.04.2 on a Raspberry Pi 3

This is the list of apps I have installed:
Enabled:
  - activity: 2.3.3
  - calendar: true
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.10.0.0
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - external
  - user_external

I'm using Redis for caching and the logfile shows the same errors that keassol posted.

**Comment by cploeger** [comment]
I just did an additional test by creating a new appointment on my mobile. I was able to sync it to my Owncloud server and after syncing my tablet, the appointment appeared at it too.

So it looks as if the calendars and CalDav sync are working and only displaying the calendars in the app fails.

**Comment by binarykitchen** [comment]
having the same problem here `Column not found: 1054 Unknown column 'publicuri' in 'field list'` - just were upgrading to v10 too

**Comment by binarykitchen** [comment]
guess it is related to https://github.com/owncloud/core/issues/27754

**Comment by binarykitchen** [comment]
workaround `ALTER TABLE oc_dav_shares ADD publicuri VARCHAR(255) NOT NULL AFTER principaluri;` does it for me

**Comment by law** [comment]
Same here - calendars do not load in the GUI, etc.

**Comment by jdpipe** [comment]
same for me. i have to revert to now owncloud 9.1 to get back online.
i think that owncloud 10 should not have been pushed to 'stable' until this issue had been checked. calendar is not 'core' though, so perhaps I have to be more careful about assuming that 'apt upgrade' is going to be safe in general.

**Comment by DeepDiver1975** [comment]
duplicate - please look here https://github.com/owncloud/core/issues/27754
