### ISSUE TITLE
not possible to create an event after integrating the Calendar App

### ISSUE THREAD

**Issue by SL1n** [owncloud/calendar#792]
When i try to create an event i get this log message:

 Fatal 	index 	Exception: {"Message":"You must pass a \\Sabre\\VObject\\Component, \\Sabre\\VObject\\Property or scalar type","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php(893): Sabre\\VObject\\Component->__set('CREATED', Object(DateTime))\n#1 \/var\/www\/owncloud\/apps\/calendar\/ajax\/event\/new.php(22): OC_Calendar_Object::createVCalendarFromRequest(Array)\n#2 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#3 [internal function]: __lambda_func(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_1346', Array)\n#5 \/var\/www\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/calendar\/...')\n#6 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/Component.php","Line":365} 

i'm using ownCloud 8.0.3

**Comment by georgehrke** [comment]
please use the issue template as described in our contributing guidelines.

> integrating the Calendar API

What API?
What does the request look like you send?

**Comment by SL1n** [comment]
After cloning this calendar app as described in the README the normal "create a new event" functionality via the owncloud webinterface isn't working anymore with the log message described above. actually i want to use the JSON API as described in the wiki area.

**Comment by georgehrke** [comment]
> After cloning this calendar app as described in the README the normal "create a new event" functionality via the owncloud webinterface isn't working anymore with the log message described above.

Can't reproduce, please use the issue template.

> actually i want to use the JSON API as described in the wiki area.

Those are drafts and not implemented on the latest master branch.

**Comment by SL1n** [comment]
### Steps to reproduce
1. Install owncloud 8.0.3 via package installation on Ubuntu 14.04
2. Including the Calendar App by cloning master branch "git clone git://github.com/owncloud/calendar.git"
3. Enable Calendar APP via http://localhost/owncloud/index.php/settings/apps
4. creating Calendar 
5. try to add an event to it


### Expected behaviour
Event should be created

### Server configuration
**ubuntu 14.04**

**apache2  service ver. 0.91-ubuntu1**
**sqlite3**
**PHP 5.5.9**
**Owncloud 8.0.3.4**
fresh installed
installed apps/ content of "/app" folder:
 activity
calendar
external files
files_encryption
files_external
 files_locking
 files_pdfviewer
 files_sharing
files_texteditor
files_trashbin
files_versions
files_videoviewer
firstrunwizard
 gallery
 provisioning_api
 templateeditor
 user_external
 user_ldap
 user_webdavauth

//config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocqo3ad8tt12',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.3.4',
  'installed' => true,
);
**Are you using encryption:** no
**Are you using an external user-backend** no


### Client configuration
**Browser:** Firefox 38.0
#### ownCloud log
{"reqId":"63ad4d9cb84a3638233da8077f0762ce","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"You must pass a \\\\Sabre\\\\VObject\\\\Component, \\\\Sabre\\\\VObject\\\\Property or scalar type\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/object.php(893): Sabre\\\\VObject\\\\Component->__set('CREATED', Object(DateTime))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/ajax\\\/event\\\/new.php(22): OC_Calendar_Object::createVCalendarFromRequest(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 [internal function]: __lambda_func(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_35', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Sabre\\\/VObject\\\/Component.php\",\"Line\":365}","level":4,"time":"2015-05-22T13:36:22+00:00"}


#### Web server error log
no error log

 #### Browser log
http://localhost/owncloud/index.php/apps/calendar/ajax/event/new.php [HTTP/1.1 500 Internal Server Error 38ms]


hope thats enough

Is the Calendar JSON API available via the rework branch? Or is there another possibility to access the calendar data from an external app?

Thanks in advance

**Comment by georgehrke** [comment]
The master branch does not work with ownCloud 8. If you insist on using the git version (which is not recommended for production), please use the stable8 branch.
