### ISSUE TITLE
Buttton for calendar sharing missing from UI

### ISSUE THREAD

**Issue by deltaphi** [owncloud/calendar#794]
### Steps to reproduce
1. Install OwnCloud 8.0.3 from OpenSuse build service
2. Manually install Calendar (release 8.0.3)
3. Create a calendar
4. Attempt to share the calendar with another user (read-only)

### Expected behaviour
There should be a button in the OwnCloud UI that allows me to share the calendar.

### Actual behaviour
The button for sharing a calendar is missing. See the following screenshot:

![bildschirmfoto 2015-05-23 um 23 25 44](https://cloud.githubusercontent.com/assets/2348915/7785822/28e604ac-01a3-11e5-8a7b-0ee85bc3e556.png)

I can share individual events from this calendar. In case this is relevant - sharing files between users does work.

How can I give other users read access to my calendar?

### Server configuration
**Operating system**: Debian 8, Running on Raspberry Pi 2

**Web server:** lighttpd 1.4.53

**Database:** Mysql 5.5

**PHP version:** PHP 5.6.7

**ownCloud version:** ownCloud 8.0.3 (stable)

**Updated from an older ownCloud or fresh install:** Updated from older ownCloud install

**List of activated apps:**

Enabled:
 - activity
 - calendar
 - contacts
 - files
 - files_locking
 - files_markdown
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - user_pwauth

Disabled:
 - external
 - files_encryption
 - files_external
 - files_videoviewer
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'hostname',
    1 => 'external.domain.com',
  ),
  'datadirectory' => '/home/owncloud-data',
  'overwrite.cli.url' => 'https://hostname/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'enable_previews' => false,
  'appcodechecker' => true,
  'user_pwauth' =>
  array (
    'pwauth_path' => '/usr/sbin/pwauth',
  ),
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** PwAuth

### Client configuration
**Browser:** Chrome

**Operating system:** OSX 10.10

#### Web server error log
Error log is empty.

#### ownCloud log (data/owncloud.log)
No entries have appeared in the owncloud log.

#### Browser log
No log available.

**Comment by RealRancor** [comment]
Hi,

that is mostly caused by Adblock/uBlock removing this share button:

https://github.com/owncloud/calendar/issues/747 , https://github.com/owncloud/calendar/issues/679 , https://github.com/owncloud/calendar/issues/713 , https://github.com/owncloud/calendar/issues/661

**Comment by deltaphi** [comment]
Hello,

thank you RealRancor, AdBlock was my problem as well. As this appears to come up rather requently -a small note in the user manual would be helpful. Perhaps something like the following: "Note: If the 'Share Calendar' button does not appear, try disabling your ad blocker."

Regards,
deltaphi

**Comment by RealRancor** [comment]
Hi,

from my PoV this needs to be fixed within the AdBlock rules rather than documented within the user manual of OC. But if you think that should be done feel free to request this at:

https://github.com/owncloud/documentation/issues

or even contribute to the documentation:

https://github.com/owncloud/documentation/blob/master/CONTRIBUTING.rst

by doing a Pull Request.

**Comment by deltaphi** [comment]
Hello,

I agree that this should be properly fixed in AdBlock. However, I figured that having a hint in the user manual couldn't hurt, so I created a pull request.

Regards,
deltaphi
