### ISSUE TITLE
Address Book buttons for share,delete,etc hidden in Safari

### ISSUE THREAD

**Issue by atrias** [owncloud/calendar#795]
When using safari browser the buttons that would allow to share, delete, download, etc for Address Books are not displayed. On firefox it works fine.

Expected result in firefox:
![firefox](https://cloud.githubusercontent.com/assets/1192231/7788709/0e1f5972-0250-11e5-8b36-7a02a52d9b64.png)

Buttons missing in safari:
![safari](https://cloud.githubusercontent.com/assets/1192231/7788716/427a4a2e-0250-11e5-9cc4-19f2b10e344f.png)

Safari ver. 8.0.6 (no extensions installed)
OSX 10.10

**Comment by georgehrke** [comment]
this is calendar, not contacts, please reopen in the contacts repo

**Comment by atrias** [comment]
oops sorry!! :D
