### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/calendar#798]
Hi,

I do not understand, in the github release page, I see that the module calendar seems in v8.1.0beta2, but in my owncloud apps page, it's 0.6.4. 
How do I know i have the lastest version ?

Thank

**Comment by georgehrke** [comment]
https://apps.owncloud.com/content/show.php?content=168707
It's says 0.6.4 as well. (in the upper left corner)

**Comment by awikatchikaen** [comment]
It's a weird numerotation, but ok ...

Thank you

**Comment by georgehrke** [comment]
8.1 is the ownCloud version number
0.6.4 is the calendar version number

**Comment by awikatchikaen** [comment]
So in the apps store, the name is "Calendar 8.0", so when i'll upgrade OC to 8.1, I'll have to reinstall a new app "Calendar 8.1" ? Or Will I have an app "Calendar 8.0" on my OC 8.1, 8.2, 9.x, 10.x ?
