### ISSUE TITLE
[stable8] caldav not work

### ISSUE THREAD

**Issue by askovpen** [owncloud/calendar#799]
### Steps to reproduce
add to ios  calendar https://cloud.some/remote.php/caldav/principals/username

### Expected behaviour
no errors

### Actual behaviour
```
2015/05/28 19:43:51 [error] 22011#0: *12199 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/cloudhome/apps/calendar/sabre/main.php' (include_path='/cloudhome/3rdparty/phpseclib/phpseclib/phpseclib:/cloudhome/3rdparty/pear/pear_exception:/cloudhome/3rdparty/pear/archive_tar:/cloudhome/lib/private:/cloudhome/config:/cloudhome/3rdparty:/cloudhome/apps:/cloudhome/lib:.:/usr/share/php5:/usr/share/php:/cloudhome') in /cloudhome/remote.php on line 54" while reading response header from upstream, 
client: 192.168.1.123, server: cloud.some, request: "PROPFIND /remote.php/caldav/principals/username/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cloud.some"
```

### Server configuration
**Operating system**: x86_64 linux

**Web server:** nginx 1.7.6

**Database:** mariadb 10.0.19

**PHP version:** 5.5.21

**ownCloud version:** 8.0.3 (git) [stable8]

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:**  
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - files
 - files_antivirus
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - galleryplus
 - updater
 - user_webdavauth

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'trusted_domains' => 
  array (
    0 => 'cloud.some',
  ),
  'datadirectory' => '/cloudhome/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'installed' => true,
  'forcessl' => true,
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '1',
  'secret' => '...',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

Seriously, bug reports like this, just pasting an error message into github issues, are completely useless ...

**Comment by askovpen** [comment]
i update

**Comment by RealRancor** [comment]
Looks to me like the same issue as in https://github.com/owncloud/calendar/issues/777

**Comment by askovpen** [comment]
yes. two commands to work:

```sql
UPDATE `oc_appconfig` set `configvalue`='calendar/appinfo/remote.php' where `configkey`='remote_caldav';
UPDATE `oc_appconfig` set `configvalue`='calendar/appinfo/remote.php' where `configkey`='remote_calendar';
```

thanks. why it no autoupdate?

**Comment by RealRancor** [comment]
@askovpen 
> why it no autoupdate?

The user in this linked issue had this problem because he had used the master branch of the calendar app which is a development version. If you did the same then it should be obvious that such stuff can happen on a development version.

**Comment by askovpen** [comment]
calendar version 0.6.4 [stable8]
appinfo/info.xml:
```
...
        <remote>
                <calendar>appinfo/remote.php</calendar>
                <caldav>appinfo/remote.php</caldav>
        </remote>
...
```
appinfo/preupdate.php need 
```sql
UPDATE `oc_appconfig` set `configvalue`='calendar/appinfo/remote.php' where `configkey`='remote_caldav';
UPDATE `oc_appconfig` set `configvalue`='calendar/appinfo/remote.php' where `configkey`='remote_calendar';
```

**Comment by askovpen** [comment]
hmm. [master](https://github.com/owncloud/calendar/tree/master) and [stable8](https://github.com/owncloud/calendar/tree/stable8) branch have same version - 0.6.4

**Comment by georgehrke** [comment]
> hmm. master and stable8 branch have same version - 0.6.4

nevertheless, the codebase is different. The caldav implementation changed.
