### ISSUE TITLE
implement sharing gui for sharing events

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#8]

**Comment by georgehrke** [comment]
removed milestone, we first need a milestone for #46. This will be taken care of in a later sprint.

**Comment by georgehrke** [comment]
I'm not even sure if sharing single events will be possible anymore.

**Comment by raghunayyar** [comment]
@georgehrke ???

**Comment by georgehrke** [comment]
We will use CalDAV sharing and not the ordinary ownCloud sharing API

**Comment by georgehrke** [comment]
will be replaced by attendee-support
