### ISSUE TITLE
Events don't sync from Client

### ISSUE THREAD

**Issue by felixbello** [owncloud/calendar#801]
### Steps to reproduce
1. Fresh Install of ownCloud 9.1.6 (stable)
2. Following the Steps of #800 to install the Calendar App
3. Add CalDav Calendar on MacOS
4. Create an Event on the Calendar

### Expected behaviour
The Event should be synchronized with the Server, it should appear on the Server.

### Actual behaviour
The Event don't Synchronize
(when you create an Event on the Server it appears on the Client but not the other way.)

### Server configuration
**Operating system**:
Debian GNU/Linux 8

**Web server:**
Apache2

**Database:**
mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Server version:** (see your admin page)
ownCloud 9.1.6 (stable)

**Calendar version:** (see the apps page)
Calendar  1.4.2

**Updated from an older installed version or fresh install:**
fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
Enabled:
  - activity: 2.3.2
  - calendar: true
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc10yf47r28k",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstoreurl": "https:\/\/marketplace.owncloud.com\/api\/v0",
        "trusted_domains": [
            "sarah.behost.ch"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx.xxx.xxx",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "mainOwnCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": false,
        "loglevel": 4
    }
}
```

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

**Operating system:**
MacOS

**CalDAV-clients:**
Calendar

#### Web server error log
no errors
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```
empty!

**Comment by ghost** [comment]
Hi,

the calendar app is only a frond-end for the calendar sync functionality in the "core" of ownCloud. Its not responsible for any sync issues so closing here for now.

The experiences have shown that such issues like you're facing are mostly caused by server mis-configurations (server is blocking specific HTTP verbs and so on). 

Please jump over to central.owncloud.org first. There a large FAQ about such issues exists here:

https://central.owncloud.org/t/how-to-fix-caldav-carddav-webdav-problems/852

If that doesn't help you can create a new thread there (login with your github account) asking for further help / support. Once it is clearly a bug in ownCloud (which i currently doubt) you can re-create a new issue in https://github.com/owncloud/core/issues

Thanks
