### ISSUE TITLE
PHP Fatal error trying to find OC\\Connector\\Sabre\\Auth

### ISSUE THREAD

**Issue by aidanamavi** [owncloud/calendar#802]
PHP Fatal error:  Class 'OC\\Connector\\Sabre\\Auth' not found in /owncloud/apps/calendar/appinfo/remote.php on line 22

ownCloud 8.0.3
Calendar 8 0.6.4

Any ideas what might be causing this?

**Comment by RealRancor** [comment]
Hi,

seems you're using the current git master of the calendar app containing this line:

https://github.com/owncloud/calendar/blob/master/appinfo/remote.php#L22

This is not compatible with OC8 as the version for 8.0.3 contains a different line:

https://github.com/owncloud/calendar/blob/v8.0.3/appinfo/remote.php#L22

**Comment by aidanamavi** [comment]
Thanks for your response! This indeed was the problem.

I'm a new ownCloud contributor. I read the README.md file, but it could be more clear. Is 'rework' the branch with the most recent commits? What purpose does the branch 'rework2' serve?

**Comment by RealRancor** [comment]
Maybe @georgehrke can answer this question.

**Comment by georgehrke** [comment]
> Is 'rework' the branch with the most recent commits?

It's a rewritten calendar app, that will replace the current master branch, past the release of ownCloud 8.1.

> What purpose does the branch 'rework2' serve?

This was just for `backup`-reasons, because a while back I had to force push onto rework. It can just be deleted.

**Comment by aidanamavi** [comment]
Thanks for the info!

**Comment by jancborchardt** [comment]
> > What purpose does the branch 'rework2' serve?
> 
> This was just for backup-reasons, because a while back I had to force push onto rework. It can just be deleted.

@georgehrke can you delete it then? It’s easily possible from https://github.com/owncloud/calendar/branches

**Comment by georgehrke** [comment]
> @georgehrke can you delete it then?

done
