### ISSUE TITLE
Synchronizing  ONE way ONLY

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#803]
I use davdroid 0.8 on my ANDROID Tab with Lollipop 5.0.2, established a sync account successfully. However, the data only will be synced one way  form OC 8.0.3 calendar to the tablet. However, the other way around FROM tablet to OC 8.0.3 calendar does not work at all!

Why ? What went wrong?
regards, hiatm4450

**Comment by hitam4450** [comment]
Problem solved!

**Comment by RealRancor** [comment]
@hitam4450 Could be useful if you're posting how did you solved the problem here and at your forums thread (which you apparently have deleted?).
