### ISSUE TITLE
Importing / subscribing online calendar

### ISSUE THREAD

**Issue by hitam4450** [owncloud/calendar#806]
How about directly importing an online calendar or in addition subscribing directly with an online calendar?

regards, hitam4450

**Comment by georgehrke** [comment]
dup, please use search before creating new issues ........

**Comment by hitam4450** [comment]
Sorry, my search did not gave any results...........

**Comment by RealRancor** [comment]
@hitam4450 See: https://github.com/owncloud/calendar/issues/192

**Comment by hitam4450** [comment]
Thanks RealRancor! The script is a real help!
