### ISSUE TITLE
Share link icon hidden in a variety of browsers

### ISSUE THREAD

**Issue by gatoperez1** [owncloud/calendar#810]
This is very similar to #795, albeit in this case it *is* Calendar's problem.

![23810_0_calendar oc](https://cloud.githubusercontent.com/assets/12861747/8132275/dd62783e-1120-11e5-9b8d-20b11a0506a6.jpg)

That screenshot was taken on Firefox 38.0.5 Windows and as you can see, the share link is missing. It does appear, for example, on FF 37.0.1 Linux, but not on FF 29.0 on Android. The link appears on whichever Internet Explorer comes with Windows 8 (sorry, can't be more precise) but the username / group to share with field does not provide suggestions or respond (different bug though).

Finally, FF 36.0.4 on Windows works correctly.

**Comment by georgehrke** [comment]
Is adblock enabled?
please disable it

**Comment by gatoperez1** [comment]
Yes, it is enabled in every Firefox browser tested. Including those where this does work.

**Comment by gatoperez1** [comment]
I confirm that disabling AdBlock, at least on FF29 Android, does bring back the "share" link.

I should also note that the "Files" section, for example, is not affected by AdBlock.

**Comment by gatoperez1** [comment]
FYI. Bug report on AdBlock forum: https://adblockplus.org/forum/viewtopic.php?f=1&t=34638

**Comment by RealRancor** [comment]
@gatoperez1 
Thanks for reporting. There is also an older report to the easylist maintainer here: https://forums.lanik.us/viewtopic.php?f=64&t=20824&p=66962
