### ISSUE TITLE
Can not edit calendar entries via Web UI in complex editing mode.

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/calendar#810]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
Tell us what should happen
Normal editing of the calendar entries, as well as before the update.

### Actual behaviour
Tell us what happens instead
Shows complex editing mode, but can not update entries

### Server configuration

**Operating system**:

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**

**ownCloud version:** (see your admin page)
10.0.2
**Calendar version:** (see the apps page)
1.5.3
**Updated from an older installed version or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2017-09-15 11-03-30](https://user-images.githubusercontent.com/1005065/30474963-894d9ff6-9a05-11e7-88dd-ec8558919104.png)

There is indeed something wrong ....
