### ISSUE TITLE
Shared calendar gets unselected by logout

### ISSUE THREAD

**Issue by voroyam** [owncloud/calendar#812]
### Steps to reproduce
1. share a calendar
2. select the shared calendar
3. log out

### Expected behaviour
shared calendar stays selected after logout

### Actual behaviour
shared calendar gets unselected

owncloud 10.0.2

Calendar newest version

**Comment by DeepDiver1975** [comment]
assigning @VicDeo because the fix is in core owncloud/core#27005

**Comment by VicDeo** [comment]
Fixed in 10.0.4beta2
master:  owncloud/core#29136
stable10:  owncloud/core#29273

**Comment by DeepDiver1975** [comment]
@voroyam can you please test this with 10.0.4beta2 ? THX

**Comment by VicDeo** [comment]
@DeepDiver1975 beta2 is unreleased, it's basically current stable10 
I just wanted to stress out that beta1 still has no fix for this issue :)

**Comment by DeepDiver1975** [comment]
this is fixed with owncloud 10.0.4
