### ISSUE TITLE
Incorrect times when creating an appointment in "Week"

### ISSUE THREAD

**Issue by dotDE** [owncloud/calendar#812]
Hello,

If i create a new appointment in the "Week"-View by selecting and pull the mouse in the calendar, the time shown in the window, is exactly 1 hour earlier.

I hope anybody can fix this. (Or is it only on my OwnCloud?!)

**Comment by georgehrke** [comment]
Please check the time zone setting in the calendar settings.

Please excuse my brevity and typos.

**Comment by dotDE** [comment]
Thank you for your fast answer. Yes! That works. But am i able to setup this as a default setting in my Administrator-Panel?

**Comment by georgehrke** [comment]
just tell tour users to allow ownCloud to locate them.
