### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Tman99** [owncloud/calendar#813]
### Steps to reproduce
1. Install calendar version 1.5.4 from apps page.
2. Try to access the calendar from any account.
3.  internal system error is shown instead of a calendar page.

### Expected behaviour
Tell us what should happen

Should see a calendar page.

### Actual behaviour
Tell us what happens instead

An internal server error is displayed instead.

Log file shows:

Error | calendar | Could not find resource file "/apps/calendar/js/vendor/autosize/dist/autosize.js"

Error | core | Exception: {"Exception":"RuntimeException","Message":"The source  file  \"\/var\/www\/owncloud\/apps\/calendar\/js\/vendor\/autosize\/dist\/autosize.js\"  does not exist.","Code":0,"Trace":"#0  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/BaseAsset.php(103):  Assetic\\Asset\\FileAsset->load()\n#1  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/AssetCollection.php(151):  Assetic\\Asset\\BaseAsset->dump(NULL)\n#2  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/AssetWriter.php(68):  Assetic\\Asset\\AssetCollection->dump()\n#3  \/var\/www\/owncloud\/lib\/private\/TemplateLayout.php(232):  Assetic\\AssetWriter->writeAsset(Object(Assetic\\Asset\\AssetCollection))\n#4  \/var\/www\/owncloud\/lib\/private\/TemplateLayout.php(143):  OC\\TemplateLayout->generateAssets()\n#5  \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(229):  OC\\TemplateLayout->__construct('user', 'calendar')\n#6  \/var\/www\/owncloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(156):  OC_Template->fetchPage()\n#7  \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(112):  OCP\\AppFramework\\Http\\TemplateResponse->render()\n#8  \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(99):  OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Calendar\\Controller\\ViewController),  'index')\n#9  \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46):  OC\\AppFramework\\App::main('ViewController', 'index',  Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10  [internal function]:  OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11  \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280):  call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler),  Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(891):  OC\\Route\\Router->match('\/apps\/calendar\/')\n#13  \/var\/www\/owncloud\/index.php(54): OC::handleRequest()\n#14  {main}","File":"\/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/FileAsset.php","Line":62}
-- | -- | --

Error | core | Exception: {"Exception":"RuntimeException","Message":"The source  file  \"\/var\/www\/owncloud\/apps\/calendar\/js\/vendor\/autosize\/dist\/autosize.js\"  does not exist.","Code":0,"Trace":"#0  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/BaseAsset.php(103):  Assetic\\Asset\\FileAsset->load()\n#1  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/AssetCollection.php(151):  Assetic\\Asset\\BaseAsset->dump(NULL)\n#2  \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/AssetWriter.php(68):  Assetic\\Asset\\AssetCollection->dump()\n#3  \/var\/www\/owncloud\/lib\/private\/TemplateLayout.php(232):  Assetic\\AssetWriter->writeAsset(Object(Assetic\\Asset\\AssetCollection))\n#4  \/var\/www\/owncloud\/lib\/private\/TemplateLayout.php(143):  OC\\TemplateLayout->generateAssets()\n#5  \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(229):  OC\\TemplateLayout->__construct('error', '')\n#6  \/var\/www\/owncloud\/lib\/private\/Template\/Base.php(129):  OC_Template->fetchPage()\n#7  \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(361):  OC\\Template\\Base->printPage()\n#8  \/var\/www\/owncloud\/index.php(73):  OC_Template::printExceptionErrorPage(Object(RuntimeException))\n#9  {main}","File":"\/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/FileAsset.php","Line":62}
-- | -- | --

*** Note: Looking at the above indicated path for the missing autosize.js file reveals that the entire folder /apps/calendar/js/vendor is missing and is not being installed with the app. ***

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see your admin page)

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Which owncloud version are you using? Please disable the asset pipeline - calendar does not work with the asset pipline.

**Comment by ghost** [comment]
No feedback after some months -> Closing

I guess this would be either fixed with https://github.com/owncloud/calendar/pull/822 (from https://github.com/owncloud/calendar/issues/821) or by disabling the asset pipeline (which is gone in newer ownCloud versions as well).
