### ISSUE TITLE
Problem with catalan translation

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#814]
OwnCloud 10.0.2 (stable) 
Calendar version 1.5.4

The file /apps/calendar/js/public/vendor.min.js has the catalan translation in what I suppose it's the old format. The month names for example are displayed as "Undefined" instead of the proper way.

I would send a patch against the file in the git repo but it's simply not there. I can't find any vendor.min.js file in the calendar git or even in the core project. Anyway, attached is the corrected vendor.min.js file and at least it works for me (I just changed the catalan translation to match the new format).

[vendor.min.js.zip](https://github.com/owncloud/calendar/files/1313434/vendor.min.js.zip)

**Comment by duub** [comment]
having same issue with oc 10.0.3 and calendar 1.5.4

**Comment by DeepDiver1975** [comment]
@serginuez can you please point me to the change you did? Its not that easy to find your changes - THX

**Comment by ghost** [comment]
the catalan part is the attached (as it's minified and I cannot find the regular file it's really a mess to manage it). I had to redo all the catalan section, as the variables and structures used looked like they were written for an older i18n format.

[catalan.txt](https://github.com/owncloud/calendar/files/1590984/catalan.txt)

**Comment by Julian1998** [comment]
@serginuez Is this fixed in oc 10.0.5? I switched to catalan and the month names are working fine?
The file you searched for is https://github.com/owncloud/core/blob/v9.1.6/core/vendor/moment/min/moment-with-locales.js

**Comment by ghost** [comment]
just updated to 10.0.5 and it still says undefined. Made a clean install and got the same result. Are you sure that the moment-with-locales.js is the file that creates apps/calendar/js/public/vendor.min.js? There are differences between them, strings that appear on the latter and not on the former.
If I set it to another language (italian for example) it works fine.

**Comment by Julian1998** [comment]
@serginuez So I switched to catala and it's working fine... Sorry that I have to ask that but did you run the Makefile?

**Comment by Julian1998** [comment]
@serginuez Please test that PR so I can see if Catalan is fixed now :)

https://github.com/owncloud/calendar/pull/907

**Comment by ghost** [comment]
Sorry, but I've tried to build the calendar app and I keep getting npm build errors, which I'm quite sure are because I have somenthing missing in my system or something not well configured (I have never worked with nodejs).

**Comment by Julian1998** [comment]
No problem... Just post it here and I will help you (if you like to)

**Comment by DeepDiver1975** [comment]
you can test our rc - [calendar-1.5.8-rc1.tar.gz](https://github.com/owncloud/calendar/files/2093329/calendar.tar.gz)

**Comment by DeepDiver1975** [comment]
closing since the user disappeared from github
