### ISSUE TITLE
HTTP error 503 when syncing with Thunderbird (w/Lightning 3.3.3)

### ISSUE THREAD

**Issue by Aquilus** [owncloud/calendar#816]
The calendar app doesn't sync with Thunderbird lightning anymore.

__Steps to reproduce__
initial cause unknown; Syncing the calender from different clients (Windows/Linux) leads to the problem.

__Expected behaviour__
The calendar app syncs with Thunderbird lightning.

__Actual behaviour__
Syncing on client-side: Thunderbird Lightning is not able to sync with the owncloud calendar app. Only on Windows-based systems, Thunderbird returns the message, that the calendar is unable to sync. Within Linux context it silently fails.
Syncing on server-side: The owncloud logfile is empty, besides the log-level is set to 0 (debug?). But Apache's access.log shows a lot of errors like 

_[IP] - - [19/Jun/2015:13:58:26 +0200] "PUT /owncloud/remote.php/caldav/calendars/[user]/[calendar]/[hash].ics HTTP/1.1" 503 2379 "-" "-"_
and
_[IP] - - [19/Jun/2015:13:58:26 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/[user]/[calendar]/ HTTP/1.1" 503 2379 "-" "-"_

As far as I can tell, there are no other errors. Also the calendar synced without any problem for about half a year before this issue came up.

__System__: Linux 3.8.13.3 #1 SMP PREEMPT Sat Jun 22 00:52:21 BRT 2013 armv7l GNU/Linux

__Apache__: Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u1 mod_ssl/2.2.22 OpenSSL/1.0.1e mod_wsgi/3.3 Python/2.7.3 configured

__MySQL__: mysql Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (armv7l) using readline 6.2

__PHP__: PHP 5.4.36-0+deb7u1 (cli)

__Owncloud__: 8.0.0.7 (Debian package)

__Calendar-App__: 0.6.4 (Debian package)

__Client__: Thunderbird 31.7.0 w/ Lightning 3.3.3

**Comment by georgehrke** [comment]
What about apache's error log?

Please excuse my brevity and typos.

**Comment by Aquilus** [comment]
With Apache's loglevel set to debug, there is some basic information about Apache in it:

[Fri Jun 19 13:57:58 2015] [info] Shared memory session cache initialised
[Fri Jun 19 13:57:58 2015] [info] Init: Initializing (virtual) servers for SSL
[Fri Jun 19 13:57:58 2015] [warn] RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Jun 19 13:57:58 2015] [warn] RSA server certificate CommonName (CN) `[...]' does NOT match server name!?
[Fri Jun 19 13:57:58 2015] [info] mod_ssl/2.2.22 compiled against Server: Apache/2.2.22, Library: OpenSSL/1.0.1e
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=595): Initializing Python.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=596): Initializing Python.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=597): Initializing Python.
[Fri Jun 19 13:57:58 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u1 mod_ssl/2.2.22 OpenSSL/1.0.1e mod_wsgi/3.3 Python/2.7.3 configured -- resuming normal operations
[Fri Jun 19 13:57:58 2015] [info] Server built: Dec 27 2014 21:29:22
[Fri Jun 19 13:57:58 2015] [debug] prefork.c(1023): AcceptMutex: sysvsem (default: sysvsem)
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=598): Initializing Python.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=599): Initializing Python.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=596): Attach interpreter ''.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=597): Attach interpreter ''.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=598): Attach interpreter ''.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=595): Attach interpreter ''.
[Fri Jun 19 13:57:58 2015] [info] mod_wsgi (pid=599): Attach interpreter ''.
[Fri Jun 19 13:58:21 2015] [info] mod_wsgi (pid=602): Initializing Python.
[Fri Jun 19 13:58:21 2015] [info] mod_wsgi (pid=602): Attach interpreter ''.

**Comment by georgehrke** [comment]
> Only on Windows-based systems, Thunderbird returns the message, that the calendar is unable to sync.

Does it provide a proper error message besides that?

please check your ownCloud and server logging settings. ownCloud.log can simply not be empty, when you set the log level to debug!

**Comment by RealRancor** [comment]
A possible reason could be:

> RSA server certificate CommonName (CN) `[...]' does NOT match server name!?

For general hints about *DAV issues have a look at:

https://forum.owncloud.org/viewtopic.php?f=17&t=7536

**Comment by Aquilus** [comment]
@RealRancor As far as I can see this thread does not provide details to my problem at all. Also, please understand, that the calendar sync has been working for at least six months without any interruptions. So I really doubt that the stated behaviour is of a general kind.

@georgehrke Thanks for the pointer. I double checked the existance of owncloud.log and came to the conclusion, that there are two log files on the server system. One in located in /var/log/ and the other (filled) one is to be found in /var/www/owncloud/data/owncloud.log . There are a lot of entries like


```
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:47:43+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/"}
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:47:44+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/[calendar2]\/"}
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:47:44+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/[calendar1]\/"}
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:47:44+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/[calendar3]\/"}
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:47:45+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/[calendar3]\/"}
{"reqId":"[reqid]","remoteAddr":"[remoteIP]","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-03-23T15:48:51+00:00","method":"PUT","url":"\/owncloud\/remote.php\/caldav\/calendars\/[user]\/[calendar1]\/[hash].ics"}
```

These messages come up every time a client tries to sync with the owncloud.

Thunderbird logs a lot of these messages

```
[JavaScript Warning: "[calCachedCalendar] Unable to perform playback action modify to the server, will try again next time ([hash],Server Replied with 503)"]
```

within the error console. Besides them, the error console is empty.

**Comment by RealRancor** [comment]
Hi,

please read the description of the "Webdav user backend" and disable this app.

**Comment by Aquilus** [comment]
Well, that seems to be the fix :)

Now I'll have to investigate who of my colleagues enabled the app and what was the reason to do so. Maybe this has been done during the latest upgrade.
