### ISSUE TITLE
9.1.6 no Calendar

### ISSUE THREAD

**Issue by voroyam** [owncloud/calendar#816]
Fresh install in docker ubuntu container

Try to enable Calender App

Get this:
![calender](https://user-images.githubusercontent.com/24212810/30749512-e8845484-9fb3-11e7-9139-fd0bf6ffa9cc.png)

`{"reqId":"Z0gNpEo\/7ExpFMhFqym9","remoteAddr":"172.17.0.1",

"app":"core","message":"Die Signatur konnte nicht \u00fcberpr\u00fcft werden. 

Bitte kontaktiere  die App-Entwickler und \u00fcberpr\u00fcfe deinen Admin-Bildschirm.",

"level":3,"time":"2017-09-22T14:28:58+00:00","method":"POST",

"url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php","user":"admin"}

`

**Comment by voroyam** [comment]
```
Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
```

**Comment by DeepDiver1975** [comment]
Didn't we take care of this recently in some other issue?
The marketplace has to be used  .... https://owncloud.org/blog/good-bye-apps-owncloud-com/
