### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'publicuri' doesn't have a default value

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/calendar#817]
### Steps to reproduce
1. Open existing Calendar
2. Attempt to share it with another OwnCloud user on the same server
3. Does not save this assignment and I see the above error in the console

### Expected behaviour
Should be able to save the sharing with another user

### Actual behaviour
Upon POST to https://xxx/remote.php/dav/calendars/xxx/family/ following error is returned:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\DriverException</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO `oc_dav_shares` (`principaluri`, `type`, `access`, `resourceid`) VALUES(?, ?, ?, ?)' with params ["principals\/users\/rachel.walker", "calendar", 3, "8"]:

SQLSTATE[HY000]: General error: 1364 Field 'publicuri' doesn't have a default value</s:message>
</d:error>
```

### Server configuration

**Operating system**: 
Ubuntu 17.04

**Web server:** 
nginx 1.12.1

**Database:** 
mysql v5.7.19

**PHP version:** 
v7.0.23

**ownCloud version:** 
10.0.3

**Calendar version:** 
1.5.4

**Updated from an older installed version or fresh install:**
From an older install

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - audioplayer: 2.1.0
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.0
  - encryption: 1.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 16.0.2
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - files_antivirus
  - firstrunwizard
  - music
  - theme-example
  - user_external
```

**ownCloud configuration:**

```
{
    "system": {
        "instanceid": "oc02ca513338",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 1,
        "logfile": "\/var\/log\/owncloud.log",
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "trashbin_retention_obligation": "30",
        "updatechecker": false,
        "enable_certificate_management": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using encryption:**
yes

### Client configuration
**Browser:**
Latest Chrome

**Operating system:**
Latest macOS

#### Web server error log
Nothing relevant

#### Log file (data/owncloud.log)
``
{"reqId":"uEBgWvHeQ5NRJ924LTHP","level":3,"time":"2017-09-26T02:45:57+00:00","remoteAddr":"113.197.65.22","user":"michael.heuberger","app":"OCP\\Share","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=Rache&perPage=200&itemType=principals","message":"Sharing backend for principals not found"}
{"reqId":"MLSavAJNQDpJM8uM55iR","level":4,"time":"2017-09-26T02:45:59+00:00","remoteAddr":"113.197.65.22","user":"michael.heuberger","app":"webdav","method":"POST","url":"\/remote.php\/dav\/calendars\/michael.heuberger\/family\/","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_dav_shares` (`principaluri`, `type`, `access`, `resourceid`) VALUES(?, ?, ?, ?)' with params [\\\"principals\\\\\\\/users\\\\\\\/rachel.walker\\\", \\\"calendar\\\", 3, \\\"8\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1364 Field 'publicuri' doesn't have a default value\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(211): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/Sharing\\\/Backend.php(99): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/Sharing\\\/Backend.php(61): OCA\\\\DAV\\\\DAV\\\\Sharing\\\\Backend->shareWith(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1604): OCA\\\\DAV\\\\DAV\\\\Sharing\\\\Backend->updateShares(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar), Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(64): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->updateShares(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar), Array, Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/Sharing\\\/Plugin.php(165): OCA\\\\DAV\\\\CalDAV\\\\Calendar->updateShares(Array, Array)\\n#10 [internal function]: OCA\\\\DAV\\\\DAV\\\\Sharing\\\\Plugin->httpPost(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:POST', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"michael.heuberger\"}"}
``

**Comment by ghost** [comment]
@binarykitchen Please note the following in the filled out issue template:

``
Please report Migration and CalDAV/sync issues to the core repo at https://github.com/owncloud/core/issues
``

There is a similar issue in core: https://github.com/owncloud/core/issues/27754

Not quite sure if this is related so you might also want to create a new issue in core about this.
