### ISSUE TITLE
When adding a new event the window is one day behind

### ISSUE THREAD

**Issue by mKneilmann** [owncloud/calendar#817]
Wenn clicking at one day in month view, the "new Event" window is setting up one day back.
For example: I click of the date 10.25.2015 and the window shows the date 10.24.2015
I search for the bug but didn't found anything. Maybe it's my fail.

![wrong](https://cloud.githubusercontent.com/assets/10676525/8285373/357094ea-1903-11e5-98f9-826640e3803c.png)

**Comment by georgehrke** [comment]
please check the timezone setting

**Comment by mKneilmann** [comment]
Ohh yes thx, then it was my fault. But it is still a bit confusing
