### ISSUE TITLE
Calendar does not load in OC10

### ISSUE THREAD

**Issue by ljep42** [owncloud/calendar#818]
### Steps to reproduce
1. Installed Calendar App from Market
2. Opened up Calendar App from App menu

### Expected behaviour
Calendar(s) should load

### Actual behaviour
Calendar(s) is stuck loading in browser

![image](https://user-images.githubusercontent.com/19956144/30933051-60d2518e-a397-11e7-8628-a04e49c73fc7.png)

### Server configuration

**Operating system**: 
"server OS": "Linux",
"server OS version": "Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l"

**Web server:**
"webserver version": "Apache\/2.4.10 (Raspbian)"

**Database:**
"dbtype": "mysql",
"version": "10.0.0.12",

**PHP version:**

**ownCloud version:** (see your admin page)
10.0.0.12
**Calendar version:** (see the apps page)
1.5.4
**Updated from an older installed version or fresh install:**
N/A
**Signing status (ownCloud 9.0 and above):**
N/A
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**
Activity
Admin Config Report 
Collaborative tags
Comments
Deleted files 
Federation
First run wizard 
Gallery
Mail Template Editor 
Market
Notifications
PDF Viewer
Provisioning API 
Share Files 
Text Editor
Update notification 
Versions
Video player
Contacts
Two Factor TOTP Provider 


```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Mozilla 54.0 (32 bit)

**Operating system:**
Windows 7

**CalDAV-clients:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

[browserlog.txt](https://github.com/owncloud/calendar/files/1338517/browserlog.txt)

[appminjs319824.txt](https://github.com/owncloud/calendar/files/1338514/appminjs319824.txt)

**Comment by DeepDiver1975** [comment]
Mind trying a different browser?

**Comment by ljep42** [comment]
Yeah it didn't work in IE 11 either, I can try later when I get home. Attaching the config report.


[config_report_20170927.json.txt](https://github.com/owncloud/calendar/files/1338536/config_report_20170927.json.txt)

**Comment by ljep42** [comment]
I did an upgrade to OC10.0.3.3 which seems to have fixed the problem.

**Comment by DeepDiver1975** [comment]
Good to know it is working now - strange to see it not working with 10.0.0.
