### ISSUE TITLE
Can't share with Groups (can with individual users)

### ISSUE THREAD

**Issue by jzeevi** [owncloud/calendar#819]
### Steps to reproduce
1.Login as admin
2.Click on share to share a calendar
3.Type the name of a group

### Expected behaviour
Group name should be recognized and made available for selection.
Note: typing a user name behaves as expected

### Actual behaviour
nothing.
NOTE: typing a user name works as expected

### Server configuration

**Operating system**: Linux (Hosted VPS)

**Web server:** Apache 2.4.27

**Database:**: mysql 5.6.37

**PHP version:** 5.6.31

**ownCloud version:** (see your admin page): 10.0.3

**Calendar version:** (see the apps page): 1.5.4

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
"No errors have been found"

**List of activated apps:**
besides the defaults, I activated contacts and calendars (those may have also been defaults, I forget)
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_videoplayer
  - theme-example
  - user_external

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder
{
    "system": {
        "instanceid": "och05vr2yoof",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "blackholeinc.net"
        ],
        "datadirectory": "\/home\/zeeviorg\/ownclouddata",
        "overwrite.cli.url": "https:\/\/blackholeinc.net\/storage",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "zeeviorg_ownc809",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "blackholeinc.net"
    },
    "apps": {
        "backgroundjob": {
            "lastjob": "9"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.4",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging,dav"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "signed": "true",
            "types": ""
        },
        "core": {
            "installedat": "1506340915.6656",
            "lastcron": "1506620944",
            "lastupdateResult": "[]",
            "lastupdatedat": "1506620028",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_group_sharing": "no",
            "shareapi_allow_links": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_allow_social_share": "no",
            "shareapi_only_share_with_group_members": "yes",
            "shareapi_share_dialog_user_enumeration_group_members": "yes",
            "umgmt_show_backend": "true"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.1",
            "types": "filesystem"
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.7.1",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "market": {
            "enabled": "yes",
            "installed_version": "0.2.2",
            "key": "4faf995438bfdff70a204c15c72dd117294a687e6964ff206632e05c2db1573a",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.1",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        }
    }
}
```

**Are you using external storage, if yes which one:**  NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** Chrome (latest)

**Operating system:** Win 7-x64

**CalDAV-clients:** none

#### Web server error log
```
Not sure how to obtain
```

#### Log file (data/owncloud.log)
``
Lots of:

{"reqId":"WcjwO2ttlpz7jyE7mFnjkQAAAAI","level":3,"time":"2017-09-25T12:02:03+00:00","remoteAddr":"71.42.222.138","user":"--","app":"PHP","method":"GET","url":"\/storage\/status.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
\/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"UfnxtHVQlcY3DstUbdyA","level":3,"time":"2017-09-28T17:53:31+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"Etj6AOlkf631ZzfgEuWk","level":3,"time":"2017-09-28T17:54:32+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"oVeuo7WFrFOLBcXQ13JC","level":3,"time":"2017-09-28T17:55:32+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"cZR7m5kMkwMTRnIl3cs9","level":3,"time":"2017-09-28T17:56:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/zeeviorg\/public_html\/2817f\/bhi\/storage\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
zeeviorg@zeevi.org [~/public_html/2817f/bhi/storage]#

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
> {"reqId":"cZR7m5kMkwMTRnIl3cs9","level":3,"time":"2017-09-28T17:56:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /home/zeeviorg/public_html/2817f/bhi/storage/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18"}

side note: please fix that by installing the php intl module

**Comment by DeepDiver1975** [comment]
> Expected behaviour
> 
> Group name should be recognized and made available for selection.
> Note: typing a user name behaves as expected
> Actual behaviour
> 
> nothing.
> NOTE: typing a user name works as expected

would it be possible to get screenshots or a smal vid?
any issues in the browser console?

THX

**Comment by jzeevi** [comment]
Here’s the screenshot after I typed in a user group:

 



 

And here is after I specify a user:

**Comment by DeepDiver1975** [comment]
> Here’s the screenshot after I typed in a user group:

attachments are no added when replying via email ....

**Comment by jzeevi** [comment]
Sorry!

Here's the screenshot from when I share with a user (expected behavior)
![image](https://user-images.githubusercontent.com/15890401/30983788-09e16562-a451-11e7-931f-57a674287bc1.png)
here's the screenshot from when I type a user group:
![image](https://user-images.githubusercontent.com/15890401/30983818-2335e7ea-a451-11e7-87cb-da964be3bef4.png)

**Comment by DeepDiver1975** [comment]
> here's the screenshot from when I type a user group:

can you please open the dev tools and see 
- if there are any errors
- if there is any request sent from the browser to the server

Are these regular groups or do they come from ldap?

THX

**Comment by jzeevi** [comment]
I have created the users and groups as this is not tied to LDAP or any other YP/NIS.

And, I'm sorry to be dense, but what does it mean "open the dev tools"?

**Comment by DeepDiver1975** [comment]
> And, I'm sorry to be dense, but what does it mean "open the dev tools"?

in firefox this is F12 - usually - there is a tab named console. Would be good to knowif there are any errors.

**Comment by jzeevi** [comment]
Ah, thanks! I'm on Chrome, but F12 does get me a set of tabs. When I open the Console and start typing the goupd name, I don't see any errors. (or actually, anything on the console). And, I apologize in advance, this is not my forte (I'm an embedded/OS guy). I do see some network activities on that tab, but am not sure how to get them to this log....

**Comment by jzeevi** [comment]
I see one entry per character that I type of this:
https://blackholeinc.net/storage/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=2&perPage=200&itemType=principals

**Comment by jzeevi** [comment]
Note: the search= field gets longer every character I type (it goes from 2 to 28 to 281 to 2817 to 2817f)

**Comment by DeepDiver1975** [comment]
This is what we need - there is a sub tab when you click on one of these requests.
One of these is named response - I'd like to see the response body

**Comment by jzeevi** [comment]
On Chrome, I don't see a sub tab (may have missed it, the screen is quite busy with the dev tools open) but I did see a response of this:

{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[],"groups":[],"remotes":[]},"users":[],"groups":[],"remotes":[]}}}

**Comment by DeepDiver1975** [comment]
hmmm ... why is this happening?

can you give it a try with a group name starting with a letter and not a number?

**Comment by jzeevi** [comment]
There's a default group of "Everyone" in owncloud. That doesn't work either.

**Comment by DeepDiver1975** [comment]
I know it!

Open the admin setting - there is a sharing section.
I assume the config option to share with groups is disabled

**Comment by jzeevi** [comment]
You are a genius!  That was it. Thank you so much for the help, and the education on the dev tools. That'll come in handy.

**Comment by DeepDiver1975** [comment]
Always happy to help! Take care and enjoy!
