### ISSUE TITLE
Calendar settings: move readonly-links to icons

### ISSUE THREAD

**Issue by bongosmurf** [owncloud/calendar#82]
In the calendar settings dialogue box, the read-only calendar links are listed at the bottom along with the two general URLs. The list of these can get quite long, when there are many calendars involved.

It might be better to make these links available through an additional icon next to the calendar's caldav-link instead.

@jancborchardt What's your opinion on this?

**Comment by jancborchardt** [comment]
This has been fixed since some time already. Closing.
