### ISSUE TITLE
Undefined month in catalan language

### ISSUE THREAD

**Issue by IzK666** [owncloud/calendar#820]
In version 1.5.4 instead of "Octubre 2017" there is an "Undefined 2017". In earlier version, v1.4.1, worked fine.
The calendar and the appointments are correct. The error is just that I have to count how many times I go forth or back to know which month is displayed.
I have tried other languages (spanish, english and français) and there is no error.

I'm using OC9.1.6.

The logs sais that "/apps/calendar/js/vendor/autosize/dist/autosize.js" is missing.

**Comment by DeepDiver1975** [comment]
> The logs sais that "/apps/calendar/js/vendor/autosize/dist/autosize.js" is missing.

similar to #821

**Comment by DeepDiver1975** [comment]
> In version 1.5.4 instead of "Octubre 2017" there is an "Undefined 2017". In earlier version, v1.4.1, worked fine.

looks like some translation is missing .....

**Comment by DeepDiver1975** [comment]
> looks like some translation is missing .....

confirmed - afaik these translations come from moment.js ...

**Comment by IzK666** [comment]
DeepDiver, which file is "moment.js". I can't find it in OC anywhere.
If you tell me where are the strings, I can translate them on transifex.

On the other side, I don't think it's a translation problem, as any untranslated string appears in english.

**Comment by DeepDiver1975** [comment]
> DeepDiver, which file is "moment.js". I can't find it in OC anywhere.
> If you tell me where are the strings, I can translate them on transifex.

this one - https://github.com/owncloud/core/blob/v9.1.6/core/vendor/moment/min/moment-with-locales.js

I'll have a closer look ....

**Comment by Julian1998** [comment]
Duplicate of https://github.com/owncloud/calendar/issues/814
