### ISSUE TITLE
autosize.js missing

### ISSUE THREAD

**Issue by aartsr** [owncloud/calendar#821]
My calendar seems to work (no problems accessing through thunderbird, outlook caldav synchronizer, iOS etc) but I do get however get the following error in the log every time the calendar app is viewed via a web browser (firefox, chrome): 

Could not find resource file "/owncloud/apps/calendar/js/vendor/autosize/dist/autosize.js"

I'm guessing it's not installed with the latest Calendar app v1.5.4? I've been running OC9.1.6 for a while now and recently upgraded the Calendar app to 1.5.4 (via this method: https://github.com/owncloud/calendar/issues/800#issuecomment-324811821).

**Comment by DeepDiver1975** [comment]
the autosize library is within js/public/vendor.min.js - no idea why it is trying to request  "/owncloud/apps/calendar/js/vendor/autosize/dist/autosize.js"

**Comment by aartsr** [comment]
#813 same autosize.js request path as well

**Comment by DeepDiver1975** [comment]
Are you running with asset pipline active? Please disable it and try again

**Comment by aartsr** [comment]
I never played around with asset pipeline and checked my OC config.php just to be sure and it's not there (assuming it's not enabled by default).

**Comment by DeepDiver1975** [comment]
> I never played around with asset pipeline and checked my OC config.php just to be sure and it's not there (assuming it's not enabled by default).

mind posting your config.php? please remove sensitive data

**Comment by aartsr** [comment]
here you go 

```php
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' =>
  array (
    0 => 'www.nowsales.eu',
    1 => 'nowsales.eu',
    2 => '141.105.120.232',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.1.6.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'XXX_',
  'dbuser' => 'XXXXXX',
  'dbpassword' => 'XXXXXXXXX',
  'installed' => true,
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{XXXXXX:143/imap/tls/novalidate-cert}INBOX'
      ),
    ),
  ),
  'forcessl' => true,
  'loglevel' => 1,
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'XXXXXXXXXX',
  'theme' => '',
  'maintenance' => false,
  'secret' => 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updatechecker' => false,
  'updater.server.url' => 'https://updates.owncloud.com/server/',
  'defaultapp' => 'calendar',
  'default_language' => 'nl',
  'appstoreurl' => 'https://marketplace.owncloud.com/api/v0'
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtphost' => 'XXXXXXXX',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'XXXXX@XXXXX.nl',
  'mail_smtppassword' => 'XXXXXXXX',
);`

**Comment by DeepDiver1975** [comment]
> here you go

thx - I could finally reproduce this last night - the fix is in #822

**Comment by aartsr** [comment]
thank you!

**Comment by aartsr** [comment]
I manually edited viewcontroller.php and main.php as per #822 and can confirm the error is gone (I couldn't find viewcontrollertest.php but I assume that's a dev setup/file).
