### ISSUE TITLE
birthday calendar: add option to set default reminder/alarm

### ISSUE THREAD

**Issue by tbeitter** [owncloud/calendar#821]
Hi there,

the birthday calender made from contact's birthdays is a heavily used and loved feature for my users. But, it is only working well if you remember to check several times a week to see if any contact's birthday is coming. 

It would be really nice if there would be an option to define a default reminder which then is active for all birthdays in this calendar. Something like "notify me about this birthday on this day at 12:00".

Thanks
Til

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/570
