### ISSUE TITLE
Sharing with write permission not possible when target user has a different display name

### ISSUE THREAD

**Issue by balta3** [owncloud/calendar#823]
### Steps to reproduce
1. Create a user "jon.doe" with display name "Jon Doe"
2. Try to share a calendar with Jon Doe and allow to edit the calendar
3. Reload calendar page

### Expected behaviour
Calendar should be shared one time with Jon Doe and he may edit the events.

### Actual behaviour
Calendar seems to be shared two times, one time with and one time without write permission. Jon Doe is not able to edit the events.

In the database:

    MariaDB [owncloud]> select * from oc_dav_shares;
    +----+---------------------------------+-------------+--------+------------+-----------+
    | id | principaluri                    | type        | access | resourceid | publicuri |
    +----+---------------------------------+-------------+--------+------------+-----------+
    | 28 | principals/users/jon.doe        | calendar    |      3 |         14 | NULL      |
    | 29 | principals/users/Jon Doe        | calendar    |      2 |         14 | NULL      |
    +----+---------------------------------+-------------+--------+------------+-----------+

### Server configuration

**Operating system**: openSUSE Tumbleweed

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.1.10

**ownCloud version:** 10.0.3.3

**Calendar version:** 1.5.4

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.3.6
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_antivirus
  - theme-example
  - user_external

**Comment by ugoviti** [comment]
I confirm this behavior.

Tested with two different production environments:

- Active Directory
- OpenLDAP

With Kind Regards

**Comment by Ricardo665** [comment]
Hello,
I'm using an Active Directory environment and I found this problem today
It seems to come from the order of the parameters in the function `updateExistingUserShare`

I fixed it in apps/calendar/templates/part.calendarlist.item.php, modifying line 169 :
`ng-change="updateExistingUserShare(item.calendar, userShare.displayname, userShare.id, userShare.writable)"`

This solution seems to work, but I am not an expert, can someone confirm this solution?
Best regards

**Comment by DeepDiver1975** [comment]
please test this fix - https://github.com/owncloud/calendar/pull/839 THX

**Comment by localguru** [comment]
@Ricardo665 this is working, but I don't really understand it. @DeepDiver1975 could you explain please?
