### ISSUE TITLE
Write permission not working with sharing

### ISSUE THREAD

**Issue by headstorm21** [owncloud/calendar#824]
### Steps to reproduce
1. Create a calendar
2. Share calendar with a specific user and give the write permission
3. create or modify event in share calendar by specific user

### Actual behaviour

When i create and share calendar with a specific user and i give write permission on, there's 2 problems:
- the first is when i refresh the calendar web page and i check the write permission on the calendar that i share, the same specific user appear 2 times, the first have the write right and the second not (give the write permission for the second is impossible)
- the second is when the specific user try to add or modify something in the share calendar, he can't

i need this share function and i don't understand why it doesn't work.

Thanks for your help. 

### Server configuration

**Operating system**:
Debian stretch

**Web server:**
Apache 2.4
**Database:**
Mariadb
**PHP version:**
7.0
**ownCloud version:** (see your admin page)
10.0.1
**Calendar version:** (see the apps page)
1.5.4
**Updated from an older installed version or fresh install:**
Fresh Install

**Comment by bwiese71** [comment]
Exactly same issue for me too on 10.0.3.3 fresh install.

**Comment by gabinita** [comment]
Same Issue on 10.0.3.3. Can share , allow edit, but the shared person cannot edit. Please advise

**Comment by gabinita** [comment]
I tried different forms, seams the if you share your calendar with a group and give edit right is working, is not working if you share with a user and give edit right is not working.

**Comment by DeepDiver1975** [comment]
please test this fix - https://github.com/owncloud/calendar/pull/839 THX

**Comment by localguru** [comment]
Same problem with 9.1.7 with calender 1.5.4, PR #839 doesn't fix it.
