### ISSUE TITLE
Can't install calendar on OC 8.1.0 (not compatible)

### ISSUE THREAD

**Issue by tflidd** [owncloud/calendar#829]
I can't install the calendar app via app store. I says that the app version is not compatible with the oc version. Manual download from github works.

Other apps already are installable: bookmarks, pictures, mail, ...

(same problem for contact app, ref: https://github.com/owncloud/contacts/issues/968)

Ubuntu 14.04 with owncloud 8.1 testing from SuSE repo (shows 8.1.0 (stable) on admin interface).

**Comment by georgehrke** [comment]
What app did you try to install? Calendar 8.0?

**Comment by tflidd** [comment]
I didn't specify the version. It's just on the apps-page via webinterface, in "productivity" it shows numerous apps. So I would expect owncloud to download the right version from the app-store ...

**Comment by georgehrke** [comment]
What was the exact name of the app you downloaded?

**Comment by tflidd** [comment]
It shows calendar 0.6.5

**Comment by tflidd** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8111200/8513550/eac3d5c4-2370-11e5-9e20-b01a2e93fd1c.png)
It doesn't even download

**Comment by tflidd** [comment]
There seems to be as well a problem with the app-store version on OC 8.0.x (see comments on apps.owncloud.com)

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/826
