### ISSUE TITLE
Consumers of shared calendar see private events

### ISSUE THREAD

**Issue by paulmenzel** [owncloud/calendar#829]
### Steps to reproduce
1. Update from ownCloud 9 to ownCloud 10
2. Have a working shared calendar with events marked as private

### Expected behaviour

Consumers of the shared calendar should not see private events.

### Actual behaviour

Some consumers are able to see these events.

**Comment by ghost** [comment]
Closing as a duplicate of https://github.com/owncloud/core/issues/26161

Background info: Since ownCloud 9.0 the caldav backend which is responsible for this is located in core.
