### ISSUE TITLE
Cannot disable event repeating

### ISSUE THREAD

**Issue by pgrzywacz** [owncloud/calendar#830]
### Steps to reproduce
1. Create an event with any form of repeating set 
2. Save
3. Edit the event and disable repeating

### Expected behaviour
Task should not be repeated anymore.

### Actual behaviour
Task is still repeating, no change is visible in the calendar view.
After entering edit form again, the repeating is still enabled.

### Server configuration
**Operating system**: Linux ownCloud 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

**Web server:** Apache/2.2.22 (Debian)

**Database:** mysqld  Ver 5.5.43-0+deb7u1 for debian-linux-gnu on x86_64 ((Debian))

**PHP version:** PHP 5.4.41-0+deb7u1 (cli) (built: May 22 2015 12:49:18)

**ownCloud version:** 8.0.4

**Updated from an older ownCloud or fresh install:** 8.0.3

**List of activated apps:** 
```
Enabled:
 - activity
 - calendar
 - files
 - files_encryption
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - provisioning_api
 - templateeditor
 - user_ldap
Disabled:
 - external
 - files_external
 - firstrunwizard
 - gallery
 - updater
 - user_external
 - user_webdavauth```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocjglgvooxqy',
  'trusted_domains' => 
  array (
    0 => 'xxx',
    1 => '10.189.0.63',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'dddd'.
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',

  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_smtphost' => 'ssss',
  'mail_smtpport' => '25',
  'mail_domain' => 'ssss.com',
  'ldapIgnoreNamingRules' => false,
  'forceSSLforSubdomains' => true,
  'maintenance' => false,
  'theme' => '',
);

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
is that really needed?
```

### Client configuration
**Browser:** Google chrome Version 43.0.2357.125 (64-bit)

**Operating system:** Debian 8

### Logs
#### Web server error log
```
no errors
```

#### ownCloud log (data/owncloud.log)
```
no recent entries
```

#### Browser log
```
console:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.```

**Comment by georgehrke** [comment]
duplicate, I'll search for the original issue asap

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/415
