### ISSUE TITLE
Invalid hash after OC 9.1.7 upgrade

### ISSUE THREAD

**Issue by aartsr** [owncloud/calendar#831]
FYI After upgrading OC from 9.1.6 to 9.1.7 the code integrity check shows invalid hashes for the calendar app (v1.5.4, which was also already installed under OC 9.1.6). Environment: Debian jessie, php 5.6.30, mysql 5.5.58, apache. It lists the following:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read the previous linked documentation to learn more about the errors and how to fix them.

Results
=======
- calendar
	- INVALID_HASH
		- controller/viewcontroller.php
		- templates/main.php

Raw output
==========
Array
(
    [calendar] => Array
        (
            [INVALID_HASH] => Array
                (
                    [controller/viewcontroller.php] => Array
                        (
                            [expected] => etc etc

**Comment by ghost** [comment]
I guess this was there on 9.1.6 as well (maybe own modifications done by you) and the uppdate triggered the integrity check again so this is now showing up.

I'm closing there for now as it is very very unlikely that this is an app problem. Please re-download the app from https://marketplace.owncloud.com/apps/calendar, replace the mentioned files and rescan the integrity.

If you need further help please jump over to https://central.owncloud.org/

**Comment by ghost** [comment]
Most likely caused by your manual changes in https://github.com/owncloud/calendar/issues/821#issuecomment-334400567
