### ISSUE TITLE
Calendar loads infinitely

### ISSUE THREAD

**Issue by kku** [owncloud/calendar#832]
See first part of the mixed issue in https://github.com/owncloud/core/issues/29663#issuecomment-347312843 and my comment concerning

> Line 4846 in calendar/js/public : var properties = ['{' + DavClient.NS_IETF + '}calendar-home-set'];

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Fedora 27

**Web server:** Apache

**Database:** MariaDB 10.2.9

**PHP version:** 7.11

**ownCloud version:** 9.1.5

**Calendar version:** 1.5.4

**Comment by ghost** [comment]
As pointed out in https://github.com/owncloud/core/issues/29663 it needs to be evaluated if this is caused by some external dependencies pulled in by Fedora 27 (e.g they are shipping sabre/vobject 4.0.x instead of 3.5.x required by ownCloud).

**Comment by kku** [comment]
I checked. Actually both are available:

`$ dnf list installed |grep sabre `
                                                                                                                                 
php-channel-sabredav.noarch             1.3-10.fc27                     @fedora 
php-sabre-dav.noarch                    3.2.2-2.fc27                    @fedora 
php-sabre-event.noarch                  2.0.2-5.fc27                    @fedora 
php-sabre-http.noarch                   4.2.3-2.fc27                    @fedora 
php-sabre-uri.noarch                    1.2.1-2.fc27                    @fedora 
php-sabre-vobject.noarch                3.5.3-6.fc27                    @fedora 
php-sabre-vobject4.noarch               4.1.3-1.fc27                    @updates
php-sabre-xml.noarch                    1.5.0-4.fc27                    @fedora 
php-sabredav-Sabre.noarch               1.0.0-17.fc27                   @fedora 
php-sabredav-Sabre_VObject.noarch       2.1.7-5.fc27                    @fedora 

Now what?

**Comment by krpage** [comment]
As kku notes, both php-sabre-vobject4 and php-sabre-vobject are installed on Fedora 27.

However it does look like vobject4 is the dependency for the owncloud packages (trying to uninstall php-sabre-vobject4 isn't possible without removing owncloud, but php-sabre-vobject can be removed).

Is there a quick hack that can be applied to make owncloud pull in the correct version?

My calendar is completely broken, and as far as I can tell this is the root cause.

**Comment by krpage** [comment]
Bug filed at:
https://bugzilla.redhat.com/show_bug.cgi?id=1525208

Let me know if I've not summarised correctly.

**Comment by krpage** [comment]
On Fedora 27, downgrading php-sabe-dav to php-sabre-dav-3.0.9-4.fc26.noarch temporarily works around this issue.

**Comment by DeepDiver1975** [comment]
> On Fedora 27, downgrading php-sabe-dav to php-sabre-dav-3.0.9-4.fc26.noarch temporarily works around this issue.

distro issue - unrelated to owncloud -> close
