### ISSUE TITLE
Can't add a CalDAV subscription that is user restricted

### ISSUE THREAD

**Issue by downdrown** [owncloud/calendar#833]
I tried to add a CalDAV Subscription with a URL like this :

**https://my.url:8080/calendar/caldav/myuser**

This CalDAV Account is restricted for "myuser".
I tried to add the credentials to the URL like:

**https://myuser@my.url:8080/calendar/caldav/myuser**

and 

**https://myuser:mypassword@my.url:8080/calendar/caldav/myuser**

But none of them worked.
I get a 401 Notification.

How can I add a restricted CalDAV Account to my subscriptions?

**Comment by downdrown** [comment]
Anything about this problem?

**Comment by Julian1998** [comment]
Is https://my.url:8080/ listed in your trusted domain list?

**Comment by Julian1998** [comment]
I have to add that I am not sure if user restricted subscriptions are working in general...

@DeepDiver1975 ?

**Comment by downdrown** [comment]
I think it's a missing feature like you guessed... but I think it's a pretty often occuring use-case when someone want's to add a calendar from a third-partie site (synology calendar in my personal case) which hase some sort of user-restriction... I think it would be a pretty nice feature to support that ...

**Comment by DeepDiver1975** [comment]
Within the subscription field only webcal links can be added. https://en.wikipedia.org/wiki/Webcal

Can you expose your calendar as webcal?

**Comment by downdrown** [comment]
Synology's Calendar effectifely exposes it's data as CalDAV ... By now every sync with any Calendar client did work properly and does it's job. I also sync to my MacBook and iPhone. But I think I cannot explicitely provide a webcal interface...

**Comment by DeepDiver1975** [comment]
If you agree I'll close this because there is unfortunately not much we can do.
