### ISSUE TITLE
Title missing when editing calendar event

### ISSUE THREAD

**Issue by Wumms** [owncloud/calendar#835]
Reproduce:
Click on an existing event in the calendar, the edit window opens with only the date filled in, the title is empty. (Also the calendar colours are missing in the calendar dropdown.)

Expected:
The title should be filled in, of course.

Version:
I used the online demo account
https://demo.owncloud.org/index.php/apps/calendar/#

Thanks guys!

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
what source did you install the calendar from?

**Comment by georgehrke** [comment]
there was some related issue I fixed yesterday, seems like the demo is using an outdated version

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/778, was fixed
