### ISSUE TITLE
owncloud 8.1 cURL error 56: Proxy CONNECT aborted

### ISSUE THREAD

**Issue by koehn** [owncloud/calendar#837]
I get a `cURL error 56: Proxy CONNECT aborted` when trying to enable Calendar 0.7.0 (and Contacts 0.4.0.0, and Tasks 0.6.0) after upgrading to OC 8.1 on Ubuntu. 

From `owncloud.log`:

    {"reqId":"[redacted]","remoteAddr":"127.0.0.1","app":"core","message":"cURL error 56: Proxy CONNECT aborted","level":3,"time":"July 07, 2015 16:36:29"}

I get this when using the webapp to enable or when using `occ`. I do not have a proxy configured.

    # dpkg -l owncloud\*
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                                          Version                     Architecture                Description
    +++-=============================================-===========================-===========================-===============================================================================================
    ii  owncloud                                      8.1.0-1                     all                         ownCloud Server - Private file sync and share server
    ii  owncloud-3rdparty                             8.1.0-1                     all                         The ownCloud app owncloud-3rdparty
    ii  owncloud-app-activity                         8.1.0-1                     all                         The ownCloud app owncloud-app-activity
    ii  owncloud-app-encryption                       8.1.0-1                     all                         The owncloud subpackage owncloud-app-encryption
    ii  owncloud-app-external                         8.1.0-1                     all                         The ownCloud app owncloud-app-external
    ii  owncloud-app-files                            8.1.0-1                     all                         The ownCloud app owncloud-app-files
    un  owncloud-app-files-encryption                 <none>                      <none>                      (no description available)
    ii  owncloud-app-files-external                   8.1.0-1                     all                         The ownCloud app owncloud-app-files-external
    ii  owncloud-app-files-locking                    8.1.0-1                     all                         The ownCloud app owncloud-app-files-locking
    ii  owncloud-app-files-pdfviewer                  8.1.0-1                     all                         The ownCloud app owncloud-app-files-pdfviewer
    ii  owncloud-app-files-sharing                    8.1.0-1                     all                         The ownCloud app owncloud-app-files-sharing
    ii  owncloud-app-files-texteditor                 8.1.0-1                     all                         The ownCloud app owncloud-app-files-texteditor
    ii  owncloud-app-files-trashbin                   8.1.0-1                     all                         The ownCloud app owncloud-app-files-trashbin
    ii  owncloud-app-files-versions                   8.1.0-1                     all                         The ownCloud app owncloud-app-files-versions
    ii  owncloud-app-files-videoviewer                8.1.0-1                     all                         The ownCloud app owncloud-app-files-videoviewer
    ii  owncloud-app-firstrunwizard                   8.1.0-1                     all                         The ownCloud app owncloud-app-firstrunwizard
    ii  owncloud-app-gallery                          8.1.0-1                     all                         The ownCloud app owncloud-app-gallery
    ii  owncloud-app-provisioning-api                 8.1.0-1                     all                         The ownCloud app owncloud-app-provisioning-api
    ii  owncloud-app-templateeditor                   8.1.0-1                     all                         The ownCloud app owncloud-app-templateeditor
    un  owncloud-app-updater                          <none>                      <none>                      (no description available)
    ii  owncloud-app-user-external                    8.1.0-1                     all                         The ownCloud app owncloud-app-user-external
    ii  owncloud-app-user-ldap                        8.1.0-1                     all                         The ownCloud app owncloud-app-user-ldap
    ii  owncloud-app-user-webdavauth                  8.1.0-1                     all                         The ownCloud app owncloud-app-user-webdavauth
    ii  owncloud-config-apache                        8.1.0-1                     all                         The ownCloud configuration for the apache web server
    un  owncloud-fhs                                  <none>                      <none>                      (no description available)
    ii  owncloud-server                               8.1.0-1                     all                         The owncloud-server package
    un  owncloud-server-core                          <none>                      <none>                      (no description available)

**Comment by LukasReschke** [comment]
Can you post your complete config as described in the reporting guidelines? Thanks.

**Comment by LukasReschke** [comment]
Also what are these for packages etc.

**Comment by koehn** [comment]
The packages are the standard Ubuntu Owncloud packages. 

    # cat config.php
    <?php
    define('DEBUG',true);
    $CONFIG = array (
      'installed' => true,
      'dbtype' => 'mysql',
      'forcessl' => true,
      'blacklisted_files' => 
      array (
        0 => '.htaccess',
      ),
      'overwritehost' => '',
      'overwriteprotocol' => '',
      'overwritewebroot' => '',
      'overwritecondaddr' => '',
      'proxy' => '',
      'proxyuserpwd' => '',
      'trusted_domains' => 
      array (
        0 => 'cloud.koehn.com',
        1 => 'cloud2.koehn.com',
      ),
      'theme' => '',
      'default_language' => 'en',
      '3rdpartyroot' => '',
      '3rdpartyurl' => '',
      'defaultapp' => 'files',
      'knowledgebaseenabled' => true,
      'appstoreenabled' => true,
      'appstoreurl' => 'http://api.apps.owncloud.com/v1',
      'mail_domain' => 'koehn.com',
      'mail_smtpdebug' => false,
      'mail_smtpmode' => 'sendmail',
      'mail_smtphost' => '127.0.0.1',
      'mail_smtpport' => '587',
      'mail_smtptimeout' => 10,
      'mail_smtpauthtype' => 'LOGIN',
      'mail_smtpname' => '[redacted]',
      'mail_smtppassword' => '[redacted]',
      'memcached_server' => 
      array (
        0 => 'localhost',
        1 => 11211,
      ),
      'trashbin_retention_obligation' => 30,
      'trashbin_auto_expire' => true,
      'allow_user_to_change_display_name' => true,
      'appcodechecker' => '',
      'updatechecker' => true,
      'has_internet_connection' => true,
      'check_for_working_webdav' => true,
      'check_for_working_htaccess' => true,
      'log_type' => 'owncloud',
      'logfile' => '',
      'loglevel' => '2',
      'logdateformat' => 'F d, Y H:i:s',
      'logtimezone' => 'Europe/Berlin',
      'log_query' => false,
      'log_authfailip' => false,
      'log_rotate_size' => false,
      'remember_login_cookie_lifetime' => 1296000,
      'session_lifetime' => 86400,
      'session_keepalive' => true,
      'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
      'xframe_restriction' => true,
      'maintenance' => false,
      'apps_paths' => 
      array (
        0 => 
        array (
          'path' => '/var/www/owncloud/apps',
          'url' => '/apps',
          'writable' => true,
        ),
      ),
      'user_backends' => 
      array (
      ),
      'customclient_desktop' => '',
      'customclient_android' => '',
      'customclient_ios' => '',
      'enable_previews' => true,
      'preview_max_x' => NULL,
      'preview_max_y' => NULL,
      'preview_max_scale_factor' => 10,
      'preview_libreoffice_path' => '/usr/bin/libreoffice',
      'preview_office_cl_parameters' => '',
      'enable_avatars' => true,
      'openssl' => 
      array (
      ),
      'singleuser' => false,
      'instanceid' => 'oc7fd72049f6',
      'datadirectory' => '/var/www/owncloud/data',
      'version' => '8.1.0.8',
      'mail_from_address' => 'owncloud-noreply',
      'secret' => '[redacted]',
      'forceSSLforSubdomains' => false,
    );

**Comment by RealRancor** [comment]
Also more a core issue than of the app itself?

**Comment by georgehrke** [comment]
not a calendar issue, either a core issue or a missing configuration / outdated curl version on your side.
probably related to https://github.com/owncloud/core/issues/17446

**Comment by LukasReschke** [comment]
@koehn Don't copy the sample config. You _do_ have a proxy definef with an empty value. Empty value != not set value.

Generally speaking it is encouraged to keep values on default if you have no good reason.
