### ISSUE TITLE
[stable8.1] birthdays not show

### ISSUE THREAD

**Issue by askovpen** [owncloud/calendar#838]
after update stable8->stable8.1 in calendar not show birthdays from contacts

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/824

please search for existing issues before creating new ones ...
additionally please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) for future bugreports as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by RealRancor** [comment]
@georgehrke Might be useful to add a CONTRIBUTING.md to this repository linking to the issue template as discussed here: https://github.com/owncloud/core/issues/14609

**Comment by georgehrke** [comment]
That might indeed help, I'll create one :)
