### ISSUE TITLE
[oC 8.1] Synchronization not working (Thunderbird, Android)

### ISSUE THREAD

**Issue by LEDfan** [owncloud/calendar#840]
Hi

Since my update from 8.1 RC2 to 8.1 Stable I can't synchronise my calendars any more. The `/remote.php/caldav` page gives an error 500.

# ownCloud log
````
{"reqId":"VZzFaoKBhznbqUuZ8oYwRwAAAAQ","remoteAddr":"81.82.70.130","app":"PHP","message":"require_once(): Failed opening required '\/srv\/**\/www\/apps\/calendar\/sabre\/main.php' (include_path='\/srv\/**\/www\/3rdparty\/pear\/pear_exception:\/srv\/**\/www\/3rdparty\/pear\/archive_tar:\/srv\/**\/www\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/srv\/**\/www\/lib\/private:\/srv\/c.ledfan.be\/www\/config:\/srv\/***/www\/3rdparty:\/srv\/c.ledfan.be\/www\/apps:\/srv\/**\/www\/lib:.:\/usr\/share\/pear:\/usr\/share\/php:\/srv\/***\/www') at \/srv\***\/www\/remote.php#132","level":3,"time":"2015-07-08T06:38:34+00:00"}
````

Web GUI is working fine, no errors in console.

I'm using calendar version 0.7.0, manually downloaded from the appstore.

This was already reported at the mailing list: http://owncloud.10557.n7.nabble.com/ownCloud-8-1-Thunderbird-Calendar-Broken-td15403.html

Let me know if you need more information.

**Comment by RealRancor** [comment]
Looks quite similar to https://github.com/owncloud/calendar/issues/777

**Comment by georgehrke** [comment]
yes, please see #777

**Comment by LEDfan** [comment]
That fixes this. But IMO this shouldn't happen. If you change the remote url in your code shouldn't:
 - this be dedected by ownCloud
 - or manually changed in `update.php`

Not a good UX experiences....

**Comment by RealRancor** [comment]
I don't know why but i didn't needed to do anything after upgrading from oC 8.0.5 with calendar 0.6.5 to oC 8.1.0 with calendar 0.7.0
