### ISSUE TITLE
OC 8.1 Import Calendar *.ics files

### ISSUE THREAD

**Issue by Allibabba** [owncloud/calendar#843]
Hi,
I'm running OC 6.x / 7.x since two years. Yesterday I set up a hosted fresh OC 8.1 installation based on a new MySQL-DB and tried to import the calendar ics-files exported from the SQLIte-DB of the running hosted OC 7.0.4 instance.
I spent the whole day in investigating the issue which prevents imports of ics-files. Although it should have been fixed already I couldn't find any working /lib/import.php version on Github.
Can anybody support me fixing this problem, please? Which version from which location can be used to replace the one delivered with 8.1 ? 

-----------------------------------------------------------------------
DETAILS:
### Steps to reproduce
1. Export Calendar from 7.0.4
2. Import .ics file in OC 8.1 in Files
3. PopUp for choosing target calendar and import file appears
4. After clicking checkmark the PopUp freezes with blank progress bar

### Server configuration
**Operating system**: Unix / Professional hoster (Version ?)

**Web server:** Apache  / Professional hoster (Version ?)
Database: MySQL-Version 5.5.44
PHP version: 5.5
ownCloud version: 8.1.0.8
Updated from an older ownCloud or fresh install: Fresh install
List of activated apps: all standard apps + Calendar, Contacts, Tasks

**The content of config/config.php:**
$CONFIG = array (
'instanceid' => 'ID',
'passwordsalt' => 'String',
'secret' => 'String',
'trusted_domains' =>
array (
0 => 'ssl-id.de',
),
'datadirectory' => '/mnt/xxx/xx/xx/xxxxxx/htdocs/owncloud/data',
'overwrite.cli.url' => 'Path',
'dbtype' => 'mysql',
'dbhost' => 'Provider',
'version' => '8.1.0.8',
'dbname' => 'Name',
'dbtableprefix' => 'oc_',
'dbuser' => 'User',
'dbpassword' => 'Password',
'logtimezone' => 'UTC',
'installed' => true,
'theme' => '',
);

```
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** /Webdav
```
### Client configuration
Browser: Firefox 39
Operating system: Win 7 Prof./64
OC log-file doens't show any related error message

-------------------------------------

Cheers,
Ralf

**Comment by bl4ckr4ptor** [comment]
Hi

I have the same Problem, maybe an other reason.

I get the following erros when i tried to upload an ICS file, exported from owncloud Version 8.0.4.
I tested that on a new installed Server and on an updatet OC Installation.

{"reqId":"G86JD\/s7rwgQZvBCApUI","remoteAddr":"217.*.*.*","app":"PHP","message":"Class 'OC\\Cache' not found at \/var\/www\/owncloud\/apps\/calendar\/lib\/import.php#330","level":3,"time":"July 08, 2015 16:25:20"}
{"reqId":"0Su5ZeBfZqRTdDI18jnG","remoteAddr":"217.*.*.*","app":"PHP","message":"Class 'OC\\Cache' not found at \/var\/www\/owncloud\/apps\/calendar\/ajax\/import\/import.php#13","level":3,"time":"July 08, 2015 16:25:20"}

I also saw a post from Calendar Plus, where they already fixed this issue (maybe similar?)

Regards,
Raphael

**Comment by criegerde** [comment]
I did an Export of my calendar (ownCloud8.1) and stored the *.ics to the ownCloud-root-Folder (/). Unfortunately nothing happens if i click on the file. The expected import-process does not appear. i got Errors in the console of Firefox 39 and ie11
![cal](https://cloud.githubusercontent.com/assets/12971682/8591300/a0993502-2627-11e5-866a-8be649ac0ff0.jpg)
ownCloud 8.1
mySql
php 5.6
Apache
Calendar 0.7.1
Looking forwared to your replies :-)

**Comment by georgehrke** [comment]
Sorry for the inconvenience

fixes:
 - master: af1ddb370c3718b628ed35f07b1e2f2ff7187492
 - stable81: 4091c71

Will release a new version of calendar by end of week

**Comment by criegerde** [comment]
i fixed the Import.php manually but the import-process still disappeares.
Coul you reproduce it? Or will it also be fixed with the next release?

**Comment by georgehrke** [comment]
> but the import-process still disappeares.

Can you please describe what you mean. I can't follow.

**Comment by criegerde** [comment]
I did an Export of my calendar (ownCloud8.1) and stored the *.ics-file to the ownCloud-root-Folder (/). Unfortunately nothing happens if i click on the file. The expected import-process does not appear. i got Errors in the console of Firefox 39 and ie11
i am not able to Import any calendars - Import functionality failed completely

**Comment by georgehrke** [comment]
Are there any other js logs? The ones you posted are definitely not related

**Comment by criegerde** [comment]
would you like to have an account to reproduce?

**Comment by criegerde** [comment]
it depends on the exported calendar - i created a new one and it works as expected.
sorry for your inconv....

**Comment by bl4ckr4ptor** [comment]
Many thanks @georgehrke 

Now it works as expected!

PS: I also updated the "calendar/ajax/import/import.php"

Regards,
Raphael

**Comment by Allibabba** [comment]
Sorry, but it still doesn't work with my 7.0.4 ics-file. Any idea?
Cheers,
Ralf

**Comment by georgehrke** [comment]
Please use the issue template. We can't help you if you just say that it doesn't work ...

Please excuse my brevity and typos.

**Comment by Allibabba** [comment]
I deeply apologise for the confusion. Copying the complete latest version of calendar instead of editing the import.php solved the problem. Now it works as expected!

Many thanks for your very quick support !!!

**Comment by georgehrke** [comment]
fixed in v0.7.2, which just got released

**Comment by fossxplorer** [comment]
I'm experiencing this issue using stable8.1:
child 10264 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Class 'OC\Cache' not found in /var/www/oc/apps/calendar/ajax/import/import.php
@georgehrke

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/pull/852/files

**Comment by fossxplorer** [comment]
Thx! Will you backport to stable8.1 at some point?

**Comment by georgehrke** [comment]
Yes, will back port it before the next release

**Comment by fossxplorer** [comment]
Great, thx a lot!
