### ISSUE TITLE
After Update to OC 8.1 CalDAV Sync doesn't work anymore

### ISSUE THREAD

**Issue by runoiz** [owncloud/calendar#844]
### Steps to reproduce
1. Upgrade to OC 8.1
2. Sync with CalDAV Client for Android 5.1.1
3. Sync with iOS embedded CalDAV Client

If "User backend using remote HTTP servers" is enabled, CalDav works, but only for CalDAV Client for Android , not iOS or Lightning
### Expected behaviour
Sync probably
### Actual behaviour
Doesn't sync with caldav clients
### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
:~# nginx -v
nginx version: nginx/1.9.2
**Database:**
:~# mysql -V
mysql  Ver 15.1 Distrib 10.1.5-MariaDB
**PHP version:**
:~# php -v
PHP 5.6.9-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
ownCloud version 8.1.0
**Updated from an older ownCloud or fresh install:**
upgrade from 8.0
**List of activated apps:**
Enabled:
 - calendar: 0.7.1
 - files: 1.1.9
 - files_locking: 
 - files_sharing: 0.6.2
 - updater: 0.6

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '####',
  'passwordsalt' => '####',
  'datadirectory' => '/opt/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '####',
  'installed' => true,
  'loglevel' => 0,
  'logtimezone' => 'Europe/Berlin',
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 14,
  'trusted_domains' => 
  array (
    0 => '###.###.###',
  ),
  'secret' => '###',
  'forcessl' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
no
### Client configuration
**Browser:**
CalDav Sync for Android
iOS 8.4 embedded Client
Thunderbird 38 with lightning 4.0.0.1
Thunderbird 31.7 with lightning 3.3.3
**Operating system:**
Ubuntu 15.04 for Thunderbird 38
Debian 7 for Thunderbird 31
iOS 8.4 and Android 5.1.1
#### Web server error log
None
#### ownCloud log (data/owncloud.log)
{"reqId":"LWqocopIjnlcOKdHm16Q","remoteAddr":"##.##.##.##","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/remote.php(132): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-09T11:23:34+02:00","method":"OPTIONS","url":"\/remote.php\/caldav\/calendars\/test\/defaultcalendar_shared_by_test\/"}
#### Browser log
None

**Comment by wikon** [comment]
seems to be related to my bug #841

**Comment by georgehrke** [comment]
yep, dup of #841

**Comment by georgehrke** [comment]
Wait

**Comment by georgehrke** [comment]
Yours say "No basic authentication headers were found".
Your client doesn't send authentication headers, therefore the server doesn't answer.

**Comment by georgehrke** [comment]
cc @RealRancor Do you remember some issues with http auth backend?

**Comment by runoiz** [comment]
@georgehrke 

I saw this one #841, but the issue is the same on all clients, whatever client I use it doesn't work. And yes it says 401 No basic authentication headers were found, but why? I tried 5 different clients. by the way, I see calendars available so the everything seems fine bar far.

Important: In CalDAV Sync for Android, there is a option called "Use preemptive authentication", if enabled it works. But there is no such option for other clients. 
http://dmfs.org/wiki/index.php?title=CalDAV-Sync_account_settings#Advanced_options

**Comment by runoiz** [comment]
I did a downgrade to 8.0.5.2 and all clients working properly

**Comment by wikon** [comment]
@runoiz but this can't be the ultimate solution :disappointed_relieved:. OC updates should be tested better before releasing them to public. We're using it in a company and if you have to invest several days of work and investigation after an update that's really :rage:. Nevertheless I respect that the basic idea behind OC is really great and in total it is a good project. 

Maybe there will be a fix in the next few days, I'm suspecting the switch from DAV 1.x to DAV 2.x i OC 8.1 as the culprit for this behavior.

**Comment by runoiz** [comment]
@wikon actually I don't see this as a big issue, downgrading is not a big deal if backup's are done well. If a software has big dependencies, e.g. DAV, bugs happen easily. 

You guess may right, I think there is a issue with the authentication in dav, as it works with BASIC HTTP auth, but this method is not supported by the most clients as I see so far.

**Comment by RealRancor** [comment]
@wikon 
> OC updates should be tested better before releasing them to public

oC != calendar app

:-)

**Comment by wikon** [comment]
@RealRancor I don't thinks it's an issue with the calendar app, rather with the SabreDAV part which belongs to the OC core? But however... we'll see if there will be a solution for that soon ;-). Downgrade is no option because then I'd lose all data from the last few days since the update has been performed.

**Comment by CRCinAU** [comment]
This is probably the same issue as https://github.com/owncloud/calendar/issues/841

For what its worth, it currently affects:
Thunderbird 38.0.1 + Lightning 4.0.1 (Windows - but probably all OSs)
DavDroid (for android)

**Comment by Allibabba** [comment]
Hi guys,

I can confirm this issue under IOS 8.3 as well. Furthermore same behaviour in CardDAV - shared contacts are shown across OC accounts but in none of my IOS devices.

Cheers,
Ralf

**Comment by skuegler** [comment]
I have the same issue. Opening a shared_by...-calendar from thunderbird does not work anymore after Upgrade zu OC 8.1. I think this is not a bug in Sabre Dav. When using the Calendar+ app there are no problems to open shared calendars in thunderbird.

**Comment by georgehrke** [comment]
dup of #841

**Comment by raimund-schluessler** [comment]
Sorry, but I still see this issue with v0.7.2 under oC8.1. when accessing CalDAV via iOS 8.4. although #841 was fixed with 0.7.2. However, sync seems to work anyway.

```
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were 
found","Code":0,"Trace":"#0 \/usr\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): 
Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 
'ownCloud')\n#1 \/usr\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector
\\Sabre\\Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n#2 \/usr\/www\/owncloud\/3rdparty
\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre
\\Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV
\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 
\/usr\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): 
call_user_func_array(Array, Array)\n#5 \/usr\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV
\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/usr\
/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV
\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/usr\
/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#8 \/usr\
/www\/owncloud\/remote.php(132): require_once('\/usr\/www\/ownclo...')\n#9 {main}","File":"\/usr
\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}
```

I also see a very similar issue with contacts v0.4.0: https://github.com/owncloud/contacts/issues/856

**Comment by RealRancor** [comment]
@raimund-schluessler If sync is working see the comments above why you're seeing this message: https://github.com/owncloud/calendar/issues/844#issuecomment-120001275 and https://github.com/owncloud/calendar/issues/844#issuecomment-120008850

**Comment by raimund-schluessler** [comment]
@RealRancor Thanks, I just wondered if this is the expected behavior. If it is, should we log these messages, or better catch them to not confuse users (like me ;) ). I could imagine there will be more error reports for this message.

**Comment by Micha-Btz** [comment]
i upraged today from 8.1.3 to 8.1.4 with the owncloud updater  in admin section.
all went well, but sync with cal/card dav doenst work anymore.

{"reqId":"be06cc11d372329c68915060ce76aa65","remoteAddr":"188.106.253.56","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('OPTIONS', 'addressbooks\\\/Mi...')\\n#4 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('OPTIONS', 'addressbooks\\\/Mi...')\\n#7 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/customers\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-05-04T03:31:05+00:00","method":"OPTIONS","url":"\/remote.php\/carddav\/addressbooks\/MichaDO\/default\/"}

{"reqId":"VjbnB1TIU2gAADpSauwAAAAZ","remoteAddr":"89.204.139.119","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/customers\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/michabtz\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-02T04:31:03+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/MichaDO\/pers%c3%b6nlich\/"}
