### ISSUE TITLE
Importing ICS files doesn't work since 8.1 upgrade

### ISSUE THREAD

**Issue by ravenscroftj** [owncloud/calendar#845]
When you import an ICS file from "files" the dialog gets stuck and the ajax calls return status:500.

The error log produces the following:

```
{"reqId":"1w3jThjJGVCSFoJBI6UT","remoteAddr":"xxxxxx","app":"PHP","message":"Class 'OC\\Cache' not found at \/var\/www\/html\/apps\/calendar\/ajax\/import\/import.php#13","level":3,"time":"2015-07-09T15:18:45+00:00"}
{"reqId":"SfYJ9j7YMP4qjGXGEQmF","remoteAddr":"xxxxxx","app":"PHP","message":"Call to undefined function Sabre\\VObject\\mb_strcut() at \/var\/www\/html\/3rdparty\/sabre\/vobject\/lib\/Property.php#247","level":3,"time":"2015-07-09T15:18:46+00:00"}
```

Steps to reproduce:

1) Upload ICS file containing multiple entries to Files
2) Click on ics file to bring up import dialog
3) Select 'Personal' Calendar and click import

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/843
