### ISSUE TITLE
PHP error DateTime::modify() expects parameter 1 to be string

### ISSUE THREAD

**Issue by BenS89** [owncloud/calendar#846]
Environment:
ownCloud Server 8.1 stable
Calendar 0.7.0

Steps to reproduce:
1. Open the calendar in the web frontend
2. Create a new calendar entry
3. Resize the calendar entry with your mouse (e.g. increase duration)

Expected behaviour:
The calendar entry gets resized without errors

Actual behaviour:
You can see the following error in the logs:

<code>DateTime::modify() expects parameter 1 to be string, object given at /share/MD0_DATA/Web/owncloud/apps/calendar/ajax/event/resize.php#31</code>

**Comment by georgehrke** [comment]
master: f3f231c
stable8.1: 0f49645

**Comment by georgehrke** [comment]
fixed in v0.7.2, which just got released
