### ISSUE TITLE
OC 8.1 Calendar import is not working

### ISSUE THREAD

**Issue by symphoniker** [owncloud/calendar#847]
### Steps to reproduce
1. Upload a large .ics file to owncloud
2. click on the file in the files app and choose to import it to an existing calendar (delete old entries)

### Expected behaviour
The import should pass fine

### Actual behaviour
Nothing

### Server configuration
**Operating system**: Raspbian (Debian) Jessie
**Web server:** Nginx 1.6.2
**Database:** Maria-DB 10.0.16
**PHP version:** PHP 5.6.9
**ownCloud version:** 8.1
**Updated from an older ownCloud or fresh install:** no
**List of activated apps:**
 - activity: 2.0.1
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - provisioning_api: 0.2
 - tasks: 0.6.0
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - gallery
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
Command not working:
sudo -u www-data php occ config:list system --public
  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.

Nothing special here. Tried with and withoud memcache.local

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
tried with differnet clients, and os all not working

#### ownCloud log (data/owncloud.log)
Error 	PHP 	Class 'OC\Cache' not found at /var/www/owncloud/apps/calendar/lib/import.php#330 	2015-07-11T06:46:09+00:00
Error 	PHP 	Class 'OC\Cache' not found at /var/www/owncloud/apps/calendar/ajax/import/import.php#13 	2015-07-11T06:45:50+00:00

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/843
