### ISSUE TITLE
Calendar not working with OwnCloud 10.0.4

### ISSUE THREAD

**Issue by Jolopu** [owncloud/calendar#850]
After updating to OwnCloud 10.0.4 the Calendar app is not working anymore. See screenshot.
### Steps to reproduce
1. Update from OC 10.0.3 to 10.0.4

### Expected behaviour
Calendar should show calendars

### Actual behaviour
No calendars are shown, datepicker doesn't work, and so on.

### Server configuration

**ownCloud version: 10.0.4

**Calendar version: 1.5.4

![owncloud-calendar](https://user-images.githubusercontent.com/34797349/34321739-5136f46a-e851-11e7-8664-8d590b2b0cfe.png)

**Comment by DeepDiver1975** [comment]
Error messages in the browser Console?

**Comment by DeepDiver1975** [comment]
How did you install the calendar App?

**Comment by Jolopu** [comment]
Installation:
Downloaded the calendar-master.zip, unpacked, uploaded the folder to /apps via FTP, renamed folder to /calendar and activated the app in the OC backend.

**Comment by Jolopu** [comment]
Chrome Console shows no error messages.

**Comment by Jolopu** [comment]
Even though the calendar is broken in the OC backend, syncing works with CalDAV.

**Comment by DeepDiver1975** [comment]
Please install the app via the Market App in your owncloud instance.
Calendar-Master.zip is takes from github and only holds the source Code not the full working App.

**Comment by Jolopu** [comment]
I tried to but when I enable the Market app, I get a spinnig cursor and the apps don't show up. The chrome console shows this error:

vue.runtime.esm.js?a427:559
TypeError: Cannot read property 'length' of null
    at VueComponent.render (List.vue?0898:29)
    at VueComponent.Vue._render (vue.runtime.esm.js?a427:4191)
    at VueComponent.updateComponent (vue.runtime.esm.js?a427:2570)
    at Watcher.get (vue.runtime.esm.js?a427:2913)
    at Watcher.run (vue.runtime.esm.js?a427:2990)
    at flushSchedulerQueue (vue.runtime.esm.js?a427:2756)
    at Array.eval (vue.runtime.esm.js?a427:694)
    at nextTickHandler (vue.runtime.esm.js?a427:641)
    at <anonymous>

**Comment by Jolopu** [comment]
This was already an issue in OC 10.0.3 

![oc-market-app](https://user-images.githubusercontent.com/34797349/34375892-ce751aa4-eb23-11e7-8fc7-294b062733cd.png)

**Comment by Jolopu** [comment]
I downloaded Calendar app from the marketplace and installed it manually. Now it works. Thank you!
