### ISSUE TITLE
Error: The objectData argument must contain an 'uri' property

### ISSUE THREAD

**Issue by BenS89** [owncloud/calendar#851]
Environment:
ownCloud Server 8.1 stable
Calendar 0.7.2

Steps to reproduce:
1. Open the calendar in the web frontend
2. Delete an existing calendar-entry

Expected behaviour:
The calendar entry gets deleted without errors

Actual behaviour:
You can see the following error in the logs:

<code>{"reqId":"YG6R6CMfS6ZymX3gnZ7a","remoteAddr":"80.187.x.x","app":"caldav","message":"Exception: {\"Message\":\"The objectData argument must contain an 'uri' property\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(149): Sabre\\\\CalDAV\\\\CalendarObject->__construct(Object(OC_Connector_Sabre_CalDAV), Array, Array)\\n#1 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(270): Sabre\\\\CalDAV\\\\Calendar->getMultipleChildren(Array)\\n#2 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(977): Sabre\\\\DAV\\\\Tree->getMultipleNodes(Array)\\n#3 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(463): Sabre\\\\DAV\\\\Server->getPropertiesForMultiplePaths(Array, Array)\\n#4 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(227): Sabre\\\\CalDAV\\\\Plugin->calendarMultiGetReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/Ben\\\/d...')\\n#6 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#11 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/remote.php(132): require_once('\\\/share\\\/MD0_DATA...')\\n#14 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php\",\"Line\":58}","level":4,"time":"2015-07-13T09:56:55+00:00"}
</code>

**Comment by georgehrke** [comment]
Are you 100%-sure that the log-message was related to the deletion?
The error-log says, that a caldav client to create an invalid calendar object.
And logging that error message is just fine, if that's the case

**Comment by BenS89** [comment]
Ok, I cannot reproduce it anymore when deleting an entry. Therefore, this issue can be closed. Sorry for that.
