### ISSUE TITLE
calendar v0.6.5 - "Unknown or bad timezone ((GMT+01.00) Sarajevo\/Warsaw\/Zagreb)" is logged

### ISSUE THREAD

**Issue by j-ed** [owncloud/calendar#854]
## Expected behavior
The calendar app should not log any error messages if it is used and should identify time zones correctly.

## Current behavior
The following error message is logged for specific events in the calendar database:
```
...,"app":"core","message":"DB execute with arguments : array (   0 => '5', )","level":0,"time":"2015-07-13 20:34:22+02:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/juergen\/juergen\/"}
...,"app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone ((GMT+01.00) Sarajevo\/Warsaw\/Zagreb) at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2015-07-13 20:34:22+02:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/juergen\/juergen\/"}
```
I had reported that error two years ago (https://github.com/owncloud/apps/issues/696) and it was fixed that time by the `SabreDav/VObject` developer but it seems that the fixed got lost somehow.

## Steps to reproduce
1. Import an event as described in https://github.com/owncloud/apps/issues/696
2. open the calendar app.
3. check the log file

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5
Calendar app version: 0.6.5

#### Client Configuration
Operating system: Windows 7
Firefox version: 39.0

**Comment by georgehrke** [comment]
bug in PHP

**Comment by j-ed** [comment]
@georgehrke Sorry to annoy you, but why is it now a PHP error although the first time I've reported the problem it has been identified as a problem of the SabeDAV/Vobjects implementation which is used by ownCloud?

**Comment by georgehrke** [comment]
https://bugs.php.net/bug.php?id=67881

**Comment by j-ed** [comment]
Thank you. Based on that information I found a comment in the SabreDAV v2.1.3 package which describes the problem more detailed: http://fossies.org/linux/sabredav/vendor/sabre/vobject/lib/TimeZoneUtil.php . Which SabreDAV version is currently used in 8.0.5?

**Comment by georgehrke** [comment]
afaik 3.3 
https://github.com/owncloud/3rdparty/blob/stable8.1/composer.lock#L1865

**Comment by RealRancor** [comment]
In 8.0.x SabreDAV 1.8.12 is used:

https://github.com/owncloud/3rdparty/blob/v8.0.5/composer.lock#L1544

which got replaced by 2.1.3 in oC 8.1.x:

https://github.com/owncloud/3rdparty/blob/v8.1.0/composer.lock#L1840
