### ISSUE TITLE
Class 'OC\\Cache' not found

### ISSUE THREAD

**Issue by shoeper** [owncloud/calendar#864]
Importing calendars leads to 
Class 'OC\\Cache' not found in apps/calendar/lib/import.php on line 330
'OC\\Cache' not found in apps/calendar/ajax/import/import.php on line 13

oc 8.1, what can I do to fix this?

**Comment by georgehrke** [comment]
duplicate

**Comment by georgehrke** [comment]
see https://github.com/owncloud/calendar/issues/843

**Comment by shoeper** [comment]
Thanks, unfortunately I wasn't able to find it.
