### ISSUE TITLE
Permissions not checked on caldav

### ISSUE THREAD

**Issue by melo1** [owncloud/calendar#866]
I have some shared calendars with read only permissions.
If I use the web interface in OC 8.1.0 the calendars are shown and are not editable.
With caldav it's possible to write and delete even in those read only calendars.

I use the latest stable versions of OC and calendar.

**Comment by LukasReschke** [comment]
@georgehrke

**Comment by melo1** [comment]
The Error remains in OC 8.1.1 with Calendar 0.7.3

{"reqId":"1M72RMTN+YM59JJZq7ZF","remoteAddr":"37.84.44.62","app":"caldav","message":"Exception: {\"Message\":\"This recurrence rule does not generate any valid instances\",\"Code\":0,\"Trace\":\"#0 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Component\\\/VEvent.php(33): Sabre\\\\VObject\\\\Recur\\\\EventIterator->__construct(Object(Sabre\\\\VObject\\\\Component\\\\VEvent))\\n#1 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(291): Sabre\\\\VObject\\\\Component\\\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\\n#2 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(79): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\\\VObject\\\\Component\\\\VEvent), Object(DateTime), Object(DateTime))\\n#3 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(41): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar), Array)\\n#4 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(145): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validate(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar), Array)\\n#5 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#6 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('1', Array)\\n#7 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#8 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/derma...')\\n#10 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#15 \\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/volume2\\\/web\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/volume2\\\/web\\\/owncloud\\\/remote.php(132): require_once('\\\/volume2\\\/web\\\/ow...')\\n#18 {main}\",\"File\":\"\\\/volume2\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Recur\\\/EventIterator.php\",\"Line\":199}","level":4,"time":"August 24, 2015 22:27:10"}

**Comment by georgehrke** [comment]
> This recurrence rule does not generate any valid instances

The client you use generates broken ics files! Nothing we can do

**Comment by melo1** [comment]
Thank you.
Very interesting, I use CalDAV-Sync for Android and it works well with OC 7.0.4
The error appears with 8.1.0

**Comment by stonerl** [comment]
@melo1 is [this the app] (https://play.google.com/store/apps/details?id=org.dmfs.carddav.Sync) you're using?

I do have the same error my logs. I contacted the developer of this app today.

**Comment by melo1** [comment]
No - it's the right developer, but the wrong all.
For calendar synchronisation you need CalDAV-sync and not CardDAV-sync.

If you use the weddav method you don't get the error anymore but the permissions error persists.
Shared calendars are shown as your own and you can write to them even if they're read only.

**Comment by stonerl** [comment]
Sorry I was pointing to the wrong APP. I meant CalDav-Sync.

**Comment by gvde** [comment]
What has the error message to do with the original problem? The error message is from a REPORT call, i.e. it retrieves entries from the calendar. It doesn't write nor delete anything in the calendar...

**Comment by melo1** [comment]
Maybe nothing - the caldav error appeared and I got those log file entries at the same time

**Comment by gvde** [comment]
Then please use the template from the contribution guidelines and describe the exact problem.

**Comment by melo1** [comment]
Where do I find the template?

**Comment by gvde** [comment]
https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md

**Comment by melo1** [comment]
I have tested the issue again and recognised that the items are written to read only calendars on Android but not synced.
So I will close this issue and open a new one soon because read only calendars are shown as writable on Android. This behaviour came with OC 8.1

**Comment by dmfs** [comment]
FTR: From what I can see the "Invalid recurrence" error is generated during a `calendar-query` Report, so the broken recurrence rule is already in ownCloud. There is no confidence that the broken rule was synced by CalDAV-Sync.
It could have been created by the ownCloud Calendar app or synced by any other client. We only know for sure when you find the affected event.

Also, if there is a broken recurrence-rule synced by an Android sync client, it's either created by a broken Android calendar app or it has been synced like that from the server itself. The sync app usually doesn't modify recurrence rules (because Android uses the same strings). CalDAV-Sync tries to fix a couple of common issues in RRULEs though.

If read-write detection worked in OC 8.0.4 and doesn't work with 8.1.1 there might be something wrong with the permissions returned by 8.1.1. CalDAV-Sync sets calendars to read-only if the server doesn't return write permissions.
However, we're currently investigating this on our end as well.
