### ISSUE TITLE
Calendar loads forever on latest Fedora

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#867]
Basically, I'm not sure how to even view the owncloud error logs to try and work out what is happening. I'm reasonably okay with using Linux, but I suspect some of the commands below are for Ubuntu not Fedora, so they didn't help me get at the logs.

### Steps to reproduce
1. Owncloud calendar just loads and never shows anything
2.
3.

### Expected behaviour
Show my calendar

### Actual behaviour
It just tries to load

### Server configuration
Installed from Fedora packages

**Operating system**:
Fedora
**Web server:**
Apache
**Database:**
Server version: 10.2.9-MariaDB MariaDB Server
**PHP version:**
php-7.1.12-1.fc27.x86_64
**ownCloud version:** (see your admin page)
ownCloud 9.1.5 (stable)
9.1.5
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
Yes, been using for a few years, and install all Fedora updates
**Signing status (ownCloud 9.0 and above):**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

[root@server ~]# sudo -u apache php occ app:list
Could not open input file: occ

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by adrianreber** [comment]
Same for me with a system just upgraded from Fedora 25 to Fedora 27.

**Comment by adrianreber** [comment]
This seems to be a duplicate of https://github.com/owncloud/core/issues/29663 and it also mentioned here: https://bugzilla.redhat.com/show_bug.cgi?id=1525208

I installed php-sabre-dav-3.0.9-4.fc26.noarch.rpm and php-sabre-vobject-3.5.3-5.fc26.noarch.rpm from Fedora 26 and it works for me again.

**Comment by ghost** [comment]
Yes, it would seem doing this "fixes" it.

dnf install https://www.rpmfind.net/linux/fedora/linux/releases/26/Everything/x86_64/os/Packages/p/php-sabre-dav-3.0.9-4.fc26.noarch.rpm
