### ISSUE TITLE
Refresh on web browser and avatar doesn't show in public calendar

### ISSUE THREAD

**Issue by ccheveaux** [owncloud/calendar#869]
### Steps to reproduce
1. Share on public mode a calendar
2. Go on link to see calendar on other browser or computer (where you are not log on on owncloud)
3. Refresh of web page every 5 seconds and avatar don't show

### Expected behaviour
A public calendar with avatar and custom refresh ?

### Actual behaviour
The public calendar work correctly but refresh is too short (5 seconds) and avatar don't show (only if you don't log in)
There may be a place to settle but I have not found despite days of research.

I don't have screen for refresh but i have one for avatar missing : 

![image](https://user-images.githubusercontent.com/22099903/34914884-f0892990-f91b-11e7-96f9-cafad6d956d7.png)

If i log on with my account, i show avatar on same url share : 

![image](https://user-images.githubusercontent.com/22099903/34914875-d1a441fe-f91b-11e7-9ac4-14fd253a3f21.png)

But my principal problem is refresh time, there is too short (5 seconds).

### Server configuration

**Operating system**: Ubuntu 14.04.5

**Web server:** Apache 2.4.7-1

**Database:** Mysql-Server 5.5.55

**PHP version:** PHP 5.6.32

**ownCloud version:** ownCloud 10.0.0.2

**Calendar version:** Calendar 1.5.4

**Updated from an older installed version or fresh install:** Update ownCloud 9.X.X to ownCloud 10.0.X
(But in fresh install same problem.)

```
"No errors have been found."
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.2.9
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.0
  - onlyoffice: 1.1.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_antivirus
  - theme-example
  - user_external
```

**ownCloud configuration:**

```
        "instanceid": "oce83af8ac14",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "owncloud.squaresoft.fr",
            "owncloud.dgm.ens-cachan.fr"
        ],
        "overwrite.cli.url": "https:\/\/owncloud.squaresoft.fr",
        "mail_smtpmode": "php",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "log_authfailip": true,
        "logtimezone": "Europe\/Paris",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** for my test platform NO, but LDAP (active directory) for the production

### Client configuration
**Browser:** Chrome 63, Edge 41 (HTML16)

**Operating system:** Windows 10 Fall Creators Update, OSX High Sierra

**CalDAV-clients:** Thunderbird Lightning, Calendar (OSX)

**Comment by paulmenzel** [comment]
As reported in #870 it’s also happening under GNU/Linux with Firefox 57 and Chromium 63.

I wonder why the page has to reload at all? I think that’s a bug. If you look at the network tab, then in the five seconds the page never seems to finish to load.

**Comment by DeepDiver1975** [comment]
@Julian1998 please have a look.

Most probable reason for this: one of the requests (maybe requesting the avatar) is failing due to missing authentication.

**Comment by ccheveaux** [comment]
The problem is on Edge and Internet Explorer too.

Yes, it's perhaps avatar.
When you are log on you see avatar but no when you are anonymous.

**Comment by paulmenzel** [comment]
Yes, the request https://oc-molgen.gnz.mpg.de/owncloud/avatar/fba29bd6-fb66-4e67-8700-087d75d21e81/192 fails with 401. No idea, if that triggers the reload. In my opinion, it’s no problem to only see the “X avatar”.

**Comment by DeepDiver1975** [comment]
yes - it's the avatar endpoint returning a 401

**Comment by ccheveaux** [comment]
```
XXXXXXXXXXXXXXXXXXX [18/Jan/2018:10:15:47 +0100] "PROPFIND /remote.php/dav/public-calendars/K8BCFCE8UASP2KOC HTTP/1.1" 207 4012 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

XXXXXXXXXXXXXXXXXXX [18/Jan/2018:10:15:47 +0100] "REPORT /remote.php/dav/public-calendars/K8BCFCE8UASP2KOC/ HTTP/1.1" 207 4159 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

XXXXXXXXXXXXXXXXXXX [18/Jan/2018:10:15:47 +0100] "GET /index.php/avatar/dgm/96 HTTP/1.1" 401 894 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
```

In my log just on refresh

**Comment by ccheveaux** [comment]
A possible patch directly on calendar app or it's on owncloud core ?

**Comment by DeepDiver1975** [comment]
please try this:

add the line below to the avatar controller https://github.com/owncloud/core/blob/master/core/Controller/AvatarController.php#L109

```php
	 * @PublicPage

**Comment by ccheveaux** [comment]
It works ! Thx !
It's for futur (minor) update of ownCloud ?

**Comment by DeepDiver1975** [comment]
> It's for futur (minor) update of ownCloud ?

I guess we will ship this with 10.0.6 - 10.0.5 is already closed and will be shipped these days.
