### ISSUE TITLE
view button logic if f***ed up

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#87]
The highlighting of the buttons for selecting the new view is broken.
There is no button preselected, although one view is obviously preselected.

Additionally if you click Today the Today button is highlighted, which doesn't make any sense.

maybe @raghunayyar ?

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar-rework/pull/73 touches the code, who ever wants to fix this: please wait till https://github.com/owncloud/calendar-rework/pull/73 is in

**Comment by raghunayyar** [comment]
The highlight works for me, only that there is no preselected button and today? But day and month and week get selected on clicking.

**Comment by georgehrke** [comment]
Yes, but you can also click today, which gets highlighted then ...
This doesn't make any sense. Clicking today should not remove the highlight from the other three buttons.
