### ISSUE TITLE
Continous refresh/reloading of calendar view

### ISSUE THREAD

**Issue by paulmenzel** [owncloud/calendar#870]
### Steps to reproduce

I am not really sure.

1. Create two calendars with different names.
2. Share one calendar, and create an event in the still private one.
3. Name the shared calendar as the private one, and move the event to the public calendar. (Instead of moved the event is now copied and visible twice.)
4. Delete the private calendar.
5. Access the Web view of the shared calendar.

### Expected behaviour

The page should not reload every ten seconds.

### Actual behaviour

The page should not reload so that the user can use the page.

Example: https://oc-molgen.gnz.mpg.de/owncloud/index.php/apps/calendar/p/879X1NUBVY395YU4/caterer

### Server configuration

1. ownCloud 10.0.4

### Client configuration

**Browser:** Firefox 57.0.4 and Chromium 63

### Console log:

> JQMIGRATE: Migrate is installed, version 1.4.0
> jquery-migrate.min.js:2:542
> Deprecation warning: tipsy is deprecated. Use tooltip instead.
> js.js:2287:2
> Navigated to https://oc-molgen.gnz.mpg.de/owncloud/index.php/apps/calendar/p/879X1NUBVY395YU4/caterer
> JQMIGRATE: Migrate is installed, version 1.4.0
> jquery-migrate.min.js:2:542
> Deprecation warning: tipsy is deprecated. Use tooltip instead.
> js.js:2287:2
> Navigated to https://oc-molgen.gnz.mpg.de/owncloud/index.php/apps/calendar/p/879X1NUBVY395YU4/caterer
> JQMIGRATE: Migrate is installed, version 1.4.0
> jquery-migrate.min.js:2:542
> Deprecation warning: tipsy is deprecated. Use tooltip instead.

**Comment by paulmenzel** [comment]
The continuous reload seems to only happen if you are *not* logged into ownCloud. So please log out or try to use a private session.

**Comment by ccheveaux** [comment]
I have a same problem : https://github.com/owncloud/calendar/issues/869

But i try to be able to customize the time of reloading to see the deactivate to be able to refresh manually.
When an anonymous consults this web page, he doesn't have time to click on a meeting to see details for example.

**Comment by paulmenzel** [comment]
@ccheveaux, thank you for making me aware of the existing issue. I’ll close this as a duplicate of #869 then.
