### ISSUE TITLE
primary link is not working for syncing

### ISSUE THREAD

**Issue by UtechtDustin** [owncloud/calendar#873]
### Expected behaviour
Use the primary link to sync all calenders of the user

### Actual behaviour
None calender will be syncing (Thunderbird shows the error "This calender is not avaible")

**CalDAV-clients:**
CalDAV-Sync(0.4.32) and/or thunderbird(52.5.0)

More Information about the versions  => https://github.com/owncloud/contacts/issues/629

**Comment by DeepDiver1975** [comment]
> More Information about the versions => owncloud/contacts#629

10.0.4 has an issue - please upgrade to 10.0.5 once released
