### ISSUE TITLE
Broken calendar item

### ISSUE THREAD

**Issue by redhell** [owncloud/calendar#878]
Hello,

in my owncloud log i've got this beautifull error message:

Exception: {"Message":"End of document reached prematurely","Code":0,"Trace":"#0 *\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(168): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 *\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine('BEGIN:VEVENT')\n#2 *\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 *\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\n#4 *\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(142): Sabre\\VObject\\Reader::read('BEGIN:VCALENDAR...')\n#5 *\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#6 *\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('3', Array)\n#7 *\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(621): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#8 *\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(231): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#9 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/Tina\/...')\n#10 *\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 *\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 *\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 *\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#15 *\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 *\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#17 *\/remote.php(132): require_once('\/var\/www\/vhosts...')\n#18 {main}","File":"*\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250} 

It seems one element is broken. How can i determine which it is and how can i remove it from the database?
In oC 8.0 the error appeared first and i think it only happens when an device synchrnoize with oC.

My specs:
- Ubuntu 14.04, PHP 5.6.11, MariaDB 10, 
- oC 8.1. (upgraded since v5)
- Apps: Calendar, Contacts, Tasks, Documents, Gallery+

**Comment by georgehrke** [comment]
see https://github.com/owncloud/calendar/issues/680#issuecomment-73427922

**Comment by georgehrke** [comment]
> how can i remove it from the database?

delete the one with the corresponding id

**Comment by redhell** [comment]
Thanks!
Found the broken event.
