### ISSUE TITLE
Shared writeable calendar appears read-only?

### ISSUE THREAD

**Issue by jenger** [owncloud/calendar#879]
When I share a calendar with another user and make the calendar editable for him, the calendar appears read-only for the user. And the `can edit` checkbox exists twice in my account.

I found an similar bug report in the nextcloud project. For me it seems to be the same issue:
https://github.com/nextcloud/calendar/issues/626
The nextcloud guys fixed the bug in nextcloud/calendar version 1.5.6.

### Steps to reproduce
1. Create a calendar
2. Share it with a user 
3. make it editable via `can edit` checkbox

### Expected behaviour
The shared user should be able to edit the calendar

### Actual behaviour
The calendar exists read-only and can't modified by the user

### Server configuration

**Operating system**:
 Ubuntu 14.04.5 LTS

**Web server:**
nginx/1.12.2 php-fpm7.1

**Database:**
mySQL 5.5.59-0ubuntu0

**PHP version:**
7.1.13

**ownCloud version:** (see your admin page)
10.0.6

**Calendar version:** (see the apps page)
1.5.4

**Updated from an older installed version or fresh install:**
8.x => 10.0.4 => 10.0.6
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

`No errors have been found.`

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - music: 0.5.5
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - security: 0.0.2
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - templateeditor
  - theme-example
  - user_external


```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**
{
    "system": {
        "instanceid": "oc04bb3e2e31",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.o22.lan",
            "cloud.gerboth.net"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "tempdirectory": "\/srv\/owncloud\/data\/tmp",
        "dbtype": "mysql",
        "version": "10.0.6.1",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud.log",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "files_external_allow_create_new_local": true,
        "singleuser": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, Local only

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox  58.0.1

**Operating system:**
Windows 10

**CalDAV-clients:**
Thunderbird 56.2.0
Android CalDav

#### Browser log
```
(nothing related)
```

**Comment by DeepDiver1975** [comment]
Next version will fix this
