### ISSUE TITLE
FR: delete single event out of a series

### ISSUE THREAD

**Issue by dercorn** [owncloud/calendar#880]
### Steps to reproduce
1. create recurring event
2. delete single event from this series
3. the whole series is deleted without request for confirmation and there is no choice to delete only a single event to begin with

### Expected behaviour
There should be a possibility to delete single events from series.

### Actual behaviour
See 3. above

**Comment by toefel1** [comment]
Need this since long ago (3 years) -> Calendar is crippled without the ability of deleting single events out of a series!!

**Comment by DeepDiver1975** [comment]
@toefel1 contributions are welcome!

**Comment by toefel1** [comment]
I am pleased to hear that!
You might cont me via pm or phone - I am nearby!

Viele Grüße,
Christian van de Weyer

**Comment by DeepDiver1975** [comment]
fixed with #920
