### ISSUE TITLE
Shared calendar sync issue in Thunderbird Lightning ("Calendar is momentarly unavailable")

### ISSUE THREAD

**Issue by stephane84** [owncloud/calendar#887]
### Steps to reproduce
1. Create a new calendar on the network in Thunderbird 40 + Lightning 4.2b1 (07/0/2015)
2. Choose Caldav and paste the link of a  calendar **shared by another user with you**
3. The calendar never synchronizes. It displays "Calendar is momentarly unavailable"

### Expected behaviour
The calendar should sync.

### Actual behaviour
In the Thunderbird console, the following error is displayed : 

		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/31f1707b-c989-46d6-b215-7a152d4ad092.ics calendar-data:
		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/5ad69ea8-2155-422c-b23d-14344512a008.ics calendar-data:
		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/729d7e14-018d-489b-a4c6-196e712526de.ics calendar-data:
		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/25bbd181-340a-4dfa-9e65-7c170a2cc256.ics calendar-data:

		...

		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/a33ae6bc-88d6-4152-b14c-bb93febcdba6.ics calendar-data:
		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/45e6550f-b8fa-4437-b8c8-6d16f38a91b6.ics calendar-data:
		Warning: CalDAV: Unexpected response, status: undefined, href: /remote.php/caldav/calendars/myusername/famille_shared_by_username/owncloud-00c009ba854f5f985edf1a0ee315d4ad.ics calendar-data:
		Warning: CalDAV: Get failed: multiget error

		Error: [calCachedCalendar] replay action failed: null, uri=https://cloud.example.com/remote.php/caldav/calendars/myusername/famille_shared_by_username, result=2147500037, op=[xpconnect wrapped calIOperation]

		Warning: Une erreur est survenue lors de la lecture de données de l'agenda : Famille. Cependant, l'erreur est certainement mineure ; le programme va donc essayer de poursuivre. Code d'erreur : 0x80004005. Description : multiget error
		Warning: Une erreur est survenue lors de la lecture de données de l'agenda : Famille. Cependant, l'erreur est certainement mineure ; le programme va donc essayer de poursuivre. Code d'erreur : READ_FAILED. Description : 

### Server configuration
**Operating system**: Raspbian on Raspberry PI

**Web server:**  lighttpd 1.4.31

**Database:** MySQL

**PHP version:** 5.2.17

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** updated since OC7

**List of activated apps:** 

Enabled:
 - activity: 2.0.1
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mia: 0.0.1
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => '************',
  'passwordsalt' => ************',
  'secret' => '*********',
  'trusted_domains' => 
  array (
    0 => '********',
    1 => '******',
  ),
  'datadirectory' => '/media/donnees/owncloud',
  'overwrite.cli.url' => 'http://cloud.***********',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:/media/donnees/mysqldb/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_dbuser',
  'dbpassword' => '***',
  'installed' => true,
  'maintenance' => false,
  'forceSSLforSubdomains' => true,
  'trashbin_retention_obligation' => 10,
  'enable_previews' => true,
  'theme' => '',
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 39.0.3

**Operating system:** Linux Ubuntu 14.04

**Comment by georgehrke** [comment]
please provide server error logs and try to translate thunderbird's error message (the bottom one) to english

**Comment by gvde** [comment]
Upgrade calendar app to 0.7.2.

**Comment by stephane84** [comment]
The translation of this error : Warning: Une erreur est survenue lors de la lecture de données de l'agenda : Famille. Cependant, l'erreur est certainement mineure ; le programme va donc essayer de poursuivre. 

could be something like... 

Warning: An error happened whilie reading the angedna data : "Famille". 
But, this error is probably minor ; the program will thus try to continue.

**Comment by stephane84** [comment]
@gvde OK, but how ? sudo apt-get updgrade doesn't popup any update ... Is there another way ?

**Comment by stephane84** [comment]
Calendar 0.7.2 solved this issue :-)

For other who may have the same problem : there are 2 calendars apps in the app store. Please make sure you deactivate 0.7.1 + delete the content of apps/calendar + activate 0.7.2

Working like a chamr with thunderbird 40.0 and Lightning 4.2b1
