### ISSUE TITLE
Calendar not reliable due to import errors

### ISSUE THREAD

**Issue by sciurius** [owncloud/calendar#888]
### Steps to reproduce
1. Import a particular .ics
2. Get "partially imported, NN errors" message

### Expected behaviour
There should be a way to find out **which** events were not imported, and why.
**This is a show stopper when migrating from another calendar application.**

**Comment by Julian1998** [comment]
@sciurius Is there no log error on console? I makes sense to inform the user about the exact error but that is sth for the oc console

Can you have a look at it?

**Comment by sciurius** [comment]
I see I can create a calendar using occ, but I do not see how I can import an .ics into it.

**Comment by Julian1998** [comment]
@sciurius No I meant the owncloud error log in your admin settings

**Comment by sciurius** [comment]
Yes, there are some messages in the owncloud log. Not exactly user friendly but they may give a clue to solve the import problems.

**Comment by Julian1998** [comment]
@sciurius We can only help you if you post them here!

**Comment by sciurius** [comment]
Oh, sorry. This was not intended as a request for help, but more a notice that I consider it solvable with these clues. In fact, I did eliminate all import errors. It turns out that SabreDAV is much stricter than DAViCal and some python libraries. 

Most errors were:

- This  recurrence rule does not generate any valid instances
This happens when the occurrences of an event are removed one by one, until no occurrence remains. For example, the RRULE specifies three repetitions and there are three EXDATEs as well. I don't know if this is allowed by the specs; SabreDAV barfs on it.

- More than one master object was found for the object with UID
One of the clients I used had a facility to duplicate an event. Unfortunately, the duplicate kept the original UID, causing the above error. (The client has been fixed since).

I use vdirsync to mirror the DAViCal database to a vdir, and then fed the vdir to ownCloud. This way I could debug the offending events individually, which was a great help.

**Comment by sciurius** [comment]
I'll close this issue with the remark that the ownCloud calendar looks very nice and (surprise!) performant. 
For example, the Synology Calendar takes 21 seconds to load, and 2 seconds to browse to a new month. OC Calendar (running on the same NAS) takes 10 seconds to load, and about 4 seconds for a new month. InfCloud (client based) takes 90 seconds to load but browses the nearby months (6 forward, 3 backward) instantaneously.
All in all I'm not disappointed so far.
