### ISSUE TITLE
summary/location/description fields blank in event edit

### ISSUE THREAD

**Issue by JoshData** [owncloud/calendar#892]
aa71f8f4b29e4c913eb58846379cecc9b50533cc, which is present in lots of tags (most recently 8.1.0), broke editing events. The summary, location, and description fields show up as blank because the corresponding variables were deleted.

The fix 998caf3f6b21c057c4540c335cf81f7670b2542f is already in master. Since ownCloud 8.1.1 is already released, and there's no 8.1.1 tag of the calendar app (which is already deeply confusing --- are calendar app releases meant to track ownCloud core releases?), I wanted to flag this for inclusion asap. Thanks.

**Comment by georgehrke** [comment]
> are calendar app releases meant to track ownCloud core releases?

No, the tags are not meant to flag anymore, because the calendar updates are released via the App Store. For the most recent tags checkout https://github.com/owncloud/calendar/tags
v0.7.2 is the latest release for ownCloud 8.1

**Comment by georgehrke** [comment]
>  broke editing events.

master was affected for a few weeks. The fix was released before we declared the version to be stable.

**Comment by JoshData** [comment]
Is this where the updates are released?

https://apps.owncloud.com/content/show.php/Calendar?content=168707

It shows a much older version number on that page, although the download seems to contain v0.7.2.

**Comment by georgehrke** [comment]
Yes, this is the correct place.

It says 0.6.5, because that's the version number of the calendar for ownCloud 8.0.
That's an issue in apps.ownCloud.com, not calendar related.

**Comment by JoshData** [comment]
I'm just trying to figure out how I know when there's a new version. Best way is to follow the 0.7.x series of tags then?

**Comment by georgehrke** [comment]
yep

**Comment by JoshData** [comment]
Okay thanks.
