### ISSUE TITLE
Shared calendar Event not shown with mobile App

### ISSUE THREAD

**Issue by jc06700** [owncloud/calendar#893]
### Steps to reproduce
1. Create an event in his calendar 
2. After the creation step, edit the event, acces the sharing tab and share the event with others OC users 

### Expected behaviour
Other users should see the  shared event using a mobile App 

### Actual behaviour
Other users can see the shared event using a web browser (working fine), 
but using a mobile App (checked with IOS and Android) the shared event doesn't appear.
Sharing the whole calendar is working fine.
The problem occurs when sharing a single event (sharing tab after the event creation step)

### Server configuration
**Operating system**: 
Linux Debian 8.1 kernel 3.16.0-4-amd64 

**Web server:** 
Apache/2.4.10

**Database:**
mysql  Ver 15.1 Distrib 10.0.20-MariaDB

**PHP version:**
PHP 5.6.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
- activity: 2.0.1
 - calendar: 0.7.3
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - ownnote: 1.05
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocnggwlyrqmk',
  'passwordsalt' => '.....',
  'secret' => '.....',
  'trusted_domains' =>
  array (
    0 => 'owncloud.domain.net',
  ),
  'datadirectory' => '/home/data/owncloud/data/',
  'overwrite.cli.url' => 'https://owncloud.domain.net',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'ocdatabase',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '.......',
  'dbpassword' => '........',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain.net',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'loglevel' => 2,
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Mozilla Iceweasel 38.1.0

**Operating system:**
Debian stretch/sid 4.1.0-1-amd64

#### Web server error log
No errors

#### ownCloud log (data/owncloud.log)
{"reqId":"K3lTUIHCF54kz23yMXQD","remoteAddr":"86.xxx.253.54","app":"PHP","message":"Undefined index: limit at \/var\/wws\/owncloud\/core\/ajax\/share.php#295","level":3,"time":"2015-08-13T00:30:12+02:00"}
{"reqId":"HrJnYASv5vM8dKnrcbEs","remoteAddr":"86.xxx.253.54","app":"PHP","message":"Undefined index: limit at \/var\/wws\/owncloud\/core\/ajax\/share.php#295","level":3,"time":"2015-08-13T00:30:12+02:00"}

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/228
