### ISSUE TITLE
shared calendars can not be hidden

### ISSUE THREAD

**Issue by skhaliq** [owncloud/calendar#896]
If you create custom calendars you can hide them in your calendar-viewport. If someone of your colleagues shares a calendar with you, you can not hide this particular calendar. Therefore after sharing a lot of calendars your viewport gets very crowded and you do not have a chance to bring order into this view.

**Comment by georgehrke** [comment]
dup of #21 

please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) for future bug reports
