### ISSUE TITLE
Calendar app is not in the 8.0.6 tarball.  And can't be 'enabled' in +Apps

### ISSUE THREAD

**Issue by alleehol** [owncloud/calendar#897]
I've upgraded/replaced 8.0.4 with the 8.0.6 tarball.  After that calendar and adressbook apps where missing.  With +apps->recommended I lould enable the adressbook but when I tried  +apps->productivity and click on [enable] button of the calendar app I get a red message:

    App can't be installed because the version in info.xml/version is not the same as the version reported from the app store

I've check the 8.0.6 tarball and the is no apps/calendar/

**Comment by georgehrke** [comment]
What version of the calendar is offered in the app management?

**Comment by alleehol** [comment]
0.6.5.

app store has 0.6.6  (download zip and looked at diff version 0.6.4 in 8.0.4)

**Comment by georgehrke** [comment]
Appstore stored indeed the wrong version number. please try again.

**Comment by alleehol** [comment]
Thx a lot.    I could enable the calendar app again!

Big Hugs!
