### ISSUE TITLE
Shared Calender doesn't send invitation by email

### ISSUE THREAD

**Issue by ikanos** [owncloud/calendar#898]
### Steps to reproduce
1. create a calendar with user a
2. share it with user b
3. as user b: create an appointment and add participant with their email-address

### Expected behaviour
Invitations should be send to the given email-address

### Actual behaviour
No email is send ;-)
It is working if user a creates an appointment, it is also working if user b creats an appointment in an "own" (not shared) calendar. 

### Server configuration

**Operating system**: 
Debian Linux

**Web server:** 
Apache

**Database:**
MySQL

**PHP version:**
7.1.14

**ownCloud version:** (see your admin page)
10.0.7

**Calendar version:** (see the apps page)
1.5

**Updated from an older installed version or fresh install:**
Updated

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- updater/vendor/autoload.php
		- updater/vendor/composer/autoload_real.php
		- updater/vendor/composer/autoload_static.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [updater/vendor/autoload.php] => Array
                        (
                            [expected] => a7195b829a39154b064c684ea2884ad9c61440a8b9d5fc62f6ed6f67f9375362160c782336f5116c474b28e17bdaff4e1643be6545113563742ba3f564e8b8a3
                            [current] => 424c177730e570a01cbd7feb9bfba664d8a0cd96d6f7919144198d84a8d9e599344351e7e4fc945f3c4a6e146f9f981a659ad3977dc5c72dd8b36b11b95152b5
                        )

                    [updater/vendor/composer/autoload_real.php] => Array
                        (
                            [expected] => dfdfb20e8f1f1de56c2c03d02a332fcddc61e39cd7bac5c6d72495629b8a3010bc559a816ad4cb2feb0eaff596ca038e0145c518c06023e3062a7228c3d6cf12
                            [current] => f46d39eb414dcabf1b3e66867de3c33a8258af4965b1a43cfa6dd71311d6392cb640be5c2ca1a18f383310175906f2262f55a4d537868569328281e858a1ac32
                        )

                    [updater/vendor/composer/autoload_static.php] => Array
                        (
                            [expected] => 74e0d332c016d3eb8643ea97d176397e70d8b985490b4cafccc00d17e2b477446cf3dd60761fa0d2b01919c27f77a87b26007719dc2e58c599f0494eb36f97a8
                            [current] => 35c8d6eb712fee78c5b8e4637d7ae693ed5fff374c165a0359d16a10ffea23f30b1651130ef1fd6a2e9b4f2fe415dc74669374751d39d4d55c75fe4e15fe338b
                        )

                )

        )

)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
$CONFIG = array (
  'instanceid' => 'REMOVED',
  'passwordsalt' => 'REMOVED',
  'trusted_domains' =>
  array (
    0 => 'REMOVED',
    1 => 'REMOVED',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '10.0.7.2',
  'dbname' => 'REMOVED',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'REMOVED',
  'loglevel' => 2,
  'updatechecker' => false,
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'REMOVED',
  'mail_domain' => 'REMOVED,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'REMOVED',
  'mail_smtpname' => 'REMOVED',
  'mail_smtppassword' => 'REMOVED',
  'updater.secret' => 'REMOVED',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chome (also tried Firefox and Safari, all latest)

**Operating system:**
macOS high sierra

**CalDAV-clients:**
Tried fantastical and in web ui of the calendar

**Comment by DeepDiver1975** [comment]
It is technically not possible. The caldav specs also defines no handling of invitation on shared calendars.

there is a longer discussion about this - I don't find the issue right away

@Julian1998 you might know the issue. please add for reference. THX
