### ISSUE TITLE
Modify only next events in recurring event

### ISSUE THREAD

**Issue by rugebiker** [owncloud/calendar#899]
It would be nice the ability that when you have a recurring event, you could modify only the upcoming events of that sequence, leaving the previous ones untouched.

Example: Recurring event for 1 year set at 6pm every week. Three months later, they decide to change the time to 7pm, so I'd like to edit the events modifying only the upcoming ones, so the new say they are at 7pm, but the past ones say they were at 6pm. Another example would be modifying the place, etc.

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/33#issuecomment-18391419
