### ISSUE TITLE
Datetime picker in calendar doesn't show right time in chinese language(correct in english) 

### ISSUE THREAD

**Issue by helloyan** [owncloud/calendar#902]
Steps to reproduce
open calendar,choose any day to click,open a event frame
click start to show datetime picker to chose another day
Expected behaviour
start / end input field should show the right day

Actual behaviour
show a wrong day

Server configuration
Operating system:
centos 7.3
Web server:
apache
Database:
mysql
PHP version:
PHP 7.1.9 (cli) (built: Aug 30 2017 20:06:08) ( NTS )

ownCloud version: (see ownCloud admin page)
ownCloud	10.0.6 (stable)

Updated from an older ownCloud or fresh install:
older owncloud

Where did you install ownCloud from:
offical

Signing status (ownCloud 9.0 and above):
ok

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
https://gist.github.com/helloyan/2d0b6bfc2e87097be83d6d02127060ac

**Comment by helloyan** [comment]
![image](https://user-images.githubusercontent.com/1699033/37135365-fa67ee20-22d7-11e8-9189-f51b0b724dad.png)

**Comment by Julian1998** [comment]
@helloyan Please test if the fix works correctly ;)

**Comment by helloyan** [comment]
no,the 1.5.7 version see the same problem

**Comment by Julian1998** [comment]
@helloyan You have to test this PR
https://github.com/owncloud/calendar/pull/907

**Comment by helloyan** [comment]
i don't know how to test  , would you release a app package?

**Comment by DeepDiver1975** [comment]
@helloyan here we go - [calendar-1.5.8-rc1.tar.gz](https://github.com/owncloud/calendar/files/2093329/calendar.tar.gz)

**Comment by helloyan** [comment]
yes，sloved my problem, good job
