### ISSUE TITLE
Apache2 uses 100% CPU when calendar app used

### ISSUE THREAD

**Issue by wom-bat** [owncloud/calendar#904]
### Steps to reproduce
Log into Owncloud with Chrome
Visit the calendar app
Run top on the server

### Expected behaviour
There should be a small spurt in CPU usage for an Apache2 process which should decrease to near zero after the request has been serviced
### Actual behaviour
One of the Apache2 processes goes to 100% and stays there.
### Server configuration

**Operating system**:
Debian Unstable
**Web server:**
Apache2 2.4.29-2 using MPM prefork
**Database:**
Mysql
**PHP version:**
PHP5: 5.6.30+dfsg-0+deb8u1
**ownCloud version:**
10.0.4.4
**Calendar version:** (see the apps page)
1.5.7
**Updated from an older installed version or fresh install:**
Updated
**Signing status (ownCloud 9.0 and above):**
No errors found

**List of activated apps:**

```
Enabled:
  - audioplayer: 2.2.4
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_reader: 1.2.3
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 16.0.2
  - impersonate: 0.1.2
  - market: 0.2.3
  - music: 0.5.6
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
 Disabled:
  - encryption
  - external
  - firstrunwizard
  - theme-example
...

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "\/owncloud",
        "proxy": "",
        "proxyuserpwd": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "default_language": "en",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "appstoreenabled": true,
        "mail_smtpdebug": false,
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "180, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": false,
        "log_type": "owncloud",
        "log_query": true,
        "logfile": "",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "xframe_restriction": true,
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "logdateformat": "F d, Y H:i:s",
        "instanceid": "520ae046af5fb",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "version": "10.0.4.4",
        "trusted_domains": [
            "chubb.wattle.id.au",
            "220.239.167.83"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "debug": true,
        "appstore.experimental.enabled": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{chubb.wattle.id.au:143\/imap\/tls}"
                ]
            }
        ],
        "mail_from_address": "owncloud",
        "mail_domain": "chubb.wattle.id.au",
        "maintenance": false
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
imap


### Client configuration
**Browser:**
Chromium
**Operating system:**
Debian

**Comment by wom-bat** [comment]
Upgraded to 10,.0.7, problem still exists.

**Comment by DeepDiver1975** [comment]
this only happens when you have the calendar app open in the browser?

load stays when you switch to another app?

**Comment by wom-bat** [comment]
This happens when I open the calendar app in the browser.  Switching to another app leaves the Apache2 process at 100%.  The only way I've found to get things back to normal is to restart Apache2.

**Comment by DeepDiver1975** [comment]
which background job execution mode are you using? ajax or system cron?

can you run following query on your database:

```sql
select * from oc_jobs

**Comment by wom-bat** [comment]
In /etc/crontab:
*/15 * * * *    www-data /usr/bin/php5 /var/www/owncloud/cron.php
```
mysql> mysql> select * from oc_jobs;
+----+---------------------------------------------------+-------------------------------------------------------+------------+--------------+-------------+--------------------+
| id | class                                             | argument                                              | last_run   | last_checked | reserved_at | execution_duration |
+----+---------------------------------------------------+-------------------------------------------------------+------------+--------------+-------------+--------------------+
|  1 | OC\BackgroundJob\Legacy\RegularJob                | ["\\OC\\Files\\Cache\\BackgroundWatcher","checkNext"] | 1524046520 |   1524046520 |           0 |                  0 |
| 26 | OC\BackgroundJob\Legacy\RegularJob                | ["OCA\\Music\\Backgroundjob\\CleanUp","run"]          | 1524046523 |   1524046523 |           0 |                  1 |
| 28 | OCA\Files\BackgroundJob\CleanupFileLocks          | null                                                  | 1524046521 |   1524046521 |           0 |                  0 |
| 29 | OCA\Files_Versions\BackgroundJob\ExpireVersions   | null                                                  | 1524046524 |   1524046524 |           0 |                  0 |
| 30 | OCA\Files\BackgroundJob\ScanFiles                 | null                                                  | 1524046518 |   1524046525 |           0 |                  1 |
| 31 | OCA\Files\BackgroundJob\DeleteOrphanedItems       | null                                                  | 1524046520 |   1524046520 |           0 |                  0 |
| 33 | OCA\Federation\SyncJob                            | null                                                  | 1524041101 |   1524046521 |           0 |                  0 |
| 34 | OCA\Activity\BackgroundJob\EmailNotification      | null                                                  | 1520220605 |   1524024001 |  1524024001 |                 -1 |
| 35 | OCA\Activity\BackgroundJob\ExpireActivities       | null                                                  | 1520225527 |   1524024001 |  1524024001 |                 -1 |
| 36 | OCA\DAV\CardDAV\SyncJob                           | null                                                  | 1524039302 |   1524046521 |           0 |                  1 |
| 37 | \OC\Authentication\Token\DefaultTokenCleanupJob   | null                                                  | 1524046522 |   1524046521 |           0 |                  0 |
| 38 | OCA\UpdateNotification\Notification\BackgroundJob | null                                                  | 1524035702 |   1524046522 |           0 |                  3 |
| 40 | OCA\Files_Sharing\DeleteOrphanedSharesJob         | null                                                  | 1524046522 |   1524046522 |           0 |                  0 |
| 41 | OCA\Files_Sharing\ExpireSharesJob                 | null                                                  | 1524035706 |   1524046522 |           0 |                  0 |
| 42 | OCA\Market\CheckUpdateBackgroundJob               | null                                                  | 1524035706 |   1524046524 |           0 |                 93 |
| 43 | OCA\Files_Trashbin\BackgroundJob\ExpireTrash      | null                                                  | 1524046525 |   1524046525 |           0 |                  0 |
+----+---------------------------------------------------+-------------------------------------------------------+------------+--------------+-------------+--------------------+
16 rows in set (0.00 sec)

```

**Comment by DeepDiver1975** [comment]
since you use system cron this is not executed on apache ....

Can you have a look at the access log of apache? Maybe you can spot the request initiating the trouble ...

Any error messages in apache error log or owncloud log?

**Comment by wom-bat** [comment]
And it's a funny thing, but I don't see any calls to the calendar app in owncloud.log.  Assuming that the log line is written *after* a request finishes, this would indicate that the HTTP requests never complete...

**Comment by wom-bat** [comment]
LIkewise nothing in the apache log.  I do see requests for "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json H

which I assume is the calendar app.

**Comment by wom-bat** [comment]
Using apachectl fullstatus I see this request is hanging:
    Srv PID Acc M CPU SS Req Conn Child Slot Client Protocol VHost Request

   2-0 4299 0/1/1  W 0.23 57 0 0.0 0.01 0.01 192.168.77.183 http/1.1
   chubb.wattle.id.au:443 REPORT
   /owncloud/remote.php/dav/calendars/peterc/holidays/ HTTP


I deleted the Holidays shared calendar and the problem appears to have gone away.

**Comment by DeepDiver1975** [comment]
looks like we have a REPORT which takes forever ....

How big is this holidays calendar? peterc seems to be the owner - was it shared with a group or users?

**Comment by DeepDiver1975** [comment]
Mind running the perf tool to find out where the process is stuck?
https://jvns.ca/blog/2018/04/16/new-perf-zine/

I did not yet find out how to use perf with php ......

**Comment by DeepDiver1975** [comment]
@wom-bat can I ask you for an export of this holiday calendar? 

Feel free to remove any personal information - hopefully it's not too big.

I assume there is a recurrence rule inside which causes an infinite loop when processing the individual elements.

THX

**Comment by wom-bat** [comment]
I deleted it tio get things to work -- sorry.  I'l close this issue, as it's no longer reproducible.

**Comment by DeepDiver1975** [comment]
> I deleted it tio get things to work -- sorry.

any chance to get it from some backup?
