### ISSUE TITLE
Clicking on web calendar to create event sets it to day before.

### ISSUE THREAD

**Issue by lolownia** [owncloud/calendar#905]
ownCloud 8.0.3 with Calendar app 0.6.6
When I click on month view in web calendar, the date is set to a day before the square I have just clicked. Seems to be an off by one error somewhere.

**Comment by georgehrke** [comment]
please check the timezone setting ...

**Comment by lolownia** [comment]
Where can I find it ?

**Comment by georgehrke** [comment]
in the settings __inside__ the calendar

**Comment by lolownia** [comment]
Ok when I allowed the browser to 'share location' with the app it started to behave correctly. So this is a default timezone which is non zero?

**Comment by georgehrke** [comment]
it's also described in the user documentation ;)

**Comment by lolownia** [comment]
Right, the default is Abidjan. Thank you for hints and for extremely fast answer!
