### ISSUE TITLE
Make date format customizable

### ISSUE THREAD

**Issue by Wernfried** [owncloud/calendar#912]
The date format in calender is fixed to "dd-mm-yyyy". This format is quite uncommon (maybe only 5-6 counties over the world use this format)

The format should be either according ISO 8601 (yyyy-mm-dd) or taken from locale settings or freely customizable. Can you add this?

Best Regards
Wernfried

**Comment by hitam4450** [comment]
I think to take the format of the date from the local settings is the most 'user friendly' solution!  :-)

regards, hitam4450

**Comment by georgehrke** [comment]
duplicate,
