### ISSUE TITLE
Documentation Request: Installation via git without build dependencies

### ISSUE THREAD

**Issue by apotek** [owncloud/calendar#916]
This is a request for documentation/feature. While there exists documentation for cloning the repository in order to do development work, I would like a simple guide to, in the most basic way, do, essentially

    git clone https://github.com/owncloud/calendar.git
    cd calendar
    # something here which would install the required angular and 3rd party js libraries for the app to
    # work. Something like:
    build.sh # shell script to download and install the third party js requirements.
    # or
    npm make # :)

Reason: It is preferable for many to keep our owncloud installations updated via git, including the apps. It's much quicker and more direct than downloading and extracting a tar.gz archive for every update.

Also, it's easier to check for updates from a git install, just by running `git tag` and looking for new releases, than roaming github or the owncloud apps market place.

If we are not developing, then we don't need all the build tools (grunt etc) that come with an `npm install` call. So perhaps there could be an npm command added to package.json that would just install the requirements for _using_ the app. A shell script, however, might be preferable for most users, so they wouldn't need to install node and npm on the server. 

Obviously, the simplest thing by far would be if the third-party js were included in the git repo itself, though I suppose that—depending on which licenses the third party js libraries use—might not be feasible.

This would be nice to have for the contacts app also, but one thing at a time :)

**Comment by DeepDiver1975** [comment]
after cloning you can simply run make - this has to be enough in each and every app repo to build the app. This is common practice and no additional documentation shall be necessary.

**Comment by DeepDiver1975** [comment]
generally speaking git repos are for developing and not for deploying. I know that some time back deployment from git was possible and also a principle we did follow in the ownCloud project.

But given the changes in the way js and php is developed these days this is no longer a reasonable way.

**Comment by DeepDiver1975** [comment]
you can run make dist or make appstore - take the tar ball and deploy that to your server.

**Comment by apotek** [comment]
Thank you @DeepDiver1975 .

So essentially, for what I want to do my process would be:

    git clone https://github.com/owncloud/calendar.git
    cd calendar
    git checkout <TAG>
    make dist
    
And then run something like:

    rsync -rv build/source/calendar <REMOTE_LOCATION>

to deploy. 

This didn't work for me, as my local build environment is missing the `run` command. My `make dist` failed after creating the tar ball with:

    a calendar/appinfo/routes.php
    a calendar/.github/issue_template.md
    make appstore
    make yarn
    cd js &&  run build
    /bin/sh: run: command not found
    make[2]: *** [yarn] Error 127
    make[1]: *** [build] Error 2
    make: *** [dist] Error 2

(Just recording all this here for if/when anyone else comes along with the same question.)

So overall, it looks like for the calendar and contacts app, it would be better for me to retrieve the build from github instead and expand it when I want to update:

    cd apps
    rm -Rf calendar
    curl -O https://github.com/owncloud/calendar/releases/download/<TAG>/calendar.tar.gz
    tar zxvf calendar.tar.gz

I'll just add this different procedure to my owncloud update script. 

Thank you for the response. If this is standard procedure, I suppose no additional documentation is needed, and this issue should be closed as won't fix :). Thanks again.
