### ISSUE TITLE
Wrong description of the app in market app

### ISSUE THREAD

**Issue by voroyam** [owncloud/calendar#919]
OC 10.0.8 on an ubuntu docker container. Browser Firefox

Why are there "????" in the description?

![bildschirmfoto von 2018-05-29 18-35-09](https://user-images.githubusercontent.com/24212810/40672456-28e8ea24-636f-11e8-837c-da98d18b64a5.png)

**Comment by DeepDiver1975** [comment]
Unsupported utf8 Emoji chars

**Comment by DeepDiver1975** [comment]
Issue in Marketplace
