### ISSUE TITLE
Thunderbird sync | Import ics | Date

### ISSUE THREAD

**Issue by prilly** [owncloud/calendar#922]
Imported calendar in owncloud not showing when synced to thunderbird lightning.

Importing a calendar file .ics in "files" tab in owncloud webview is working ok, the imported calendar entrys is showing fine in the calendar app. when syncing this calendar with Thunderbird Lightning with CalDAV the entrys that is imported in the calendar by the file is not showing in thunderbird, calendar entrys that are CREATED inside the calendar app in owncloud webviews is syncing fine and showing in Thunderbird lightning.

It seems imported events by file in owncloud webview has problems syncing to Thunderbird Lightning, a workaround is to open each and every imported event inside the owncloud calendar webview and hit the "save" button, after doing this the event is showing inside Thunderbird after a reseync of the calendar.

owncloud 8.1.1

IMPORTED EVENT:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.7.3
BEGIN:VEVENT
DTSTART:20150824T061500Z
DTEND;VALUE=:20150824T074500Z
UID:271313--432227791-0@timeedit.com
DTSTAMP:20150820T110229Z
LAST-MODIFIED:20150820T110229Z
SUMMARY:ITE1849 Satelittfjernmåling og bildebehandling\, ITE1915 Satellitt
 fjernmåling og instrumentering
LOCATION:E2460 KLASSEROM
DESCRIPTION:Svein Arne Munkvold\nID 271313
END:VEVENT
END:VCALENDAR

EVENT AFTER "SAVING" EVENT AND WHEN THUNDERBIRD IS ACCEPTING THE ENTRY:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 0.7.3
BEGIN:VEVENT
DTSTART;TZID=Europe/Oslo:20150820T081500
DTEND;TZID=Europe/Oslo:20150820T094500
UID:281126--432227791-0@timeedit.com
DTSTAMP:20150902T012022Z
LAST-MODIFIED:20150902T012022Z
SUMMARY:ITE1849 Satelittfjernmåling og bildebehandling\, ITE1915 Satellitt
 fjernmåling og instrumentering
LOCATION:E2460 KLASSEROM
DESCRIPTION:Svein Arne Munkvold\nID 281126
CLASS:PUBLIC
CATEGORIES:
END:VEVENT
END:VCALENDAR

The problem seems to be with this entrys:

DTSTART:20150824T061500Z
DTEND;VALUE=:20150824T074500Z

DTSTART;TZID=Europe/Oslo:20150820T081500
DTEND;TZID=Europe/Oslo:20150820T094500

the import function is not correclty setting the time, to fix this a "save" has do be done with the event inside owncloud calendar webview for each event.

**Comment by georgehrke** [comment]
duplicate, related to https://github.com/owncloud/calendar/pull/876

**Comment by georgehrke** [comment]
please search for existing issues before creating new ones ......
