### ISSUE TITLE
Access to undeclared static property: Sabre\VObject\Property::$classMap

### ISSUE THREAD

**Issue by maxidebiax** [owncloud/calendar#925]
### Steps to reproduce
I've upgraded from 8.0.4 to 8.1.1. (WebUI update).

No problem during and after the upgrade.

Troubles came right after apps enabling (News, Contact, Calendar) : blank page.....

So I tried to disable these apps by using command line.... I can't do anythin, I've the same error all the time :+1: 

max@web:/home/web/public/cloud$ sudo -u www-data php occ app:disable mail
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37

max@web:/home/web/public/cloud$ sudo -u www-data php occ app:disable calendar
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37

root@web:/home/web/public/cloud# sudo -u www-data php occ app:disable calendar
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37

### Expected behaviour
No more Blank Page ^^

### Actual behaviour
Blank Page

### Server configuration
**Operating system**: 

**Web server:** Debian Jessie

**Database:** mysql 5.5.44

**PHP version:** 5.6.12

**ownCloud version:** (see ownCloud admin page) 8.1.1

**Updated from an older ownCloud or fresh install:** from 8.0.4

**List of activated apps:**
None at first, then : mail, news, calendar, contact
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list

root@web:/home/web/public/cloud# sudo -u www-data php occ app:list
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37


**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXXXXXXXXx',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXx',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx',
  'trusted_domains' => 
  array (
    0 => 'cloud.XXXXXXXX.fr',
    1 => 'web.XXXXXXX.fr',
  ),
  'datadirectory' => '/home/cloud/',
  'overwrite.cli.url' => 'http://cloud.XXXXXXX.fr',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => 'XXXXXXXXX',
  'installed' => true,
  'forcessl' => false,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'XXXXXXXX.fr',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.XXXXXXXX.fr',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'maxime@XXXXXXX.fr',
  'mail_smtppassword' => 'XXXXXXXXXX',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

root@web:/home/web/public/cloud# sudo -u www-data php occ config:list system --public
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local : /home/musique

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Nope

### Client configuration
**Browser:** Iceweasel

**Operating system:** Debian Stretch

#### Web server error log
```
Insert your webserver log here
```
[Sat Sep 05 12:57:41.636365 2015] [:error] [pid 1031] [client IPFROMHOME:59636] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37, referer: http://cloud.XXXXXXXX.fr/index.php/apps/files/
[Sat Sep 05 13:01:47.666934 2015] [:error] [pid 29615] [client IPFROMHOME:59685] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37, referer: http://cloud.XXXXXXX.fr/index.php/settings/admin
[Sat Sep 05 13:09:41.592468 2015] [:error] [pid 29616] [client IPFROMHOME:59761] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37, referer: http://cloud.XXXXXXXX.fr/index.php/apps/files/
[Sat Sep 05 13:13:47.609439 2015] [:error] [pid 27016] [client IPFROMHOME:59802] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37, referer: http://cloud.XXXXXXXX.fr/index.php/settings/admin
[Sat Sep 05 13:21:41.588359 2015] [:error] [pid 21758] [client IPFROMHOME:59892] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37, referer: http://cloud.XXXXXXXX.fr/index.php/apps/files/
[Sat Sep 05 13:23:15.651510 2015] [:error] [pid 29274] [client IPFROMHOME:59924] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37
[Sat Sep 05 13:23:18.680089 2015] [:error] [pid 21758] [client IPFROMHOME:59929] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37
[Sat Sep 05 14:13:46.506928 2015] [:error] [pid 2480] [client IPFROMHOME:60621] PHP Fatal error:  Access to undeclared static property: Sabre\\VObject\\Property::$classMap in /home/web/public/cloud/apps/calendar/appinfo/app.php on line 37

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```{"reqId":"80929cfe1696ee0dc40f961e47e7ab95","remoteAddr":"IPFROMHOME","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-03T07:25:28+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/contacts"}
{"reqId":"9764074f5ae56ef70024fab010f9a07f","remoteAddr":"IPFROMHOME","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-03T07:25:31+00:00","method":"POST","url":"\/cloud\/index.php\/apps\/contacts\/preference\/set"}
{"reqId":"8d53a6c57c79399665201694e1db5e64","remoteAddr":"IPFROMHOME","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-03T07:25:36+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/export"}
{"reqId":"8d53a6c57c79399665201694e1db5e64","remoteAddr":"IPFROMHOME","app":"contacts","message":"OCA\\Contacts\\Controller\\ExportController::exportAddressBook","level":0,"time":"2015-06-03T07:25:36+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/export"}
{"reqId":"5c488cfe0152fa19bcc97d22296cd129","remoteAddr":"IPFROMHOME","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-03T07:25:42+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/export"}
{"reqId":"5c488cfe0152fa19bcc97d22296cd129","remoteAddr":"IPFROMHOME","app":"contacts","message":"OCA\\Contacts\\Controller\\ExportController::exportAddressBook","level":0,"time":"2015-06-03T07:25:42+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/export"}
{"reqId":"0bd2caec1e4b2903251149b96f1ad269","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/home\/web\/public\/cloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-06-03T07:30:02+00:00","method":"--","url":"--"}
{"reqId":"e87257a6dd11c279539acd85de2d8420","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/home\/web\/public\/cloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-06-03T07:35:02+00:00","method":"--","url":"--"}








I'm really worried.... What can I do to disable these apps ? (after, i'll be able to install manually the apps)


Thx For Reading.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
you have an outdated calendar version, how did you upgrade?

**Comment by maxidebiax** [comment]
I did it the silly way : Just click on the "activate" button on the webUI right after upgrading owncloud core.
I've understood that I've got an outdated calendar version, but how can i disable this outdated version (with command line....) ?

**Comment by maxidebiax** [comment]
I downloaded the latest version of owncloud-server by my own. I "rm" all files from my owncloud folder except the "config" folder (my /data are outside).
And my Owncloud were back. Now I can install apps one by one manually.
