### ISSUE TITLE
caldav exception: Sabre\DAVACL\Exception\NeedPrivileges

### ISSUE THREAD

**Issue by amandabee** [owncloud/calendar#928]
I upgraded to 8.1.1 (not sure from what version, but I last upgraded in Dec 2014 so I suspect I leap frogged a few) and I'm having trouble with my calendar. 

### Steps to reproduce
For any calendar URL, adding ?export to the URL should return an `.ics` of the calendar. If you're logged in you can just go to `https://www.example.com/owncloud/remote.php/caldav/calendars/user/cal_name?export` -- using `wget` I'd do `https://user:password@www.example.com...`

### Expected Behavior
Should give you an `.ics` of the calendar's events. 

### Actual behaviour
Instead I get this even though the same user can see the calendar in the Owncloud web interface just fine:

    <?xml version="1.0" encoding="utf-8"?>
    <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
      <s:sabredav-version>2.1.6</s:sabredav-version>
      <s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
      <s:message>User did not have the required privileges ({DAV:}read) for path "calendars/amanda/example"</s:message>
      <d:need-privileges>
        <d:resource>
          <d:href>/owncloud/remote.php/caldav/calendars/amanda/example</d:href>
          <d:privilege>
            <d:read/>
          </d:privilege>
        </d:resource>
      </d:need-privileges>
    </d:error>

### Server configuration
**Operating system**: Ubuntu 12.04.5 LTS

**Web server:** Apache

**Database:** Sqlite

**PHP version:** 5.6.10

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** Calendar

**config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'occ7c1677a99',
  'passwordsalt' => 'redacted',
  'trusted_domains' =>  
  array (
    0 => 'example.com',
    1 => 'www.example.com',
  ),  
  'datadirectory' => '/home/abh/example.com/owncloud/data',
  'overwrite.cli.url' => 'http://example.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.1.3',
  'installed' => true,
  'theme' => '', 
  'maintenance' => false,
  'secret' => 'redacted',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'redacted',
  'mail_domain' => 'redacted',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtphost' => 'redacted',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '587',
  'mail_smtpname' => 'redacted',
  'mail_smtppassword' => 'redacted',
);

```

**external storage:** no.

**encryption:** yes, https.  but it doesn't seem to make a difference whether I use it or not.

**external user-backend:** No.

Possible this is related to @danc911's issue at <https://github.com/owncloud/calendar/issues/880> though it is hard to be sure.

**Comment by georgehrke** [comment]
What version of the calendar app do you use?

**Comment by amandabee** [comment]
0.7.3

**Comment by amandabee** [comment]
Hmm. I had pulled it from <https://github.com/owncloud/calendar/releases/download/v0.7.3/calendar.zip> but tried cloning the latest version, still 0.73, but definitely not identical code, and it works.

**Comment by benoit9126** [comment]
I had the same problem when I upgraded to OC 8.1.1 too. I suppose the problem comes from the cookies stored by Thunderbird/Firefox. I deleted all cookies for these two softwares.
Then, the problem disappeared for me. If it can help...
