### ISSUE TITLE
Public shared calendar reloads every 7 seconds

### ISSUE THREAD

**Issue by dmalkmus** [owncloud/calendar#929]
| 10.0.9.5
-- | --

### Steps to reproduce
1: sign in in any account
2: create a new calendar in the calendar app
3: share this calendar public
4: copy the link into clipboard
5: logout from owncloud as any anonymous public user
6: paste the link into a new tab

### Expected behaviour
Public shared calendar, viewed as not logged-in-user in a webbrowser shoud stay on the selected view, e. g. moth, week. So i can view all events

### Actual behaviour
Public shared calendar reloads the whole page every 7 seconds.

### Server configuration

**Operating system**: Debian stretch

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
7

**ownCloud version:** (see your admin page)
10.0.9.5

**Calendar version:** (see the apps page)
1.5.7

**Updated from an older installed version or fresh install:**
updated from 10.0.9.3

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Enabled:
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**

```
{
    "system": {
        "instanceid": "ocad0eb2a1c6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owc.everlite.de",
            "vdebian.everlite.de"
        ],
        "datadirectory": "\/var\/www\/html\/owc.everlite.de\/data",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "owc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": false,
        "forceSSLforSubdomains": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes, https wildcard cert
```

### Client configuration
**Browser:**
Mozilla Firefox, Internet Explorer, Edge

**Operating system:**
MS Windows 10 Pro, latest updates

**Comment by DeepDiver1975** [comment]
Please test 1.5.8-rc1: https://github.com/owncloud/calendar/pull/921#issuecomment-396518406

**Comment by dmalkmus** [comment]
The Version 1.5.8-rc1 wors for me! Thank You!

**Comment by DeepDiver1975** [comment]
> The Version 1.5.8-rc1 wors for me! Thank You!

we will soon release this via the marketplace.
