### ISSUE TITLE
Set up transifex

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#93]

**Comment by georgehrke** [comment]
What's the state here? :)

**Comment by DeepDiver1975** [comment]
who do we handle translations here? I assume some angular libs.

What is the format of the translation files?

**Comment by georgehrke** [comment]
For the translation of weekdays and months and so we extract the information from moment.js, so we don't need to localize that at all :)

All other strings are translated using the `t` function in javascript.

**Comment by DeepDiver1975** [comment]
so you are reusing ownClouds js translation mechanism.

let me have a look then ;-)

**Comment by DeepDiver1975** [comment]
https://www.transifex.com/owncloud_robot/owncloud/calendar-rework/

https://ci.owncloud.org/view/translation-sync/job/translation-sync-calendar-rework
