### ISSUE TITLE
Friends cannot hide shared calendars

### ISSUE THREAD

**Issue by zaclys** [owncloud/calendar#930]
Hi,

Recently a few users reported one bug regarding the ownCloud calendar
functionality : when they share calendars with friends, their friends cannot
hide these calendars from their web interface. Is there a way to do it ?

Thank you for your support.

Best regards,
Mother Zaclys

**Comment by georgehrke** [comment]
dup of #21 
please search for existing bug reports before creating new ones .......

**Comment by georgehrke** [comment]
This issue is even mentioned in the FAQ ...
https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#faq
