### ISSUE TITLE
Make CalDAV link for birthday calendar available via GUI

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/calendar#933]
Since https://github.com/owncloud/contacts/issues/67 there is a CalDAV birthday calendar available.

In Calendar 0.7.3 it is available via URL ``https://<myowncloud>/remote.php/caldav/calendars/<user>/contact_birthdays``. However, one has to *know* that URL. It would be nice if it was shown to the user somewhere in the GUI, e.g. in the calendar app settings just below `Primary CalDAV address`.

PS: There are calendar programs (e.g. Thunderbird with Lightning) which do not list all calendars when entering the primary URL. Also GET was disabled for that URL (used to work with an older version of oC).

**Comment by RealRancor** [comment]
> However, one has to know that URL

Thats true. But at least its documented here: https://doc.owncloud.org/server/8.1/user_manual/pim/calendar.html#special-caldav-urls

**Comment by RealRancor** [comment]
@LukeOwncloud Please test https://github.com/owncloud/calendar/pull/946

**Comment by LukeOwncloud** [comment]
Perfect!
