### ISSUE TITLE
Drone setup

### ISSUE THREAD

**Issue by davitol** [owncloud/calendar#935]
Move from Travis to Drone

**Comment by phil-davis** [comment]
Added to sprint backlog. Maybe this can go in the next sprint - should be easy enough to do now that we have "standard" drone starlark etc.

**Comment by phil-davis** [comment]
@HariBhandari07 I switched https://drone.owncloud.com/owncloud/calendar/settings to `.drone.star`
You can make a PR to rename `.drone.starlark` to `.drone.star` and delete `.drone.yml`
