### ISSUE TITLE
Problem with Mac OS X Calendar and space between username

### ISSUE THREAD

**Issue by reinerj** [owncloud/calendar#937]
We face a problem with OC 8.1.2 and MAC OS X Calendar It works perfect fine with Evolution Calendar on Linux but under Mac we get the following problem. 

The username on OC is something like „Hugo Boss“ with a space. between the names. The authentication fail. When we create a new test user without the space the login works perfect. We cannot simple change the usernames as OC is in production since around 3 years. 

Mac OS X is 10.10.5

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ......

**Comment by reinerj** [comment]
### Steps to reproduce
1. Create a user with s username with a space between first and last name. Something like „Hugo Boss"
2. Add a new Caldav account and copy the URL from OC 
3. After you save you get an error message that <calendar cannot connect to OC and you asked for the password again and again 

### Expected behaviour
Calendar should be added, Works since a long time on Evolution + Fedora

### Actual behaviour
Nothing beside you asked again and again for the password. The URL which is shown is like: https://mydomain.org/caldav/principals/hugo+boss

### Server configuration
**Operating system**:
OpenBSD, We tried the same with CentOS

**Web server:**
Apache
**Database:**

MySQL
**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
8.1.2

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Activity
Default encryption module
Deleted files
Pictures 
Share Files
Text Editor
Versions
Calendar


```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using encryption:** yes

**Are you using an external user-backend, NO

### Client configuration
Mac OS X Calendar

**Operating system:**
Mac OS X 10.10.5

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

**Comment by gvde** [comment]
> Add a new Caldav account and copy the URL from OC 

And what is the exact URL you have there?

**Comment by reinerj** [comment]
https://www.mydomain.org/remote.php/caldav/principals/Hugo+Boss/

**Comment by gvde** [comment]
Does this URL work better: https://www.mydomain.org/remote.php/caldav/principals/Hugo%20Boss/

**Comment by reinerj** [comment]
No, Now i get direct. It is a unknown error occured

**Comment by gvde** [comment]
The %20 URL does work for me. Actually, Calendar turns it into a space if it is entered into the "Server Path" field.
Check the settings in the preferences of Calendar to see if everything is correct set up for your calendar. It should work if you use %20 in the URL.

**Comment by reinerj** [comment]
OK, we just created a new account and it does work also with the space. now we need to found out why it does not work with the old accounts

**Comment by reinerj** [comment]
Finnaly it worked with %20, Was cached on the Mac, Thanks

**Comment by gvde** [comment]
Actually, this is a bug and needs to be fixed. The + encoding in the URL won't work when passed back to caldav. Thus it needs to be shown as %20 in the iOS CalDAV URL.
#938 uses % encoding for spaces and it should now show a working URL in the iOS URL field.

**Comment by RealRancor** [comment]
Just did a short test on my 8.1.3 instance with calendar 0.7.3 and it seems the CalDAV link of a calendar itself is printed out correctly:

https://example.com/remote.php/caldav/calendars/test%20user/pers%C3%B6nlich

where the "primary link" has the wrong encoding:

https://example.com/remote.php/caldav/principals/test+user/
