### ISSUE TITLE
Interaction to toggle open or close state of datepicker

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/calendar#94]
After the recent merge, clicking on the date-picker changes its view from weekly to monthly/yearly. [1]
Because of this we currently don't have a way to close the datepicker. Do we need these views? Or we can use the monthly view and use the header to toggle the monthly content. What do you think? @georgehrke @jancborchardt 

[1] : http://angular-ui.github.io/bootstrap/#/datepicker

**Comment by georgehrke** [comment]
I don't think we need the different views. IMO we should replace the top bar with a  custom one that looks alike the current one, but instead of changing views the field in the middle toggles the visibility of the date picker.

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by georgehrke** [comment]
proposal is in https://github.com/owncloud/calendar-rework/pull/97

**Comment by jancborchardt** [comment]
I don’t really get the issue. Just do it like we do it in the Calendar app at the moment. :) Or what changed?

**Comment by raghunayyar** [comment]
@georgehrke lets not get into mobile at the moment. We really need the calendar up and working in all respects on desktop. We will start with the mobile version right after.

**Comment by jancborchardt** [comment]
Yep, I’d also say while we should also pay attention to mobile, desktop has to be the absolute focus here.
