### ISSUE TITLE
syncing with caldav broke in ios 12 

### ISSUE THREAD

**Issue by soydepr** [owncloud/calendar#947]
### Steps to reproduce
open settings in ipad and add other account caldav for clanedar

### Expected behaviour
calendar should connect to owncloud calendar

### Actual behaviour
login fail , worked fine in ios 11.4.1  broke in ios 12

### Server configuration
OC 10.0.9
**Operating system**:
RASPBIAN STRETCH 
**Web server:**
LIGHTTPD
**Database:**
MARIADB
**PHP version:**
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
**ownCloud version:** (see your admin page)
10.0.9
**Calendar version:** (see the apps page)
1.5.8-rc2
**Updated from an older installed version or fresh install:**
fresh install 
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
no such file 

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
Enabled:
  - calendar: 1.5.8-rc2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.5
  - notes: 2.0.4
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - security: 0.0.2
  - systemtags: 0.3.0
  - updatenotification: 0.2.1



```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

<?php
$CONFIG = array (
  'instanceid' => 'oc6qxxzie2mn',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxxxxxxx'
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.1.9',
    2 => 'xxxxxxx',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'xxxxxxxxxx'
  'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:5432',
  'dbtableprefix' => 'xx_',
  'dbuser' => 'xx',
  'dbpassword' => 'xxxxx',
  'logtimezone' => 'America/New_York',
  'installed' => true,
  'cron_log' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'D1,D2',
'filelocking.enabled' => true,
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
     'host' => 'localhost',
     'port' => 6379,
     'timeout' => 0.0,
     'password' => '', // Optional, if not defined no password will be used.
      ),

'defaultapp' => 'calendar',

);

**Comment by soydepr** [comment]
This is working now when using letsencrypt ssl with port 443 https.  Should it remain open or close?

**Comment by Julian1998** [comment]
@soydepr We let it open. It seems like this is problem behaviour occurs very often and can't always be fixed with https

**Comment by soydepr** [comment]
@Julian1998 I did notice that last night worked on iphone but not on iPad then this morning it worked on iPad :-)

**Comment by milkywade** [comment]
Hi there - I created a github account just for this issue. It happens to me in iPhone and iPad. CalDav & CardDav have never worked since updating to iOS 12. Rather handicapping by my account. 

FYI Apache's access.log sends this:  HTTP/1.1" 401 1070 "-" "iOS/12.0 (16A366) dataaccessd/1.0"

**Comment by milkywade** [comment]
Why this issue has no assignee ?

**Comment by soydepr** [comment]
> Why this issue has no assignee ?

I share your frustration I’m just thre reporter ,

I did get it to work via https port 443 see @Julian1998 comments

**Comment by milkywade** [comment]
Thanks, saw that, although it did not seem to work all the time so I thought maybe we can wait. But I discovered I can not. Do you know a simple to get SSL working for apache on the pi ? My previous attempts at making it work have been unsuccessful.

**Comment by soydepr** [comment]
I use lighttpd and it did not work with simple ssl so I  finally got letsenceypt and it started working for me

**Comment by milkywade** [comment]
thx. been at it all morning. First with openssl, Now trying letsencrypt. Do you use a DNS server ? If not, what's the domain name one could use when creating the certificate ?

**Comment by soydepr** [comment]
I have dns via 

http://freedns.afraid.org

Hope it helps took me a week to get certificate most Likely  you will run into daily limit

**Comment by milkywade** [comment]
hmm, thanks, so that implies connecting the pi to the Internet, which is like ... no :-). Tried installing a local dns server, got it working, then indicating the local domain name during the certbot script execution but then letsencrypt failed (this is normal) as the domain name is not recognized publicly. D'oh. This is being very formative but it's as far as I'll get for a while...

@owncloud developers can anyone release a bugfix to make this work over HTTP / LAN ?

**Comment by milkywade** [comment]
ok. finally. made it work.

In "short":
1. installed a DNS server on the pi, configured it
2. followed tip #5 in [this guide](https://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/) to create a self-signed Root CA (_very_ important) and a cert for apache itself, linked to the Root CA
3. installed the Root CA on my iPhone
4. re-run the account config in the iPhone with the new server name

I'm glad I made it work but no one should have to go through this.

Let me know if questions. Cheers.

**Comment by soydepr** [comment]
@milkywade interesting u want a local cloud

**Comment by soydepr** [comment]
@milkywade  do you have a guide on setting the dns server. kind like this private cloud concept

**Comment by milkywade** [comment]
Hi there - I used [this one](https://carpie.net/articles/setting-up-a-home-network-dhcp-dns-server-with-dnsmasq) [carpie.net] + fine-tuned as I have a vague idea of what DNS is and what I wanted. Example: I used entries in /etc/hosts which dnsmasq reads as I did not want to enable DHCP (I have my main router doing that and did not want to tweak further).

Now your mileage might vary but dnsmasq is very easy to set up (last time I tried to install bind I ended up with a moderate headache).

**Comment by milkywade** [comment]
now, honestly, I'm not ever sure that a DNS server is necessary, you might want to try creating the certificate using an IP address instead of a FQDN first as, if it works, you do not need the DNS server.

**Comment by soydepr** [comment]
Thanks @milkywade if I understand you correctly you can’t reach from the outside

**Comment by Julian1998** [comment]
@milkywade Right now we suggest that apples new ios 12 version had some security updates including not sending authentication headers on http. As I said this is just a suggestion (But if it would be correct - then we can't do anything right now)

**Comment by soydepr** [comment]
@Julian1998  are you saying you guys not looking for a workaround ? hence close the issue.

ios 12 beta was out for a long time this should of been caught or noticed .

**Comment by DeepDiver1975** [comment]
> @Julian1998 are you saying you guys not looking for a workaround ?

There is no workaround to be applied. ios 12 calendar sends authentication information only if ssl and a valid cert is in place.

**Comment by soydepr** [comment]
but as others mentioned not always valid ssl fixes the issue .it did for me though

BTW noting in today ios update addresses this issue

**Comment by Julian1998** [comment]
@soydepr Do you have a link that you can share with ous where the issue is adressed? Can't find it on google.

**Comment by soydepr** [comment]
Meant today’s ios update  did **NOT ** address this issue

**Comment by soydepr** [comment]
@Julian1998   I mentioned nothing was mentioned about this issue in the update

**Comment by DeepDiver1975** [comment]
Well ... I don't think this can be seen as an issue on the ios side. It's a security hardening apple did add to make sure no passwords are leaked via insecure connections. Generally speaking their intention is good.

**Comment by milkywade** [comment]
> 
> 
> Thanks @milkywade if I understand you correctly you can’t reach from the outside

no, no need

**Comment by milkywade** [comment]
> 
> 
> @milkywade Right now we suggest that apples new ios 12 version had some security updates including not sending authentication headers on http. As I said this is just a suggestion (But if it would be correct - then we can't do anything right now)

@DeepDiver1975 Hi there - think it makes sense. I saw this week that bitdefender (sometimes) applies the same logic as well and will not allow sending your password in clear. Wish this would have been more obvious before as I could not find that documented after a couple of google searches. All is well which ends well, sending passwords in clear, even in your own LAN is never a good thing. Thanks for the follow up.

**Comment by Julian1998** [comment]
> Well ... I don't think this can be seen as an issue on the ios side. It's a security hardening apple did add to make sure no passwords are leaked via insecure connections. Generally speaking their intention is good.
