### ISSUE TITLE
Bug in SQL Table XXX_clndr_objects when importing a calendar

### ISSUE THREAD

**Issue by PhilippeThueler** [owncloud/calendar#948]
I imported a calendar in *.ICS format into Owncloud calendar. I then wanted to have it in Lightning, so I used the calDAV link to add the calender into Lightning. It was then impossible to sync the events with Lightning. But, I found three exceptions that were correctly syncing though:
- new events created into Lightning were successfully synced back to owncloud
- all-day events were ok
- events that I edited in Owncloud then appeared in Lightning.

This draw me to the conclusion that the problem was in the import process in Calendar.
Have compared two events in the MySQL table XXX_clndr_objects, one that was correctly synced and one that wasn't, I noticed a bug in the MySQL content:
![capture](https://cloud.githubusercontent.com/assets/15035851/10372073/828f7a1a-6de6-11e5-98fb-09b51b62c209.PNG)
The text ;VALUE=: is obviously a bug in the code creating the MySQL Query during the import process.
I manually corrected this error by replacing VALUE=: by VALUE=Date:, re-imported the MySQL table into Owncloud, and now, all my events are showing up in Lightning properly...
So, to the developpers that know were to correct that, please do!
Greeting, Philippe

**Comment by PhilippeThueler** [comment]
Warning: In all-day events, it is correct to have DTSTART;VALUE=DATE:20150905 and DTEND;VALUE=DATE:20150921\r\n

**Comment by gvde** [comment]
1. Always use the template from the contribution guidelines to post issues. Your post lacks all the most important information, e.g. the owncloud version you use.

2. Always first search existing issues before posting. You would immediately find #922 #876 

3. Making random changes can make things worse, even when it seems it helped for you. VALUE=DATE means that value given is a date. However, 20151001T160000Z very much looks like a specific date & time, thus the correct VALUE setting would be DATE-TIME or do it just like the DTSTART attribute, i.e. omit the parameter altogether and just use the DTEND with the actual date-time value... With VALUE=DATE a client could convert the DTEND date-time to a date value removing the time information...
