### ISSUE TITLE
get data about js test coverage

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#95]

**Comment by DeepDiver1975** [comment]
can we upload js coverage to scrutinizer?

**Comment by georgehrke** [comment]
I don't think so

https://scrutinizer-ci.com/docs/tools/external-code-coverage/

**Comment by georgehrke** [comment]
@dominicrico Do you know a good tool?

**Comment by dominicrico** [comment]
To get test coverage? Yes, there are some and they are easy to implement into karma. Istanbul is one of them.

**Comment by dominicrico** [comment]
I one of my plugins I use lcov, as you can see here [angular reading indicator](https://github.com/dominicrico/angular-reading-indicator)
