### ISSUE TITLE
Exception template file not found: template:main after upgrade to 1.6.0 (from 1.5.7)

### ISSUE THREAD

**Issue by Schack17** [owncloud/calendar#950]
owncloud 10.0.9.5
### Steps to reproduce
1. update calendar from 1.5.7 to 1.6.0
2. Open ../index.php/apps/calendar/
3. Error message in browser.

### Expected behaviour
Show calendar app

### Actual behaviour
Error message

### Server configuration

**Operating system**: raspbian Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Web server:** apache2 2.4.10

**Database:** mysql 5.5.60

**PHP version:** 5.6.37-0+deb8u1

**ownCloud version:** 10.0.9.5

**Calendar version:** 1.6.0

**Updated from an older installed version or fresh install:** 1.5.7

**Signing status (ownCloud 9.0 and above):** signed

**List of activated apps:**
Enabled:
  - activity: 2.3.7
  - audioplayer: 2.3.1
  - bookmarks: 0.10.3
  - calendar: 1.5.7
  - checksum: 0.3.5
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - diagnostics: 0.1.2
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_ftp: 0.2.0
  - files_mv: 0.8.2
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - guests: 0.5.0
  - market: 0.2.5
  - music: 0.9.2
  - notifications: 0.3.4
  - ownbackup: 17.7.0
  - provisioning_api: 0.5.0
  - sensorlogger: 0.0.6
  - systemtags: 0.3.0
  - tasks: 0.9.6
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - apporder
  - direct_menu
  - documents
  - encryption
  - notes
  - ownnote

**ownCloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwritehost": "***REMOVED SENSITIVE VALUE***"
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "oc",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "excluded_directories": [
            ".snapshot",
            "~snapshot",
            "node_modules"
        ],
        "theme": "",
        "maintenance": false,
        "default_language": "de",
        "defaultapp": "calendar",
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "updatechecker": false,
        "logtimezone": "Europe\/Berlin",
        "appstore.experimental.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "loglevel": 2,
        "integrity.check.disabled": true,
        "singleuser": false
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome / Firefox

**Operating system:** Win10 x64

**CalDAV-clients:** -

#### Web server error log
{"reqId":"h57fByhLQmFwQco7ELco","level":3,"time":"2018-09-21T11:07:54+02:00","remoteAddr":"145.253.99.42","user":"ben","app":"index","method":"GET","url":"\/index.php\/apps\/calendar\/","message":"Exception: {\"Exception\":\"Exception\",
\"Message\":\"template file not found: template:main\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(203): OC\\\\Template\\\\TemplateFileLocator->find('main')\\n#1 \\\/var\\\/www\\\/ownc
loud\\\/lib\\\/private\\\/legacy\\\/template.php(88): OC_Template->findTemplate(Object(OC\\\\Theme\\\\Theme), 'calendar', 'main')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(150): OC_T
emplate->__construct('calendar', 'main', 'user')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#4 \\\/var\\\/www\\\/owncloud\
\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Calendar\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/TemplateFileLocator.php\",\"Line\":55}"}

**Comment by DeepDiver1975** [comment]
Does the file Apps/calendar/templates/main.php exist?

**Comment by Schack17** [comment]
Sorry. This was a problem with my server. It runs out of space.
