### ISSUE TITLE
Modify User-Agent check in CalDAV component to account for Windows 10

### ISSUE THREAD

**Issue by KHismoom** [owncloud/calendar#954]
There is a check of the user-agent string in owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php in line 620 to account for a problem with the CalDAV sync client in Windows Phone.
The native Windows 10 calendar app has the same problem (wrongly submitted depth value of 0), but a different user-agent ('MSFT-WIN-3/' instead of 'MSFT-WP/' on Windows Phone).

Modify check in owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php in line 620 to account for this user-agent, so the calendar app in Windows 10 works with OwnCloud, or add a more generic check to account for different (future) versions of Windows (Phone) CalDAV clients. Obviously, they all start with the string 'MSFT-', but I am not sure, if there are different clients that submit a user-agent string matching this pattern, for whom this would break functionality.

**Comment by DeepDiver1975** [comment]
From my pov this should be reported upstream https://github.com/fruux/sabre-dav/issues - THX

@evert FYI

**Comment by KHismoom** [comment]
Ok, will do.

**Comment by DeepDiver1975** [comment]
> Ok, will do.

THX a lot!

**Comment by RealRancor** [comment]
Ref: https://github.com/fruux/sabre-dav/issues/727
