### ISSUE TITLE
Error syncing with Thunderbird

### ISSUE THREAD

**Issue by Niklas974** [owncloud/calendar#956]
### Steps to reproduce
1. Set up Clean thunderbird, try to import Calendar

### Expected behaviour
Calendar should sync to thunderbird

### Actual behaviour
Calendar did not sync to thunderbird, Android with CalDav Sync works

### Server configuration
**Operating system**:
CentOS release 6.7 (Final)  2.6.32-431.20.3.el6.x86_64

**Web server:**
Apache/2.2.15 (CentOS)

**Database:**
mysql 5.1.73

**PHP version:**
5.6.12

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.3 (stable) 

**Updated from an older ownCloud or fresh install:**
new install, data migrated from old server.
old Server: oc 8.1.3, updatet from oc 5

**List of activated apps:**
Enabled:
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - updater: 0.6
Disabled:
 - activity
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

  'trusted_domains' => 
  array (
    0 => 'HOST',
  ),
  'datadirectory' => '/var/www/virtual/niklasgo/html/data',
  'overwrite.cli.url' => 'https://HOST',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'x_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'USR',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'share_folder' => '/Shared',
  'mail_smtpmode' => 'php',
  'loglevel' => 2,

**Are you using external storage, if yes which one:** local/smb/sftp/...
nope

**Are you using encryption:** yes/no
only transport

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
nope

### Client configuration
**Browser:**
newly installed thunderbird 38.3 on Windows 7,
thunderbird 38.3 on ubuntu

#### Web server error log
2001:7c0:409:: - - [18/Oct/2015:18:29:57 +0200] "PROPFIND /remote.php/caldav/calendars/Niklas/privat/ HTTP/1.1" 207 135187 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.3.0 Lightning/4.0.3.1"
2001:7c0:409:: - - [18/Oct/2015:18:29:57 +0200] "REPORT /remote.php/caldav/calendars/Niklas/privat/ HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.3.0 Lightning/4.0.3.1"
2001:7c0:409:: - - [18/Oct/2015:18:30:15 +0200] "POST /index.php/heartbeat HTTP/1.1" 200 - "https://OC-HOST/index.php/settings/admin" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"

NOTE: Timestamps in UTC +2

#### ownCloud log (data/owncloud.log)
{"reqId":"afth52E\/d2Td+jQq\/zZQ","remoteAddr":"WINDOWS-CLIENT-IP","app":"PHP","message":"Class 'OCA\\Calendar\\Sabre\\OC_Connector_Sabre_CalDAV_CalendarObject' not found at \/var\/www\/virtual\/niklasgo\/html\/apps\/calendar\/lib\/sabre\/calendar.php#150","level":3,"time":"2015-10-18T14:29:38+00:00"}
{"reqId":"I437OIJN6yVztfrGeHlh","remoteAddr":"WINDOWS-CLIENT-IP","app":"PHP","message":"Class 'OCA\\Calendar\\Sabre\\OC_Connector_Sabre_CalDAV_CalendarObject' not found at \/var\/www\/virtual\/niklasgo\/html\/apps\/calendar\/lib\/sabre\/calendar.php#150","level":3,"time":"2015-10-18T14:30:03+00:00"}
{"reqId":"QqxHD6YHRi0tWWvCCDvK","remoteAddr":"LINUX-CLIENT-IP","app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/niklasgo\/html\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-18T14:30:14+00:00"}

NOTE: Timestamps in UTC

#### Browser log
From Windows Thunderbird:

Zeitstempel: 18.10.2015 16:29:43
Warnung: getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.
Quelldatei: chrome://messenger/content/jquery.js
Zeile: 3

Zeitstempel: 18.10.2015 16:30:03
Warnung: CalDAV: Get failed: CalDAV: Error: got status 500 fetching calendar data for test, null
Quelldatei: file:///C:/Users/Niklas/AppData/Roaming/Thunderbird/Profiles/22c6h4qn.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/components/calDavCalendar.js
Zeile: 1213

Zeitstempel: 18.10.2015 16:30:03
Fehler: [calCachedCalendar] replay action failed: null, uri=https://OC-HOSTNAME/remote.php/caldav/calendars/Niklas/privat, result=2147500037, op=[xpconnect wrapped calIOperation]
Quelldatei: file:///C:/Users/Niklas/AppData/Roaming/Thunderbird/Profiles/22c6h4qn.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCachedCalendar.js
Zeile: 322

Zeitstempel: 18.10.2015 16:30:03
Warnung: Fehler beim Lesen von Daten für Kalender: test. Allerdings ist dieser Fehler wahrscheinlich vernachlässigbar, daher versucht das Programm fortzufahren. Fehlercode: 0x80004005. Beschreibung: CalDAV: Error: got status 500 fetching calendar data for test, null
Quelldatei: file:///C:/Users/Niklas/AppData/Roaming/Thunderbird/Profiles/22c6h4qn.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Zeile: 960
[something like: Error on reading data from Calendar: test. But this is probably negligible, programm will try to continue.]

NOTE: Timestamps in UTC+2

**Comment by gvde** [comment]
If you post log extracts please make sure they are related.
Your web server log is "16/Oct/2015:08:16:30 +0200", owncloud.log is "2015-10-16T07:38:52+00:00", Thunderbird is "16.10.2015 09:27:36".
Most importantly, the 500 error from the owncloud.log which is shown in the web server log is missing.

**Comment by Niklas974** [comment]
Thank you for answering so soon. I posted new log entries with matching timestamps.

Sorry for missing on that the first time.

**Comment by gvde** [comment]
>  {"reqId":"I437OIJN6yVztfrGeHlh","remoteAddr":"WINDOWS-CLIENT-IP","app":"PHP","message":"Class 'OCA\Calendar\Sabre\OC_Connector_Sabre_CalDAV_CalendarObject' not found at \/var\/www\/virtual\/niklasgo\/html\/apps\/calendar\/lib\/sabre\/calendar.php#150","level":3,"time":"2015-10-18T14:30:03+00:00"}

Check the file /var\/www\/virtual\/niklasgo\/html\/apps\/calendar\/lib\/sabre\/calendar.php at line 150.

Does your file have so many lines? Because mine doesn't. Nor do the latest version from the master or stable8.1 branch on github. https://github.com/owncloud/calendar/blob/stable8.1/lib/share/calendar.php

**Comment by Niklas974** [comment]
My bad. Instead of downloading the stable .zip Archive I just checked out the git repository…
I fixed it now and it works just fine.

Thank you very much for your help on finding the problem!

**Comment by Xefir** [comment]
It seems to be introduced by https://github.com/owncloud/calendar/pull/775

Rollbacking below this commit and works again on 8.2RC3

**Comment by georgehrke** [comment]
@Niklas974 Can you verify that revoking #775 fixes the issue for you?

**Comment by Niklas974** [comment]
# git clone https://github.com/owncloud/calendar.git
--> broken
# git checkout a86851268b4c406aa9d95af4e7114b28ab961576 (commit before merging #775 )
--> working again
# git checkout master
--> broken again

Reverting the commit was not possible, as conflicts came up. I'm happy to try some different method to help out if you tell me.
