### ISSUE TITLE
possible validation error for COUNT and UNTIL in calendar objects

### ISSUE THREAD

**Issue by thommierother** [owncloud/calendar#958]
1. create new calendar
2. add appointments through OC Web interface (10.0.0.10)
3. synchronize with MS Outlook 2016 through https://caldavsynchronizer.org/de/ 

### Expected behaviour
no validation error for calendar objects

### Actual behaviour
synchronization log shows:

<?xml version="1.0"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>thommie3_kalender</ProfileName>
  <ProfileId>3dd3085a-fc58-49c1-a57b-1d141e23ccd2</ProfileId>
  <StartTime>2018-10-15T14:16:41.9336349Z</StartTime>
  <ADelta>Unchanged: 10 , Added: 0 , Deleted 0 ,  Changed 0</ADelta>
  <BDelta>Unchanged: 9 , Added: 43 , Deleted 0 ,  Changed 1</BDelta>
  <AJobsInfo>Create 0 , Update 0 , Delete 0</AJobsInfo>
  <BJobsInfo>Create 0 , Update 0 , Delete 0</BJobsInfo>
  <LoadErrors>
    <LoadError>
      <EntityId>/owncloud/remote.php/dav/calendars/thommie3/personal/1532183792.R191.ics</EntityId>
      **<Error>System.ArgumentException: Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive.**
   bei DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.CheckMutuallyExclusive[T,U](String name1, String name2, T obj1, U obj2)
   bei DDay.iCal.Serialization.iCalendar.RecurrencePatternSerializer.Deserialize(TextReader tr)
   bei DDay.iCal.Serialization.iCalendar.DataMapSerializer.Deserialize(TextReader tr)
   bei DDay.iCal.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c)
   bei DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   bei DDay.iCal.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o)
   bei DDay.iCal.iCalParser.icalbody(ISerializationContext ctx, IICalendar iCal)
   bei DDay.iCal.iCalParser.icalendar(ISerializationContext ctx)
   bei DDay.iCal.Serialization.iCalendar.iCalendarSerializer.Deserialize(TextReader tr)
   bei CalDavSynchronizer.Implementation.CalDavRepository`1.DeserializeCalendar(String iCalData, IStringSerializer calendarSerializer)
   bei CalDavSynchronizer.Implementation.CalDavRepository`1.TryDeserializeCalendar(String iCalData, IICalendar&amp; calendar, WebResourceName uriOfCalendarForLogging, IStringSerializer calendarSerializer, ILoadEntityLogger logger)</Error>
      <IsAEntity>false</IsAEntity>
      <IsWarning>false</IsWarning>
    </LoadError>
### Server configuration

**Operating system**:
ubuntu 16.04 LTS

**Web server:**
apache 2.4.x

**Database:**
mariadb

**PHP version:**
7.2.x

**Comment by Julian1998** [comment]
Hi! Can you share your calendar as ics file? You can remove sensitive data or create an own calendar. (I can't reproduce that count and until behavior)

**Comment by thommierother** [comment]
Please download personal-2018-10-17.ics from 
https://www.netzwissen.de/owncloud/index.php/s/wSPHcVdjc5m90wB
I will remove it again by tomorrow ...

**Comment by DeepDiver1975** [comment]
> Please download personal-2018-10-17.ics from
> https://www.netzwissen.de/owncloud/index.php/s/wSPHcVdjc5m90wB
> I will remove it again by tomorrow ...

I have it - you can unshare again - THX

**Comment by DeepDiver1975** [comment]
@Julian1998 you know where to find me :rofl:

**Comment by Julian1998** [comment]
@DeepDiver1975 In the bar around the corner I guess :D

**Comment by thommierother** [comment]
@Julian1998 did you have time to look at it?

**Comment by Julian1998** [comment]
@thommierother No sorry... But I got your data :) Hopefully this week!

**Comment by thommierother** [comment]
@Julian1998 Any news on this issue?

**Comment by Julian1998** [comment]
@thommierother There are no simultaneous COUNT-UNTIL-events in your calendar. So maybe it's a bug in your calDav client. Did you change a recurrence ending of an existing event from UNTIL to COUNT (or other way round)

**Comment by thommierother** [comment]
issue re-created for caldavsynchronizer developers: https://sourceforge.net/p/outlookcaldavsynchronizer/tickets/1057/
