### ISSUE TITLE
Since MacOS Mojave 10.14 error in Calendar under ownCloud 10.0.10.

### ISSUE THREAD

**Issue by rrustema** [owncloud/calendar#959]
The error occured since updating my iPhone to iOS 12.0 and MacBook air to macos 10.14.

The calendar client on the Mac stopped synchronising with my (personal) owncloud-setup with Calendar and gives the error:

“Your calendar couldn’t be refreshed.”

“The server did not recognise your user name or password for account “host”. Make sure you enter them correctly.”

To be precise, I thought it was because I did not have an ssl-certificate on my domain and I used an old version of owncloud. Before coming here I fixed that. Now https on my domain (Let's Encrypt) and the latest owncloud version. Same error as before. Please advice!

First posted on https://central.owncloud.org/t/since-macos-mojave-10-14-error-in-calendar-under-owncloud-10-0-10-4/16335

### Steps to reproduce
1. update iOS and Macos clients to the latest
2.
3.

### Expected behaviour
Uninterrupted caldav synchronisation is what should happen after an update.

### Actual behaviour
Calendar client under macos gives:

“Your calendar couldn’t be refreshed.”

“The server did not recognise your user name or password for account “host”. Make sure you enter them correctly.”

### Server configuration

**Operating system**:

**Web server:**
Server Version: Apache/2.4.25 (Debian)

**Database:**
mysql

**PHP version:**
7.2
**ownCloud version:** (see your admin page)
10.0.10.4
**Calendar version:** (see the apps page)
1.6.0
**Updated from an older installed version or fresh install:**
last update

**Comment by DeepDiver1975** [comment]
>  Now https on my domain (Let's Encrypt) and the latest owncloud version. Same error as before. Please advice!

maybe macos is not seeing lets encrypt certs as valid due to missing root certs.

Can you open owncloud in the browser and watch out for errors?

**Comment by rrustema** [comment]
When I go to /owncloud/index.php/apps/calendar/ on my domain with Firefox and I ask 'more information' from the green 'lock' icon I see no errors. 

In the webinterface of the calendar I see the error: "The "Strict-Transport-Security" HTTP header is not configured to at least "15552000" seconds. For enhanced security we recommend enabling HSTS as described in our security tips." 

I suspect that I have to add/modify a line in .htaccess saying:

`<IfModule mod_headers.c>
  Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
</IfModule>`

Correct?

(a bit later)
Did that. The error in the Calendar app disappeared, but it did not solve the problem. The Mac calendar client still gives the error "Your calendar couldn’t be refreshed."

**Comment by rrustema** [comment]
Anything else I can try? I am getting a bit desperate with my calendars on phone and desktop not synchronising.

**Comment by rrustema** [comment]
By the way, synchronising the local folder 'owncloud' using the owncloud desktop client on the same machine gives no error. Assuming this client also asks for correct certificates then we can say the certificate is not an issue. 

Any other thoughts on narrowing down the cause?

I copy-pasted the password I use from my password manager as a new password in the owncloud webclient to replace the existing one. I got the error that a new password can not be identical to the old one. This same password I also pasted into the local calendar app, just to be sure. 

Any logfiles I should look for? When I consult the 'Console' client under macos I see nothing related.

**Comment by Julian1998** [comment]
I am not 100% sure but I would guess that the webDav(ownCloud) and calDav(apple) client authentications work independent of each other. We got a problem with ios12 and http... I know you use https so I guess it's a configuration error.

Can you post your ownCloud log and browser console log?

**Comment by rrustema** [comment]
what is the convention for sharing a logfile?

I just put it at http://www.rrr.deds.nl/owncloud.log 

Can you see something relevant in it? 

How is the browser console log relevant? I never use a browser for my Calendar. Where to find it if it is?

txs!

**Comment by Julian1998** [comment]
@rrustema Oh you don't use the web ui for creating calendars/events?

**Comment by Julian1998** [comment]
Yeah I found something interesting. 

403 Invalid or unknown sync token

https://github.com/owncloud/core/issues/30820

**Comment by Julian1998** [comment]
I will close this issue. It's a general sync issue so this is just a duplicate.

It seems to be most likely a bug with sync token given/created by apple.
