### ISSUE TITLE
Calendar release on app store for 8.2

### ISSUE THREAD

**Issue by PVince81** [owncloud/calendar#960]
@DeepDiver1975 raised to keep track of publishing the 8.2 compatible version on the app store.
(note: the git version worked well for me so far since 8.2RC1)

**Comment by georgehrke** [comment]
just packaged the release, adding a link on apps.owncloud.com right now

**Comment by georgehrke** [comment]
see https://github.com/owncloud/calendar/releases

**Comment by georgehrke** [comment]
And it's live on apps.owncloud.com: https://apps.owncloud.com/content/show.php?content=168707

**Comment by PVince81** [comment]
I disabled calendar, removed my local git version, then installed from the app store on OC 8.2RC3 and it worked fine. :+1:
