### ISSUE TITLE
/inbox/ not found (404) for CalDAV Scheduling

### ISSUE THREAD

**Issue by jjeising** [owncloud/calendar#962]
I've just upgraded to v0.8.0. Looking at [the diff](https://github.com/owncloud/calendar/compare/v0.7.3...v0.8.0) [CalDAV Scheduling](http://sabre.io/dav/scheduling/) was just added.

But it seems the implementation is somehow incomplete: When trying to sync with Calendar.app on Mac OS X 10.11 there is an error:
```
[...] "PROPFIND /remote.php/caldav/calendars/[...]/inbox/ HTTP/1.1" 404 294 "-" "Mac+OS+X/10.11 (15A284) CalendarAgent/361"
```
It's also shown in Calendar.app as an alert.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

**Comment by jjeising** [comment]
### Steps to reproduce
1. Install OwnCloud Calendar App v0.8.0 on OwnCloud 8.2.0.
2. Setup CalDAV Syncing in Calendar.app on OS X 10.11.
3. Try to sync.

### Expected behaviour
Sync without errors.

### Actual behaviour
Server side 404, Calendar.app on OS X shows 
```
The URL [...]/remote.php/caldav/principals/[...]/ encountered HTTP error 404. Make sure the URL is correct.
```

### Server configuration
**ownCloud version:** ownCloud 8.2.0 (stable)
**Updated from an older ownCloud or fresh install:** Update.
**List of activated apps:** Files, Calendar, Contacts

**Are you using external storage, if yes which one:** local
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Operating system:** Mac OS X 10.11

### Logs
#### Web server error log
```
[...] "PROPFIND /remote.php/caldav/calendars/[...]/inbox/ HTTP/1.1" 404 294 "-" "Mac+OS+X/10.11 (15A284) CalendarAgent/361"
```

#### ownCloud log (data/owncloud.log)
```
Exception: {
	"Message":"HTTP/1.1 404 Node with name 'inbox' could not be found",
	"Exception":"Sabre/DAV/Exception/NotFound","Code":0,
	"Trace":"#0 .../owncloud/apps/calendar/lib/sabre/usercalendars.php(47): Sabre/CalDAV/CalendarHome->getChild('inbox')
#1 .../owncloud/3rdparty/sabre/dav/lib/DAV/Tree.php(76): OCA/Calendar/Sabre/UserCalendars->getChild('inbox')
#2 .../owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(920): Sabre/DAV/Tree->getNodeForPath('calendars/XXX...')
#3 .../owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(327): Sabre/DAV/Server->getPropertiesForPath('calendars/XXX...', Array, 0)
#4 [internal function]: Sabre/DAV/CorePlugin->httpPropfind(Object(Sabre/HTTP/Request), Object(Sabre/HTTP/Response))
#5 .../owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#6 .../owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre/Event/EventEmitter->emit('method:PROPFIND', Array)
#7 .../owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre/DAV/Server->invokeMethod(Object(Sabre/HTTP/Request), Object(Sabre/HTTP/Response))
#8 .../owncloud/apps/calendar/appinfo/remote.php(67): Sabre/DAV/Server->exec()
#9 .../owncloud/remote.php(137): require_once('.../...')
#10 {main}",
	"File":".../owncloud/3rdparty/sabre/dav/lib/CalDAV/CalendarHome.php",
	"Line":170
}```

**Comment by georgehrke** [comment]
@evert Do we need to load another plugin to make the inbox work?
https://github.com/owncloud/calendar/blob/master/appinfo/remote.php#L49

**Comment by georgehrke** [comment]
Okay, we are probably missing our own implementation of Sabre\CalDAV\Backend\SchedulingSupport

**Comment by evert** [comment]
Yep I was just gonna answer that. It should be fairly simple because it's just a matter of storing inbox items. To get started you could even *not* store any inbox items. I hear from some people that keeping the inbox empty works in some (if not all) cases.

**Comment by nicokaiser** [comment]
Temporary workaround may be adding a calendar called "Inbox". Worked for me.

**Comment by DeepDiver1975** [comment]
We should consider reverting this PR https://github.com/owncloud/calendar/pull/881 - or somebody will come up with a fix :wink:

**Comment by ilpssun** [comment]
@nicokaiser The workaround seems to fix the error for me, too.

**Comment by evert** [comment]
Thats a pretty bad idea and can definitely mess stuff up for you in the future

**Comment by ilpssun** [comment]
@evert How so?

**Comment by gvde** [comment]
@ilpssun The inbox calendar is a special purpose calendar for caldav scheduling. It's not a normal calendar. Thus creating a calendar called "inbox" will most likely create conflicts with a caldav scheduling once it is working properly.
That's why it's a "workaround" and should be removed once the bug has been fixed...

**Comment by nicokaiser** [comment]
Exactly. The workaround was a try to make the calendar (in its current stable version) somehow work again on OS X (in its current stable version). Once the "inbox" feature (whatever that is) is either supported or disabled, the workaround can (and should) be removed.

**Comment by ilpssun** [comment]
@gvde Ok, I understand it's a workaround and needs to be removed once the implementation is working properly.  But from your explanation I take it that it should not create any problems until then.
Thanks for the explanation.  I'm looking forward to a fix :-)

**Comment by kaksikanaa** [comment]
Any fix for this yet? The Calendar app is unusable also with EMclient connecting to Owncloud on Windows until this is fixed.

**Comment by georgehrke** [comment]
> I hear from some people that keeping the inbox empty works in some (if not all) cases.

@evert Is that really an acceptable solution? :confused:

**Comment by mroi** [comment]
My workaround is to revert 053e9cf0dbd2e1e8eac0a5a3dc441785e5d8262b.

**Comment by gvde** [comment]
I guess reverting is the current solution.

The empty inbox is definitively only a temporary workaround.

**Comment by evert** [comment]
@georgehrke , no it's a bad idea and it can cause odd corruption issues. It basically will cause multiple events with the same UID's to start appearing, and clients may trip over that. So yea, I don't think it's an appropriate workaround.

The best quick and easy workaround is to implement SchedulingSupport and make every function from that interface basically 'do nothing'. That _will_ solve the issue without major side-effects.

**Comment by gvde** [comment]
@evert What would be the "major side-effect" of reverting the patch and removing SchedulingSupport? Sounds to me like the best solution not to offer a function which hasn't been implemented, yet, instead of offering it but not doing anything...

**Comment by evert** [comment]
The scheduling plugin is responsible for freebusy lookups, delivering invites and replies and sending out email. Turning off the scheduling plugin turns those features off without any additional side-effects.

**Comment by gvde** [comment]
@evert Sounds to me like the best solution at this time...

**Comment by Zigulle** [comment]
The workaround (reverting 053e9cf ) works for me to. Now OS X is syncing with owncloud 8.2 and calendar-app 8.0

**Comment by Azimoth** [comment]
@Zigulle @mroi I'm sorry to ask, but… how do I revert to 053e9cf?

**Comment by gvde** [comment]
@azimoth to revert the commit, click on the link of the commit and see what has changed with that commit.

In this case, lines 46-52 in appinfo/remote.php (found in the calendar app, i.e. /var/www/owncloud/apps/calendar/appinfo/remote.php or similar depending on your installation).

To revert the commit you undo what the commit has done, i.e. you remove those lines 46-52 which are shown green when you click on the commit. 

That's it...

**Comment by Azimoth** [comment]
Seems to work. Thanks a lot. (I first tried simply replacing the "new" remote.php with the "old" remote.php, which did not work)
I understand this "edited" remote.php will simply be replaced when I install a newer version, so no further problems are to be expected? Or is there anything to watch out for?

**Comment by mroi** [comment]
@Azimoth Yes, it should just be replaced. Let’s hope the next version fixes the issue for good.

**Comment by georgehrke** [comment]
Ok, so for now, let's revert it and release a new version in the next couple of days. We can take care of a proper solution afterwords.

**Comment by mroi** [comment]
@georgehrke I think that would be useful. And it may save you further support effort.

**Comment by georgehrke** [comment]
Here are the revert pull requests:
master: https://github.com/owncloud/calendar/pull/969
stable8.2: https://github.com/owncloud/calendar/pull/970

**Comment by thetrial** [comment]
So this means, if one does not change the source, OC 8.2 does not work with Apple’s iCal? That makes me wonder. I had to change it. No other way to get this to work. Were there no tests before?

**Comment by jens-maus** [comment]
I also had problems with OC 8.2 and Apple iCal and applied the mentioned revert pull request and now iCal doesn't complain about any 404 error anymore. Thus, would be nice to see these pull requests being applied so that one of the next updates fixes this problem.

**Comment by dokterbob** [comment]
It is kind of weird that a serious issue like this - affecting a significant number of users - can make it through to the 'stable' release of a package. It makes me a bit worried about running ownCloud in production if significant numbers of users are supposed to manually patch the source to get it to work on one of the major platforms (OS X).

If there is a simple workaround, would it not make sensible release engineering to roll out 8.2.1 reverting the relevant pull request on the stable branch (so it becomes stable once more) and then properly fixing the issue on a release or feature branch (i.e. fixing the original pull request)?

I am sure a lot of OC users would be much obliged. I, for one, do not run OC from the Git repo in production. Rather, I use (signed) packages for convenient upgrades. It is bad enough that a 'broken' build can be released but at least try to fix it as soon as possible: pragmatism (unbreaking the sync on OS X) over idealism (not shipping until it is elegantly solved) would be much appreciated here.

P.S. Apologise the flame, you all did make a pretty good product, otherwise I wouldn't be using it. Though quality assurance might be a point of improvement. :)

**Comment by DeepDiver1975** [comment]
9.0 will come with caldav and carddav as part of core.
Please expert this to work then.
In addition I welcome every mac user to test the master branch in core these days - a pull request is ready to test soon-ish.

**Comment by jancborchardt** [comment]
@dokterbob there apparently are not a lot of OS X users testing this in the beta phase, so you would be a big help there.

**Comment by dokterbob** [comment]
I haven't seen a notification that the calendar is in beta anywhere. I was under the impression it was stable. 

As I use OC in production and am less than willing to touch PHP code to test for and fix bugs myself I think I'm unlikely to help with testing of the new release, perhaps until a release candidate. 

However, perhaps it might be possible to perform these type of tests automatically. In many other software projects there is the policy of requiring full unit test coverage before allowing new code in. At least in the Django community this has resulted in marvelous stability, though hiccups in stable releases have happened at times -but were usually fixed within hours of discovery. 

Another option might be to automatically test synchronization for several platforms through the automation of a bunch of virtual machines. If nobody has yet thought of it I might be able to research this concept and make a proposal (though my time for implementing it is limited). Of course that would be a different ticket. 

Jan-Christoph Borchardt <notifications@github.com> schreef op 11 november 2015 09:10:12 CET:

**Comment by dokterbob** [comment]
Whoops, sorry, I misread your post. I will see if I can manage to run 9.0 in beta to provide feedback, though there is a Curl issue with the FreeBSD package disabling me to automatically fetch updates (i.e. the beta channel).

**Comment by simsasaile** [comment]
Thanks for the workaround! Reverting to 053e9cf worked for me as well.

**Comment by jancborchardt** [comment]
@dokterbob yep – prior to every ownCloud release there’s a beta phase. And even just testing master every now and then is easily possible. No need to touch PHP code for that at all. Just test and report issues. Thanks! :)

**Comment by georgehrke** [comment]
just released v0.8.1

**Comment by dokterbob** [comment]
\o/

**Comment by dokterbob** [comment]
Installed, synced and smiled. :)

Thanks!
