### ISSUE TITLE
[For Semver] Calendar 1.6.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/calendar#967]
### Reason

- Set max version to 10 because core platform is switching to Semver
- Adjust showing timezone - [#961](https://github.com/owncloud/calendar/issues/961)

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test: Install from the provided tarball and enable in ownCloud stable10
- [x] Test: https://github.com/owncloud/calendar/pull/961#issuecomment-445736667

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/gM7TtiM1wAsXlMh
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/calendar/pull/969

**Comment by PVince81** [comment]
@davitol please test tarball https://cloud.owncloud.com/index.php/s/gM7TtiM1wAsXlMh

**Comment by DeepDiver1975** [comment]
>     * x Test: [#961 (comment)](https://github.com/owncloud/calendar/pull/961#issuecomment-445736667)

not a issue ... false alarm

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready
