### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/calendar#975]
### Steps to reproduce
1. Create or edit an event
2. Change the time
3.

### Expected behaviour
Tell us what should happen
German Translation of all text in the side view of events

### Actual behaviour
Tell us what happens instead
hour an minute over the time selection

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see your admin page)
10.0.10.4
**Calendar version:** (see the apps page)
1.6.1
**Updated from an older installed version or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**ownCloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Can you please provide screen shots? I’m not exactly sure I understand what part of the editor you refer to

**Comment by prsnbrg** [comment]
![screenshot 21](https://user-images.githubusercontent.com/29964525/52364793-5bef5680-2a46-11e9-8713-323e17b598a0.png)

the modal with the hour and the minute have no translation.

**Comment by DeepDiver1975** [comment]
The reason for this is most likly an outdated momentjs library somewhere in the stack. I'll have a look ....
