### ISSUE TITLE
Help with app calendar

### ISSUE THREAD

**Issue by tomanluke** [owncloud/calendar#982]
Hello.

I need to edit apk Calendar. 
1. I want the time displayed the 8 to 20 or the calendar was only 8 to 20.
2. Block the ability to edit the color of the calendar or the names of other users. They can only add something to or delete, etc. but can not change the colors and names of calendars. Ideally, you could only do admin, if not so just as it removed.
3. The ability to quickly export to pdf, or simply to write the .ics format that export to .pdf.

Thank you in advance for your help

**Comment by georgehrke** [comment]
> I want the time displayed the 8 to 20 or the calendar was only 8 to 20.

please checkout the full calendar doc, http://fullcalendar.io/docs1/agenda/firstHour/ might be useful

> Block the ability to edit the color of the calendar or the names of other users. They can only add something to or delete, etc. but can not change the colors and names of calendars. Ideally, you could only do admin, if not so just as it removed.

you would have to modify https://github.com/owncloud/calendar/blob/master/ajax/calendar/update.php

> The ability to quickly export to pdf, or simply to write the .ics format that export to .pdf.

Well, you can export each calendar as ical. I don't know, what exactly you want the pdf to look like. Maybe there is some linux command line tool to automate it.
