### ISSUE TITLE
Hide not your calendar

### ISSUE THREAD

**Issue by tomanluke** [owncloud/calendar#984]
Hello.
Normally the person who creates the calendar, and then make it available to a group can only hide it. How to do that every user can hide it?
I want to create a calendar task for some people and I would like that everyone could see only the tasks for yourself, or for a person.
The following screenshots. Such a thing can do only person who created the calendar. I would like to be able to do each person.

http://imgur.com/0JkipmV

http://imgur.com/SrfGWSi

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/21
