### ISSUE TITLE
1.6.2: all calendars disappeared after upgrade

### ISSUE THREAD

**Issue by thommierother** [owncloud/calendar#993]
After cli upgrade to calendar 1.6.2, all calendars previously selected in the left pane disappeared, I only see a "waiting circle" forever.

Tested  with OC 10.1.0 and Firefox 60.5 ESR and Chromium 71.0.3578.98

Browser console shows (I don't know if this is relevant):

> 20:25:51.544 Error: current-user-principal could not be determined
> app.js:5055:10

**Comment by DeepDiver1975** [comment]
@thommierother this happens in case the response of the first propfind is returning an error.

Please try to logoff and logon and if this still happens I need a screenshot of that failing PROPFIND from the network tab of our browser

**Comment by thommierother** [comment]
Sorry for that, this was my fault. I forgot to disable maintenance singleuser mode after the upgrade. All is fine now ;-).
