### ISSUE TITLE
No release with max_version >= 8.2.1 ; app is unavailable

### ISSUE THREAD

**Issue by eltrai** [owncloud/calendar#996]
At the moment, it seems to me that there is no release of this app that support owncloud 8.2.1 (which is officially out as of 15 days ago).

Therefore, the app is currently broken for all users that have an up-to-date owncloud and update this app through releases.

I did notice that the max_version was increased in 37fa440869e8ff8157f71929882abba67644f66c, but that commit is not included in any released version.

**Comment by georgehrke** [comment]
max version 8.2 should also include support for 8.2.1.

but first of all: please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

**Comment by eltrai** [comment]
Hum, somehow it was just a problem on my local copy. Sorry for disturbing. :flushed: 

PS : I'll use the template next time, thanks.
